INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1112_06','V1112','陈主管',6,'我先和客户沟通安抚，你稍后主动给客户发致歉消息。','wǒ xiān hé kè hù gōu tōng ān fǔ， nǐ shāo hòu zhǔ dòng gěi kè hù fā zhì qiàn xiāo xī。','Chú sẽ trao đổi trấn an khách trước, lát nữa em chủ động nhắn lời xin lỗi khách nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1112_07','V1112','阮明',7,'好，我马上编辑道歉文字，一定注意之后操作小心。','hǎo， wǒ mǎ shàng biān jí dào qiàn wén zì， yí dìng zhù yì zhī hòu cāo zuò xiǎo xīn。','Dạ, em soạn tin nhắn xin lỗi ngay đây, nhất định sau này sẽ chú ý thao tác cẩn thận hơn.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1113','SVL2','上班途中骑车摔伤，向主管申请工伤就医与带薪休养',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1113','SIT1113','P1','suon_se','ban_chinh_thuc',NULL,'上下班合理路线内发生非本人主要责任交通事故，属于工伤范畴，用人单位需正常发放休养期间工资。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1113_01','V1113','阮明',1,'陈主管，我骑车来上班路上摔倒，膝盖擦伤严重，想请假就医。','chén zhǔ guǎn， wǒ qí chē lái shàng bān lù shàng shuāi dǎo， xī gài cā shāng yán zhòng， xiǎng qǐng jià jiù yī。','Chú Trần ơi, em đi xe đạp đến chỗ làm bị ngã trên đường, đầu gối trầy nặng lắm, em muốn xin nghỉ đi khám ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1113_02','V1113','陈主管',2,'伤得严重吗？上下班途中非本人主责事故可以走工伤报备。','shāng dé yán zhòng ma？ shàng xià bān tú zhōng fēi běn rén zhǔ zé shì gù kě yǐ zǒu gōng shāng bào bèi。','Bị nặng vậy à? Tai nạn trên đường đi làm mà không phải lỗi chính của em thì có thể làm hồ sơ tai nạn lao động đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1113_03','V1113','阮明',3,'交警判定对方全责，医院诊断单据我都保存好了。','jiāo jǐng pàn dìng duì fāng quán zé， yī yuàn zhěn duàn dān jù wǒ dōu bǎo cún hǎo le。','Cảnh sát giao thông xác định bên kia hoàn toàn có lỗi, giấy chẩn đoán của bệnh viện em cũng giữ đầy đủ rồi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1113_04','V1113','陈主管',4,'你安心去治疗，休养这几天按正常工时发放薪资。','nǐ ān xīn qù zhì liáo， xiū yǎng zhè jǐ tiān àn zhèng cháng gōng shí fā fàng xīn zī。','Em cứ yên tâm đi chữa trị, những ngày nghỉ dưỡng thương này vẫn tính lương theo giờ làm bình thường.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1113_05','V1113','阮明',5,'太感谢您了，我处理完伤口再把病历拍照发给您报备。','tài gǎn xiè nín le， wǒ chǔ lǐ wán shāng kǒu zài bǎ bìng lì pāi zhào fā gěi nín bào bèi。','Cảm ơn chú nhiều lắm, xử lý vết thương xong em sẽ chụp lại bệnh án gửi chú để báo cáo ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1113_06','V1113','陈主管',6,'不用着急上班，养好伤再回来，工作我先安排其他人顶替。','bù yòng zháo jí shàng bān， yǎng hǎo shāng zài huí lái， gōng zuò wǒ xiān ān pái qí tā rén dǐng tì。','Không cần vội đi làm đâu, dưỡng thương khỏe hẳn rồi hãy quay lại, công việc chú sắp người khác thay tạm cho.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1114','SVL2','客户因语言沟通不畅产生投诉，上前配合主管安抚致歉',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1114','SIT1114','P1','twist','ban_chinh_thuc',NULL,'服务业遇到外籍员工语言沟通纠纷，主管会优先出面沟通，不会将全部责任归咎外籍员工。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1114_01','V1114','阮明',1,'陈主管，这位客户听不懂我的表达，已经有点生气投诉了。','chén zhǔ guǎn， zhè wèi kè hù tīng bù dǒng wǒ de biǎo dá， yǐ jīng yǒu diǎn shēng qì tóu sù le。','Chú Trần ơi, vị khách này nghe không hiểu em nói gì, có vẻ hơi bực và đã khiếu nại rồi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1114_02','V1114','陈主管',2,'你先别着急解释，我来和客户沟通，你在一旁帮忙递单据。','nǐ xiān bié zháo jí jiě shì， wǒ lái hé kè hù gōu tōng， nǐ zài yī páng bāng máng dì dān jù。','Em đừng vội giải thích, để chú nói chuyện với khách, em đứng bên cạnh phụ đưa giấy tờ nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1114_03','V1114','阮明',3,'都怪我中文表达不够流畅，给门店添麻烦了，实在不好意思。','dōu guài wǒ zhōng wén biǎo dá bù gòu liú chàng， gěi mén diàn tiān má fán le， shí zài bù hǎo yì sī。','Tại em nói tiếng Trung chưa đủ trôi chảy, làm phiền cửa hàng rồi, thật sự xin lỗi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1114_04','V1114','陈主管',4,'没事，外籍员工语言沟通有障碍很正常，我来安抚客户。','méi shì， wài jí yuán gōng yǔ yán gōu tōng yǒu zhàng ài hěn zhèng cháng， wǒ lái ān fǔ kè hù。','Không sao đâu, nhân viên nước ngoài giao tiếp có chút trở ngại là chuyện bình thường mà, để chú trấn an khách cho.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1114_05','V1114','阮明',5,'等下我要不要主动跟客户道个歉，缓和一下气氛？','děng xià wǒ yào bù yào zhǔ dòng gēn kè hù dào gè qiàn， huǎn hé yī xià qì fēn？','Lát nữa em có nên chủ động xin lỗi khách để làm dịu không khí không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1114_06','V1114','陈主管',6,'等我解释清楚业务问题，你再简单致歉会更合适。','děng wǒ jiě shì qīng chǔ yè wù wèn tí， nǐ zài jiǎn dān zhì qiàn huì gèng hé shì。','Đợi chú giải thích rõ vấn đề nghiệp vụ xong, em xin lỗi ngắn gọn sau sẽ hợp lý hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1114_07','V1114','阮明',7,'好，我听您安排，之后我也会多练习日常服务用语。','hǎo， wǒ tīng nín ān pái， zhī hòu wǒ yě huì duō liàn xí rì cháng fú wù yòng yǔ。','Dạ, em nghe theo sắp xếp của chú, sau này em cũng sẽ luyện tập thêm câu từ phục vụ hàng ngày.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1115','SVL2','临近下班临时安排加班，询问加班补贴与下班返程时间',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1115','SIT1115','P1','that_bai_nhe','ban_chinh_thuc',NULL,'法定工作日加班用人单位需支付1.5倍薪资，休息日加班2倍，法定节假日3倍，员工可主动询问加班薪酬标准。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1115_01','V1115','阮明',1,'陈主管，我原定六点下班，现在临时安排加班，有加班补贴吗？','chén zhǔ guǎn， wǒ yuán dìng liù diǎn xià bān， xiàn zài lín shí ān pái jiā bān， yǒu jiā bān bǔ tiē ma？','Chú Trần ơi, em vốn định sáu giờ tan làm, giờ đột xuất phải làm thêm, vậy có phụ cấp làm thêm giờ không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1115_02','V1115','陈主管',2,'今天临时整理库存，加班两小时，按一点五倍时薪结算补贴。','jīn tiān lín shí zhěng lǐ kù cún， jiā bān liǎng xiǎo shí， àn yì diǎn wǔ bèi shí xīn jié suàn bǔ tiē。','Hôm nay đột xuất kiểm kê kho, làm thêm hai tiếng, tính phụ cấp theo một phẩy năm lần lương giờ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1115_03','V1115','阮明',3,'可是我七点有线上语言课，加班会错过上课时间呢。','kě shì wǒ qī diǎn yǒu xiàn shàng yǔ yán kè， jiā bān huì cuò guò shàng kè shí jiān ne。','Nhưng bảy giờ em có lớp học tiếng online, làm thêm thì lỡ mất giờ học rồi ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1115_04','V1115','陈主管',4,'今晚库存必须清点完成，课程只能你自己调整时间啦。','jīn wǎn kù cún bì xū qīng diǎn wán chéng， kè chéng zhǐ néng nǐ zì jǐ tiáo zhěng shí jiān la。','Tối nay bắt buộc phải kiểm kê xong kho, còn lớp học thì em tự điều chỉnh giờ thôi nhé.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1115_05','V1115','阮明',5,'那我只能课后回看录播，麻烦您把加班工时记录清楚。','nà wǒ zhǐ néng kè hòu huí kàn lù bō， má fán nín bǎ jiā bān gōng shí jì lù qīng chǔ。','Vậy em đành xem lại video ghi hình sau buổi học, phiền chú ghi rõ giờ làm thêm giúp em ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1115_06','V1115','陈主管',6,'放心，考勤系统会单独标注加班时长，月底统一结算。','fàng xīn， kǎo qín xì tǒng huì dān dú biāo zhù jiā bān shí cháng， yuè dǐ tǒng yī jié suàn。','Yên tâm đi, hệ thống chấm công sẽ ghi riêng thời gian làm thêm, cuối tháng tính chung một lần.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1115_07','V1115','阮明',7,'好，我现在留下来清点库存，尽快完成早点下班。','hǎo， wǒ xiàn zài liú xià lái qīng diǎn kù cún， jǐn kuài wán chéng zǎo diǎn xià bān。','Dạ, giờ em ở lại kiểm kê kho, cố gắng làm xong sớm để về sớm.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1116','SVL2','电脑里实习重要文件误删，求助同事找回备份资料',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1116','SIT1116','P1','suon_se','tuy_y',NULL,'国内企业办公电脑普遍配备云端自动备份，同事之间互相协助处理办公故障是职场常见互助行为。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1116_01','V1116','阮明',1,'小佳，糟糕，我刚不小心把实习报告文件全部删掉了啊。','xiǎo jiā， zāo gāo， wǒ gāng bù xiǎo xīn bǎ shí xí bào gào wén jiàn quán bù shān diào le a。','Tiểu Giai, chết rồi, mình vừa lỡ tay xóa mất hết file báo cáo thực tập rồi.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1116_02','V1116','小佳',2,'别慌，公司电脑每天自动云端备份，我教你恢复备份就行。','bié huāng， gōng sī diàn nǎo měi tiān zì dòng yún duān bèi fèn， wǒ jiāo nǐ huī fù bèi fèn jiù xíng。','Đừng hoảng, máy công ty ngày nào cũng tự động sao lưu lên cloud mà, để mình chỉ cho cậu cách khôi phục.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1116_03','V1116','阮明',3,'真的吗？我还以为要重新做一整天，快教教我操作步骤吧。','zhēn de ma？ wǒ hái yǐ wéi yào chóng xīn zuò yī zhěng tiān， kuài jiāo jiāo wǒ cāo zuò bù zhòu ba。','Thật hả? Mình còn tưởng phải làm lại từ đầu cả ngày, nhanh chỉ mình cách làm đi.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1116_04','V1116','小佳',4,'我一步步带你点备份界面，十分钟就能找回全部文档。','wǒ yí bù bù dài nǐ diǎn bèi fèn jiè miàn， shí fēn zhōng jiù néng zhǎo huí quán bù wén dàng。','Mình dẫn cậu bấm từng bước vào giao diện sao lưu, mười phút là lấy lại hết tài liệu thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1116_05','V1116','阮明',5,'太谢谢你了，要是文件找不回，明天没办法交给导师。','tài xiè xiè nǐ le， yào shì wén jiàn zhǎo bù huí， míng tiān méi bàn fǎ jiāo gěi dǎo shī。','Cảm ơn cậu nhiều lắm, chứ file mà không tìm lại được thì mai không có gì nộp cho giảng viên hướng dẫn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1116_06','V1116','小佳',6,'小事，以后记得自己手动多存一份，避免再次误删。','xiǎo shì， yǐ hòu jì de zì jǐ shǒu dòng duō cún yī fèn， bì miǎn zài cì wù shān。','Chuyện nhỏ ấy mà, sau này nhớ tự tay lưu thêm một bản nữa để tránh xóa nhầm lần nữa nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1116_07','V1116','阮明',7,'我记住啦，这次多亏有你帮忙！','wǒ jì zhù la， zhè cì duō kuī yǒu nǐ bāng máng！','Mình nhớ rồi, lần này may có cậu giúp đó!','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1117','SVL2','工位贵重耳机在工作区丢失，找人事调取监控查找',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1117','SIT1117','P1','twist','ban_chinh_thuc',NULL,'企业办公监控仅覆盖公共走道、前台，独立工位无监控，丢失私人物品只能通过内部群求助同事。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1117_01','V1117','阮明',1,'小吴，我工位的耳机不见了，能不能调取办公区监控看看？','xiǎo wú， wǒ gōng wèi de ěr jī bú jiàn le， néng bù néng diào qǔ bàn gōng qū jiān kòng kàn kàn？','Tiểu Ngô, tai nghe ở chỗ ngồi của tôi bị mất rồi, cô có thể xin trích xuất camera khu văn phòng giúp tôi xem thử được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1117_02','V1117','小吴',2,'可以调监控，但只能查看公共区域，私人工位死角拍不到哦。','kě yǐ diào jiān kòng， dàn zhǐ néng chá kàn gōng gòng qū yù， sī rén gōng wèi sǐ jiǎo pāi bú dào ó。','Trích xuất thì được, nhưng chỉ xem được khu vực chung thôi, còn góc khuất chỗ ngồi riêng thì camera không quay tới đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1117_03','V1117','阮明',3,'我中午外出吃饭忘了收耳机，回来就找不到，大概率被人误拿。','wǒ zhōng wǔ wài chū chī fàn wàng le shōu ěr jī， huí lái jiù zhǎo bú dào， dà gài lǜ bèi rén wù ná。','Trưa tôi ra ngoài ăn cơm quên không cất tai nghe, lúc về thì không thấy đâu nữa, chắc là bị ai đó lấy nhầm rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1117_04','V1117','小吴',4,'我现在调取中午时段录像，你在这里稍等几分钟。','wǒ xiàn zài diào qǔ zhōng wǔ shí duàn lù xiàng， nǐ zài zhè lǐ shāo děng jǐ fēn zhōng。','Giờ tôi trích xuất camera lúc buổi trưa, anh chờ ở đây vài phút nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1117_05','V1117','阮明',5,'如果监控找不到，我能不能在公司群里发寻物启事问问同事？','rú guǒ jiān kòng zhǎo bú dào， wǒ néng bù néng zài gōng sī qún lǐ fā xún wù qǐ shì wèn wèn tóng shì？','Nếu xem camera mà không tìm ra, tôi có thể đăng thông báo tìm đồ trong nhóm chung của công ty để hỏi mọi người không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1117_06','V1117','小吴',6,'可以，我帮你转发公司全员群，方便大家帮忙留意。','kě yǐ， wǒ bāng nǐ zhuǎn fā gōng sī quán yuán qún， fāng biàn dà jiā bāng máng liú yì。','Được chứ, tôi giúp anh đăng lên nhóm toàn công ty, để mọi người tiện để ý giúp.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1117_07','V1117','阮明',7,'麻烦你了，耳机对我学习工作都很重要，希望能找回来。','má fán nǐ le， ěr jī duì wǒ xué xí gōng zuò dōu hěn zhòng yào， xī wàng néng zhǎo huí lái。','Phiền cô rồi, tai nghe đó với tôi quan trọng lắm, cả học tập lẫn công việc, mong là tìm lại được.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1118','SVL2','发薪日工资少发，找人事核对考勤、扣款明细补发差额',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1118','SIT1118','P1','suon_se','ban_chinh_thuc',NULL,'国内企业每月会发放薪资明细，包含出勤、加班、请假扣款、个税等项目，薪资异议当月可核对更正。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1118_01','V1118','阮明',1,'小吴，今天发薪到账金额比我核算的少三百，想核对一下明细。','xiǎo wú， jīn tiān fā xīn dào zhàng jīn é bǐ wǒ hé suàn de shǎo sān bǎi， xiǎng hé duì yī xià míng xì。','Tiểu Ngô, lương hôm nay chuyển vào tài khoản ít hơn tôi tính ba trăm, muốn nhờ cô đối chiếu lại chi tiết xem sao.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1118_02','V1118','小吴',2,'我调取你的考勤表，上周有半天临时请假，扣除了当日工时工资。','wǒ diào qǔ nǐ de kǎo qín biǎo， shàng zhōu yǒu bàn tiān lín shí qǐng jià， kòu chú le dāng rì gōng shí gōng zī。','Để tôi lấy bảng chấm công của anh xem, tuần trước anh có xin nghỉ nửa ngày đột xuất, nên bị trừ tiền công ngày hôm đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1118_03','V1118','阮明',3,'原来是请假扣款，我忘记核算这部分，还以为是计算出错了。','yuán lái shì qǐng jià kòu kuǎn， wǒ wàng jì hé suàn zhè bù fèn， hái yǐ wéi shì jì suàn chū cuò le。','Thì ra là bị trừ do nghỉ phép, tôi quên tính phần này, còn tưởng là tính sai đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1118_04','V1118','小吴',4,'我把本月薪资明细截图发给你，每一笔扣款都标注清楚啦。','wǒ bǎ běn yuè xīn zī míng xì jié tú fā gěi nǐ， měi yī bǐ kòu kuǎn dōu biāo zhù qīng chǔ la。','Tôi gửi cho anh ảnh chụp bảng lương chi tiết tháng này, từng khoản khấu trừ đều ghi rõ hết rồi đó.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1118_05','V1118','阮明',5,'我看完明细确认无误，下次我会自己记录好出勤天数。','wǒ kàn wán míng xì què rèn wú wù， xià cì wǒ huì zì jǐ jì lù hǎo chū qín tiān shù。','Tôi xem xong bảng chi tiết thấy đúng rồi, lần sau tôi sẽ tự ghi lại số ngày đi làm cho cẩn thận.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1118_06','V1118','小吴',6,'有薪资疑问随时来找我核对，当月都可以申请补发核对差额。','yǒu xīn zī yí wèn suí shí lái zhǎo wǒ hé duì， dàng yuè dōu kě yǐ shēn qǐng bǔ fā hé duì chā é。','Có thắc mắc gì về lương cứ đến tìm tôi đối chiếu, trong tháng đều có thể xin bù chênh lệch nếu cần.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1118_07','V1118','阮明',7,'好的，辛苦你帮忙查明细啦。','hǎo de， xīn kǔ nǐ bāng máng chá míng xì la。','Được rồi, cảm ơn cô đã giúp tôi kiểm tra chi tiết nhé.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1119','SVL2','兼职老板以业绩不达标为由克扣全额底薪，协商维权',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1119','SIT1119','P1','that_bai_nhe','ban_chinh_thuc',NULL,'用人单位无权单方面克扣劳动合同约定的基础底薪，劳动者可拨打全国劳动保障热线12333维权。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1119_01','V1119','阮明',1,'店长，这个月业绩没达标，您直接扣除全部底薪，这样不符合约定吧？','diàn zhǎng， zhè ge yuè yè jì méi dá biāo， nín zhí jiē kòu chú quán bù dǐ xīn， zhè yàng bù fú hé yuē dìng ba？','Cửa hàng trưởng, tháng này doanh số không đạt mà anh trừ luôn cả lương cơ bản, vậy không đúng với thỏa thuận rồi ạ.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1119_02','V1119','王店长',2,'店里规定业绩不达标只能拿提成，底薪全部扣除。','diàn lǐ guī dìng yè jì bù dá biāo zhǐ néng ná tí chéng， dǐ xīn quán bù kòu chú。','Quy định của cửa hàng là doanh số không đạt thì chỉ được nhận hoa hồng, lương cơ bản bị trừ hết.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1119_03','V1119','阮明',3,'合同里写明底薪是固定发放，业绩只影响提成，不能扣底薪的。','hé tóng lǐ xiě míng dǐ xīn shì gù dìng fā fàng， yè jì zhǐ yǐng xiǎng tí chéng， bù néng kòu dǐ xīn de。','Trong hợp đồng ghi rõ lương cơ bản là khoản cố định, doanh số chỉ ảnh hưởng đến hoa hồng thôi, không được trừ vào lương cơ bản.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1119_04','V1119','王店长',4,'门店临时调整规则，这个月只能按新规定结算薪资。','mén diàn lín shí diào zhěng guī zé， zhè ge yuè zhǐ néng àn xīn guī dìng jié suàn xīn zī。','Cửa hàng tạm thời điều chỉnh quy định, tháng này chỉ có thể tính lương theo quy định mới thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1119_05','V1119','阮明',5,'如果协商不一致，我可以拨打12333劳动热线反映情况吗？','rú guǒ xié shāng bù yī zhì， wǒ kě yǐ bō dǎ 12333 láo dòng rè xiàn fǎn yìng qíng kuàng ma？','Nếu không thỏa thuận được, tôi có thể gọi đường dây nóng lao động 12333 để phản ánh việc này không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1119_06','V1119','王店长',6,'别投诉，我折中一下，扣除一半底薪，底薪另一半照常发放。','bié tóu sù， wǒ zhé zhōng yī xià， kòu chú yí bàn dǐ xīn， dǐ xīn lìng yí bàn zhào cháng fā fàng。','Đừng khiếu nại, tôi thỏa hiệp một chút, chỉ trừ một nửa lương cơ bản, nửa còn lại vẫn trả bình thường.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1119_07','V1119','阮明',7,'行，我接受这个方案，希望下次调整规则提前和员工沟通。','xíng， wǒ jiē shòu zhè ge fāng àn， xī wàng xià cì tiáo zhěng guī zé tí qián hé yuán gōng gōu tōng。','Được ạ, tôi chấp nhận phương án này, mong lần sau điều chỉnh quy định thì trao đổi trước với nhân viên.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1120','SVL2','询问寒暑假全职兼职薪资翻倍、加班薪酬计算标准',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1120','SIT1120','P1','suon_se','ban_chinh_thuc',NULL,'寒暑假、法定节假日兼职薪资上浮有明确计算标准，企业需提前告知员工薪酬核算规则。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1120_01','V1120','阮明',1,'小吴，寒暑假我可以全天上班，薪资会按全职标准翻倍吗？','xiǎo wú， hán shǔ jià wǒ kě yǐ quán tiān shàng bān， xīn zī huì àn quán zhí biāo zhǔn fān bèi ma？','Tiểu Ngô, kỳ nghỉ hè đông tôi có thể làm cả ngày, vậy lương có được tính gấp đôi theo chuẩn full-time không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1120_02','V1120','小吴',2,'寒暑假单日工时不超合规上限，时薪上浮百分之三十，不算翻倍。','hán shǔ jià dān rì gōng shí bù chāo hé guī shàng xiàn， shí xīn shàng fú bǎi fēn zhī sān shí， bù suàn fān bèi。','Kỳ nghỉ hè đông nếu số giờ làm trong ngày không vượt mức quy định thì lương theo giờ tăng thêm ba mươi phần trăm, không tính là gấp đôi đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1120_03','V1120','阮明',3,'那法定节假日值班，三倍薪资是包含基础时薪在内吗？','nà fǎ dìng jié jià rì zhí bān， sān bèi xīn zī shì bāo hán jī chǔ shí xīn zài nèi ma？','Vậy trực vào ngày lễ pháp định, lương gấp ba đó có bao gồm cả lương giờ cơ bản không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1120_04','V1120','小吴',4,'三倍薪酬是额外叠加，当天基础工资照常发放，叠加三倍补贴。','sān bèi xīn chóu shì é wài dié jiā， dàng tiān jī chǔ gōng zī zhào cháng fā fàng， dié jiā sān bèi bǔ tiē。','Lương gấp ba là cộng thêm riêng, lương cơ bản ngày hôm đó vẫn trả bình thường, cộng thêm phần phụ cấp gấp ba lên trên.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1120_05','V1120','阮明',5,'我清楚计算规则了，假期排班我可以多报名值班。','wǒ qīng chǔ jì suàn guī zé le， jià qī pái bān wǒ kě yǐ duō bào míng zhí bān。','Tôi hiểu cách tính rồi, đợt xếp ca nghỉ lễ tôi sẽ đăng ký trực nhiều hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1120_06','V1120','小吴',6,'好，需要假期排班提前一周和我说，我给你预留班次。','hǎo， xū yào jià qī pái bān tí qián yī zhōu hé wǒ shuō， wǒ gěi nǐ yù liú bān cì。','Được, cần xếp ca nghỉ lễ thì báo trước một tuần cho tôi, tôi sẽ giữ ca cho cậu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1120_07','V1120','阮明',7,'没问题，我会提前和你报备排班需求。','méi wèn tí， wǒ huì tí qián hé nǐ bào bèi pái bān xū qiú。','Không vấn đề gì, tôi sẽ báo trước nhu cầu xếp ca với chị.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1121','SVL2','企业发放现金工资，咨询是否合规、如何留存收入凭证',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1121','SIT1121','P1','twist','ban_chinh_thuc',NULL,'企业现金发薪合法，但外籍学生签证续签需要收入证明，现金发放需企业加盖公章出具纸质薪资证明。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1121_01','V1121','阮明',1,'店长，咱们每月发现金工资，这样发放薪资是合规的吗？','diàn zhǎng， zán men měi yuè fā xiàn jīn gōng zī， zhè yàng fā fàng xīn zī shì hé guī de ma？','Cửa hàng trưởng, hàng tháng bên mình trả lương tiền mặt, vậy phát lương kiểu này có đúng quy định không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1121_02','V1121','王店长',2,'现金发放没问题，你每次签字领取工资条留存好就行。','xiàn jīn fà fàng méi wèn tí， nǐ měi cì qiān zì lǐng qǔ gōng zī tiáo liú cún hǎo jiù xíng。','Trả tiền mặt không sao cả, mỗi lần em ký nhận và giữ lại phiếu lương là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1121_03','V1121','阮明',3,'可是我需要薪资流水用来办理签证续签，现金没有转账记录怎么办？','kě shì wǒ xū yào xīn zī liú shuǐ yòng lái bàn lǐ qiān zhèng xù qiān， xiàn jīn méi yǒu zhuǎn zhàng jì lù zěn me bàn？','Nhưng mà em cần sao kê lương để làm thủ tục gia hạn visa, tiền mặt thì không có bản ghi chuyển khoản, vậy phải làm sao ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1121_04','V1121','王店长',4,'我可以每月给你加盖门店公章的薪资证明，用来替代银行流水。','wǒ kě yǐ měi yuè gěi nǐ jiā gài mén diàn gōng zhāng de xīn zī zhèng míng， yòng lái tì dài yín háng liú shuǐ。','Anh có thể hàng tháng làm cho em giấy xác nhận lương có đóng dấu của cửa hàng, dùng để thay cho sao kê ngân hàng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1121_05','V1121','阮明',5,'每月都能开证明吗？出入境需要连续三个月收入凭证呢。','měi yuè dōu néng kāi zhèng míng ma？ chū rù jìng xū yào lián xù sān gè yuè shōu rù píng zhèng ne。','Tháng nào cũng làm được giấy xác nhận ạ? Bên xuất nhập cảnh yêu cầu chứng từ thu nhập liên tục ba tháng đó ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1121_06','V1121','王店长',6,'没问题，每月发薪当天我同步给你打印盖章薪资证明。','méi wèn tí， měi yuè fā xīn dàng tiān wǒ tóng bù gěi nǐ dǎ yìn gài zhāng xīn zī zhèng míng。','Không vấn đề gì, cứ đến ngày phát lương hàng tháng là anh in và đóng dấu giấy xác nhận lương gửi em luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1121_07','V1121','阮明',7,'太感谢了，这下不用担心签证材料缺少流水凭证。','tài gǎn xiè le， zhè xià bù yòng dān xīn qiān zhèng cái liào quē shǎo liú shuǐ píng zhèng。','Cảm ơn anh nhiều lắm, vậy là khỏi lo hồ sơ visa thiếu chứng từ thu nhập rồi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1122','SVL2','同事频繁推脱分配给自己的工作，委婉找主管协调分工',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1122','SIT1122','P1','suon_se','ban_chinh_thuc',NULL,'职场遇到同事推诿工作，优先向直属主管客观沟通协调，不直接和同事发生争执是国内职场通用处事方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1122_01','V1122','阮明',1,'陈主管，想和您沟通一下分工的小事，不知道您现在有空吗？','chén zhǔ guǎn， xiǎng hé nín gōu tōng yī xià fēn gōng de xiǎo shì， bù zhī dào nín xiàn zài yǒu kòng ma？','Chủ nhiệm Trần, em muốn trao đổi với chị một chút về việc phân công công việc, không biết chị có rảnh không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1122_02','V1122','陈主管',2,'你说，工作上有什么难处都可以直接和我讲。','nǐ shuō， gōng zuò shàng yǒu shén me nán chǔ dōu kě yǐ zhí jiē hé wǒ jiǎng。','Em cứ nói, công việc có khó khăn gì thì cứ nói thẳng với chị.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1122_03','V1122','阮明',3,'原本分配给另一位同事的工作，他总推脱交给我来完成。','yuán běn fèn pèi jǐ lìng yī wèi tóng shì de gōng zuò， tā zǒng tuī tuō jiāo gěi wǒ lái wán chéng。','Công việc vốn giao cho một bạn đồng nghiệp khác, nhưng bạn ấy cứ đùn đẩy giao cho em làm hết.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1122_04','V1122','陈主管',4,'我清楚情况，等下我和那位同事单独沟通，明确各自岗位职责。','wǒ qīng chǔ qíng kuàng， děng xià wǒ hé nà wèi tóng shì dān dú gōu tōng， míng què gè zì gǎng wèi zhí zé。','Chị hiểu tình hình rồi, lát nữa chị sẽ nói chuyện riêng với bạn đó, làm rõ trách nhiệm của từng vị trí.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1122_05','V1122','阮明',5,'我不是不愿意帮忙，只是自己手头任务也比较多，兼顾不过来。','wǒ bú shì bù yuàn yì bāng máng， zhǐ shì zì jǐ shǒu tóu rèn wù yě bǐ jiào duō， jiān gù bù guò lái。','Em không phải là không muốn giúp, chỉ là việc trong tay em cũng khá nhiều, không kham nổi thêm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1122_06','V1122','陈主管',6,'放心，我会划分清晰分工，不会让你额外承担不属于你的工作。','fàng xīn， wǒ huì huà fēn qīng xī fēn gōng， bú huì ràng nǐ é wài chéng dān bù shǔ yú nǐ de gōng zuò。','Yên tâm đi, chị sẽ phân công rõ ràng, không để em phải gánh thêm việc không thuộc phần của mình đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1122_07','V1122','阮明',7,'麻烦主管帮忙协调，我会做好自己分内所有工作。','má fán zhǔ guǎn bāng máng xié tiáo， wǒ huì zuò hǎo zì jǐ fèn nèi suǒ yǒu gōng zuò。','Phiền chị giúp em điều phối, em sẽ làm tốt hết phần việc của mình.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1123','SVL2','团建聚餐临时无法到场，提前向主管请假说明理由',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1123','SIT1123','P1','suon_se','tuy_y',NULL,'公司团建属于团队集体活动，临时无法参加提前主动请假会被视作懂礼貌，无故缺席容易给领导留下负面印象。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1123_01','V1123','阮明',1,'陈主管，今晚公司团建聚餐我没办法到场，跟您提前请假啦。','chén zhǔ guǎn， jīn wǎn gōng sī tuán jiàn jù cān wǒ méi bàn fǎ dào chǎng， gēn nín tí qián qǐng jià la。','Chủ nhiệm Trần, tối nay tiệc liên hoan team building của công ty em không tham gia được, xin phép chị trước nhé.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1123_02','V1123','陈主管',2,'怎么啦？是有什么重要的事情走不开吗？','zěn me la？ shì yǒu shén me zhòng yào de shì qíng zǒu bù kāi ma？','Sao vậy? Có việc gì quan trọng không dứt ra được à?','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1123_03','V1123','阮明',3,'今晚要和国际学院老师沟通实习备案材料，时间刚好冲突了。','jīn wǎn yào hé guó jì xué yuàn lǎo shī gōu tōng shí xí bèi àn cái liào， shí jiān gāng hǎo chōng tū le。','Tối nay em phải trao đổi với thầy cô bên khoa quốc tế về hồ sơ đăng ký thực tập, đúng lúc trùng giờ luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1123_04','V1123','陈主管',4,'没事，工作要紧，团建不去不会扣全勤，不用有压力。','méi shì， gōng zuò yào jǐn， tuán jiàn bù qù bú huì kòu quán qín， bù yòng yǒu yā lì。','Không sao, công việc quan trọng hơn, không đi team building cũng không bị trừ điểm chuyên cần đâu, đừng lo lắng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1123_05','V1123','阮明',5,'真不好意思错过团队聚餐，下次团建我一定准时参加。','zhēn bù hǎo yì sī cuò guò tuán duì jù cān， xià cì tuán jiàn wǒ yí dìng zhǔn shí cān jiā。','Thật ngại quá vì lỡ buổi liên hoan của cả nhóm, lần sau team building em nhất định tham gia đúng giờ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1123_06','V1123','陈主管',6,'没关系，我让同事帮你打包一份团建点心明天带给你。','méi guān xì， wǒ ràng tóng shì bāng nǐ dǎ bāo yī fèn tuán jiàn diǎn xīn míng tiān dài gěi nǐ。','Không sao đâu, chị nhờ đồng nghiệp gói cho em một phần đồ ăn của buổi team building, mai mang cho em.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1123_07','V1123','阮明',7,'太贴心了，多谢主管体谅！','tài tiē xīn le， duō xiè zhǔ guǎn tǐ liàng！','Chị chu đáo quá, cảm ơn chị đã thông cảm nhiều nha!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1124','SVL2','老员工私下安排额外无偿杂活，礼貌拒绝并说明岗位职责',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1124','SIT1124','P1','that_bai_nhe','tuy_y',NULL,'国内职场可礼貌拒绝不属于自身岗位职责的无偿额外工作，无需勉强自己承担无报酬劳动。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1124_01','V1124','阮明',1,'刘哥，下班之后打扫仓库不在我的岗位工作范围内，实在没办法帮忙啦。','liú gē， xià bān zhī hòu dǎ sǎo cāng kù bù zài wǒ de gǎng wèi gōng zuò fàn wéi nèi， shí zài méi bàn fǎ bāng máng la。','Anh Lưu ơi, dọn kho sau giờ làm không thuộc phạm vi công việc của em, thật sự em không giúp được ạ.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1124_02','V1124','老刘',2,'大家都是同事，顺手做一下又不麻烦，不用分得这么清楚吧？','dà jiā dōu shì tóng shì， shùn shǒu zuò yī xià yòu bù má fán， bù yòng fēn de zhè me qīng chǔ ba？','Đồng nghiệp với nhau cả, tiện tay làm chút có phiền phức gì đâu, cần phải rạch ròi vậy à?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1124_03','V1124','阮明',3,'我下班要赶去学校上课，而且额外工作没有工时记录，不符合排班规定。','wǒ xià bān yào gǎn qù xué xiào shàng kè， ér qiě é wài gōng zuò méi yǒu gōng shí jì lù， bù fú hé pái bān guī dìng。','Em tan làm phải chạy đi học, với lại làm thêm ngoài giờ không được tính công, không đúng quy định phân ca ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1124_04','V1124','老刘',4,'就一小会儿，耽误不了你多长时间，大家平时都互相帮忙的。','jiù yī xiǎo huì er， dān wù bù liǎo nǐ duō zhǎng shí jiān， dà jiā píng shí dōu hù xiāng bāng máng de。','Có chút xíu thôi mà, tốn thời gian của em bao nhiêu đâu, mọi người bình thường vẫn hay giúp nhau mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1124_05','V1124','阮明',5,'实在抱歉，我今天课程不能迟到，您可以问问当班晚班同事。','shí zài bào qiàn， wǒ jīn tiān kè chéng bù néng chí dào， nín kě yǐ wèn wèn dāng bān wǎn bān tóng shì。','Thật sự xin lỗi anh, hôm nay em không thể trễ học được, anh hỏi mấy bạn ca tối xem sao.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1124_06','V1124','老刘',6,'行吧，那我自己来收拾，下次有时间再请你搭把手。','xíng ba， nà wǒ zì jǐ lái shōu shí， xià cì yǒu shí jiān zài qǐng nǐ dā bǎ shǒu。','Thôi được, vậy để anh tự dọn, lần sau rảnh thì giúp anh một tay nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1124_07','V1124','阮明',7,'实在不好意思，之后有空我会主动搭把手帮忙。','shí zài bù hǎo yì sī， zhī hòu yǒu kòng wǒ huì zhǔ dòng dā bǎ shǒu bāng máng。','Em thật sự ngại quá, lần sau rảnh em sẽ chủ động phụ giúp ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1125','SVL2','中介收取高额兼职介绍费，拒绝付费并向市场监管投诉',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1125','SIT1125','P1','suon_se','chinh_thuc',NULL,'正规人力资源中介禁止提前收取高额介绍费，违规收费可向市场监督管理局举报维权。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1125_01','V1125','阮明',1,'小郑，还没上岗就要收五百元兼职介绍费，这个收费不合理。','xiǎo zhèng， hái méi shàng gǎng jiù yào shōu wǔ bǎi yuán jiān zhí jiè shào fèi， zhè ge shōu fèi bù hé lǐ。','Chị Trịnh, chưa đi làm mà đã thu năm trăm tệ phí giới thiệu việc làm thêm, mức phí này không hợp lý.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1125_02','V1125','小郑',2,'我们给你匹配优质岗位，介绍费是行业统一标准哦。','wǒ men gěi nǐ pǐ pèi yōu zhì gǎng wèi， jiè shào fèi shì háng yè tǒng yī biāo zhǔn ó。','Chúng tôi giúp bạn ghép công việc chất lượng, phí giới thiệu là mức chuẩn chung của ngành đó.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1125_03','V1125','阮明',3,'正规中介不能提前收取高额介绍费，我不会支付这笔费用。','zhèng guī zhōng jiè bù néng tí qián shōu qǔ gāo é jiè shào fèi， wǒ bú huì zhī fù zhè bǐ fèi yòng。','Trung tâm môi giới chính quy không được thu trước phí giới thiệu cao như vậy, tôi sẽ không trả khoản phí này.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1125_04','V1125','小郑',4,'不交钱就不给你推送岗位信息，你自己很难找到合适兼职。','bù jiāo qián jiù bù gěi nǐ tuī sòng gǎng wèi xìn xī， nǐ zì jǐ hěn nán zhǎo dào hé shì jiān zhí。','Không nộp tiền thì chúng tôi sẽ không gửi thông tin việc làm cho bạn, bạn tự tìm việc phù hợp sẽ rất khó đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1125_05','V1125','阮明',5,'我会拨打市场监管热线投诉违规收费，再见。','wǒ huì bō dǎ shì chǎng jiān guǎn rè xiàn tóu sù wéi guī shōu fèi， zài jiàn。','Tôi sẽ gọi đường dây nóng quản lý thị trường để khiếu nại việc thu phí trái quy định, chào chị.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1125_06','V1125','小郑',6,'别投诉，我不收介绍费，直接免费给你推荐岗位行不行？','bié tóu sù， wǒ bù shōu jiè shào fèi， zhí jiē miǎn fèi gěi nǐ tuī jiàn gǎng wèi xíng bù xíng？','Đừng khiếu nại mà, hay là tôi không thu phí giới thiệu nữa, giới thiệu việc miễn phí luôn cho bạn được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1125_07','V1125','阮明',7,'不必了，我不信任你们机构，会选择学校官方兼职渠道。','bù bì le， wǒ bù xìn rèn nǐ men jī gòu， huì xuǎn zé xué xiào guān fāng jiān zhí qú dào。','Không cần đâu, tôi không tin tưởng trung tâm của các người, tôi sẽ chọn kênh việc làm thêm chính thức của trường.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1126','SVL2','兼职老板拖欠工资失联，拨打12333劳动热线求助维权',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1126','SIT1126','P1','twist','chinh_thuc',NULL,'12333是全国统一劳动维权热线，外籍务工人员薪资拖欠纠纷可同等受理维权。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1126_01','V1126','阮明',1,'您好，我要投诉雇主拖欠我的兼职薪资，老板现在联系不上了。','nín hǎo， wǒ yào tóu sù gù zhǔ tuō qiàn wǒ de jiān zhí xīn zī， lǎo bǎn xiàn zài lián xì bù shàng le。','Chào anh/chị, tôi muốn khiếu nại việc chủ sử dụng lao động nợ lương làm thêm của tôi, giờ liên lạc không được với ông chủ nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1126_02','V1126','接线员',2,'请提供用工门店地址、老板联系方式、你的兼职用工协议。','qǐng tí gōng yòng gōng mén diàn dì zhǐ、 lǎo bǎn lián xì fāng shì、 nǐ de jiān zhí yòng gōng xié yì。','Bạn vui lòng cung cấp địa chỉ cửa hàng sử dụng lao động, cách liên hệ với ông chủ, và hợp đồng làm thêm của bạn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1126_03','V1126','阮明',3,'协议纸质版放在宿舍，我只有微信排班记录和聊天截图凭证。','xié yì zhǐ zhì bǎn fàng zài sù shè， wǒ zhǐ yǒu wēi xìn pái bān jì lù hé liáo tiān jié tú píng zhèng。','Bản giấy của hợp đồng để ở ký túc xá, tôi chỉ có bản ghi phân ca trên WeChat và ảnh chụp màn hình tin nhắn làm bằng chứng thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1126_04','V1126','接线员',4,'截图可以作为辅助证据，下周携带纸质协议到辖区劳动监察大队登记。','jié tú kě yǐ zuò wéi fǔ zhù zhèng jù， xià zhōu xié dài zhǐ zhì xié yì dào xiá qū láo dòng jiān chá dà duì dēng jì。','Ảnh chụp màn hình có thể dùng làm chứng cứ bổ sung, tuần sau bạn mang bản giấy hợp đồng đến đội giám sát lao động khu vực để đăng ký nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1126_05','V1126','阮明',5,'我是外籍留学生，维权流程和国内学生一样吗？','wǒ shì wài jí liú xué shēng， wéi quán liú chéng hé guó nèi xué shēng yī yàng ma？','Tôi là du học sinh nước ngoài, quy trình bảo vệ quyền lợi có giống với sinh viên trong nước không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1126_06','V1126','接线员',6,'流程完全相同，携带护照、居留卡一同前往即可受理。','liú chéng wán quán xiāng tóng， xié dài hù zhào、 jū liú kǎ yī tóng qián wǎng jí kě shòu lǐ。','Quy trình hoàn toàn giống nhau, bạn mang theo hộ chiếu, thẻ cư trú đến là được tiếp nhận xử lý ngay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1126_07','V1126','阮明',7,'好的，我下周准时过去登记，麻烦你们帮忙追回薪资。','hǎo de， wǒ xià zhōu zhǔn shí guò qù dēng jì， má fán nǐ men bāng máng zhuī huí xīn zī。','Vâng ạ, tuần sau tôi sẽ đến đăng ký đúng giờ, phiền anh/chị giúp tôi đòi lại tiền lương.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1127','SVL2','实习结束前，和人事确认实习证明盖章、发放时间',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1127','SIT1127','P1','suon_se','ban_chinh_thuc',NULL,'国内企业实习证明必须加盖公司公章，仅业务章、部门章学校不予认可，实习结束前需提前和人事确认开具时间。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1127_01','V1127','阮明',1,'小吴，我下周实习到期，想确认实习证明什么时候能盖章发放？','xiǎo wú， wǒ xià zhōu shí xí dào qī， xiǎng què rèn shí xí zhèng míng shén me shí hòu néng gài zhāng fā fàng？','Chị Ngô ơi, tuần sau là em hết thời gian thực tập rồi, em muốn xác nhận khi nào giấy chứng nhận thực tập được đóng dấu và phát ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1127_02','V1127','小吴',2,'你提交实习总结之后，三个工作日就能盖好公章交给你。','nǐ tí jiāo shí xí zǒng jié zhī hòu， sān gè gōng zuò rì jiù néng gài hǎo gōng zhāng jiāo gěi nǐ。','Sau khi em nộp bản tổng kết thực tập, ba ngày làm việc là có con dấu và giao cho em thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1127_03','V1127','阮明',3,'证明需要写明实习时长和我的岗位内容，方便学校归档对吧？','zhèng míng xū yào xiě míng shí xí shí cháng hé wǒ de gǎng wèi nèi róng， fāng biàn xué xiào guī dàng duì ba？','Giấy chứng nhận cần ghi rõ thời gian thực tập và nội dung công việc của em để trường tiện lưu hồ sơ đúng không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1127_04','V1127','小吴',4,'标准模板都会标注完整信息，用于留学、学分认定都没问题。','biāo zhǔn mú bǎn dōu huì biāo zhù wán zhěng xìn xī， yòng yú liú xué、 xué fēn rèn dìng dōu méi wèn tí。','Mẫu chuẩn đều ghi đầy đủ thông tin, dùng để du học hay công nhận tín chỉ đều không vấn đề gì.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1127_05','V1127','阮明',5,'太好了，我今天写完实习总结马上交给你。','tài hǎo le， wǒ jīn tiān xiě wán shí xí zǒng jié mǎ shàng jiāo gěi nǐ。','Tuyệt quá ạ, hôm nay em viết xong bản tổng kết là nộp cho chị ngay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1127_06','V1127','小吴',6,'提交完成后我会优先给你办理，不耽误你交回学院。','tí jiāo wán chéng hòu wǒ huì yōu xiān gěi nǐ bàn lǐ， bù dān wù nǐ jiāo huí xué yuàn。','Sau khi em nộp xong chị sẽ ưu tiên làm cho em, không để trễ hạn nộp về khoa đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1127_07','V1127','阮明',7,'辛苦你啦，这份证明对我的学业履历很重要。','xīn kǔ nǐ la， zhè fèn zhèng míng duì wǒ de xué yè lǚ lì hěn zhòng yào。','Cảm ơn chị nhiều lắm, giấy chứng nhận này quan trọng với hồ sơ học tập của em lắm ạ.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1128','SVL2','收到无薪资"免费实习"招聘邀约，咨询老师判断是否合规',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1128','SIT1128','P1','that_bai_nhe','ban_chinh_thuc',NULL,'留学生自主寻找的校外实习不属于教学必修实习，用人单位必须支付不低于当地最低兼职时薪的劳动报酬。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1128_01','V1128','阮明',1,'张老师，有家企业招无薪资免费实习，请问这种岗位合规吗？','zhāng lǎo shī， yǒu jiā qǐ yè zhāo wú xīn zī miǎn fèi shí xí， qǐng wèn zhè zhǒng gǎng wèi hé guī ma？','Cô Trương ơi, có một công ty tuyển thực tập không lương, cho em hỏi vị trí này có đúng quy định không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1128_02','V1128','张老师',2,'仅在校必修教学实习可无薪资，校外自主实习必须发放薪资。','jǐn zài xiào bì xiū jiào xué shí xí kě wú xīn zī， xiào wài zì zhǔ shí xí bì xū fà fàng xīn zī。','Chỉ có thực tập giảng dạy bắt buộc trong trường mới được không lương, thực tập ngoài trường tự nguyện thì bắt buộc phải trả lương.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1128_03','V1128','阮明',3,'这家企业说能积累履历，所以不支付实习工资，我有点心动。','zhè jiā qǐ yè shuō néng jī lěi lǚ lì， suǒ yǐ bù zhī fù shí xí gōng zī， wǒ yǒu diǎn xīn dòng。','Công ty này nói có thể tích lũy kinh nghiệm nên không trả lương thực tập, em thấy hơi xiêu lòng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1128_04','V1128','张老师',4,'无偿校外实习违反用工规定，企业会无偿占用你的劳动力。','wú cháng xiào wài shí xí wéi fǎn yòng gōng guī dìng， qǐ yè huì wú cháng zhàn yòng nǐ de láo dòng lì。','Thực tập ngoài trường không lương là vi phạm quy định lao động, công ty sẽ lợi dụng sức lao động của em mà không trả gì cả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1128_05','V1128','阮明',5,'那我直接拒绝这个邀约，重新找有薪资的正规实习岗位？','nà wǒ zhí jiē jù jué zhè ge yāo yuē， chóng xīn zhǎo yǒu xīn zī de zhèng guī shí xí gǎng wèi？','Vậy em từ chối lời mời này luôn, tìm lại vị trí thực tập chính quy có lương ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1128_06','V1128','张老师',6,'没错，我可以转发学院正规实习招聘渠道给你参考。','méi cuò， wǒ kě yǐ zhuǎn fā xué yuàn zhèng guī shí xí zhāo pìn qú dào gěi nǐ cān kǎo。','Đúng vậy, cô có thể chuyển cho em kênh tuyển thực tập chính quy của khoa để tham khảo.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1128_07','V1128','阮明',7,'多谢老师提醒，差点选择不合规的无偿实习岗位。','duō xiè lǎo shī tí xǐng， chà diǎn xuǎn zé bù hé guī de wú cháng shí xí gǎng wèi。','Em cảm ơn cô nhắc nhở nhiều lắm, suýt nữa em chọn nhầm vị trí thực tập không lương trái quy định.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1129','SVL2','兼职结束办理工作交接，核对物品归还清单避免扣款',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1129','SIT1129','P1','suon_se','ban_chinh_thuc',NULL,'离职交接时务必双方共同核对工具、物品清单并签字留存，避免后续企业以物品丢失为由克扣薪资。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1129_01','V1129','阮明',1,'小吴，我今天办理兼职离职，我们核对一下物品归还清单吧。','xiǎo wú， wǒ jīn tiān bàn lǐ jiān zhí lí zhí， wǒ men hé duì yī xià wù pǐn guī huán qīng dān ba。','Chị Ngô, hôm nay em làm thủ tục nghỉ việc làm thêm, mình cùng đối chiếu danh sách bàn giao đồ đạc nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1129_02','V1129','小吴',2,'好，工作服、工作平板、储物柜钥匙全部带来了吗？','hǎo， gōng zuò fú、 gōng zuò píng bǎn、 chǔ wù guì yào shi quán bù dài lái le ma？','Ừ, đồng phục, máy tính bảng công việc, chìa khóa tủ đồ em mang theo đủ hết chưa?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1129_03','V1129','阮明',3,'全部完好无损带来了，没有丢失、损坏任何工具物品。','quán bù wán hǎo wú sǔn dài lái le， méi yǒu diū shī、 sǔn huài rèn hé gōng jù wù pǐn。','Em mang đủ và còn nguyên vẹn hết ạ, không làm mất hay hư hỏng dụng cụ nào cả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1129_04','V1129','小吴',4,'核对完毕，物品齐全，不会产生任何物品扣款。','hé duì wán bì， wù pǐn qí quán， bú huì chǎn shēng rèn hé wù pǐn kòu kuǎn。','Đối chiếu xong rồi, đồ đạc đầy đủ, sẽ không bị trừ tiền vì đồ đạc gì cả đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1129_05','V1129','阮明',5,'太好了，我还担心弄丢配件会扣除工资呢。','tài hǎo le， wǒ hái dān xīn nòng diū pèi jiàn huì kòu chú gōng zī ne。','May quá, em còn lo làm mất phụ kiện thì bị trừ lương ấy chứ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1129_06','V1129','小吴',6,'清单我签字一份给你留存，薪资会在当月发薪日正常到账。','qīng dān wǒ qiān zì yī fèn gěi nǐ liú cún， xīn zī huì zài dàng yuè fā xīn rì zhèng cháng dào zhàng。','Danh sách chị ký một bản để em giữ, lương sẽ về đúng ngày trả lương của tháng như bình thường.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1129_07','V1129','阮明',7,'多谢这段时间照顾，有需要我随时配合后续核对。','duō xiè zhè duàn shí jiān zhào gù， yǒu xū yào wǒ suí shí pèi hé hòu xù hé duì。','Em cảm ơn chị đã chăm sóc trong thời gian qua, cần gì chị cứ gọi em phối hợp đối chiếu thêm ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1130','SVL2','暑期短期实习结束，咨询能否延长实习周期增加履历',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1130','SIT1130','P1','twist','ban_chinh_thuc',NULL,'短期实习延长周期需要企业管理层二次审批，外籍学生延长实习还需同步更新学校备案与出入境实习加注。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1130_01','V1130','阮明',1,'陈主管，我的暑期短期实习快结束了，想申请延长两个月实习周期。','chén zhǔ guǎn， wǒ de shǔ qī duǎn qī shí xí kuài jié shù le， xiǎng shēn qǐng yán cháng liǎng gè yuè shí xí zhōu qī。','Anh Trần, kỳ thực tập hè ngắn hạn của em sắp kết thúc rồi, em muốn xin gia hạn thêm hai tháng thực tập ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1130_02','V1130','陈主管',2,'门店现阶段人手充足，延长岗位我需要向上级申请审批。','mén diàn xiàn jiē duàn rén shǒu chōng zú， yán cháng gǎng wèi wǒ xū yào xiàng shàng jí shēn qǐng shěn pī。','Hiện tại cửa hàng đủ nhân lực rồi, việc gia hạn vị trí anh phải xin phê duyệt từ cấp trên.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1130_03','V1130','阮明',3,'我这段实习的工作表现您也清楚，我愿意继续认真完成工作。','wǒ zhè duàn shí xí de gōng zuò biǎo xiàn nín yě qīng chǔ， wǒ yuàn yì jì xù rèn zhēn wán chéng gōng zuò。','Anh cũng biết kết quả làm việc của em trong đợt thực tập này rồi, em sẵn sàng tiếp tục làm việc nghiêm túc ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1130_04','V1130','陈主管',4,'我明天向上级提交申请，三天内给你答复消息吧。','wǒ míng tiān xiàng shàng jí tí jiāo shēn qǐng， sān tiān nèi gěi nǐ dá fù xiāo xī ba。','Ngày mai anh sẽ nộp đơn xin lên cấp trên, trong ba ngày sẽ có phản hồi cho em nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1130_05','V1130','阮明',5,'如果审批不通过，我能不能之后寒暑假再来短期实习？','rú guǒ shěn pī bù tōng guò， wǒ néng bù néng zhī hòu hán shǔ jià zài lái duǎn qī shí xí？','Nếu không được duyệt, sau này em có thể quay lại thực tập ngắn hạn vào kỳ nghỉ hè, nghỉ đông không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1130_06','V1130','陈主管',6,'当然可以，门店长期接收留学生短期实习，优先录用你。','dāng rán kě yǐ， mén diàn zhǎng qī jiē shōu liú xué shēng duǎn qī shí xí， yōu xiān lù yòng nǐ。','Đương nhiên được, cửa hàng lâu nay vẫn nhận du học sinh thực tập ngắn hạn, sẽ ưu tiên nhận em.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1130_07','V1130','阮明',7,'麻烦主管帮忙提交申请，我会耐心等待审批结果。','má fán zhǔ guǎn bāng máng tí jiāo shēn qǐng， wǒ huì nài xīn děng dài shěn pī jié guǒ。','Phiền anh giúp em nộp đơn xin, em sẽ kiên nhẫn chờ kết quả phê duyệt ạ.',NULL) ON CONFLICT DO NOTHING;



INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT203','CP_M') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT204','CP_F') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT205','CP_H') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT206','CP_H') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT207','CP_H') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT214','CP_A') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT215','CP_A') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT216','CP_B') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT219','CP_C') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT220','CP_D') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT222','CP_E') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT224','CP_F') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT225','CP_B') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT226','CP_E') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT227','CP_G') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT236','CP_J') ON CONFLICT DO NOTHING;
