
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT815','SHT2','咨询论文致谢、摘要、关键词标准写作规范',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V815','SIT815','P1','suon_se','chinh_thuc',NULL,'国内本科毕业论文强制要求中文摘要+英文摘要、规范关键词、简短致谢，三部分有固定字数与格式标准。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L815_01','V815','阮明',1,'老师，想请教毕业论文摘要、关键词、致谢三段写作规范。','lǎo shī， xiǎng qǐng jiào bì yè lùn wén zhāi yào、 guān jiàn cí、 zhì xiè sān duàn xiě zuò guī fàn。','Thưa thầy, em muốn hỏi quy chuẩn viết ba phần tóm tắt, từ khóa và lời cảm ơn trong luận văn tốt nghiệp ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L815_02','V815','李老师',2,'摘要三百字以内，完整概括研究目的、方法、结论；关键词3-5个。','zhāi yào sān bǎi zì yǐ nèi， wán zhěng gài kuò yán jiū mù dì、 fāng fǎ、 jié lùn； guān jiàn cí 3-5 gè。','Tóm tắt viết trong khoảng ba trăm chữ, phải nêu đầy đủ mục đích nghiên cứu, phương pháp, kết luận; từ khóa từ 3 đến 5 từ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L815_03','V815','阮明',3,'致谢部分可以感谢家人、同学、授课老师，篇幅有限制吗？','zhì xiè bù fèn kě yǐ gǎn xiè jiā rén、 tóng xué、 shòu kè lǎo shī， piān fú yǒu xiàn zhì ma？','Phần cảm ơn có thể cảm ơn gia đình, bạn học, thầy cô giảng dạy, có giới hạn độ dài không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L815_04','V815','李老师',4,'致谢篇幅一页以内，简洁真诚即可，不用过度冗长抒情嘛。','zhì xiè piān fú yī yè yǐ nèi， jiǎn jié zhēn chéng jí kě， bù yòng guò dù rǒng cháng shū qíng ma。','Phần cảm ơn viết trong một trang thôi, ngắn gọn chân thành là được, không cần dài dòng bày tỏ cảm xúc quá đâu.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L815_05','V815','阮明',5,'摘要需要中英文双语版本，翻译关键词也要对应准确？','zhāi yào xū yào zhōng yīng wén shuāng yǔ bǎn běn， fān yì guān jiàn cí yě yào duì yìng zhǔn què？','Tóm tắt có cần viết cả hai thứ tiếng Việt và tiếng Trung không ạ, từ khóa dịch cũng phải chính xác tương ứng phải không thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L815_06','V815','李老师',6,'本科毕业论文摘要中英文对照，关键词逐词精准翻译。','běn kē bì yè lùn wén zhāi yào zhōng yīng wén duì zhào， guān jiàn cí zhú cí jīng zhǔn fān yì。','Luận văn tốt nghiệp đại học thì tóm tắt phải song ngữ đối chiếu, từ khóa dịch từng từ cho chính xác.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L815_07','V815','阮明',7,'我按照规范撰写三段内容，初稿写完发给您检查。','wǒ àn zhào guī fàn zhuàn xiě sān duàn nèi róng， chū gǎo xiě wán fā gěi nín jiǎn chá。','Em sẽ viết ba phần theo đúng quy chuẩn, viết xong bản nháp sẽ gửi thầy kiểm tra ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT816','SHT2','电脑崩溃丢失作业初稿，向老师说明情况申请延后上交',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V816','SIT816','P1','twist','ban_chinh_thuc',NULL,'学生设备故障丢失作业属于合理客观事由，多数老师会适度放宽提交期限，但会提醒养成云端备份文件的习惯。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L816_01','V816','阮明',1,'老师不好意思，昨晚电脑系统崩溃，存储的课程论文初稿全部丢失。','lǎo shī bù hǎo yì sī， zuó wǎn diàn nǎo xì tǒng bēng kuì， cún chǔ de kè chéng lùn wén chū gǎo quán bù diū shī。','Thầy ơi cho em xin lỗi, tối qua máy tính em bị sập hệ thống, toàn bộ bản nháp luận văn môn học lưu trên máy mất sạch rồi ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L816_02','V816','李老师',2,'有没有云端备份、U盘备份，能找回一部分写作内容吗？','yǒu méi yǒu yún duān bèi fèn、U pán bèi fèn， néng zhǎo huí yī bù fèn xiě zuò nèi róng ma？','Em có sao lưu trên mây hay trong USB không, có tìm lại được phần nào không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L816_03','V816','阮明',3,'没有及时云端同步，只保留少量手写草稿，完整电子版全部丢失嘛。','méi yǒu jí shí yún duān tóng bù， zhǐ bǎo liú shǎo liàng shǒu xiě cǎo gǎo， wán zhěng diàn zi bǎn quán bù diū shī ma。','Em không kịp đồng bộ lên mây, chỉ còn lại ít bản viết tay thôi, còn bản điện tử đầy đủ thì mất hết rồi thầy ạ.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L816_04','V816','李老师',4,'正常截止时间今天下午，突发设备故障可以延后一天提交。','zhèng cháng jié zhǐ shí jiān jīn tiān xià wǔ， tū fā shè bèi gù zhàng kě yǐ yán hòu yī tiān tí jiāo。','Hạn nộp bình thường là chiều nay, nhưng thiết bị hỏng đột xuất thì có thể lùi lại một ngày để nộp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L816_05','V816','阮明',5,'我今天通宵重新撰写，明天上午一定完整上交定稿。','wǒ jīn tiān tōng xiāo chóng xīn zhuàn xiě， míng tiān shàng wǔ yí dìng wán zhěng shàng jiāo dìng gǎo。','Em sẽ thức đêm nay viết lại từ đầu, sáng mai chắc chắn sẽ nộp bản hoàn chỉnh cuối cùng ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L816_06','V816','李老师',6,'下次重要作业记得云端备份，避免设备故障丢失全部文稿。','xià cì zhòng yào zuò yè jì de yún duān bèi fèn， bì miǎn shè bèi gù zhàng diū shī quán bù wén gǎo。','Lần sau làm bài quan trọng nhớ sao lưu lên mây, để tránh mất hết bài vở khi thiết bị hỏng nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L816_07','V816','阮明',7,'感谢老师通融延后提交，之后一定养成备份文件的习惯。','gǎn xiè lǎo shī tōng róng yán hòu tí jiāo， zhī hòu yí dìng yǎng chéng bèi fèn wén jiàn de xí guàn。','Em cảm ơn thầy đã thông cảm cho lùi hạn nộp, từ nay em nhất định sẽ tập thói quen sao lưu file ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT817','SHT2','分不清直接引用、间接转述，找助教讲解论文写作规范',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V817','SIT817','P1','suon_se','tuy_y',NULL,'学术写作严格区分直接引用与间接转述，大段无标注摘抄会判定抄袭，大幅拉高查重重复率。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L817_01','V817','阮明',1,'学长，写论文分不清直接引用和间接转述，很容易查重超标。','xué zhǎng， xiě lùn wén fēn bù qīng zhí jiē yǐn yòng hé jiàn jiē zhuǎn shù， hěn róng yì chá zhòng chāo biāo。','Anh ơi, em viết luận văn cứ lẫn lộn giữa trích dẫn trực tiếp với thuật lại gián tiếp, dễ bị trùng lặp vượt ngưỡng lắm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L817_02','V817','张学长',2,'直接引用加引号标注页码，篇幅不能过长；转述改写句式无需引号。','zhí jiē yǐn yòng jiā yǐn hào biāo zhù yè mǎ， piān fú bù néng guò cháng； zhuǎn shù gǎi xiě jù shì wú xū yǐn hào。','Trích dẫn trực tiếp thì cho vào ngoặc kép kèm số trang, không được dài quá; còn thuật lại thì phải đổi cách diễn đạt, không cần ngoặc kép.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L817_03','V817','阮明',3,'大段文献观点只能全部改写转述，不能连续直接摘抄原文对吧？','dà duàn wén xiàn guān diǎn zhǐ néng quán bù gǎi xiě zhuǎn shù， bù néng lián xù zhí jiē zhāi chāo yuán wén duì ba？','Vậy những đoạn quan điểm dài trong tài liệu chỉ được viết lại toàn bộ theo cách của mình, không được chép nguyên văn liên tục đúng không anh?','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L817_04','V817','张学长',4,'单次直接引用不能超过三行，长观点必须拆分转述融合自己分析。','dān cì zhí jiē yǐn yòng bù néng chāo guò sān xíng， zhǎng guān diǎn bì xū chāi fēn zhuǎn shù róng hé zì jǐ fēn xī。','Trích dẫn trực tiếp một lần không được quá ba dòng, quan điểm dài thì phải tách ra rồi lồng phân tích của mình vào.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L817_05','V817','阮明',5,'我拿一段自己写的文字，麻烦你标出哪里引用格式出错。','wǒ ná yī duàn zì jǐ xiě de wén zì， má fán nǐ biāo chū nǎ lǐ yǐn yòng gé shì chū cuò。','Em có một đoạn tự viết, phiền anh chỉ giúp chỗ nào trích dẫn sai định dạng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L817_06','V817','张学长',6,'没问题，逐句给你修改示范，方便你之后独立写作。','méi wèn tí， zhú jù gěi nǐ xiū gǎi shì fàn， fāng biàn nǐ zhī hòu dú lì xiě zuò。','Được thôi, anh sửa mẫu cho em từng câu một, để sau này em tự viết được luôn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L817_07','V817','阮明',7,'听完示范清晰很多，不会再出现引用违规问题。','tīng wán shì fàn qīng xī hěn duō， bú huì zài chū xiàn yǐn yòng wéi guī wèn tí。','Nghe anh làm mẫu xong em hiểu rõ hơn nhiều rồi, chắc không còn bị lỗi trích dẫn nữa đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT818','SHT2','询问期末课程论文字数下限、允许浮动范围',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V818','SIT818','P1','suon_se','ban_chinh_thuc',NULL,'课程论文、毕业论文有硬性最低正文字数要求，篇幅不足会被判定内容单薄，大幅扣分。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L818_01','V818','阮明',1,'老师，期末课程论文要求最低字数五千字，上下浮动多少算合格？','lǎo shī， qī mò kè chéng lùn wén yāo qiú zuì dī zì shù wǔ qiān zì， shàng xià fú dòng duō shǎo suàn hé gé？','Thưa cô, luận văn cuối kỳ yêu cầu tối thiểu năm nghìn chữ, dao động trên dưới bao nhiêu thì vẫn đạt ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L818_02','V818','李老师',2,'正文五千字不含摘要参考文献，上下浮动五百字以内都可接受哦。','zhèng wén wǔ qiān zì bù hán zhāi yào cān kǎo wén xiàn， shàng xià fú dòng wǔ bǎi zì yǐ nèi dōu kě jiē shòu ó。','Phần thân bài năm nghìn chữ không tính tóm tắt với tài liệu tham khảo, dao động trong khoảng năm trăm chữ đều chấp nhận được nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L818_03','V818','阮明',3,'字数不足四千五，会直接扣除论文基础分数吗？','zì shù bù zú sì qiān wǔ， huì zhí jiē kòu chú lùn wén jī chǔ fēn shù ma？','Nếu thiếu chưa đủ bốn nghìn năm trăm chữ thì có bị trừ thẳng điểm cơ bản của bài không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L818_04','V818','李老师',4,'低于四千五会判定内容单薄，基础分直接减半。','dī yú sì qiān wǔ huì pàn dìng nèi róng dān bó， jī chǔ fēn zhí jiē jiǎn bàn。','Dưới bốn nghìn năm trăm chữ sẽ bị coi là nội dung sơ sài, điểm cơ bản bị trừ một nửa luôn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L818_05','V818','阮明',5,'图表、注释文字算不算入正文字数统计？','tú biǎo、 zhù shì wén zì suàn bù suàn rù zhèng wén zì shù tǒng jì？','Vậy chữ trong biểu đồ, chú thích có tính vào tổng số chữ của thân bài không cô?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L818_06','V818','李老师',6,'图表说明、页下注释不计入，仅主体论述段落统计字数。','tú biǎo shuō míng、 yè xià zhù shì bù jì rù， jǐn zhǔ tǐ lùn shù duàn luò tǒng jì zì shù。','Phần chú thích biểu đồ, chú thích chân trang không tính vào, chỉ tính số chữ ở các đoạn lập luận chính thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L818_07','V818','阮明',7,'我控制正文五千字左右，保证内容完整不缺篇幅。','wǒ kòng zhì zhèng wén wǔ qiān zì zuǒ yòu， bǎo zhèng nèi róng wán zhěng bù quē piān fú。','Em sẽ canh phần thân bài khoảng năm nghìn chữ, đảm bảo nội dung đầy đủ không thiếu dung lượng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT819','SHT2','论文提交系统上传失败，咨询学院教务线上补交渠道',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V819','SIT819','P1','twist','ban_chinh_thuc',NULL,'课程、毕业论文线上提交系统有固定截止时间与文件格式、大小限制，超时通道自动关闭不再受理。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L819_01','V819','阮明',1,'老师，论文线上提交系统上传文档一直提示失败，无法完成提交。','lǎo shī， lùn wén xiàn shàng tí jiāo xì tǒng shàng chuán wén dàng yì zhí tí shì shī bài， wú fǎ wán chéng tí jiāo。','Thưa cô, em tải luận văn lên hệ thống nộp bài trực tuyến mãi mà cứ báo lỗi, không nộp được ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L819_02','V819','教务老师',2,'大概率文档内存过大、格式不是PDF，系统仅支持PDF格式上传嘛。','dà gài lǜ wén dàng nèi cún guò dà、 gé shì bú shì PDF， xì tǒng jǐn zhī chí PDF gé shì shàng chuán ma。','Nhiều khả năng là do file quá nặng hoặc không phải định dạng PDF, hệ thống chỉ nhận file PDF thôi đó.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L819_03','V819','阮明',3,'我原本是Word文档，直接转换PDF之后文件大小超系统限制。','wǒ yuán běn shì Word wén dàng， zhí jiē zhuǎn huàn PDF zhī hòu wén jiàn dà xiǎo chāo xì tǒng xiàn zhì。','Ban đầu em làm file Word, chuyển sang PDF xong thì dung lượng lại vượt quá giới hạn của hệ thống.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L819_04','V819','教务老师',4,'压缩PDF文件降低分辨率，缩小内存后重新进入系统提交。','yā suō PDF wén jiàn jiàng dī fēn biàn lǜ， suō xiǎo nèi cún hòu chóng xīn jìn rù xì tǒng tí jiāo。','Em nén file PDF lại, giảm độ phân giải xuống cho nhẹ rồi vào hệ thống nộp lại nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L819_05','V819','阮明',5,'今天是提交截止日，压缩完成后错过零点还能补交吗？','jīn tiān shì tí jiāo jié zhǐ rì， yā suō wán chéng hòu cuò guò líng diǎn hái néng bǔ jiāo ma？','Hôm nay là hạn chót nộp bài rồi, nếu nén xong mà lỡ qua giờ giao thừa thì còn nộp bù được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L819_06','V819','教务老师',6,'系统零点关闭通道，今晚二十三点五十九分前必须上传成功。','xì tǒng líng diǎn guān bì tōng dào， jīn wǎn èr shí sān diǎn wǔ shí jiǔ fēn qián bì xū shàng chuán chéng gōng。','Đúng nửa đêm hệ thống sẽ đóng cổng nộp bài, tối nay phải tải lên thành công trước hai mươi ba giờ năm mươi chín phút.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L819_07','V819','阮明',7,'我立刻压缩文档，赶在通道关闭前完成论文提交。','wǒ lì kè yā suō wén dàng， gǎn zài tōng dào guān bì qián wán chéng lùn wén tí jiāo。','Em nén file ngay bây giờ, cố gắng nộp xong luận văn trước khi hệ thống đóng cổng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT820','SHT3','想引用网络自媒体资料，咨询老师是否符合学术规范',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V820','SIT820','P1','that_bai_nhe','ban_chinh_thuc',NULL,'自媒体、短视频平台内容不具备学术权威性，高校论文不允许单独以此作为核心论证依据。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L820_01','V820','阮明',1,'老师，论文里想引用自媒体公众号文章的数据作为论据可以吗？','lǎo shī， lùn wén lǐ xiǎng yǐn yòng zì méi tǐ gōng zhòng hào wén zhāng de shù jù zuò wéi lùn jù kě yǐ ma？','Thưa cô, em muốn dùng số liệu từ một bài viết trên trang tự truyền thông làm luận cứ trong luận văn, có được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L820_02','V820','李老师',2,'自媒体无正规学术审核，仅能作为辅助参考，不能当作核心论据。','zì méi tǐ wú zhèng guī xué shù shěn hé， jǐn néng zuò wéi fǔ zhù cān kǎo， bù néng dàng zuò hé xīn lùn jù。','Nội dung tự truyền thông không qua thẩm định học thuật chính thống, chỉ dùng làm tham khảo phụ thôi, không thể coi là luận cứ chính được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L820_03','V820','阮明',3,'如果数据来源只有自媒体，有没有办法合规写入论文内容？','rú guǒ shù jù lái yuán zhǐ yǒu zì méi tǐ， yǒu méi yǒu bàn fǎ hé guī xiě rù lùn wén nèi róng？','Nếu nguồn số liệu chỉ có từ tự truyền thông, có cách nào đưa vào luận văn cho đúng quy chuẩn không cô?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L820_04','V820','李老师',4,'必须搭配官方期刊、统计年鉴佐证，单独自媒体内容不予认可嘛。','bì xū dā pèi guān fāng qī kān、 tǒng jì nián jiàn zuǒ zhèng， dān dú zì méi tǐ nèi róng bù yǔ rèn kě ma。','Bắt buộc phải có tạp chí chính thống, niên giám thống kê kèm theo để chứng minh, chỉ dùng riêng nội dung tự truyền thông thì không được công nhận đâu.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L820_05','V820','阮明',5,'那我放弃自媒体素材，重新检索官方行业报告替换论据。','nà wǒ fàng qì zì méi tǐ sù cái， chóng xīn jiǎn suǒ guān fāng háng yè bào gào tì huàn lùn jù。','Vậy em bỏ tư liệu tự truyền thông, tìm lại báo cáo ngành chính thức để thay thế luận cứ vậy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L820_06','V820','李老师',6,'学术论文优先采用官方、期刊、专著类权威文献资料。','xué shù lùn wén yōu xiān cǎi yòng guān fāng、 qī kān、 zhuān zhù lèi quán wēi wén xiàn zī liào。','Luận văn học thuật nên ưu tiên dùng tài liệu chính thống, tạp chí, chuyên khảo có uy tín.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L820_07','V820','阮明',7,'我重新查找正规数据源，保证论文引用符合学术标准。','wǒ chóng xīn chá zhǎo zhèng guī shù jù yuán， bǎo zhèng lùn wén yǐn yòng fú hé xué shù biāo zhǔn。','Em sẽ tìm lại nguồn số liệu chuẩn, đảm bảo phần trích dẫn trong luận văn đúng chuẩn học thuật.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT821','SHT3','咨询老师期末复习重点、必考章节范围',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V821','SIT821','P1','suon_se','ban_chinh_thuc',NULL,'期末考前老师会划定大致复习范围，缩小复习体量，但不会直接透露原题，依靠学生自主背诵理解。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L821_01','V821','阮明',1,'老师，距离期末考还有两周，想咨询课程核心复习重点章节。','lǎo shī， jù lí qī mò kǎo hái yǒu liǎng zhōu， xiǎng zī xún kè chéng hé xīn fù xí zhòng diǎn zhāng jié。','Thưa cô, còn hai tuần nữa là thi cuối kỳ, em muốn hỏi những chương trọng tâm cần ôn của môn học ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L821_02','V821','李老师',2,'课本中间四个单元是试卷主要考点，首尾单元仅少量选择题哦。','kè běn zhōng jiān sì gè dān yuán shì shì juàn zhǔ yào kǎo diǎn， shǒu wěi dān yuán jǐn shǎo liàng xuǎn zé tí ó。','Bốn đơn vị bài ở giữa sách là trọng tâm chính của đề thi, hai đơn vị đầu cuối chỉ có ít câu trắc nghiệm thôi.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L821_03','V821','阮明',3,'课后拓展阅读书目、课外补充案例会不会出大题？','kè hòu tuò zhǎn yuè dú shū mù、 kè wài bǔ chōng àn lì huì bú huì chū dà tí？','Sách đọc thêm sau bài học với các tình huống bổ sung ngoài giờ có ra vào câu lớn không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L821_04','V821','李老师',4,'大题全部来自课内课本与课堂例题，课外内容仅少量选择填空。','dà tí quán bù lái zì kè nèi kè běn yǔ kè táng lì tí， kè wài nèi róng jǐn shǎo liàng xuǎn zé tián kòng。','Câu lớn đều lấy từ sách giáo trình và ví dụ trên lớp, phần ngoài chương trình chỉ có ít câu trắc nghiệm hay điền khuyết thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L821_05','V821','阮明',5,'名词解释、论述题分别对应课本哪一部分内容？','míng cí jiě shì、 lùn shù tí fēn bié duì yìng kè běn nǎ yī bù fèn nèi róng？','Vậy phần giải thích thuật ngữ với câu luận thuật ứng với phần nào trong sách ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L821_06','V821','李老师',6,'名词解释每单元课后词汇，论述题是课堂反复讲解的核心观点。','míng cí jiě shì měi dān yuán kè hòu cí huì， lùn shù tí shì kè táng fǎn fù jiǎng jiě de hé xīn guān diǎn。','Giải thích thuật ngữ là từ vựng sau mỗi đơn vị bài, còn câu luận thuật là những quan điểm cốt lõi được giảng đi giảng lại trên lớp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L821_07','V821','阮明',7,'我优先重点复习核心单元，针对性背诵大题考点。','wǒ yōu xiān zhòng diǎn fù xí hé xīn dān yuán， zhēn duì xìng bèi sòng dà tí kǎo diǎn。','Em sẽ ưu tiên ôn kỹ các đơn vị trọng tâm, học thuộc có mục tiêu những điểm hay ra câu lớn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT822','SHT3','错过随堂小测，询问老师能否安排补测',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V822','SIT822','P1','twist','ban_chinh_thuc',NULL,'因病、公事请假缺测可凭证明补测，无故缺考无补测机会，直接扣除对应平时分。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L822_01','V822','阮明',1,'老师，上周随堂小测我生病请假，没能到场完成测试。','lǎo shī， shàng zhōu suí táng xiǎo cè wǒ shēng bìng qǐng jià， méi néng dào chǎng wán chéng cè shì。','Thưa cô, tuần trước bài kiểm tra nhỏ trên lớp em bị ốm phải nghỉ, không đến làm bài được ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L822_02','V822','李老师',2,'有医院病假证明备案的学生，可以统一参加期末前集中补测。','yǒu yī yuàn bìng jià zhèng míng bèi àn de xué shēng， kě yǐ tǒng yī cān jiā qī mò qián jí zhōng bǔ cè。','Học sinh có giấy chứng nhận nghỉ ốm của bệnh viện nộp lưu hồ sơ thì được xếp thi bù tập trung trước kỳ thi cuối kỳ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L822_03','V822','阮明',3,'我保留完整医院病历单据，今天带来给您登记备案可以吗？','wǒ bǎo liú wán zhěng yī yuàn bìng lì dān jù， jīn tiān dài lái gěi nín dēng jì bèi àn kě yǐ ma？','Em còn giữ đầy đủ hồ sơ bệnh án của bệnh viện, hôm nay mang đến để cô đăng ký lưu lại được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L822_04','V822','李老师',4,'病历登记截止本周四，周四之后不再受理补测报名嘛。','bìng lì dēng jì jié zhǐ běn zhōu sì， zhōu sì zhī hòu bù zài shòu lǐ bǔ cè bào míng ma。','Hạn đăng ký hồ sơ bệnh án là đến hết thứ Năm tuần này, sau thứ Năm sẽ không nhận đăng ký thi bù nữa đâu.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L822_05','V822','阮明',5,'补测试卷难度、分值和正常随堂小测完全一致吗？','bǔ cè shì juàn nán dù、 fēn zhí hé zhèng cháng suí táng xiǎo cè wán quán yí zhì ma？','Đề thi bù về độ khó và thang điểm có hoàn toàn giống bài kiểm tra bình thường trên lớp không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L822_06','V822','李老师',6,'题型、分值标准相同，只是作答时间缩短十分钟。','tí xíng、 fēn zhí biāo zhǔn xiāng tóng， zhǐ shì zuò dá shí jiān suō duǎn shí fēn zhōng。','Dạng đề và thang điểm giống nhau, chỉ có thời gian làm bài rút ngắn mười phút thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L822_07','V822','阮明',7,'我今天上交病假单登记，按时参加统一补测。','wǒ jīn tiān shàng jiāo bìng jià dān dēng jì， àn shí cān jiā tǒng yī bǔ cè。','Hôm nay em sẽ nộp giấy nghỉ ốm để đăng ký, đúng giờ tham gia thi bù tập trung.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT823','SHT3','期末挂科，咨询补考报名时间、复习范围',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V823','SIT823','P1','suon_se','chinh_thuc',NULL,'国内大学补考最高绩点60分，仅标记及格，无法参与奖学金评选，重修才能刷新分数。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L823_01','V823','阮明',1,'老师，这门专业课期末挂科，想咨询补考报名与复习范围。','lǎo shī， zhè mén zhuān yè kè qī mò guà kē， xiǎng zī xún bǔ kǎo bào míng yǔ fù xí fàn wéi。','Thưa thầy/cô, môn chuyên ngành này em bị rớt ở kỳ cuối, em muốn hỏi thời gian đăng ký thi lại và phạm vi ôn tập.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L823_02','V823','教务老师',2,'开学第一周线上系统开放补考报名，逾期视为自动放弃补考。','kāi xué dì yī zhōu xiàn shàng xì tǒng kāi fàng bǔ kǎo bào míng， yú qī shì wèi zì dòng fàng qì bǔ kǎo。','Tuần đầu tiên của học kỳ mới, hệ thống trực tuyến sẽ mở đăng ký thi lại, quá hạn coi như tự động từ bỏ quyền thi lại.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L823_03','V823','阮明',3,'补考试卷考点和期末试卷范围一样，还是会更换全新章节？','bǔ kǎo shì juàn kǎo diǎn hé qī mò shì juàn fàn wéi yī yàng， hái shì huì gēng huàn quán xīn zhāng jié？','Phạm vi kiến thức đề thi lại có giống đề thi cuối kỳ không, hay sẽ đổi sang chương hoàn toàn mới ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L823_04','V823','教务老师',4,'考点范围完全相同，试卷题目全部重新出题，不会使用原卷。','kǎo diǎn fàn wéi wán quán xiāng tóng， shì juàn tí mù quán bù chóng xīn chū tí， bú huì shǐ yòng yuán juǎn。','Phạm vi kiến thức hoàn toàn giống nhau, nhưng đề thi sẽ ra hoàn toàn mới, không dùng lại đề cũ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L823_05','V823','阮明',5,'补考及格即可拿到学分，补考分数会直接替代期末成绩吗？','bǔ kǎo jí gé jí kě ná dào xué fēn， bǔ kǎo fēn shù huì zhí jiē tì dài qī mò chéng jì ma？','Thi lại đạt điểm đậu là được cấp tín chỉ, điểm thi lại có được thay thế trực tiếp cho điểm cuối kỳ không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L823_06','V823','教务老师',6,'补考最高记60分及格，无论考多高都不会计入高分。','bǔ kǎo zuì gāo jì 60 fēn jí gé， wú lùn kǎo duō gāo dōu bú huì jì rù gāo fēn。','Điểm thi lại tối đa chỉ ghi nhận 60 điểm đậu, dù thi cao đến đâu cũng không tính là điểm cao.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L823_07','V823','阮明',7,'我暑假完整复习课本核心内容，开学顺利通过补考。','wǒ shǔ jià wán zhěng fù xí kè běn hé xīn nèi róng， kāi xué shùn lì tōng guò bǔ kǎo。','Em sẽ ôn kỹ toàn bộ nội dung trọng tâm trong sách suốt hè, đầu học kỳ mới sẽ thi lại đậu suôn sẻ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT824','SHT3','补考仍未通过，咨询重修选课流程与缴费标准',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V824','SIT824','P1','that_bai_nhe','chinh_thuc',NULL,'补考不及格必须重修该门课程，按学分收取重修费用，全部考核达标才能拿到对应学分。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L824_01','V824','阮明',1,'老师，补考依旧没有及格，想咨询课程重修办理流程。','lǎo shī， bǔ kǎo yī jiù méi yǒu jí gé， xiǎng zī xún kè chéng chóng xiū bàn lǐ liú chéng。','Thưa thầy/cô, em thi lại vẫn chưa đạt, em muốn hỏi quy trình đăng ký học lại môn này ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L824_02','V824','教务老师',2,'下一学期选课周期，线上系统勾选重修课程，缴纳重修学分费。','xià yī xué qī xuǎn kè zhōu qī， xiàn shàng xì tǒng gōu xuǎn chóng xiū kè chéng， jiǎo nà chóng xiū xué fēn fèi。','Vào kỳ đăng ký học phần của học kỳ tới, em chọn tick môn học lại trên hệ thống trực tuyến rồi đóng học phí học lại theo tín chỉ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L824_03','V824','阮明',3,'重修需要全程跟班上课、完成全部平时作业与课堂小测吗？','chóng xiū xū yào quán chéng gēn bān shàng kè、 wán chéng quán bù píng shí zuò yè yǔ kè táng xiǎo cè ma？','Học lại có phải theo học đầy đủ cùng lớp, hoàn thành hết bài tập thường xuyên và các bài kiểm tra trên lớp không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L824_04','V824','教务老师',4,'是的，重修完整复刻正常课程考核规则，出勤、作业、考试全部计分嘛。','shì de， chóng xiū wán zhěng fù kè zhèng cháng kè chéng kǎo hé guī zé， chū qín、 zuò yè、 kǎo shì quán bù jì fēn ma。','Đúng vậy, học lại áp dụng đầy đủ quy chế đánh giá như học bình thường, điểm danh, bài tập, thi cử đều được tính điểm hết đó.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L824_05','V824','阮明',5,'一学分重修收费标准多少，一门完整课程一共几学分？','yī xué fēn chóng xiū shōu fèi biāo zhǔn duō shǎo， yī mén wán zhěng kè chéng yī gòng jǐ xué fēn？','Mức thu phí học lại mỗi tín chỉ là bao nhiêu, và một môn học đầy đủ có tổng cộng bao nhiêu tín chỉ ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L824_06','V824','教务老师',6,'每学分一百元，本课程四学分，一次性缴纳四百元重修费。','měi xué fēn yì bǎi yuán， běn kè chéng sì xué fēn， yí cì xìng jiǎo nà sì bǎi yuán chóng xiū fèi。','Mỗi tín chỉ một trăm nghìn đồng, môn này có bốn tín chỉ, đóng một lần bốn trăm nghìn đồng phí học lại.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L824_07','V824','阮明',7,'我记下选课时间，下一学期按时报名重修认真学习。','wǒ jì xià xuǎn kè shí jiān， xià yī xué qī àn shí bào míng chóng xiū rèn zhēn xué xí。','Em ghi lại thời gian đăng ký học phần, học kỳ tới sẽ đăng ký học lại đúng hạn và học nghiêm túc.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT825','SHT3','询问考场允许携带的文具，禁止带入物品清单',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V825','SIT825','P1','suon_se','ban_chinh_thuc',NULL,'国内标准化考场严格管控随身物品，电子设备、纸质资料一律禁止带入，草稿纸统一发放回收。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L825_01','V825','阮明',1,'老师，期末考场允许携带哪些文具，有物品禁止带入考场吗？','lǎo shī， qī mò kǎo chǎng yǔn xǔ xié dài nǎ xiē wén jù， yǒu wù pǐn jìn zhǐ dài rù kǎo chǎng ma？','Thầy ơi, phòng thi cuối kỳ được mang những dụng cụ học tập nào ạ, có vật dụng nào bị cấm mang vào phòng thi không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L825_02','V825','李老师',2,'黑色签字笔、2B铅笔、橡皮、直尺可带入；手机、课本、草稿纸全部禁止哦。','hēi sè qiān zì bǐ、2B qiān bǐ、 xiàng pí、 zhí chǐ kě dài rù； shǒu jī、 kè běn、 cǎo gǎo zhǐ quán bù jìn zhǐ ó。','Bút bi mực đen, bút chì 2B, tẩy, thước kẻ thì được mang; điện thoại, sách giáo khoa, giấy nháp thì tuyệt đối cấm nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L825_03','V825','阮明',3,'透明文件袋装文具可以，彩色帆布文具袋会不会不让带进考场？','tòu míng wén jiàn dài zhuāng wén jù kě yǐ， cǎi sè fān bù wén jù dài huì bú huì bù ràng dài jìn kǎo chǎng？','Em đựng dụng cụ học tập trong túi hồ sơ trong suốt thì được, còn túi vải bố nhiều màu thì có bị cấm mang vào phòng thi không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L825_04','V825','李老师',4,'建议透明无图案文具袋，方便监考老师快速检查袋内物品。','jiàn yì tòu míng wú tú àn wén jù dài， fāng biàn jiān kǎo lǎo shī kuài sù jiǎn chá dài nèi wù pǐn。','Nên dùng túi đựng dụng cụ trong suốt, không hoa văn, để giám thị kiểm tra đồ trong túi cho nhanh.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L825_05','V825','阮明',5,'考场会统一发放草稿纸，不需要自己携带白纸对吧？','kǎo chǎng huì tǒng yī fā fàng cǎo gǎo zhǐ， bù xū yào zì jǐ xié dài bái zhǐ duì ba？','Phòng thi sẽ phát giấy nháp đồng loạt, nên em không cần tự mang giấy trắng theo đúng không ạ?','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L825_06','V825','李老师',6,'每场考试统一分发草稿纸，离场全部回收不允许带出考场。','měi chǎng kǎo shì tǒng yī fēn fā cǎo gǎo zhǐ， lí chǎng quán bù huí shōu bù yǔn xǔ dài chū kǎo chǎng。','Mỗi buổi thi đều phát giấy nháp thống nhất, hết giờ thu lại hết, không được mang ra khỏi phòng thi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L825_07','V825','阮明',7,'我只准备规定文具，不带任何禁止物品进入考场。','wǒ zhǐ zhǔn bèi guī dìng wén jù， bù dài rèn hé jìn zhǐ wù pǐn jìn rù kǎo chǎng。','Vậy em chỉ chuẩn bị đúng dụng cụ quy định thôi, không mang bất kỳ vật gì bị cấm vào phòng thi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT826','SHT3','复习资料丢失，找同学拷贝完整复习提纲',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V826','SIT826','P1','twist','tuy_y',NULL,'老师内部复习提纲属于班级专属学习材料，一般不允许跨班级大范围转发。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L826_01','V826','阮明',1,'我存复习提纲的U盘弄丢了，能不能把你的全套复习资料发我一份？','wǒ cún fù xí tí gāng de U pán nòng diū le， néng bù néng bǎ nǐ de quán tào fù xí zī liào fā wǒ yī fèn？','Cái USB lưu đề cương ôn tập của tớ bị mất rồi, cậu gửi cho tớ trọn bộ tài liệu ôn tập của cậu được không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L826_02','V826','苏雯',2,'可以全部打包发给你，但是提纲内老师标注的内部例题不能转发给其他班级。','kě yǐ quán bù dǎ bāo fā gěi nǐ， dàn shì tí gāng nèi lǎo shī biāo zhù de nèi bù lì tí bù néng zhuǎn fā gěi qí tā bān jí。','Gửi hết cho cậu cũng được, nhưng mấy bài tập mẫu nội bộ mà thầy đánh dấu trong đề cương thì không được chuyển cho lớp khác đâu nha.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L826_03','V826','阮明',3,'我只自己复习，绝不外传资料，这点你放心。','wǒ zhǐ zì jǐ fù xí， jué bù wài chuán zī liào， zhè diǎn nǐ fàng xīn。','Tớ chỉ tự ôn thôi, tuyệt đối không phát tán tài liệu ra ngoài, điểm này cậu cứ yên tâm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L826_04','V826','苏雯',4,'文件很大，微信传输容易卡顿，我分享网盘链接给你下载嘛。','wén jiàn hěn dà， wēi xìn chuán shū róng yì kǎ dùn， wǒ fēn xiǎng wǎng pán liàn jiē gěi nǐ xià zài ma。','File nặng lắm, gửi qua WeChat dễ bị đơ, để tớ chia sẻ link ổ đĩa mạng cho cậu tải về nhé.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L826_05','V826','阮明',5,'网盘下载完我立刻核对章节，补齐丢失的背诵提纲。','wǎng pán xià zài wán wǒ lì kè hé duì zhāng jié， bǔ qí diū shī de bèi sòng tí gāng。','Tải xong ở ổ đĩa mạng là tớ đối chiếu chương mục ngay, bổ sung lại phần đề cương học thuộc bị mất.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L826_06','V826','苏雯',6,'提纲划了必考背诵点，优先背诵标红大题内容。','tí gāng huà le bì kǎo bèi sòng diǎn， yōu xiān bèi sòng biāo hóng dà tí nèi róng。','Đề cương đã gạch sẵn mấy điểm chắc chắn thi rồi, ưu tiên học thuộc trước phần câu lớn được bôi đỏ nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L826_07','V826','阮明',7,'太感谢，丢失资料差点耽误期末复习进度。','tài gǎn xiè， diū shī zī liào chà diǎn dān wù qī mò fù xí jìn dù。','Cảm ơn cậu nhiều lắm, mất tài liệu suýt nữa làm chậm tiến độ ôn thi cuối kỳ của tớ rồi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT827','SHT4','咨询平时分过低，期末卷面需要多少分才能及格',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V827','SIT827','P1','suon_se','ban_chinh_thuc',NULL,'总评分数按固定比例加权计算，平时分偏低时需要更高期末卷面分数才能及格。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L827_01','V827','阮明',1,'老师，我出勤分、课堂小测得分不高，想问问期末卷面最低多少能总评及格。','lǎo shī， wǒ chū qín fēn、 kè táng xiǎo cè dé fēn bù gāo， xiǎng wèn wèn qī mò juàn miàn zuì dī duō shǎo néng zǒng píng jí gé。','Thầy ơi, điểm chuyên cần và điểm kiểm tra nhỏ trên lớp của em không cao lắm, em muốn hỏi bài thi cuối kỳ cần tối thiểu bao nhiêu điểm thì tổng kết mới đạt.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L827_02','V827','李老师',2,'平时分目前只有12分，期末试卷至少考76分，总评才能达到60分及格线。','píng shí fēn mù qián zhǐ yǒu 12 fēn， qī mò shì juàn zhì shǎo kǎo 76 fēn， zǒng píng cái néng dá dào 60 fēn jí gé xiàn。','Điểm quá trình hiện tại của em chỉ được 12 điểm, bài thi cuối kỳ phải đạt ít nhất 76 điểm thì tổng kết mới chạm ngưỡng 60 điểm đạt yêu cầu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L827_03','V827','阮明',3,'试卷满分一百分，76分难度偏高，我需要重点背诵全部大题吗？','shì juàn mǎn fēn yì bǎi fēn，76 fēn nán dù piān gāo， wǒ xū yào zhòng diǎn bèi sòng quán bù dà tí ma？','Bài thi thang điểm một trăm, mà 76 điểm thì khá khó, vậy em có cần học thuộc trọng tâm hết các câu lớn không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L827_04','V827','李老师',4,'论述、简答分值占比高，抓住大题就能拉高卷面总分。','lùn shù、 jiǎn dá fēn zhí zhàn bǐ gāo， zhuā zhù dà tí jiù néng lā gāo juàn miàn zǒng fēn。','Câu luận và câu hỏi ngắn chiếm tỷ trọng điểm cao, nắm chắc mấy câu lớn là kéo được tổng điểm bài thi lên.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L827_05','V827','阮明',5,'选择题分值低，复习时可以适当减少选择背诵时间？','xuǎn zé tí fēn zhí dī， fù xí shí kě yǐ shì dàng jiǎn shǎo xuǎn zé bèi sòng shí jiān？','Câu trắc nghiệm điểm thấp, vậy khi ôn tập em có thể giảm bớt thời gian học thuộc phần trắc nghiệm không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L827_06','V827','李老师',6,'选择保证基础分，大题尽量拿满，平衡分配复习精力。','xuǎn zé bǎo zhèng jī chǔ fēn， dà tí jǐn liàng ná mǎn， píng héng fēn pèi fù xí jīng lì。','Trắc nghiệm thì cứ giữ chắc điểm cơ bản, còn câu lớn thì cố lấy trọn điểm, phân bổ đều công sức ôn tập.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L827_07','V827','阮明',7,'我重点攻克主观大题，争取期末卷面达标顺利及格。','wǒ zhòng diǎn gōng kè zhǔ guān dà tí， zhēng qǔ qī mò juàn miàn dá biāo shùn lì jí gé。','Vậy em sẽ tập trung chinh phục các câu lớn tự luận, cố gắng để bài thi cuối kỳ đạt chuẩn và qua môn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT828','SHT4','选课系统卡顿抢不到心仪选修课，咨询教务调剂方案',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V828','SIT828','P1','twist','ban_chinh_thuc',NULL,'高校选修课名额有限，首轮选满只能等待学生退课产生空位，无人工扩容插队渠道。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L828_01','V828','阮明',1,'老师，线上选课系统卡顿，我心仪的汉语文化选修课已经选满关闭。','lǎo shī， xiàn shàng xuǎn kè xì tǒng kǎ dùn， wǒ xīn yí de hàn yǔ wén huà xuǎn xiū kè yǐ jīng xuǎn mǎn guān bì。','Thầy ơi, hệ thống đăng ký học online bị đơ, môn tự chọn văn hóa Hán ngữ mà em thích đã đầy chỗ và đóng đăng ký rồi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L828_02','V828','教务老师',2,'首轮选课结束后有一轮补选调剂通道，三天后系统重新开放空位。','shǒu lún xuǎn kè jié shù hòu yǒu yī lún bǔ xuǎn diào jì tōng dào， sān tiān hòu xì tǒng chóng xīn kāi fàng kōng wèi。','Sau vòng đăng ký đầu tiên sẽ có một đợt đăng ký bổ sung và điều chỉnh, ba ngày nữa hệ thống sẽ mở lại các suất trống.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L828_03','V828','阮明',3,'补选通道是随机释放退课空位，还是可以人工登记插队？','bǔ xuǎn tōng dào shì suí jī shì fàng tuì kè kòng wèi， hái shì kě yǐ rén gōng dēng jì chā duì？','Đợt đăng ký bổ sung là ngẫu nhiên phát chỗ trống do người khác hủy đăng ký, hay là có thể đăng ký thủ công để xếp trước ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L828_04','V828','教务老师',4,'无人工插队登记，只能等待其他学生退课后系统自动释放名额嘛。','wú rén gōng chā duì dēng jì， zhǐ néng děng dài qí tā xué shēng tuì kè hòu xì tǒng zì dòng shì fàng míng é ma。','Không có chuyện đăng ký thủ công để xếp trước đâu, chỉ có thể chờ sinh viên khác hủy môn rồi hệ thống tự động cấp suất thôi nha.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L828_05','V828','阮明',5,'如果补选依旧抢不到，有没有同类型替代选修课推荐？','rú guǒ bǔ xuǎn yī jiù qiǎng bú dào， yǒu méi yǒu tóng lèi xíng tì dài xuǎn xiū kè tuī jiàn？','Nếu đợt bổ sung vẫn không đăng ký được thì có môn tự chọn nào cùng loại để thay thế không thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L828_06','V828','教务老师',6,'有两门民俗类选修课内容相近，难度、学分完全一致。','yǒu liǎng mén mín sú lèi xuǎn xiū kè nèi róng xiāng jìn， nán dù、 xué fēn wán quán yí zhì。','Có hai môn tự chọn về văn hóa dân gian nội dung khá tương tự, độ khó và số tín chỉ hoàn toàn giống nhau.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L828_07','V828','阮明',7,'三天后准时登录系统补选，备选同步勾选民俗课程。','sān tiān hòu zhǔn shí dēng lù xì tǒng bǔ xuǎn， bèi xuǎn tóng bù gōu xuǎn mín sú kè chéng。','Vậy ba ngày nữa em sẽ đăng nhập đúng giờ để đăng ký bổ sung, đồng thời tick chọn thêm môn văn hóa dân gian làm phương án dự phòng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT829','SHT4','选错课程，咨询退课截止时间、退课学分规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V829','SIT829','P1','suon_se','ban_chinh_thuc',NULL,'开学初期设有免费退课窗口期，窗口期外放弃课程会判定弃考挂科，影响学籍学分记录。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L829_01','V829','阮明',1,'老师，我选课误选高阶汉语课程，自身基础跟不上，想办理退课。','lǎo shī， wǒ xuǎn kè wù xuǎn gāo jiē hàn yǔ kè chéng， zì shēn jī chǔ gēn bù shàng， xiǎng bàn lǐ tuì kè。','Thầy ơi, em đăng ký nhầm phải môn Hán ngữ nâng cao, nền tảng bản thân không theo kịp, em muốn xin rút môn ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L829_02','V829','教务老师',2,'开学第二周周五是免费退课截止日，退课后学分不计入本学期修读记录。','kāi xué dì èr zhōu zhōu wǔ shì miǎn fèi tuì kè jié zhǐ rì， tuì kè hòu xué fēn bù jì rù běn xué qī xiū dú jì lù。','Thứ Sáu tuần thứ hai của học kỳ là hạn chót rút môn miễn phí, rút sau đó thì tín chỉ sẽ không tính vào hồ sơ học tập kỳ này.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L829_03','V829','阮明',3,'超过截止日期再退课，会标记课程挂科记录在学籍系统吗？','chāo guò jié zhǐ rì qī zài tuì kè， huì biāo jì kè chéng guà kē jì lù zài xué jí xì tǒng ma？','Nếu quá hạn mới rút môn thì có bị ghi vào hệ thống hồ sơ học tập là môn trượt không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L829_04','V829','教务老师',4,'逾期退课按弃考处理，直接记挂科，需要后续重修缴费。','yú qī tuì kè àn qì kǎo chǔ lǐ， zhí jiē jì guà kē， xū yào hòu xù chóng xiū jiǎo fèi。','Rút môn trễ hạn thì tính như bỏ thi, ghi thẳng là trượt môn, sau này phải học lại và đóng học phí lại.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L829_05','V829','阮明',5,'今天周二，我现在线上提交退课申请，来得及免费撤销课程。','jīn tiān zhōu èr， wǒ xiàn zài xiàn shàng tí jiāo tuì kè shēn qǐng， lái de jí miǎn fèi chè xiāo kè chéng。','Hôm nay là thứ Ba, em nộp đơn rút môn online ngay bây giờ thì vẫn kịp hủy môn miễn phí đúng không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L829_06','V829','教务老师',6,'线上申请提交后一小时内系统自动审核完成退课。','xiàn shàng shēn qǐng tí jiāo hòu yī xiǎo shí nèi xì tǒng zì dòng shěn hé wán chéng tuì kè。','Sau khi nộp đơn online, trong vòng một tiếng hệ thống sẽ tự động duyệt xong việc rút môn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L829_07','V829','阮明',7,'我立刻操作退课，重新选择适配我水平的基础选修课。','wǒ lì kè cāo zuò tuì kè， chóng xīn xuǎn zé shì pèi wǒ shuǐ píng de jī chǔ xuǎn xiū kè。','Vậy em thao tác rút môn ngay, rồi chọn lại môn tự chọn cơ bản phù hợp với trình độ của mình.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT830','SHT4','申请开具在校在读证明用于签证、实习',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V830','SIT830','P1','suon_se','chinh_thuc',NULL,'学院加盖公章的在读证明属于官方学籍凭证，出入境、企业实习均认可其法律效力，复印件无公章无效。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L830_01','V830','阮明',1,'老师，我需要官方在校在读证明，用于续签居留许可和校外实习备案。','lǎo shī， wǒ xū yào guān fāng zài xiào zài dú zhèng míng， yòng yú xù qiān jū liú xǔ kě hé xiào wài shí xí bèi àn。','Thưa thầy, em cần giấy xác nhận đang học chính thức, để dùng gia hạn giấy phép cư trú và đăng ký thực tập bên ngoài trường.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L830_02','V830','教务老师',2,'填写纸质申请表，携带护照、学生证，当场打印加盖学院公章哦。','tián xiě zhǐ zhì shēn qǐng biǎo， xié dài hù zhào、 xué shēng zhèng， dāng chǎng dǎ yìn jiā gài xué yuàn gōng zhāng ó。','Em điền vào mẫu đơn giấy, mang theo hộ chiếu và thẻ sinh viên, chúng tôi sẽ in tại chỗ và đóng dấu chính thức của khoa ngay ạ.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L830_03','V830','阮明',3,'证明可以一次性打印两份，签证、实习分开使用吗？','zhèng míng kě yǐ yí cì xìng dǎ yìn liǎng fèn， qiān zhèng、 shí xí fēn kāi shǐ yòng ma？','Giấy xác nhận có thể in một lần được hai bản để dùng riêng cho visa và thực tập không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L830_04','V830','教务老师',4,'无份数限制，需要几份直接说明，全部同步盖章生效。','wú fèn shù xiàn zhì， xū yào jǐ fèn zhí jiē shuō míng， quán bù tóng bù gài zhāng shēng xiào。','Không giới hạn số bản, cần bao nhiêu bản cứ nói rõ, tất cả sẽ được đóng dấu có hiệu lực cùng lúc.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L830_05','V830','阮明',5,'在读证明开具完成，当天就能直接拿去出入境大厅办理签证？','zài dú zhèng míng kāi jù wán chéng， dàng tiān jiù néng zhí jiē ná qù chū rù jìng dà tīng bàn lǐ qiān zhèng？','Giấy xác nhận đang học làm xong là ngay hôm đó em có thể mang thẳng đến phòng xuất nhập cảnh để làm visa được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L830_06','V830','教务老师',6,'盖红色公章的原件具备官方效力，可直接用于签证、实习备案。','gài hóng sè gōng zhāng de yuán jiàn jù bèi guān fāng xiào lì， kě zhí jiē yòng yú qiān zhèng、 shí xí bèi àn。','Bản gốc có đóng dấu đỏ chính thức là có giá trị pháp lý, có thể dùng trực tiếp cho visa và đăng ký thực tập.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L830_07','V830','阮明',7,'我填好申请表，现在提交办理两份在读证明。','wǒ tián hǎo shēn qǐng biǎo， xiàn zài tí jiāo bàn lǐ liǎng fèn zài dú zhèng míng。','Vậy em điền xong mẫu đơn rồi, giờ nộp luôn để xin làm hai bản giấy xác nhận đang học ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT831','SHT4','咨询学分修读进度，还差多少学分满足毕业要求',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V831','SIT831','P1','twist','chinh_thuc',NULL,'本科有硬性毕业总学分底线，综测竞赛加分仅用于评优，不能抵扣必修、选修毕业学分。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L831_01','V831','阮明',1,'老师，想核对我已修学分总数，还差多少学分才能达标毕业。','lǎo shī， xiǎng hé duì wǒ yǐ xiū xué fēn zǒng shù， hái chà duō shǎo xué fēn cái néng dá biāo bì yè。','Thưa thầy, em muốn kiểm tra lại tổng số tín chỉ đã học của mình, còn thiếu bao nhiêu tín chỉ nữa mới đủ điều kiện tốt nghiệp ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L831_02','V831','教务老师',2,'毕业总学分要求140分，你目前只修满112分，还差28学分。','bì yè zǒng xué fēn yāo qiú 140 fēn， nǐ mù qián zhǐ xiū mǎn 112 fēn， hái chà 28 xué fēn。','Yêu cầu tổng tín chỉ tốt nghiệp là 140 tín chỉ, hiện tại em mới học được 112 tín chỉ, còn thiếu 28 tín chỉ nữa.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L831_03','V831','阮明',3,'剩余学分只能靠专业课、选修课补齐，没有其他加分渠道吗？','shèng yú xué fēn zhǐ néng kào zhuān yè kè、 xuǎn xiū kè bǔ qí， méi yǒu qí tā jiā fēn qú dào ma？','Số tín chỉ còn thiếu chỉ có thể bù bằng môn chuyên ngành và môn tự chọn thôi ạ, không còn kênh cộng điểm nào khác sao thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L831_04','V831','教务老师',4,'竞赛、论文综测加分不抵扣毕业学分，仅用于奖学金评选嘛。','jìng sài、 lùn wén zōng cè jiā fēn bù dǐ kòu bì yè xué fēn， jǐn yòng yú jiǎng xué jīn píng xuǎn ma。','Điểm cộng từ thi đấu hay bài luận đánh giá tổng hợp không được khấu trừ vào tín chỉ tốt nghiệp đâu, chỉ dùng để xét học bổng thôi nha.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L831_05','V831','阮明',5,'剩余两个学期，平均每学期需要修十四分才能按时毕业？','shèng yú liǎng gè xué qī， píng jūn měi xué qī xū yào xiū shí sì fēn cái néng àn shí bì yè？','Còn hai học kỳ nữa, trung bình mỗi kỳ em cần học đủ mười bốn tín chỉ mới tốt nghiệp đúng hạn được đúng không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L831_06','V831','教务老师',6,'没错，每学期至少七门课程，不能大量少选学分课。','méi cuò， měi xué qī zhì shǎo qī mén kè chéng， bù néng dà liàng shǎo xuǎn xué fēn kè。','Đúng vậy, mỗi kỳ ít nhất phải học bảy môn, không được chọn quá ít môn dẫn đến thiếu tín chỉ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L831_07','V831','阮明',7,'我之后每学期足额选课，保证按期修满毕业学分。','wǒ zhī hòu měi xué qī zú é xuǎn kè， bǎo zhèng àn qī xiū mǎn bì yè xué fēn。','Vậy từ giờ mỗi kỳ em sẽ đăng ký đủ số môn, đảm bảo học đủ tín chỉ tốt nghiệp đúng thời hạn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT832','SHT4','咨询辅修专业报名条件、额外课时安排',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V832','SIT832','P1','suon_se','ban_chinh_thuc',NULL,'国内高校辅修专业面向成绩合格无挂科学生开设，授课集中周末，完成后发放独立辅修证明。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L832_01','V832','阮明',1,'老师，想报名外贸辅修专业，请问报名基础条件有哪些？','lǎo shī， xiǎng bào míng wài mào fǔ xiū zhuān yè， qǐng wèn bào míng jī chǔ tiáo jiàn yǒu nǎ xiē？','Thưa thầy, em muốn đăng ký ngành học phụ về ngoại thương, xin hỏi điều kiện cơ bản để đăng ký là gì ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L832_02','V832','教务老师',2,'本专业平均分70分以上，无挂科记录，大二可提交辅修申请。','běn zhuān yè píng jūn fēn 70 fēn yǐ shàng， wú guà kē jì lù， dà èr kě tí jiāo fǔ xiū shēn qǐng。','Điểm trung bình chuyên ngành chính từ 70 điểm trở lên, không có môn trượt, sinh viên năm hai có thể nộp đơn đăng ký học phụ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L832_03','V832','阮明',3,'辅修课程全部安排在周末，会不会和本专业课程冲突？','fǔ xiū kè chéng quán bù ān pái zài zhōu mò， huì bú huì hé běn zhuān yè kè chéng chōng tū？','Các môn học phụ đều xếp vào cuối tuần, vậy có bị trùng với các môn chuyên ngành chính không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L832_04','V832','教务老师',4,'辅修统一周六全天授课，工作日无额外课时，不会冲突主修课。','fǔ xiū tǒng yī zhōu liù quán tiān shòu kè， gōng zuò rì wú é wài kè shí， bú huì chōng tū zhǔ xiū kè。','Học phụ được xếp học trọn ngày thứ Bảy, không có tiết học thêm vào ngày thường, nên sẽ không trùng với môn chính đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L832_05','V832','阮明',5,'辅修完成后发放辅修证书，证书和主修毕业证一同发放吗？','fǔ xiū wán chéng hòu fā fàng fǔ xiū zhèng shū， zhèng shū hé zhǔ xiū bì yè zhèng yī tóng fā fàng ma？','Sau khi hoàn thành học phụ sẽ được cấp chứng chỉ, chứng chỉ này có được phát cùng lúc với bằng tốt nghiệp chuyên ngành chính không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L832_06','V832','教务老师',6,'毕业时同步发放辅修结业证明，求职可作为专业补充凭证。','bì yè shí tóng bù fā fàng fǔ xiū jié yè zhèng míng， qiú zhí kě zuò wéi zhuān yè bǔ chōng píng zhèng。','Khi tốt nghiệp sẽ cấp đồng thời giấy chứng nhận hoàn thành học phụ, có thể dùng làm minh chứng chuyên môn bổ sung khi xin việc.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L832_07','V832','阮明',7,'我本学期稳住平均分，下学期申请报名外贸辅修。','wǒ běn xué qī wěn zhù píng jūn fēn， xià xué qī shēn qǐng bào míng wài mào fǔ xiū。','Vậy học kỳ này em sẽ giữ vững điểm trung bình, học kỳ sau sẽ nộp đơn đăng ký học phụ ngoại thương.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT833','SHT4','教务系统个人信息拼音拼写错误，申请更正学籍信息',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V833','SIT833','P1','twist','chinh_thuc',NULL,'学籍姓名、国籍、证件号属于锁定核心信息，学生无法线上自行修改，必须线下提交证件佐证人工更正。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L833_01','V833','阮明',1,'老师，教务系统里我的姓名拼音拼写错误，和护照不一致影响办签证。','lǎo shī， jiào wù xì tǒng lǐ wǒ de xìng míng pīn yīn pīn xiě cuò wù， hé hù zhào bù yī zhì yǐng xiǎng bàn qiān zhèng。','Thưa thầy/cô, tên em ghi trong hệ thống giáo vụ bị sai phần phiên âm, không khớp với hộ chiếu nên ảnh hưởng đến việc xin visa ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L833_02','V833','教务老师',2,'填写学籍信息变更申请表，附上护照原件复印件佐证正确拼写。','tián xiě xué jí xìn xī biàn gēng shēn qǐng biǎo， fù shàng hù zhào yuán jiàn fù yìn jiàn zuǒ zhèng zhèng què pīn xiě。','Em điền vào mẫu đơn đề nghị thay đổi thông tin học tịch, kèm theo bản photo hộ chiếu gốc để làm căn cứ đối chiếu cách viết đúng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L833_03','V833','阮明',3,'线上系统不能自行修改，必须线下纸质申请人工后台更正嘛。','xiàn shàng xì tǒng bù néng zì xíng xiū gǎi， bì xū xiàn xià zhǐ zhì shēn qǐng rén gōng hòu tái gēng zhèng ma。','Vậy là hệ thống online không tự sửa được, phải nộp đơn giấy trực tiếp để bộ phận hậu đài chỉnh sửa thủ công đúng không ạ?','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L833_04','V833','教务老师',4,'学籍核心姓名属于锁定信息，仅教务管理员有权限后台修改。','xué jí hé xīn xìng míng shǔ yú suǒ dìng xìn xī， jǐn jiào wù guǎn lǐ yuán yǒu quán xiàn hòu tái xiū gǎi。','Tên trong học tịch là thông tin cốt lõi bị khóa, chỉ quản trị viên giáo vụ mới có quyền sửa ở hậu đài.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L833_05','V833','阮明',5,'提交申请表之后，多久能同步更新全校教务系统信息？','tí jiāo shēn qǐng biǎo zhī hòu， duō jiǔ néng tóng bù gēng xīn quán xiào jiào wù xì tǒng xìn xī？','Sau khi nộp đơn thì bao lâu thông tin sẽ được đồng bộ cập nhật trên toàn hệ thống giáo vụ của trường ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L833_06','V833','教务老师',6,'三个工作日内完成修改，更新后打印成绩单姓名同步更正。','sān gè gōng zuò rì nèi wán chéng xiū gǎi， gēng xīn hòu dǎ yìn chéng jì dān xìng míng tóng bù gēng zhèng。','Trong vòng ba ngày làm việc sẽ sửa xong, sau khi cập nhật thì tên trên bảng điểm in ra cũng sẽ được sửa đồng bộ theo.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L833_07','V833','阮明',7,'我带好护照复印件，今天提交信息变更申请表。','wǒ dài hǎo hù zhào fù yìn jiàn， jīn tiān tí jiāo xìn xī biàn gēng shēn qǐng biǎo。','Vậy em mang theo bản photo hộ chiếu, hôm nay nộp đơn đề nghị thay đổi thông tin luôn ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT834','SHT5','打印官方成绩单用于升学，咨询打印盖章流程',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V834','SIT834','P1','suon_se','ban_chinh_thuc',NULL,'境外升学、签证使用的成绩单必须校内官方纸质打印+鲜红公章，自行截图打印无法律效力。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L834_01','V834','阮明',1,'老师，我准备升学深造，需要多份加盖公章的官方成绩单。','lǎo shī， wǒ zhǔn bèi shēng xué shēn zào， xū yào duō fèn jiā gài gōng zhāng de guān fāng chéng jì dān。','Thưa thầy/cô, em chuẩn bị học lên cao hơn nên cần vài bản bảng điểm chính thức có đóng dấu đỏ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L834_02','V834','教务老师',2,'线上系统预约打印，预约完成携带学生证线下领取盖章成绩单哦。','xiàn shàng xì tǒng yù yuē dǎ yìn， yù yuē wán chéng xié dài xué shēng zhèng xiàn xià lǐng qǔ gài zhāng chéng jì dān ó。','Em đặt lịch in trên hệ thống online, đặt xong thì mang thẻ sinh viên đến lấy bảng điểm đã đóng dấu nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L834_03','V834','阮明',3,'电子版成绩单截图自行打印，能不能加盖学院公章？','diàn zi bǎn chéng jì dān jié tú zì xíng dǎ yìn， néng bù néng jiā gài xué yuàn gōng zhāng？','Nếu em tự chụp màn hình bảng điểm điện tử rồi tự in ra thì có được đóng dấu của khoa không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L834_04','V834','教务老师',4,'仅校内打印机输出的官方纸质成绩单可盖章，自行打印截图无效。','jǐn xiào nèi dǎ yìn jī shū chū de guān fāng zhǐ zhì chéng jì dān kě gài zhāng， zì xíng dǎ yìn jié tú wú xiào。','Chỉ bảng điểm chính thức in từ máy in trong trường mới được đóng dấu, tự chụp màn hình rồi in ra thì không có giá trị đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L834_05','V834','阮明',5,'一次最多能打印五份，每份都单独加盖红色公章吗？','yī cì zuì duō néng dǎ yìn wǔ fèn， měi fèn dōu dān dú jiā gài hóng sè gōng zhāng ma？','Một lần em có thể in tối đa bao nhiêu bản, mỗi bản đều được đóng dấu đỏ riêng ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L834_06','V834','教务老师',6,'每份独立盖章，全部具备同等官方效力用于境外升学。','měi fèn dú lì gài zhāng， quán bù jù bèi tóng děng guān fāng xiào lì yòng yú jìng wài shēng xué。','Mỗi bản đều được đóng dấu riêng, tất cả đều có giá trị chính thức như nhau, dùng để học lên ở nước ngoài được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L834_07','V834','阮明',7,'我线上预约打印五份成绩单，下午来办公室领取。','wǒ xiàn shàng yù yuē dǎ yìn wǔ fèn chéng jì dān， xià wǔ lái bàn gōng shì lǐng qǔ。','Vậy em đặt lịch in năm bản bảng điểm trên hệ thống online, chiều nay em qua văn phòng lấy ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
