INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L836_02','V836','管理员',2,'图书馆阅览区禁止大声交谈，我过去提醒两位同学保持安静。','tú shū guǎn yuè lǎn qū jìn zhǐ dà shēng jiāo tán， wǒ guò qù tí xǐng liǎng wèi tóng xué bǎo chí ān jìng。','Khu đọc sách của thư viện cấm nói chuyện lớn tiếng, để tôi qua nhắc hai bạn đó giữ trật tự.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L836_03','V836','阮明',3,'如果他们需要小组讨论，有没有专门的讨论室可以转移过去？','rú guǒ tā men xū yào xiǎo zǔ tǎo lùn， yǒu méi yǒu zhuān mén de tǎo lùn shì kě yǐ zhuǎn yí guò qù？','Nếu hai bạn đó cần thảo luận nhóm thì có phòng thảo luận riêng để chuyển sang không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L836_04','V836','管理员',4,'一楼设有独立小组研讨室，交谈类学习活动统一安排在研讨室嘛。','yī lóu shè yǒu dú lì xiǎo zǔ yán tǎo shì， jiāo tán lèi xué xí huó dòng tǒng yī ān pái zài yán tǎo shì ma。','Tầng một có phòng thảo luận nhóm riêng, các hoạt động học tập cần trao đổi đều được sắp xếp vào phòng thảo luận đó cả mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L836_05','V836','阮明',5,'我想要全程安静无交谈的区域，能不能调整我的自习座位？','wǒ xiǎng yào quán chéng ān jìng wú jiāo tán de qū yù， néng bù néng tiáo zhěng wǒ de zì xí zuò wèi？','Em muốn ngồi ở khu vực hoàn toàn yên tĩnh, không ai nói chuyện, vậy có thể đổi chỗ ngồi cho em không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L836_06','V836','管理员',6,'二楼深度自习区全程静音，我带你去空位落座不受打扰。','èr lóu shēn dù zì xí qū quán chéng jìng yīn， wǒ dài nǐ qù kòng wèi luò zuò bù shòu dǎ rǎo。','Khu tự học chuyên sâu ở tầng hai im lặng hoàn toàn, để tôi dẫn em đến chỗ trống ngồi, không bị làm phiền đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L836_07','V836','阮明',7,'感谢协调安静自习区域，方便我专心复习期末内容。','gǎn xiè xié tiáo ān jìng zì xí qū yù， fāng biàn wǒ zhuān xīn fù xí qī mò nèi róng。','Cảm ơn anh/chị đã sắp xếp khu vực yên tĩnh, giờ em có thể yên tâm tập trung ôn thi cuối kỳ rồi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT837','SHT5','报名校内学术讲座，咨询签到、综测加分规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V837','SIT837','P1','suon_se','tuy_y',NULL,'国内高校综测体系包含学术讲座、竞赛加分，需全程到场完成签到流程才能录入加分记录。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L837_01','V837','阮明',1,'你好，我想报名本周外贸学术讲座，请问参与能综测加分吗？','nǐ hǎo， wǒ xiǎng bào míng běn zhōu wài mào xué shù jiǎng zuò， qǐng wèn cān yù néng zōng cè jiā fēn ma？','Chào anh, em muốn đăng ký buổi hội thảo học thuật về ngoại thương tuần này, tham gia có được cộng điểm tổng hợp không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L837_02','V837','干事',2,'现场签到、听完讲座提交简短心得，一次讲座加0.2综测分哦。','xiàn chǎng qiān dào、 tīng wán jiǎng zuò tí jiāo jiǎn duǎn xīn dé， yī cì jiǎng zuò jiā 0.2 zōng cè fēn ó。','Điểm danh trực tiếp, nghe xong hội thảo nộp bài thu hoạch ngắn, mỗi buổi được cộng 0.2 điểm tổng hợp nha.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L837_03','V837','阮明',3,'讲座时长两小时，中途提前离场还能正常计入加分吗？','jiǎng zuò shí cháng liǎng xiǎo shí， zhōng tú tí qián lí chǎng hái néng zhèng cháng jì rù jiā fēn ma？','Hội thảo kéo dài hai tiếng, nếu giữa chừng ra về sớm thì có được tính cộng điểm bình thường không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L837_04','V837','干事',4,'全程听完签到两次（入场、散场），中途离场不予记录加分。','quán chéng tīng wán qiān dào liǎng cì （rù chǎng、 sàn chǎng）， zhōng tú lí chǎng bù yǔ jì lù jiā fēn。','Phải nghe hết toàn bộ và điểm danh hai lần (lúc vào, lúc tan), ra về giữa chừng thì không được ghi nhận cộng điểm đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L837_05','V837','阮明',5,'讲座名额有限，需要提前线上报名锁定席位吗？','jiǎng zuò míng é yǒu xiàn， xū yào tí qián xiàn shàng bào míng suǒ dìng xí wèi ma？','Số suất tham gia hội thảo có hạn, vậy có cần đăng ký trước trên mạng để giữ chỗ không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L837_06','V837','干事',6,'线上小程序提前预约，无预约现场有空位也可临时入场。','xiàn shàng xiǎo chéng xù tí qián yù yuē， wú yù yuē xiàn chǎng yǒu kòng wèi yě kě lín shí rù chǎng。','Đặt chỗ trước qua app mini trên mạng, nếu không đặt trước mà tại chỗ còn suất trống thì vẫn có thể vào tạm được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L837_07','V837','阮明',7,'我线上预约席位，全程参与讲座完成签到拿综测加分。','wǒ xiàn shàng yù yuē xí wèi， quán chéng cān yù jiǎng zuò wán chéng qiān dào ná zōng cè jiā fēn。','Vậy em đặt chỗ trước trên mạng, tham gia đầy đủ hội thảo, điểm danh xong để lấy điểm cộng tổng hợp.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT838','SHT5','和中国同学结成语言交换搭档，约定每周练习时段',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V838','SIT838','P1','suon_se','tuy_y',NULL,'高校留学生与本国学生结成语言交换搭档是普遍互助学习方式，双方互相教授母语，零成本提升口语能力。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L838_01','V838','阮明',1,'我们结成语言交换搭档吧，我教你越南语，你帮我练习汉语。','wǒ men jié chéng yǔ yán jiāo huàn dā dàng ba， wǒ jiāo nǐ yuè nán yǔ， nǐ bāng wǒ liàn xí hàn yǔ。','Hay là mình kết đôi trao đổi ngôn ngữ đi, tớ dạy cậu tiếng Việt, cậu giúp tớ luyện tiếng Trung nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L838_02','V838','苏雯',2,'太好了，每周三傍晚两小时，一半时间汉语、一半越南语互换练习。','tài hǎo le， měi zhōu sān bàng wǎn liǎng xiǎo shí， yí bàn shí jiān hàn yǔ、 yí bàn yuè nán yǔ hù huàn liàn xí。','Tuyệt quá, mỗi tuần chiều tối thứ Tư hai tiếng, một nửa thời gian nói tiếng Trung, một nửa nói tiếng Việt để luyện đổi qua lại.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L838_03','V838','阮明',3,'练习地点图书馆一楼研讨室，有白板方便写单词、句子讲解对吧？','liàn xí dì diǎn tú shū guǎn yī lóu yán tǎo shì， yǒu bái bǎn fāng biàn xiě dān cí、 jù zi jiǎng jiě duì ba？','Địa điểm luyện tập là phòng thảo luận tầng một thư viện, có bảng trắng để viết từ vựng, giải thích câu cho dễ đúng không?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L838_04','V838','苏雯',4,'研讨室安静，不会打扰其他人，还能书写词汇互相讲解。','yán tǎo shì ān jìng， bú huì dǎ rǎo qí tā rén， hái néng shū xiě cí huì hù xiāng jiǎng jiě。','Phòng thảo luận yên tĩnh, không làm phiền ai cả, lại có thể viết từ vựng ra để giải thích cho nhau.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L838_05','V838','阮明',5,'每次结束布置少量口语练习任务，下周见面复盘巩固。','měi cì jié shù bù zhì shǎo liàng kǒu yǔ liàn xí rèn wù， xià zhōu jiàn miàn fù pán gǒng gù。','Mỗi lần học xong thì giao một ít bài tập luyện nói, tuần sau gặp lại thì ôn lại và củng cố nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L838_06','V838','苏雯',6,'分工互补互相提升语言，长期坚持进步会很明显。','fēn gōng hù bǔ hù xiāng tí shēng yǔ yán， cháng qī jiān chí jìn bù huì hěn míng xiǎn。','Bổ trợ qua lại như vậy, cùng nâng cao ngôn ngữ của nhau, kiên trì lâu dài thì tiến bộ sẽ thấy rõ luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L838_07','V838','阮明',7,'每周三固定时段见面语言交换，稳步提升双方外语水平。','měi zhōu sān gù dìng shí duàn jiàn miàn yǔ yán jiāo huàn， wěn bù tí shēng shuāng fāng wài yǔ shuǐ píng。','Vậy cố định mỗi thứ Tư hàng tuần gặp nhau trao đổi ngôn ngữ, từng bước nâng cao trình độ ngoại ngữ của cả hai.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT839','SHT5','咨询综测加分项目：讲座、竞赛、论文申报规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V839','SIT839','P1','suon_se','ban_chinh_thuc',NULL,'综测分数用于奖学金、评优评先，各类学术活动加分可叠加，但设置单学年加分上限。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L839_01','V839','阮明',1,'老师，想咨询留学生综合测评加分全部可申报项目细则。','lǎo shī， xiǎng zī xún liú xué shēng zōng hé cè píng jiā fēn quán bù kě shēn bào xiàng mù xì zé。','Thưa thầy/cô, em muốn hỏi chi tiết quy định về tất cả các hạng mục có thể đăng ký để cộng điểm tổng hợp cho lưu học sinh ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L839_02','V839','教务老师',2,'分为学术讲座、学科竞赛、期刊论文、社会实践四大类加分。','fēn wéi xué shù jiǎng zuò、 xué kē jìng sài、 qī kān lùn wén、 shè huì shí jiàn sì dà lèi jiā fēn。','Chia thành bốn nhóm lớn để cộng điểm là hội thảo học thuật, thi đấu học thuật, bài báo đăng tạp chí, và thực tế xã hội.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L839_03','V839','阮明',3,'校级汉语竞赛拿奖，一次能加多少综测分数？','xiào jí hàn yǔ jìng sài ná jiǎng， yī cì néng jiā duō shǎo zōng cè fēn shù？','Nếu đạt giải trong cuộc thi tiếng Trung cấp trường thì một lần được cộng bao nhiêu điểm tổng hợp ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L839_04','V839','教务老师',4,'校级竞赛三等奖0.3分、二等奖0.5分、一等奖0.8分，逐级递增。','xiào jí jìng sài sān děng jiǎng 0.3 fēn、 èr děng jiǎng 0.5 fēn、 yì děng jiǎng 0.8 fēn， zhú jí dì zēng。','Giải ba cấp trường được 0.3 điểm, giải nhì 0.5 điểm, giải nhất 0.8 điểm, tăng dần theo thứ hạng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L839_05','V839','阮明',5,'发表普通校园期刊短文，论文加分和竞赛加分可以叠加吗？','fā biǎo pǔ tōng xiào yuán qī kān duǎn wén， lùn wén jiā fēn hé jìng sài jiā fēn kě yǐ dié jiā ma？','Nếu đăng bài viết ngắn trên tạp chí thông thường của trường, thì điểm cộng cho bài báo và điểm cộng thi đấu có được cộng dồn với nhau không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L839_06','V839','教务老师',6,'全部项目加分可叠加，单学年综测加分上限两分。','quán bù xiàng mù jiā fēn kě dié jiā， dān xué nián zōng cè jiā fēn shàng xiàn liǎng fēn。','Tất cả các hạng mục đều được cộng dồn, nhưng mức trần cộng điểm tổng hợp trong một năm học là hai điểm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L839_07','V839','阮明',7,'我多参与讲座、汉语竞赛，争取提升学年综测分数。','wǒ duō cān yù jiǎng zuò、 hàn yǔ jìng sài， zhēng qǔ tí shēng xué nián zōng cè fēn shù。','Vậy em sẽ tham gia thêm hội thảo và thi tiếng Trung, cố gắng nâng điểm tổng hợp của năm học lên ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT840','SHT5','报名校级汉语竞赛，咨询参赛材料、评比标准',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V840','SIT840','P1','twist','tuy_y',NULL,'留学生汉语竞赛综合考察发音、逻辑表达，禁止剪辑配音视频，保证真实口语水平比拼。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L840_01','V840','阮明',1,'你好，我想报名校级留学生汉语竞赛，需要准备什么参赛材料？','nǐ hǎo， wǒ xiǎng bào míng xiào jí liú xué shēng hàn yǔ jìng sài， xū yào zhǔn bèi shén me cān sài cái liào？','Chào anh, em muốn đăng ký cuộc thi tiếng Trung cấp trường dành cho lưu học sinh, cần chuẩn bị những tài liệu dự thi gì ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L840_02','V840','干事',2,'线上提交一分钟汉语自我介绍视频，线下现场参与演讲答题环节。','xiàn shàng tí jiāo yì fēn zhōng hàn yǔ zì wǒ jiè shào shì pín， xiàn xià xiàn chǎng cān yù yǎn jiǎng dá tí huán jié。','Nộp online một video tự giới thiệu bằng tiếng Trung dài một phút, rồi tham gia phần thuyết trình và trả lời câu hỏi trực tiếp.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L840_03','V840','阮明',3,'竞赛评分侧重发音标准，还是内容立意、流畅度综合评判？','jìng sài píng fēn cè zhòng fā yīn biāo zhǔn， hái shì nèi róng lì yì、 liú chàng dù zōng hé píng pàn？','Cuộc thi chấm điểm thiên về phát âm chuẩn, hay là đánh giá tổng hợp cả nội dung ý tưởng và độ trôi chảy vậy anh?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L840_04','V840','干事',4,'发音40%、内容立意30%、表达流畅度30%，三项综合打分嘛。','fā yīn 40%、 nèi róng lì yì 30%、 biǎo dá liú chàng dù 30%， sān xiàng zōng hé dǎ fēn ma。','Phát âm 40%, nội dung ý tưởng 30%, độ trôi chảy khi diễn đạt 30%, chấm điểm tổng hợp cả ba tiêu chí đó mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L840_05','V840','阮明',5,'报名截止后天傍晚，我今天录制自我介绍视频线上提交。','bào míng jié zhǐ hòu tiān bàng wǎn， wǒ jīn tiān lù zhì zì wǒ jiè shào shì pín xiàn shàng tí jiāo。','Hạn đăng ký là chiều tối ngày kia, vậy hôm nay em quay video tự giới thiệu rồi nộp online luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L840_06','V840','干事',6,'视频不能后期剪辑配音，必须完整现场原声录制。','shì pín bù néng hòu qī jiǎn jí pèi yīn， bì xū wán zhěng xiàn chǎng yuán shēng lù zhì。','Video không được dựng hậu kỳ hay lồng tiếng, bắt buộc phải quay trọn vẹn bằng âm thanh gốc tại chỗ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L840_07','V840','阮明',7,'我无剪辑完整录制视频，按时提交参赛报名素材。','wǒ wú jiǎn jí wán zhěng lù zhì shì pín， àn shí tí jiāo cān sài bào míng sù cái。','Em không chỉnh sửa gì, quay trọn vẹn video và nộp tài liệu đăng ký dự thi đúng hạn ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT901','SXH1','主动询问球场陌生人，加入临时羽毛球组队玩耍',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V901','SIT901','P1','suon_se','tuy_y',NULL,'国内校园运动场临时组队十分普遍，场地、球具费用当场AA分摊，陌生人共同运动很容易快速熟悉。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L901_01','V901','阮明',1,'你好，看你们还差一位队友，我可以加入一起打羽毛球吗？','nǐ hǎo， kàn nǐ men hái chà yī wèi duì yǒu， wǒ kě yǐ jiā rù yì qǐ dǎ yǔ máo qiú ma？','Chào bạn, mình thấy các bạn thiếu một người, cho mình chơi cầu lông cùng luôn được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L901_02','V901','小杨',2,'没问题，正好缺人，你有自带球拍还是用球场公用拍？','méi wèn tí， zhèng hǎo quē rén， nǐ yǒu zì dài qiú pāi hái shì yòng qiú chǎng gōng yòng pāi？','Không vấn đề gì, đang thiếu người đây, bạn có mang vợt riêng không hay dùng vợt của sân?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L901_03','V901','阮明',3,'我带了球拍，咱们打两小时，场地费四个人平分对吧？','wǒ dài le qiú pāi， zán men dǎ liǎng xiǎo shí， chǎng dì fèi sì gè rén píng fēn duì ba？','Mình có mang vợt rồi, chơi hai tiếng thôi nhé, tiền sân chia đều bốn người đúng không?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L901_04','V901','小杨',4,'对，打完现场AA转账，每个人摊下来很便宜的。','duì， dǎ wán xiàn chǎng AA zhuǎn zhàng， měi gè rén tān xià lái hěn pián yi de。','Đúng rồi, chơi xong chuyển khoản AA luôn, chia ra mỗi người có mấy đồng à.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L901_05','V901','阮明',5,'太好了，平时很少找到人一起打球，今天刚好赶上。','tài hǎo le， píng shí hěn shǎo zhǎo dào rén yì qǐ dǎ qiú， jīn tiān gāng hǎo gǎn shàng。','Tuyệt quá, bình thường ít khi kiếm được người chơi cùng, hôm nay đúng lúc gặp được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L901_06','V901','小杨',6,'每周四下午我们都会来球场，你有空可以常过来组队。','měi zhōu sì xià wǔ wǒ men dōu huì lái qiú chǎng， nǐ yǒu kòng kě yǐ cháng guò lái zǔ duì。','Tụi mình cứ chiều thứ Năm hàng tuần là ra sân, bạn rảnh thì cứ qua chơi chung nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L901_07','V901','阮明',7,'记下时间，下周同一时间我再来球场找你们。','jì xià shí jiān， xià zhōu tóng yī shí jiān wǒ zài lái qiú chǎng zhǎo nǐ men。','Ghi lại giờ rồi, tuần sau cùng giờ này mình lại ra sân tìm mọi người.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT902','SXH1','观看校园文艺晚会，和身边陌生同学简单搭话交流观感',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V902','SIT902','P1','twist','tuy_y',NULL,'看演出时和邻座陌生人聊节目内容是自然破冰方式，国内学生不会觉得唐突。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L902_01','V902','阮明',1,'刚刚那个民族舞蹈节目编排真好看，你觉得怎么样？','gāng gāng nà ge mín zú wǔ dǎo jié mù biān pái zhēn hǎo kàn， nǐ jué de zěn me yàng？','Tiết mục múa dân tộc lúc nãy dàn dựng đẹp thật đấy, bạn thấy sao?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L902_02','V902','陈雨',2,'我也很喜欢，就是灯光有点暗，演员面部细节看不清呢。','wǒ yě hěn xǐ huān， jiù shì dēng guāng yǒu diǎn àn， yǎn yuán miàn bù xì jié kàn bù qīng ne。','Mình cũng thích lắm, chỉ tội ánh sáng hơi tối, nhìn không rõ mặt diễn viên.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L902_03','V902','阮明',3,'后面还有留学生合唱节目，听说有东南亚语种的歌曲。','hòu miàn hái yǒu liú xué shēng hé chàng jié mù， tīng shuō yǒu dōng nán yà yǔ zhǒng de gē qǔ。','Lát nữa còn có tiết mục hợp xướng của du học sinh nữa, nghe nói có bài hát tiếng Đông Nam Á đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L902_04','V902','陈雨',4,'我特意留到最后看，可惜中场手机没电，没法拍照记录。','wǒ tè yì liú dào zuì hòu kàn， kě xī zhōng chǎng shǒu jī méi diàn， méi fǎ pāi zhào jì lù。','Mình cố tình ở lại xem đến cuối, tiếc là giữa chừng điện thoại hết pin, không chụp ảnh lưu lại được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L902_05','V902','阮明',5,'我的手机电量充足，等下节目结束可以分几张照片给你。','wǒ de shǒu jī diàn liàng chōng zú， děng xià jié mù jié shù kě yǐ fēn jǐ zhāng zhào piān gěi nǐ。','Điện thoại mình còn đầy pin, lát nữa hết chương trình mình gửi vài tấm cho bạn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L902_06','V902','陈雨',6,'太感谢啦，晚会结束加个联系方式，方便你发图给我。','tài gǎn xiè la， wǎn huì jié shù jiā gè lián xì fāng shì， fāng biàn nǐ fā tú gěi wǒ。','Cảm ơn nhiều nha, xong buổi kết bạn Zalo đi để bạn gửi ảnh cho mình tiện hơn.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L902_07','V902','阮明',7,'好，散场之后我们互相加好友，分享晚会现场照片。','hǎo， sàn chǎng zhī hòu wǒ men hù xiāng jiā hǎo yǒu， fēn xiǎng wǎn huì xiàn chǎng zhào piān。','Ừ, tan buổi rồi mình kết bạn với nhau, chia sẻ ảnh chụp tối nay cho vui.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT903','SXH1','报名校内志愿公益活动，活动中结识不同专业同学',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V903','SIT903','P1','suon_se','ban_chinh_thuc',NULL,'校内志愿活动是跨专业社交主流渠道，国内学生普遍愿意通过公益活动拓展朋友圈。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L903_01','V903','阮明',1,'学姐你好，我想报名周末社区敬老志愿活动，需要什么流程？','xué jiě nǐ hǎo， wǒ xiǎng bào míng zhōu mò shè qū jìng lǎo zhì yuàn huó dòng， xū yào shén me liú chéng？','Chào chị, em muốn đăng ký hoạt động tình nguyện chăm sóc người già cuối tuần, cần làm những thủ tục gì ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L903_02','V903','学姐',2,'线上填报名表单，周六早上八点在校门口集合统一出发哦。','xiàn shàng tián bào míng biǎo dān， zhōu liù zǎo shàng bā diǎn zài xiào mén kǒu jí hé tǒng yī chū fā ó。','Điền form đăng ký online, sáng thứ Bảy tám giờ tập trung ở cổng trường rồi cùng xuất phát nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L903_03','V903','阮明',3,'活动都是不同学院的学生参加吗，会不会只有我们专业？','huó dòng dōu shì bù tóng xué yuàn de xué shēng cān jiā ma， huì bú huì zhǐ yǒu wǒ men zhuān yè？','Hoạt động có sinh viên nhiều khoa khác nhau tham gia không, hay chỉ có mỗi ngành mình vậy chị?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L903_04','V903','学姐',4,'全校各专业都有人报名，正好能认识很多新朋友。','quán xiào gè zhuān yè dōu yǒu rén bào míng， zhèng hǎo néng rèn shí hěn duō xīn péng yǒu。','Cả trường ngành nào cũng có người đăng ký hết, đúng dịp để quen thêm nhiều bạn mới đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L903_05','V903','阮明',5,'活动主要做哪些工作，我提前准备简单的小节目给老人。','huó dòng zhǔ yào zuò nǎ xiē gōng zuò， wǒ tí qián zhǔn bèi jiǎn dān de xiǎo jié mù gěi lǎo rén。','Hoạt động chủ yếu làm những việc gì ạ, em chuẩn bị trước một tiết mục nhỏ cho các cụ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L903_06','V903','学姐',6,'陪老人聊天、打扫房间，会才艺的话表演小段节目很受欢迎。','péi lǎo rén liáo tiān、 dǎ sǎo fáng jiān， huì cái yì de huà biǎo yǎn xiǎo duàn jié mù hěn shòu huān yíng。','Chủ yếu là trò chuyện với các cụ, dọn phòng, ai có tài lẻ thì biểu diễn một đoạn nhỏ được hưởng ứng lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L903_07','V903','阮明',7,'我准备一段越南简单民谣，周末准时来参与志愿活动。','wǒ zhǔn bèi yī duàn yuè nán jiǎn dān mín yáo， zhōu mò zhǔn shí lái cān yù zhì yuàn huó dòng。','Em chuẩn bị một bài dân ca Việt Nam đơn giản, cuối tuần sẽ đến tham gia tình nguyện đúng giờ ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT904','SXH1','约朋友周末去城市公园徒步、逛景区，协商出行路线预算',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V904','SIT904','P1','twist','tuy_y',NULL,'多人外出游玩会兼顾体力、预算、返程时间集体协商，所有公共开销统一AA是通用社交规则。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L904_01','V904','阮明',1,'这周末天气很好，我们约上几个朋友去郊外公园徒步好不好？','zhè zhōu mò tiān qì hěn hǎo， wǒ men yuē shàng jǐ gè péng yǒu qù jiāo wài gōng yuán tú bù hǎo bù hǎo？','Cuối tuần này thời tiết đẹp lắm, tụi mình rủ thêm mấy đứa bạn ra công viên ngoại ô đi bộ nhé?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L904_02','V904','苏雯',2,'可以，有两条路线，短途两小时、长途五小时，大家体力不一样。','kě yǐ， yǒu liǎng tiáo lù xiàn， duǎn tú liǎng xiǎo shí、 cháng tú wǔ xiǎo shí， dà jiā tǐ lì bù yí yàng。','Được đó, có hai lộ trình, ngắn thì hai tiếng, dài thì năm tiếng, mỗi người sức khỏe khác nhau mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L904_03','V904','阮明',3,'长途路程远，来回公交票价会高出不少，预算需要提前算清嘛。','cháng tú lù chéng yuǎn， lái huí gōng jiāo piào jià huì gāo chū bù shǎo， yù suàn xū yào tí qián suàn qīng ma。','Đi tuyến dài xa hơn, tiền vé xe buýt khứ hồi cũng đắt hơn kha khá, phải tính trước ngân sách chứ nhỉ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L904_04','V904','苏雯',4,'那我们先问所有人意愿，多数人选短途就走轻松路线。','nà wǒ men xiān wèn suǒ yǒu rén yì yuàn， duō shù rén xuǎn duǎn tú jiù zǒu qīng sōng lù xiàn。','Vậy mình hỏi ý kiến mọi người trước đã, đa số chọn tuyến ngắn thì đi cho nhẹ nhàng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L904_05','V904','阮明',5,'零食、矿泉水我来采购，所有人AA分摊食材花费。','líng shí、 kuàng quán shuǐ wǒ lái cǎi gòu， suǒ yǒu rén AA fēn tān shí cái huā fèi。','Đồ ăn vặt với nước suối để mình lo mua, mọi người chia đều tiền đồ ăn theo kiểu AA nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L904_06','V904','苏雯',6,'傍晚返程避开晚高峰，不会耽误晚上自习休息。','bàng wǎn fǎn chéng bì kāi wǎn gāo fēng， bú huì dān wù wǎn shàng zì xí xiū xī。','Chiều về tránh giờ cao điểm, khỏi ảnh hưởng đến giờ tự học tối nay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L904_07','V904','阮明',7,'我现在在群里征集大家意见，敲定最终出行方案。','wǒ xiàn zài zài qún lǐ zhēng jí dà jiā yì jiàn， qiāo dìng zuì zhōng chū xíng fāng àn。','Giờ mình đang hỏi ý kiến mọi người trong nhóm, chốt phương án đi chơi cuối cùng luôn.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT905','SXH1','宿舍公共观影夜，和室友商量影片选择、零食分摊',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V905','SIT905','P1','suon_se','tuy_y',NULL,'宿舍集体活动零食、饮品费用均分，同时会考虑周边宿舍作息，控制活动结束时间避免噪音扰民。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L905_01','V905','阮明',1,'今晚没课，我们宿舍办观影夜，大家投票选一部电影看吧？','jīn wǎn méi kè， wǒ men sù shè bàn guān yǐng yè， dà jiā tóu piào xuǎn yī bù diàn yǐng kàn ba？','Tối nay không có tiết, tụi mình tổ chức xem phim trong phòng ký túc xá, biểu quyết chọn một bộ đi?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L905_02','V905','小林',2,'有人想看喜剧，有人想看纪实纪录片，很难统一口味。','yǒu rén xiǎng kàn xǐ jù， yǒu rén xiǎng kàn jì shí jì lù piàn， hěn nán tǒng yī kǒu wèi。','Có người muốn xem hài, có người lại muốn xem phim tài liệu, khó mà hợp khẩu vị hết được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L905_03','V905','阮明',3,'那分上下半场，先放喜剧，后半段看纪实短片兼顾所有人。','nà fēn shàng xià bàn chǎng， xiān fàng xǐ jù， hòu bàn duàn kàn jì shí duǎn piàn jiān gù suǒ yǒu rén。','Vậy chia đôi buổi, nửa đầu chiếu hài, nửa sau xem phim tài liệu ngắn cho hợp ý mọi người luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L905_04','V905','小林',4,'零食饮料统一网购，下单之后四个人平均分摊费用。','líng shí yǐn liào tǒng yī wǎng gòu， xià dān zhī hòu sì gè rén píng jūn fēn tān fèi yòng。','Đồ ăn vặt với nước ngọt đặt online chung, đặt xong rồi bốn người chia đều tiền nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L905_05','V905','阮明',5,'我负责挑选影片，你统计大家想吃的零食清单。','wǒ fù zé tiāo xuǎn yǐng piàn， nǐ tǒng jì dà jiā xiǎng chī de líng shí qīng dān。','Mình lo chọn phim, bạn tổng hợp danh sách đồ ăn vặt mọi người muốn ăn nha.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L905_06','V905','小林',6,'熄灯前结束观影，不熬夜打扰隔壁宿舍休息。','xī dēng qián jié shù guān yǐng， bù áo yè dǎ rǎo gé bì sù shè xiū xī。','Xem xong trước giờ tắt đèn, khỏi thức khuya làm phiền phòng bên cạnh nghỉ ngơi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L905_07','V905','阮明',7,'安排妥当，今晚宿舍一起轻松放松一下。','ān pái tuǒ dàng， jīn wǎn sù shè yì qǐ qīng sōng fàng sōng yī xià。','Sắp xếp ổn thỏa rồi, tối nay cả phòng cùng thư giãn một chút cho vui.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT906','SXH1','校内桌游局，询问新人参与规则、是否收取分摊费用',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V906','SIT906','P1','that_bai_nhe','tuy_y',NULL,'线下桌游聚会大多会点饮品，多数人默认统一分摊，若有饮食禁忌可单独结算，无需勉强跟随大众消费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L906_01','V906','阮明',1,'我第一次来桌游局，想问游戏规则和场地费用怎么算？','wǒ dì yī cì lái zhuō yóu jú， xiǎng wèn yóu xì guī zé hé chǎng dì fèi yòng zěn me suàn？','Mình lần đầu đến chơi board game, cho mình hỏi luật chơi với tiền sân tính thế nào vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L906_02','V906','小周',2,'桌游社提供全部卡牌，活动室免费使用，只需要AA奶茶钱。','zhuō yóu shè tí gōng quán bù kǎ pái， huó dòng shì miǎn fèi shǐ yòng， zhǐ xū yào AA nǎi chá qián。','Câu lạc bộ board game cung cấp hết bài rồi, phòng sinh hoạt dùng miễn phí, chỉ cần chia tiền trà sữa AA thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L906_03','V906','阮明',3,'奶茶可以不点，只参与游戏不用分摊饮品费用吗？','nǎi chá kě yǐ bù diǎn， zhǐ cān yù yóu xì bù yòng fēn tān yǐn pǐn fèi yòng ma？','Vậy không gọi trà sữa, chỉ tham gia chơi game thôi thì không cần chia tiền đồ uống đúng không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L906_04','V906','小周',4,'大家默认每人点一杯饮品，不点的话有点不合群嘛。','dà jiā mò rèn měi rén diǎn yī bēi yǐn pǐn， bù diǎn de huà yǒu diǎn bù hé qún ma。','Mọi người mặc định mỗi người gọi một ly, không gọi thì hơi lạc lõng với nhóm đó nha.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L906_05','V906','阮明',5,'我肠胃不适合喝甜饮，单独买矿泉水，只分摊矿泉水费用行吗？','wǒ cháng wèi bú shì hé hē tián yǐn， dān dú mǎi kuàng quán shuǐ， zhǐ fēn tān kuàng quán shuǐ fèi yòng xíng ma？','Bụng mình không hợp uống đồ ngọt, mình mua riêng nước suối, chỉ chia tiền nước suối thôi được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L906_06','V906','小周',6,'没问题，跟老板说清楚，只算自己饮用水的钱。','méi wèn tí， gēn lǎo bǎn shuō qīng chǔ， zhǐ suàn zì jǐ yǐn yòng shuǐ de qián。','Không sao đâu, nói rõ với chủ quán là được, chỉ tính tiền nước bạn uống thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L906_07','V906','阮明',7,'好，我先学习基础桌游规则，不勉强自己点奶茶。','hǎo， wǒ xiān xué xí jī chǔ zhuō yóu guī zé， bù miǎn qiǎng zì jǐ diǎn nǎi chá。','Được rồi, để mình học luật chơi cơ bản trước, không ép mình gọi trà sữa nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT907','SXH1','参加校园国际文化节，展示本国特色小吃与传统手工',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V907','SIT907','P1','suon_se','ban_chinh_thuc',NULL,'校园国际文化节鼓励各国留学生展示本土美食、手工艺，是跨文化交流、结交各国朋友的重要活动。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L907_01','V907','阮明',1,'老师，我报名文化节摊位，准备越南春卷和手工竹编展示可以吗？','lǎo shī， wǒ bào míng wén huà jié tān wèi， zhǔn bèi yuè nán chūn juǎn hé shǒu gōng zhú biān zhǎn shì kě yǐ ma？','Thưa cô, em đăng ký gian hàng lễ hội văn hóa, chuẩn bị chả giò Việt Nam với trưng bày đan tre thủ công có được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L907_02','V907','老师',2,'完全合适，每个国家摊位提供少量试吃，吸引其他同学参观哦。','wán quán hé shì， měi gè guó jiā tān wèi tí gōng shǎo liàng shì chī， xī yǐn qí tā tóng xué cān guān ó。','Hoàn toàn phù hợp, mỗi gian hàng của mỗi nước sẽ cho nếm thử một chút, thu hút các bạn khác đến tham quan nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L907_03','V907','阮明',3,'食材采购费用学院有补贴，还是需要留学生自行承担？','shí cái cǎi gòu fèi yòng xué yuàn yǒu bǔ tiē， hái shì xū yào liú xué shēng zì xíng chéng dān？','Chi phí nguyên liệu khoa có hỗ trợ không ạ, hay là du học sinh phải tự lo hết?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L907_04','V907','老师',4,'基础食材学院报销，额外精致配料由个人自愿准备。','jī chǔ shí cái xué yuàn bào xiāo， é wài jīng zhì pèi liào yóu gè rén zì yuàn zhǔn bèi。','Nguyên liệu cơ bản khoa thanh toán lại, còn nguyên liệu tinh xảo thêm thì tự nguyện chuẩn bị.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L907_05','V907','阮明',5,'我现场简单演示竹编手法，方便来往同学体验手工。','wǒ xiàn chǎng jiǎn dān yǎn shì zhú biān shǒu fǎ， fāng biàn lái wǎng tóng xué tǐ yàn shǒu gōng。','Em sẽ trình diễn trực tiếp cách đan tre luôn, để các bạn qua lại tiện trải nghiệm thủ công.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L907_06','V907','老师',6,'活动当天人流量很大，提前半小时到场布置摊位。','huó dòng dàng tiān rén liú liàng hěn dà， tí qián bàn xiǎo shí dào chǎng bù zhì tān wèi。','Hôm diễn ra hoạt động lượng người rất đông, đến sớm nửa tiếng để dọn dẹp gian hàng nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L907_07','V907','阮明',7,'我提前备好食材与手工材料，文化节准时布置摊位。','wǒ tí qián bèi hǎo shí cái yǔ shǒu gōng cái liào， wén huà jié zhǔn shí bù zhì tān wèi。','Em sẽ chuẩn bị sẵn nguyên liệu và đồ thủ công trước, đến giờ lễ hội là dọn gian hàng ngay.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT908','SXH2','多人聚餐AA结算，核对账单、分摊转账，有人忘记付款提醒对方',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V908','SIT908','P1','twist','tuy_y',NULL,'多人AA聚餐统一由一人代收款项，提醒未付款人时语气委婉，避免让对方产生被催促的尴尬。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L908_01','V908','阮明',1,'我把餐厅完整账单发到群里，所有人人均三十五元，核对一下。','wǒ bǎ cān tīng wán zhěng zhàng dān fā dào qún lǐ， suǒ yǒu rén rén jūn sān shí wǔ yuán， hé duì yī xià。','Mình gửi hóa đơn đầy đủ của nhà hàng lên nhóm rồi, mỗi người ba mươi lăm đồng, mọi người kiểm tra lại giúp mình nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L908_02','V908','苏雯',2,'大部分人已经转账给我，只有两位同学还没有付款。','dà bù fèn rén yǐ jīng zhuǎn zhàng gěi wǒ， zhǐ yǒu liǎng wèi tóng xué hái méi yǒu fù kuǎn。','Phần lớn mọi người chuyển khoản cho mình rồi, chỉ còn hai bạn chưa thanh toán thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L908_03','V908','阮明',3,'可能他们忘记看群消息，我温和提醒一句，别让对方尴尬。','kě néng tā men wàng jì kàn qún xiāo xī， wǒ wēn hé tí xǐng yī jù， bié ràng duì fāng gān gà。','Chắc họ quên xem tin nhắn nhóm, để mình nhắc nhẹ một câu, đừng để người ta ngại nha.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L908_04','V908','苏雯',4,'说得委婉一点，就说我统一收款后要给店家结账。','shuō dé wěi wǎn yì diǎn， jiù shuō wǒ tǒng yī shōu kuǎn hòu yào gěi diàn jiā jié zhàng。','Nói khéo một chút thôi, cứ bảo là mình gom đủ tiền rồi mới thanh toán cho quán.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L908_05','V908','阮明',5,'各位，麻烦有空转一下聚餐分摊费，我今晚统一结清账单哈。','gè wèi， má fán yǒu kòng zhuǎn yī xià jù cān fēn tān fèi， wǒ jīn wǎn tǒng yī jié qīng zhàng dān hā。','Mọi người ơi, ai rảnh thì chuyển khoản tiền chia phần bữa ăn giúp mình nhé, tối nay mình thanh toán hết luôn ạ.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L908_06','V908','小林',6,'收到，我现在立刻转账，刚才自习完全没看手机。','shōu dào， wǒ xiàn zài lì kè zhuǎn zhàng， gāng cái zì xí wán quán méi kàn shǒu jī。','Nhận được rồi, mình chuyển khoản ngay đây, lúc nãy tự học xong có xem điện thoại đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L908_07','V908','阮明',7,'全部款项收齐，这次聚餐开销结算完毕。','quán bù kuǎn xiàng shōu qí， zhè cì jù cān kāi xiāo jié suàn wán bì。','Thu đủ hết tiền rồi, bữa ăn lần này coi như thanh toán xong xuôi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT909','SXH2','朋友过节送小礼物，推辞几番后礼貌收下并回赠伴手礼',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V909','SIT909','P1','suon_se','tuy_y',NULL,'国内人情讲究礼尚往来，收到礼物会先礼貌推辞一次再收下，后续准备等价小伴手礼回赠对方。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L909_01','V909','阮明',1,'不用特意给我准备中秋月饼，太破费啦，我不好意思收下。','bù yòng tè yì gěi wǒ zhǔn bèi zhōng qiū yuè bǐng， tài pò fèi la， wǒ bù hǎo yì sī shōu xià。','Cậu không cần đặc biệt chuẩn bị bánh Trung thu cho tớ đâu, tốn kém quá, tớ ngại nhận lắm.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L909_02','V909','苏雯',2,'只是一盒普通月饼，一点心意，你不用跟我客气。','zhǐ shì yī hé pǔ tōng yuè bǐng， yì diǎn xīn yì， nǐ bù yòng gēn wǒ kè qì。','Chỉ là một hộp bánh bình thường thôi mà, chút tấm lòng thôi, cậu đừng khách sáo với tớ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L909_03','V909','阮明',3,'那我收下这份心意，下周我把家里寄来的越南咖啡回送给你。','nà wǒ shōu xià zhè fèn xīn yì， xià zhōu wǒ bǎ jiā lǐ jì lái de yuè nán kā fēi huí sòng gěi nǐ。','Vậy tớ xin nhận tấm lòng này, tuần sau tớ gửi lại cậu cà phê Việt Nam nhà tớ gửi sang nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L909_04','V909','苏雯',4,'不用专门回礼，大家朋友之间不用计较这么多。','bù yòng zhuān mén huí lǐ， dà jiā péng yǒu zhī jiān bù yòng jì jiào zhè me duō。','Không cần đáp lễ đâu, bạn bè với nhau tính toán chi li làm gì.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L909_05','V909','阮明',5,'礼尚往来是我们两国都有的习惯，一定要收下我的伴手礼。','lǐ shàng wǎng lái shì wǒ men liǎng guó dōu yǒu de xí guàn， yí dìng yào shōu xià wǒ de bàn shǒu lǐ。','Có đi có lại là phong tục cả hai nước mình đều có, cậu nhất định phải nhận quà của tớ đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L909_06','V909','苏雯',6,'行，那我收下咖啡，下次过节我们简单小礼物互相分享。','xíng， nà wǒ shōu xià kā fēi， xià cì guò jié wǒ men jiǎn dān xiǎo lǐ wù hù xiāng fēn xiǎng。','Được rồi, vậy tớ nhận cà phê, lần sau đến dịp lễ mình đơn giản tặng nhau món quà nhỏ thôi nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L909_07','V909','阮明',7,'好，之后节日互相送平价小特产，不用贵重礼品。','hǎo， zhī hòu jié rì hù xiāng sòng píng jià xiǎo tè chǎn， bù yòng guì zhòng lǐ pǐn。','Ừ, sau này lễ tết mình tặng nhau đặc sản giá bình dân thôi, không cần quà đắt tiền.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT910','SXH2','主动请客吃饭，拒绝朋友抢单，解释自己提前规划买单',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V910','SIT910','P1','twist','tuy_y',NULL,'朋友之间答谢请客十分常见，对方抢单时会说明请客缘由，约定下次轮流做东，平衡人情往来。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L910_01','V910','阮明',1,'今天是我请你吃饭，别跟我抢买单，我早就计划好了。','jīn tiān shì wǒ qǐng nǐ chī fàn， bié gēn wǒ qiǎng mǎi dān， wǒ zǎo jiù jì huà hǎo le。','Hôm nay tớ mời cậu ăn cơm, đừng giành trả tiền với tớ, tớ tính trước rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L910_02','V910','苏雯',2,'不行，每次都是你请客，这次必须我来付钱。','bù xíng， měi cì dōu shì nǐ qǐng kè， zhè cì bì xū wǒ lái fù qián。','Không được, lần nào cũng là cậu mời, lần này nhất định để tớ trả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L910_03','V910','阮明',3,'上次你帮我整理一整本汉语笔记，这次就当答谢你的帮忙嘛。','shàng cì nǐ bāng wǒ zhěng lǐ yī zhěng běn hàn yǔ bǐ jì， zhè cì jiù dāng dá xiè nǐ de bāng máng ma。','Lần trước cậu giúp tớ chép cả một cuốn vở tiếng Trung, lần này coi như tớ cảm ơn cậu vậy.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L910_04','V910','苏雯',4,'只是小事而已，不用专门请客花这么多钱。','zhǐ shì xiǎo shì ér yǐ， bù yòng zhuān mén qǐng kè huā zhè me duō qián。','Chuyện nhỏ xíu thôi mà, không cần mời hẳn tốn kém vậy đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L910_05','V910','阮明',5,'心意一定要收下，下次换你请客，我们轮流做东。','xīn yì yí dìng yào shōu xià， xià cì huàn nǐ qǐng kè， wǒ men lún liú zuò dōng。','Tấm lòng này cậu phải nhận, lần sau đến lượt cậu mời, mình thay phiên nhau nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L910_06','V910','苏雯',6,'那好吧，下次吃饭不许再跟我抢账单。','nà hǎo ba， xià cì chī fàn bù xǔ zài gēn wǒ qiǎng zhàng dān。','Thôi được rồi, lần sau ăn cơm không được giành trả tiền với tớ nữa đâu đấy.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L910_07','V910','阮明',7,'没问题，下次聚餐全部由你买单。','méi wèn tí， xià cì jù cān quán bù yóu nǐ mǎi dān。','Không thành vấn đề, lần sau ăn uống để cậu bao trọn hết.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT911','SXH2','多人外出喝奶茶，提前说好各自付款，避免互相垫付混淆',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V911','SIT911','P1','suon_se','tuy_y',NULL,'小额饮品、小吃分开自行付款，是年轻人简化人情、避免垫付纠纷的通用社交方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L911_01','V911','阮明',1,'我们去奶茶店，大家各自扫码点单自己付款，免得之后算不清垫付。','wǒ men qù nǎi chá diàn， dà jiā gè zì sǎo mǎ diǎn dān zì jǐ fù kuǎn， miǎn de zhī hòu suàn bù qīng diàn fù。','Mình vào quán trà sữa, ai nấy tự quét mã gọi món và tự trả tiền, khỏi sau này tính không ra ai ứng tiền cho ai.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L911_02','V911','小林',2,'有时候有人手机没电，临时垫付之后很容易忘记转账。','yǒu shí hòu yǒu rén shǒu jī méi diàn， lín shí diàn fù zhī hòu hěn róng yì wàng jì zhuǎn zhàng。','Có lúc điện thoại hết pin, ứng tiền trước rồi lại dễ quên chuyển khoản lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L911_03','V911','阮明',3,'分开付款最省事，不用事后挨个核对转账记录。','fēn kāi fù kuǎn zuì shěng shì， bù yòng shì hòu āi gè hé duì zhuǎn zhàng jì lù。','Trả riêng là tiện nhất, khỏi phải đối chiếu từng cái lịch sử chuyển khoản sau này.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L911_04','V911','苏雯',4,'行，到店每个人自己下单，不用统一一个人买单。','xíng， dào diàn měi gè rén zì jǐ xià dān， bù yòng tǒng yī yí gè rén mǎi dān。','Được, đến quán ai nấy tự gọi món, không cần dồn cho một người trả hết.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L911_05','V911','阮明',5,'想喝什么直接点，不用顾虑饮品价格互相迁就。','xiǎng hē shén me zhí jiē diǎn， bù yòng gù lǜ yǐn pǐn jià gé hù xiāng qiān jiù。','Thích uống gì thì cứ gọi thoải mái, khỏi phải e ngại giá đồ uống rồi nhường nhịn nhau.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L911_06','V911','小林',6,'这个办法省心，避免一堆转账记录分不清谁欠谁。','zhè ge bàn fǎ shěng xīn， bì miǎn yī duī zhuǎn zhàng jì lù fēn bù qīng shuí qiàn shuí。','Cách này nhàn thật, khỏi phải rối tung lên với đống chuyển khoản không biết ai nợ ai.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L911_07','V911','阮明',7,'那我们现在去奶茶店各自下单。','nà wǒ men xiàn zài qù nǎi chá diàn gè zì xià dān。','Vậy giờ mình đi quán trà sữa, ai nấy tự gọi món nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT912','SXH2','朋友生病住院，邀约同学一起买水果前去探望慰问',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V912','SIT912','P1','suon_se','ban_chinh_thuc',NULL,'国内探望病人有送礼禁忌，梨谐音"离"不宜赠送；多人结伴探望、控制时长，不打扰病人休养。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L912_01','V912','阮明',1,'听说小杨发烧住院，我们约几个朋友买水果去医院看望他吧？','tīng shuō xiǎo yáng fā shāo zhù yuàn， wǒ men yuē jǐ gè péng yǒu mǎi shuǐ guǒ qù yī yuàn kàn wàng tā ba？','Nghe nói Tiểu Dương bị sốt phải nhập viện, hay là mình rủ vài bạn mua ít trái cây vào thăm cậu ấy nhé?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L912_02','V912','小林',2,'可以，医院适合送苹果、橙子这类温和水果，不要送梨。','kě yǐ， yī yuàn shì hé sòng píng guǒ、 chéng zi zhè lèi wēn hé shuǐ guǒ， bú yào sòng lí。','Được đó, vào viện thì hợp mang táo, cam kiểu trái cây lành tính, đừng mang lê nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L912_03','V912','阮明',3,'梨在中文谐音不吉利，探望病人确实不适合携带对吧？','lí zài zhōng wén xié yīn bù jí lì， tàn wàng bìng rén què shí bú shì hé xié dài duì ba？','Lê phát âm tiếng Trung nghe không may mắn, đi thăm bệnh đúng là không hợp mang phải không?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L912_04','V912','小林',4,'没错，我们四个人凑钱买一箱鲜果，统一分摊费用。','méi cuò， wǒ men sì gè rén còu qián mǎi yī xiāng xiān guǒ， tǒng yī fēn tān fèi yòng。','Đúng vậy, bốn đứa mình góp tiền mua một thùng trái cây tươi, chia đều chi phí ra.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L912_05','V912','阮明',5,'下午没课，三点左右在医院楼下集合一起上楼探望。','xià wǔ méi kè， sān diǎn zuǒ yòu zài yī yuàn lóu xià jí hé yī qǐ shàng lóu tàn wàng。','Chiều nay không có tiết, khoảng ba giờ mình tập trung dưới sảnh bệnh viện rồi cùng lên thăm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L912_06','V912','小林',6,'探望时间控制半小时，不耽误病人休息恢复。','tàn wàng shí jiān kòng zhì bàn xiǎo shí， bù dān wù bìng rén xiū xī huī fù。','Thời gian thăm nên gói gọn trong nửa tiếng thôi, để bệnh nhân còn nghỉ ngơi hồi phục.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L912_07','V912','阮明',7,'我现在联系其他同学，敲定下午探望时间。','wǒ xiàn zài lián xì qí tā tóng xué， qiāo dìng xià wǔ tàn wàng shí jiān。','Giờ tớ liên hệ mấy bạn khác luôn, chốt giờ thăm buổi chiều.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT913','SXH2','节日邀请中国朋友来宿舍，亲手做越南特色饭菜招待',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V913','SIT913','P1','twist','tuy_y',NULL,'邀请好友到宿舍亲手做饭招待，代表十分重视这段友谊，是很真诚的社交待客方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L913_01','V913','阮明',1,'中秋宿舍不熄灯，你来我宿舍，我亲手做越南米粉招待你。','zhōng qiū sù shè bù xī dēng， nǐ lái wǒ sù shè， wǒ qīn shǒu zuò yuè nán mǐ fěn zhāo dài nǐ。','Trung thu ký túc xá không tắt đèn, cậu qua phòng tớ đi, tớ tự tay nấu bún gạo Việt Nam đãi cậu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L913_02','V913','苏雯',2,'太麻烦你了，买菜、做饭收拾要花很长时间。','tài má fán nǐ le， mǎi cài、 zuò fàn shōu shí yào huā hěn zhǎng shí jiān。','Phiền cậu quá đi, đi chợ, nấu ăn rồi dọn dẹp chắc mất nhiều thời gian lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L913_03','V913','阮明',3,'食材我已经提前网购备好，只需要简单蒸煮，不会很费力嘛。','shí cái wǒ yǐ jīng tí qián wǎng gòu bèi hǎo， zhǐ xū yào jiǎn dān zhēng zhǔ， bú huì hěn fèi lì ma。','Nguyên liệu tớ đặt online chuẩn bị sẵn hết rồi, chỉ cần hấp nấu qua loa thôi, không mất công lắm đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L913_04','V913','苏雯',4,'我带一盒月饼过去搭配晚餐，咱们两国小吃一起品尝。','wǒ dài yī hé yuè bǐng guò qù dā pèi wǎn cān， zán men liǎng guó xiǎo chī yì qǐ pǐn cháng。','Vậy tớ mang một hộp bánh Trung thu qua ăn kèm bữa tối, hai đứa mình cùng thưởng thức món ăn của hai nước.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L913_05','V913','阮明',5,'宿舍小电锅功率有限，菜品种类不多，你别嫌弃简单。','sù shè xiǎo diàn guō gōng lǜ yǒu xiàn， cài pǐn zhǒng lèi bù duō， nǐ bié xián qì jiǎn dān。','Nồi điện mini ở ký túc xá công suất có hạn, món ăn không nhiều đâu, cậu đừng chê đơn giản nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L913_06','V913','苏雯',6,'亲手做的饭菜比外面餐厅更有心意，我很期待。','qīn shǒu zuò de fàn cài bǐ wài miàn cān tīng gèng yǒu xīn yì， wǒ hěn qī dài。','Đồ ăn tự tay làm còn có tâm hơn nhà hàng bên ngoài nhiều, tớ mong lắm đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L913_07','V913','阮明',7,'那晚上七点来宿舍，我们一起过节聊天。','nà wǎn shàng qī diǎn lái sù shè， wǒ men yì qǐ guò jié liáo tiān。','Vậy bảy giờ tối cậu qua phòng tớ nhé, mình cùng đón lễ trò chuyện.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT914','SXH2','收到朋友贵重礼物，担心人情过重，和对方沟通下次减少花销',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V914','SIT914','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内朋友交往更推崇平价走心小礼物，贵重礼品容易让对方产生人情压力，双方会提前约定简化送礼开销。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L914_01','V914','阮明',1,'这条围巾价格太高，贵重礼物我收下心里很过意不去。','zhè tiáo wéi jīn jià gé tài gāo， guì zhòng lǐ wù wǒ shōu xià xīn lǐ hěn guò yì bù qù。','Chiếc khăn quàng này giá cao quá, món quà quý giá thế này tớ nhận mà trong lòng thấy áy náy quá.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L914_02','V914','苏雯',2,'只是一份生日礼物，不用放在心上。','zhǐ shì yī fèn shēng rì lǐ wù， bù yòng fàng zài xīn shàng。','Chỉ là quà sinh nhật thôi mà, cậu đừng để bụng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L914_03','V914','阮明',3,'普通平价小特产就足够，这么贵重的礼物让我不知道怎么回礼。','pǔ tōng píng jià xiǎo tè chǎn jiù zú gòu， zhè me guì zhòng de lǐ wù ràng wǒ bù zhī dào zěn me huí lǐ。','Đặc sản bình dân là đủ rồi, quà quý giá thế này khiến tớ không biết đáp lễ thế nào.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L914_04','V914','苏雯',4,'朋友不用刻意计较礼物价值，不用非要等价回赠。','péng yǒu bù yòng kè yì jì jiào lǐ wù jià zhí， bù yòng fēi yào děng jià huí zèng。','Bạn bè không cần tính toán giá trị món quà làm gì, không cần phải đáp lại tương xứng đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L914_05','V914','阮明',5,'下次过节千万不要买高价礼品，不然我不敢再收你的礼物了。','xià cì guò jié qiān wàn bú yào mǎi gāo jià lǐ pǐn， bù rán wǒ bù gǎn zài shōu nǐ de lǐ wù le。','Lần sau đến dịp lễ tuyệt đối đừng mua quà đắt tiền nữa, không thì tớ không dám nhận quà của cậu nữa đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L914_06','V914','苏雯',6,'好，之后只送零食、书签这类平价小物件。','hǎo， zhī hòu zhǐ sòng líng shí、 shū qiān zhè lèi píng jià xiǎo wù jiàn。','Được rồi, sau này tớ chỉ tặng đồ ăn vặt, bookmark kiểu vật nhỏ giá bình dân thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L914_07','V914','阮明',7,'这样轻松相处，不用因为人情礼物有心理负担。','zhè yàng qīng sōng xiāng chǔ， bù yòng yīn wèi rén qíng lǐ wù yǒu xīn lǐ fù dān。','Như vậy mới thoải mái, không phải vì quà cáp mà mang gánh nặng tâm lý.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT915','SXH3','因中外饮食礼仪差异产生小尴尬，主动和朋友解释本国习惯',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V915','SIT915','P1','suon_se','tuy_y',NULL,'中外餐桌礼仪存在大量差异，出现小尴尬主动说明本国习惯，多数中国年轻人会包容理解，不会苛责。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L915_01','V915','阮明',1,'刚刚吃饭我直接端碗喝汤，是不是和国内餐桌礼仪不一样？','gāng gāng chī fàn wǒ zhí jiē duān wǎn hē tāng， shì bú shì hé guó nèi cān zhuō lǐ yí bù yí yàng？','Vừa nãy ăn cơm tớ bưng bát húp canh trực tiếp, có phải khác với phép tắc bàn ăn ở đây không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L915_02','V915','苏雯',2,'这边习惯碗放在桌上喝汤，我还以为你不太适应菜品。','zhè biān xí guàn wǎn fàng zài zhuō shàng hē tāng， wǒ hái yǐ wéi nǐ bù tài shì yìng cài pǐn。','Ở đây quen để bát trên bàn húp canh, tớ còn tưởng cậu không hợp món ăn chứ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L915_03','V915','阮明',3,'越南日常吃饭都会端起碗，是从小养成的饮食习惯，没有失礼的意思。','yuè nán rì cháng chī fàn dōu huì duān qǐ wǎn， shì cóng xiǎo yǎng chéng de yǐn shí xí guàn， méi yǒu shī lǐ de yì si。','Ở Việt Nam ăn cơm hằng ngày đều bưng bát lên, đó là thói quen từ nhỏ, không có ý gì thất lễ đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L915_04','V915','苏雯',4,'原来是两国礼仪差别，完全没关系，我能理解。','yuán lái shì liǎng guó lǐ yí chā bié， wán quán méi guān xì， wǒ néng lǐ jiě。','Hóa ra là khác biệt phép tắc giữa hai nước thôi, không sao cả, tớ hiểu mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L915_05','V915','阮明',5,'下次聚餐我会注意入乡随俗，兼顾这边餐桌习惯。','xià cì jù cān wǒ huì zhù yì rù xiāng suí sú， jiān gù zhè biān cān zhuō xí guàn。','Lần sau ăn uống chung tớ sẽ chú ý nhập gia tùy tục, để hợp với thói quen bàn ăn ở đây hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L915_06','V915','苏雯',6,'不用刻意改变自己，两国习俗不同很正常，不用拘谨。','bù yòng kè yì gǎi biàn zì jǐ， liǎng guó xí sú bù tóng hěn zhèng cháng， bù yòng jū jǐn。','Không cần cố ý thay đổi bản thân đâu, phong tục hai nước khác nhau là chuyện bình thường, cậu đừng gò bó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L915_07','V915','阮明',7,'谢谢你包容不同的饮食礼仪，不会让我觉得尴尬。','xiè xiè nǐ bāo róng bù tóng de yǐn shí lǐ yí， bú huì ràng wǒ jué de gān gà。','Cảm ơn cậu đã bao dung với phép tắc ăn uống khác biệt, không làm tớ thấy ngại chút nào.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT916','SXH3','说话直爽无意间冒犯中国同学，事后主动道歉、说明文化差异',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V916','SIT916','P1','twist','ban_chinh_thuc',NULL,'东南亚部分国家交流风格直白，和国内委婉含蓄的沟通方式有冲突，产生矛盾后主动解释文化差异并道歉，容易化解隔阂。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_01','V916','阮明',1,'昨天聊天我说话太直接，伤到你的感受，我郑重跟你道歉。','zuó tiān liáo tiān wǒ shuō huà tài zhí jiē， shāng dào nǐ de gǎn shòu， wǒ zhèng zhòng gēn nǐ dào qiàn。','Hôm qua nói chuyện tớ ăn nói thẳng quá, làm cậu buồn lòng, tớ xin lỗi cậu một cách nghiêm túc.',NULL) ON CONFLICT DO NOTHING;
