
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT735','SSH5','干洗店送洗衣物，询问污渍清洗、取件时效',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V735','SIT735','P1','twist','tuy_y',NULL,'重度油污、陈年污渍无法保证完全洗净，干洗店会根据清洗效果调整收费，提前告知顾客预期。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L735_01','V735','阮明',1,'你好，这件外套沾了油污，送过来干洗能完全洗掉污渍吗？','nǐ hǎo， zhè jiàn wài tào zhān le yóu wū， sòng guò lái gān xǐ néng wán quán xǐ diào wū zì ma？','Chào anh, cái áo khoác này dính dầu mỡ, đem giặt khô ở đây có sạch hết được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L735_02','V735','干洗店员',2,'大面积油污需要特殊去渍剂，不一定能彻底清除干净。','dà miàn jī yóu wū xū yào tè shū qù zì jì， bù yí dìng néng chè dǐ qīng chú gān jìng。','Vết dầu loang diện rộng như này cần dùng chất tẩy chuyên dụng, chưa chắc đã sạch hoàn toàn đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L735_03','V735','阮明',3,'要是洗完还有残留油污，会收取全套干洗费用嘛？','yào shì xǐ wán hái yǒu cán liú yóu wū， huì shōu qǔ quán tào gān xǐ fèi yòng ma？','Vậy nếu giặt xong mà vẫn còn dính dầu, tiệm có tính đủ tiền giặt khô không ạ?','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L735_04','V735','干洗店员',4,'尽力清洗，无法去除重度污渍仅收取基础洗护半价嘛。','jìn lì qīng xǐ， wú fǎ qù chú zhòng dù wū zì jǐn shōu qǔ jī chǔ xǐ hù bàn jià ma。','Bên anh sẽ cố hết sức để giặt, nếu vết bẩn nặng quá không tẩy được thì chỉ tính nửa giá giặt cơ bản thôi.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L735_05','V735','阮明',5,'正常洗护多久可以取件，三天后过来取来得及吗？','zhèng cháng xǐ hù duō jiǔ kě yǐ qǔ jiàn， sān tiān hòu guò lái qǔ lái de jí ma？','Giặt bình thường thì mất mấy ngày lấy được, ba ngày sau em quay lại lấy có kịp không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L735_06','V735','干洗店员',6,'标准洗护两天完工，三天来取完全没有问题。','biāo zhǔn xǐ hù liǎng tiān wán gōng， sān tiān lái qǔ wán quán méi yǒu wèn tí。','Giặt tiêu chuẩn hai ngày là xong rồi, ba ngày sau lấy hoàn toàn thoải mái.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L735_07','V735','阮明',7,'那我把外套留在店里，后天下午前来取衣服。','nà wǒ bǎ wài tào liú zài diàn lǐ， hòu tiān xià wǔ qián lái qǔ yī fú。','Vậy em để áo lại tiệm nha, chiều mốt em quay lại lấy áo.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT736','SSH5','上门保洁预约，和保洁阿姨确认清洁范围与时间',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V736','SIT736','P1','suon_se','ban_chinh_thuc',NULL,'上门保洁分基础清扫、深度清洁两类服务，厨房重度油污清理属于额外增值服务，需要增加时长与费用。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L736_01','V736','阮明',1,'阿姨，我预约两小时全屋保洁，跟您确认清洁区域吧。','ā yí， wǒ yù yuē liǎng xiǎo shí quán wū bǎo jié， gēn nín què rèn qīng jié qū yù ba。','Chị ơi, em đặt hai tiếng dọn dẹp toàn bộ nhà, để em xác nhận lại khu vực dọn với chị nhé.','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L736_02','V736','保洁阿姨',2,'客厅、卧室、卫生间常规清扫，厨房油污深度清洗需要额外加时。','kè tīng、 wò shì、 wèi shēng jiān cháng guī qīng sǎo， chú fáng yóu wū shēn dù qīng xǐ xū yào é wài jiā shí。','Phòng khách, phòng ngủ, nhà vệ sinh thì lau dọn bình thường, còn bếp mà muốn tẩy sạch dầu mỡ thì cần tính thêm giờ ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L736_03','V736','阮明',3,'厨房简单擦拭台面即可，不用深度清理厚重油污。','chú fáng jiǎn dān cā shì tái miàn jí kě， bù yòng shēn dù qīng lǐ hòu zhòng yóu wū。','Bếp thì chỉ cần lau sơ mặt bàn thôi, không cần dọn kỹ hết lớp dầu mỡ dày đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L736_04','V736','保洁阿姨',4,'两小时只做基础除尘拖地，不含重度厨房油污清理。','liǎng xiǎo shí zhǐ zuò jī chǔ chú chén tuō dì， bù hán zhòng dù chú fáng yóu wū qīng lǐ。','Hai tiếng thì chỉ làm phần lau bụi, lau nhà cơ bản thôi, không bao gồm dọn dầu mỡ nặng trong bếp ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L736_05','V736','阮明',5,'本周六上午九点上门，我提前把桌面杂物收纳好。','běn zhōu liù shàng wǔ jiǔ diǎn shàng mén， wǒ tí qián bǎ zhuō miàn zá wù shōu nà hǎo。','Thứ Bảy này chín giờ sáng chị đến nhé, em sẽ dọn đồ đạc trên bàn gọn gàng trước.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L736_06','V736','保洁阿姨',6,'到点准时上门，杂物收纳干净清洁效率更高。','dào diǎn zhǔn shí shàng mén， zá wù shōu nà gān jìng qīng jié xiào lǜ gèng gāo。','Vậy đúng giờ chị sẽ đến, đồ đạc gọn gàng thì dọn dẹp cũng nhanh và hiệu quả hơn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L736_07','V736','阮明',7,'我提前整理房间，方便阿姨快速完成全屋保洁。','wǒ tí qián zhěng lǐ fáng jiān， fāng biàn ā yí kuài sù wán chéng quán wū bǎo jié。','Em sẽ dọn phòng trước, để chị tiện làm sạch cả nhà cho nhanh.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT737','SSH6','报名校园羽毛球社团，咨询会费、活动固定时间',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V737','SIT737','P1','suon_se','tuy_y',NULL,'国内高校学生社团会费低廉，仅用于活动耗材、场地租赁，定期开展免费校内文体活动。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L737_01','V737','阮明',1,'学长，我想加入羽毛球社团，请问入社需要缴纳会费吗？','xué zhǎng， wǒ xiǎng jiā rù yǔ máo qiú shè tuán， qǐng wèn rù shè xū yào jiǎo nà huì fèi ma？','Anh ơi, em muốn tham gia câu lạc bộ cầu lông, vào câu lạc bộ có phải đóng hội phí không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L737_02','V737','学长',2,'一年二十元会费，全部用于采购羽毛球、场地租赁哦。','yī nián èr shí yuán huì fèi， quán bù yòng yú cǎi gòu yǔ máo qiú、 chǎng dì zū lìn ó。','Một năm hội phí hai mươi tệ, dùng hết để mua cầu lông với thuê sân đó.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L737_03','V737','阮明',3,'社团固定活动周几开展，是校内体育馆场地吗？','shè tuán gù dìng huó dòng zhōu jǐ kāi zhǎn， shì xiào nèi tǐ yù guǎn chǎng dì ma？','Câu lạc bộ sinh hoạt cố định vào thứ mấy vậy anh, có phải ở nhà thi đấu trong trường không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L737_04','V737','学长',4,'每周四傍晚六点到八点，校内羽毛球馆专属场地。','měi zhōu sì bàng wǎn liù diǎn dào bā diǎn， xiào nèi yǔ máo qiú guǎn zhuān shǔ chǎng dì。','Mỗi tối thứ Năm từ sáu đến tám giờ, ở nhà thi đấu cầu lông riêng trong trường luôn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L737_05','V737','阮明',5,'没有自带球拍，社团可以临时借用训练球拍吗？','méi yǒu zì dài qiú pāi， shè tuán kě yǐ lín shí jiè yòng xùn liàn qiú pāi ma？','Em không có vợt riêng, câu lạc bộ có cho mượn vợt tập tạm thời không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L737_06','V737','学长',6,'新人可免费借用公用球拍，长期参与建议自备球拍。','xīn rén kě miǎn fèi jiè yòng gōng yòng qiú pāi， cháng qī cān yù jiàn yì zì bèi qiú pāi。','Thành viên mới thì được mượn vợt chung miễn phí, còn tham gia lâu dài thì nên tự sắm vợt riêng nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L737_07','V737','阮明',7,'我今天缴纳会费入社，周四准时参加社团活动。','wǒ jīn tiān jiǎo nà huì fèi rù shè， zhōu sì zhǔn shí cān jiā shè tuán huó dòng。','Vậy hôm nay em đóng hội phí vào câu lạc bộ luôn, thứ Năm em sẽ đến sinh hoạt đúng giờ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT738','SSH6','校园操场运动扭伤，前往医务室简单处理伤口',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V738','SIT738','P1','twist','ban_chinh_thuc',NULL,'校内医务室跌打损伤、消炎外敷药品均可医保报销，运动受伤可免费冷敷理疗处理。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L738_01','V738','阮明',1,'护士，操场跑步崴到脚踝，现在肿胀疼痛没法正常走路。','hù shì， cāo chǎng pǎo bù wǎi dào jiǎo huái， xiàn zài zhǒng zhàng téng tòng méi fǎ zhèng cháng zǒu lù。','Cô ơi, em chạy ở sân vận động bị trẹo mắt cá chân, giờ sưng đau không đi lại bình thường được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L738_02','V738','护士',2,'先坐下抬高腿部冷敷消肿，我给你开外用消炎药膏。','xiān zuò xià tái gāo tuǐ bù lěng fū xiāo zhǒng， wǒ gěi nǐ kāi wài yòng xiāo yán yào gāo。','Em ngồi xuống, kê cao chân lên chườm lạnh cho giảm sưng, cô sẽ kê cho em thuốc mỡ kháng viêm bôi ngoài.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L738_03','V738','阮明',3,'冷敷需要持续多久，今晚还能正常下床行走吗？','lěng fū xū yào chí xù duō jiǔ， jīn wǎn hái néng zhèng cháng xià chuáng xíng zǒu ma？','Chườm lạnh cần bao lâu vậy cô, tối nay em có xuống giường đi lại bình thường được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L738_04','V738','护士',4,'连续冷敷二十分钟，三天之内尽量减少走路、剧烈运动嘛。','lián xù lěng fū èr shí fēn zhōng， sān tiān zhī nèi jǐn liàng jiǎn shǎo zǒu lù、 jù liè yùn dòng ma。','Chườm lạnh liên tục hai mươi phút, trong ba ngày cố gắng hạn chế đi lại, vận động mạnh nhé.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L738_05','V738','阮明',5,'药膏医保可以报销吗，还是需要全额自费购买？','yào gāo yī bǎo kě yǐ bào xiāo ma， hái shì xū yào quán é zì fèi gòu mǎi？','Thuốc mỡ có được bảo hiểm y tế thanh toán không ạ, hay em phải tự trả toàn bộ tiền thuốc?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L738_06','V738','护士',6,'外用跌打药膏纳入学生医保，只需要自费三成费用。','wài yòng diē dǎ yào gāo nà rù xué shēng yī bǎo， zhǐ xū yào zì fèi sān chéng fèi yòng。','Thuốc mỡ trị bong gân được đưa vào bảo hiểm y tế sinh viên, em chỉ cần tự trả ba mươi phần trăm thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L738_07','V738','阮明',7,'我拿药之后回宿舍静养，不再剧烈运动加重扭伤。','wǒ ná yào zhī hòu huí sù shè jìng yǎng， bù zài jù liè yùn dòng jiā zhòng niǔ shāng。','Em lấy thuốc xong sẽ về ký túc xá nghỉ ngơi, không vận động mạnh nữa kẻo trẹo nặng thêm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT739','SSH6','咨询校园奖学金申请条件、提交材料截止日期',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V739','SIT739','P1','suon_se','chinh_thuc',NULL,'留学生奖学金对出勤率、期末分数有硬性门槛，逾期不接受补报，错过只能等待下一学年申报。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L739_01','V739','阮明',1,'老师您好，想咨询留学生校级奖学金的申请基础条件。','lǎo shī nín hǎo， xiǎng zī xún liú xué shēng xiào jí jiǎng xué jīn de shēn qǐng jī chǔ tiáo jiàn。','Chào thầy/cô, em muốn hỏi về điều kiện cơ bản để nộp đơn xin học bổng cấp trường dành cho lưu học sinh ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L739_02','V739','教务老师',2,'全年出勤率达标、期末平均分七十五分以上方可申报。','quán nián chū qín lǜ dá biāo、 qī mò píng jūn fēn qī shí wǔ fēn yǐ shàng fāng kě shēn bào。','Tỷ lệ chuyên cần cả năm phải đạt chuẩn, điểm trung bình học kỳ từ bảy mươi lăm điểm trở lên mới đủ điều kiện đăng ký.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L739_03','V739','阮明',3,'申请需要提交成绩单、在校证明，截止提交日期是哪天？','shēn qǐng xū yào tí jiāo chéng jì dān、 zài xiào zhèng míng， jié zhǐ tí jiāo rì qī shì nǎ tiān？','Hồ sơ cần nộp bảng điểm, giấy xác nhận đang học, vậy hạn chót nộp hồ sơ là ngày nào ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L739_04','V739','教务老师',4,'本月二十五号下午五点关闭申报通道，逾期不予受理。','běn yuè èr shí wǔ hào xià wǔ wǔ diǎn guān bì shēn bào tōng dào， yú qī bù yǔ shòu lǐ。','Cổng đăng ký sẽ đóng lúc năm giờ chiều ngày hai mươi lăm tháng này, nộp trễ sẽ không được xét ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L739_05','V739','阮明',5,'材料线上系统提交，还是纸质复印件线下上交学院？','cái liào xiàn shàng xì tǒng tí jiāo， hái shì zhǐ zhì fù yìn jiàn xiàn xià shàng jiāo xué yuàn？','Hồ sơ nộp qua hệ thống online, hay là nộp bản giấy photo trực tiếp cho khoa ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L739_06','V739','教务老师',6,'线上填报信息，纸质材料线下送至国际学院办公室。','xiàn shàng tián bào xìn xī， zhǐ zhì cái liào xiàn xià sòng zhì guó jì xué yuàn bàn gōng shì。','Điền thông tin online, còn bản giấy thì nộp trực tiếp tại văn phòng học viện quốc tế nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L739_07','V739','阮明',7,'我这周整理好全部材料，提前完成奖学金申报。','wǒ zhè zhōu zhěng lǐ hǎo quán bù cái liào， tí qián wán chéng jiǎng xué jīn shēn bào。','Vậy tuần này em sẽ chuẩn bị đầy đủ hồ sơ, hoàn thành đăng ký học bổng sớm ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT740','SSH6','校内丢失水杯、雨伞，去失物招领处登记寻物',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V740','SIT740','P1','that_bai_nhe','tuy_y',NULL,'校园失物招领处仅短期保管遗失物品，超过一周无人认领会统一收纳，长期无人认领定期清理。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L740_01','V740','阮明',1,'你好，我昨天操场丢失黑色水杯、折叠雨伞，前来登记寻物。','nǐ hǎo， wǒ zuó tiān cāo chǎng diū shī hēi sè shuǐ bēi、 zhé dié yǔ sǎn， qián lái dēng jì xún wù。','Chào anh/chị, hôm qua em làm mất bình nước màu đen và cây dù gấp ở sân vận động, em đến đăng ký tìm đồ ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L740_02','V740','工作人员',2,'登记物品外观、丢失地点、你的联系方式，有人上交会通知你。','dēng jì wù pǐn wài guān、 diū shī dì diǎn、 nǐ de lián xì fāng shì， yǒu rén shàng jiāo huì tōng zhī nǐ。','Em đăng ký hình dạng đồ vật, chỗ mất, số điện thoại liên hệ của em, có ai nộp lên thì bên anh/chị sẽ báo cho em.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L740_03','V740','阮明',3,'水杯侧面印有越南文字标识，雨伞是深蓝色，特征很明显。','shuǐ bēi cè miàn yìn yǒu yuè nán wén zì biāo shí， yǔ sǎn shì shēn lán sè， tè zhēng hěn míng xiǎn。','Bình nước có in chữ tiếng Việt ở mặt bên, còn dù thì màu xanh navy, đặc điểm khá rõ ràng ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L740_04','V740','工作人员',4,'今日上交失物清单没有匹配物品，大概率还未被捡拾上交嘛。','jīn rì shàng jiāo shī wù qīng dān méi yǒu pǐ pèi wù pǐn， dà gài lǜ hái wèi bèi jiǎn shí shàng jiāo ma。','Danh sách đồ thất lạc nộp lên hôm nay không khớp món nào cả, chắc là chưa ai nhặt được nộp lên đâu.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L740_05','V740','阮明',5,'要是之后有人送到招领处，麻烦打电话通知我过来领取。','yào shì zhī hòu yǒu rén sòng dào zhāo lǐng chù， má fán dǎ diàn huà tōng zhī wǒ guò lái lǐng qǔ。','Nếu sau này có ai đem nộp lên, phiền anh/chị gọi điện báo em đến nhận nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L740_06','V740','工作人员',6,'登记信息留存一周，一周无人认领物品统一清理存放。','dēng jì xìn xī liú cún yī zhōu， yī zhōu wú rén rèn lǐng wù pǐn tǒng yī qīng lǐ cún fàng。','Thông tin đăng ký sẽ lưu lại một tuần, sau một tuần không ai nhận thì đồ sẽ được gom lại lưu kho.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L740_07','V740','阮明',7,'我三天后再来招领处询问，看看有没有捡到我的物品。','wǒ sān tiān hòu zài lái zhāo lǐng chù xún wèn， kàn kàn yǒu méi yǒu jiǎn dào wǒ de wù pǐn。','Ba ngày nữa em sẽ quay lại phòng tìm đồ hỏi thăm, xem có nhặt được đồ của em chưa.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT801','SHT1','向同班同学借课件PPT，拷贝到自己电脑复习',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V801','SIT801','P1','suon_se','tuy_y',NULL,'国内课堂老师大多会课后分享电子课件，同学之间互相转发课件、笔记是很普遍的互助学习习惯。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L801_01','V801','阮明',1,'苏雯，昨天专业课老师的课件我忘记拷贝，能发我一份PPT吗？','sū wén， zuó tiān zhuān yè kè lǎo shī de kè jiàn wǒ wàng jì kǎo bèi， néng fā wǒ yī fèn PPT ma？','Tô Văn ơi, hôm qua mình quên copy slide bài giảng chuyên ngành của thầy, cậu gửi cho mình bản PPT được không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L801_02','V801','苏雯',2,'没问题，我把完整课件打包，微信文件传输发给你就行啦。','méi wèn tí， wǒ bǎ wán zhěng kè jiàn dǎ bāo， wēi xìn wén jiàn chuán shū fā gěi nǐ jiù xíng la。','Không vấn đề gì, mình đóng gói cả bộ slide lại rồi gửi qua truyền file WeChat cho cậu là được nè.','AM02') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L801_03','V801','阮明',3,'文件内存很大，微信会不会压缩模糊里面的表格内容？','wén jiàn nèi cún hěn dà， wēi xìn huì bú huì yā suō mó hú lǐ miàn de biǎo gé nèi róng？','File nặng vậy WeChat có nén làm mờ mấy cái bảng biểu trong đó không ta?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L801_04','V801','苏雯',4,'我发原文件不压缩，要是打不开我再分享网盘链接给你呢。','wǒ fā yuán wén jiàn bù yā suō， yào shì dǎ bù kāi wǒ zài fēn xiǎng wǎng pán liàn jiē gěi nǐ ne。','Mình gửi file gốc không nén đâu, nếu mở không được thì mình chia sẻ link ổ đĩa mạng cho cậu nhé.','AM04') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L801_05','V801','阮明',5,'太好了，我今晚对照课件梳理今天课堂没听懂的知识点。','tài hǎo le， wǒ jīn wǎn duì zhào kè jiàn shū lǐ jīn tiān kè táng méi tīng dǒng de zhī shí diǎn。','Tuyệt quá, tối nay mình đối chiếu slide để rà lại mấy chỗ chưa hiểu trên lớp hôm nay.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L801_06','V801','苏雯',6,'课件里标注了期末重点，复习的时候可以优先看标红部分。','kè jiàn lǐ biāo zhù le qī mò zhòng diǎn， fù xí de shí hòu kě yǐ yōu xiān kàn biāo hóng bù fèn。','Trong slide có đánh dấu trọng tâm cuối kỳ đó, lúc ôn thì ưu tiên xem phần bôi đỏ trước nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L801_07','V801','阮明',7,'太感谢你，有完整课件复习会轻松很多。','tài gǎn xiè nǐ， yǒu wán zhěng kè jiàn fù xí huì qīng sōng hěn duō。','Cảm ơn cậu nhiều lắm, có slide đầy đủ thì ôn bài nhẹ nhàng hơn hẳn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT802','SHT1','询问老师课堂录音是否允许，方便课后复盘知识点',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V802','SIT802','P1','twist','ban_chinh_thuc',NULL,'课堂自用录音一般老师都会许可，但传播授课录音、课件属于侵犯教学版权，会被制止。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L802_01','V802','阮明',1,'李老师，我汉语听力反应慢一点，请问上课可以手机录音吗？','lǐ lǎo shī， wǒ hàn yǔ tīng lì fǎn yìng màn yì diǎn， qǐng wèn shàng kè kě yǐ shǒu jī lù yīn ma？','Thầy Lý ơi, em nghe tiếng Trung phản xạ hơi chậm, thầy cho em ghi âm bài giảng được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L802_02','V802','李老师',2,'单纯自己课后复习录音是可以的，但禁止转发、上传网络平台。','dān chún zì jǐ kè hòu fù xí lù yīn shì kě yǐ de， dàn jìn zhǐ zhuǎn fā、 shàng chuán wǎng luò píng tái。','Chỉ tự ghi âm để ôn lại cho bản thân thì được, nhưng cấm chuyển phát cho người khác hay đăng lên mạng nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L802_03','V802','阮明',3,'我只自己私下复盘，绝对不会分享录音给其他同学或者发到网上。','wǒ zhǐ zì jǐ sī xià fù pán， jué duì bú huì fēn xiǎng lù yīn gěi qí tā tóng xué huò zhě fā dào wǎng shàng。','Em chỉ tự nghe lại riêng thôi ạ, tuyệt đối không chia sẻ bản ghi âm cho bạn khác hay đăng lên mạng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L802_04','V802','李老师',4,'还有一点，录音不能遮挡其他同学，手机音量一定要完全静音嘛。','hái yǒu yì diǎn， lù yīn bù néng zhē dǎng qí tā tóng xué， shǒu jī yīn liàng yí dìng yào wán quán jìng yīn ma。','Còn một điều nữa, ghi âm không được che khuất các bạn khác, và điện thoại phải để im lặng hoàn toàn nhé.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L802_05','V802','阮明',5,'我把手机调成飞行模式，只开启本地录音，不会弹出消息打扰课堂。','wǒ bǎ shǒu jī diào chéng fēi xíng mó shì， zhǐ kāi qǐ běn dì lù yīn， bú huì dàn chū xiāo xī dǎ rǎo kè táng。','Em sẽ để điện thoại ở chế độ máy bay, chỉ bật ghi âm nội bộ thôi, sẽ không có thông báo hiện lên làm phiền lớp học đâu ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L802_06','V802','李老师',6,'如果后期有听不懂的地方，结合录音再来办公室问我也可以。','rú guǒ hòu qī yǒu tīng bù dǒng de dì fāng， jié hé lù yīn zài lái bàn gōng shì wèn wǒ yě kě yǐ。','Nếu sau này có chỗ nào không hiểu, em cứ kết hợp bản ghi âm rồi lên văn phòng hỏi thầy cũng được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L802_07','V802','阮明',7,'谢谢您允许录音，课后我能反复梳理课堂难点。','xiè xiè nín yǔn xǔ lù yīn， kè hòu wǒ néng fǎn fù shū lǐ kè táng nán diǎn。','Em cảm ơn thầy đã cho phép ghi âm, sau giờ học em có thể xem lại nhiều lần những chỗ khó ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT803','SHT1','课堂听不懂专业词汇，课后找同学一对一讲解',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V803','SIT803','P1','suon_se','tuy_y',NULL,'课后同学之间一对一拆解难点、互相讲题是高校主流互助学习方式。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L803_01','V803','阮明',1,'今天课上老师讲的几个贸易专业术语，我完全没理解含义啊。','jīn tiān kè shàng lǎo shī jiǎng de jǐ gè mào yì zhuān yè shù yǔ， wǒ wán quán méi lǐ jiě hán yì a。','Hôm nay trên lớp thầy giảng mấy thuật ngữ chuyên ngành thương mại, mình chả hiểu gì cả luôn á.','AM05') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L803_02','V803','苏雯',2,'这几个词是国内外贸常用词汇，我举简单例子给你拆解意思。','zhè jǐ gè cí shì guó nèi wài mào cháng yòng cí huì， wǒ jǔ jiǎn dān lì zi gěi nǐ chāi jiě yì si。','Mấy từ này là từ vựng ngoại thương thông dụng trong nước á, để mình lấy ví dụ đơn giản phân tích cho cậu nghe.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L803_03','V803','阮明',3,'每个词汇搭配例句讲一遍，我才能分清使用场景对吧？','měi gè cí huì dā pèi lì jù jiǎng yī biàn， wǒ cái néng fēn qīng shǐ yòng chǎng jǐng duì ba？','Mỗi từ đi kèm câu ví dụ giảng qua một lượt, vậy mình mới phân biệt được ngữ cảnh sử dụng đúng không?','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L803_04','V803','苏雯',4,'没错，我结合课本习题举例，方便你区分易混淆词汇。','méi cuò， wǒ jié hé kè běn xí tí jǔ lì， fāng biàn nǐ qū fēn yì hùn xiáo cí huì。','Đúng rồi đó, mình sẽ lấy ví dụ theo bài tập trong sách, để cậu dễ phân biệt mấy từ hay bị nhầm lẫn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L803_05','V803','阮明',5,'耽误你半小时休息时间，实在不好意思麻烦你。','dān wù nǐ bàn xiǎo shí xiū xī shí jiān， shí zài bù hǎo yì sī má fán nǐ。','Làm mất nửa tiếng nghỉ ngơi của cậu, thật ngại quá đi mất.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L803_06','V803','苏雯',6,'互相讲题很正常，之后我有语言难题也会找你帮忙。','hù xiāng jiǎng tí hěn zhèng cháng， zhī hòu wǒ yǒu yǔ yán nán tí yě huì zhǎo nǐ bāng máng。','Giảng bài qua lại cho nhau là chuyện bình thường mà, sau này mình có vướng mắc gì về ngôn ngữ cũng nhờ cậu giúp nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L803_07','V803','阮明',7,'太感谢，听完讲解一下子清晰多了。','tài gǎn xiè， tīng wán jiǎng jiě yī xià zi qīng xī duō le。','Cảm ơn cậu nhiều, nghe cậu giảng xong là thấy rõ ràng hẳn lên luôn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT804','SHT1','咨询老师课程平时分构成：出勤、课堂发言、小测占比',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V804','SIT804','P1','suon_se','ban_chinh_thuc',NULL,'国内大学课程普遍实行平时分+期末试卷综合打分，不会仅凭一次期末成绩定总分，鼓励日常课堂参与。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L804_01','V804','阮明',1,'老师，想向您咨询这门课期末总评分数的分配标准。','lǎo shī， xiǎng xiàng nín zī xún zhè mén kè qī mò zǒng píng fēn shù de fēn pèi biāo zhǔn。','Thầy ơi, em muốn hỏi thầy về cách tính điểm tổng kết cuối kỳ của môn này ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L804_02','V804','李老师',2,'总评由三部分组成：出勤20%、课堂发言与随堂小测30%、期末试卷50%哦。','zǒng píng yóu sān bù fèn zǔ chéng： chū qín 20%、 kè táng fā yán yǔ suí táng xiǎo cè 30%、 qī mò shì juàn 50% ó。','Điểm tổng kết gồm ba phần: điểm danh 20%, phát biểu trên lớp cùng kiểm tra nhỏ 30%, bài thi cuối kỳ 50% nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L804_03','V804','阮明',3,'随堂小测每节课都会有吗，缺课一次会直接扣掉出勤分？','suí táng xiǎo cè měi jié kè dōu huì yǒu ma， quē kè yī cì huì zhí jiē kòu diào chū qín fēn？','Kiểm tra nhỏ buổi nào cũng có ạ, nghỉ học một buổi là bị trừ thẳng điểm chuyên cần luôn hả thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L804_04','V804','李老师',4,'无故缺课单次扣5分，请假备案不扣分；小测每月一次，错过可补。','wú gù quē kè dān cì kòu 5 fēn， qǐng jià bèi àn bù kòu fēn； xiǎo cè měi yuè yī cì， cuò guò kě bǔ。','Nghỉ không phép một lần trừ 5 điểm, có xin phép ghi nhận thì không bị trừ; kiểm tra nhỏ mỗi tháng một lần, lỡ có bỏ lỡ thì được thi bù.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L804_05','V804','阮明',5,'课堂发言只要主动回答问题，就能拿到对应的平时分吗？','kè táng fā yán zhǐ yào zhǔ dòng huí dá wèn tí， jiù néng ná dào duì yìng de píng shí fēn ma？','Phát biểu trên lớp chỉ cần chủ động trả lời câu hỏi là được tính điểm quá trình đúng không thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L804_06','V804','李老师',6,'主动思考作答、有完整观点，都会记录课堂表现分。','zhǔ dòng sī kǎo zuò dá、 yǒu wán zhěng guān diǎn， dōu huì jì lù kè táng biǎo xiàn fēn。','Chỉ cần chủ động suy nghĩ trả lời, có quan điểm rõ ràng, đều được ghi nhận vào điểm thể hiện trên lớp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L804_07','V804','阮明',7,'我清楚分值规则了，之后多主动参与课堂互动。','wǒ qīng chǔ fēn zhí guī zé le， zhī hòu duō zhǔ dòng cān yù kè táng hù dòng。','Em đã hiểu rõ quy tắc tính điểm rồi ạ, sau này em sẽ tích cực tham gia phát biểu hơn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT805','SHT1','忘记带课本，和同桌共用一本书听课',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V805','SIT805','P1','twist','tuy_y',NULL,'课堂忘记带教材和同桌共用书本很常见，但不建议长期如此，会影响双方记笔记效率。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L805_01','V805','阮明',1,'糟糕，早上出门匆忙，把专业课课本落在宿舍了，能和你共用一本吗？','zāo gāo， zǎo shàng chū mén cōng máng， bǎ zhuān yè kè kè běn luò zài sù shè le， néng hé nǐ gòng yòng yī běn ma？','Chết rồi, sáng nay ra khỏi nhà vội quá, mình để quên sách chuyên ngành ở ký túc xá, cho mình xem chung sách với cậu được không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L805_02','V805','小林',2,'可以一起看，不过书本放在中间，记笔记会有点挤不方便。','kě yǐ yì qǐ kàn， bù guò shū běn fàng zài zhōng jiān， jì bǐ jì huì yǒu diǎn jǐ bù fāng biàn。','Xem chung thì được, nhưng để sách ở giữa vậy ghi chép sẽ hơi chật, bất tiện đó.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L805_03','V805','阮明',3,'我只对照书页听讲解，笔记先记在草稿纸上，下课再整理。','wǒ zhǐ duì zhào shū yè tīng jiǎng jiě， bǐ jì xiān jì zài cǎo gǎo zhǐ shàng， xià kè zài zhěng lǐ。','Mình chỉ nhìn theo trang sách nghe giảng thôi, ghi chú thì tạm ghi ra giấy nháp, xuống lớp rồi sắp xếp lại sau.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L805_04','V805','小林',4,'老师等下要勾画重点段落，我们分开两边各自标注会不会混乱嘛。','lǎo shī děng xià yào gōu huà zhòng diǎn duàn luò， wǒ men fēn kāi liǎng biān gè zì biāo zhù huì bú huì hùn luàn ma。','Lát nữa thầy sẽ khoanh vùng đoạn trọng tâm, hai đứa mỗi bên tự đánh dấu riêng vậy có bị loạn không ta.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L805_05','V805','阮明',5,'我手机拍课本页面，重点自己在照片上标记，不影响你看书。','wǒ shǒu jī pāi kè běn yè miàn， zhòng diǎn zì jǐ zài zhào piān shàng biāo jì， bù yǐng xiǎng nǐ kàn shū。','Mình chụp ảnh trang sách bằng điện thoại, phần trọng tâm tự đánh dấu trên ảnh, không ảnh hưởng cậu xem sách đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L805_06','V805','小林',6,'这样也行，有看不懂的段落随时指给我一起讨论。','zhè yàng yě xíng， yǒu kàn bù dǒng de duàn luò suí shí zhǐ gěi wǒ yì qǐ tǎo lùn。','Vậy cũng được, có đoạn nào cậu không hiểu thì cứ chỉ cho mình để cùng bàn luôn nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L805_07','V805','阮明',7,'今天多亏你，不然整节课没法跟上老师进度。','jīn tiān duō kuī nǐ， bù rán zhěng jié kè méi fǎ gēn shàng lǎo shī jìn dù。','Hôm nay may có cậu giúp, không thì cả tiết học mình chẳng theo kịp tiến độ của thầy luôn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT806','SHT1','上课手机静音没做到，被老师提醒课堂纪律',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V806','SIT806','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内课堂严格管控手机声响，震动、响铃都会被老师提醒，多次违规会扣除课堂表现分。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L806_01','V806','阮明',1,'老师对不起，刚刚手机消息突然响铃，打断您讲课了。','lǎo shī duì bù qǐ， gāng gāng shǒu jī xiāo xī tū rán xiǎng líng， dǎ duàn nín jiǎng kè le。','Thầy ơi em xin lỗi, vừa nãy điện thoại em bỗng dưng đổ chuông, làm gián đoạn bài giảng của thầy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L806_02','V806','李老师',2,'课堂要求所有手机必须完全静音或关机，你忘记调整设置了？','kè táng yāo qiú suǒ yǒu shǒu jī bì xū wán quán jìng yīn huò guān jī， nǐ wàng jì tiáo zhěng shè zhì le？','Trên lớp yêu cầu tất cả điện thoại phải để im lặng hoàn toàn hoặc tắt máy, em quên chỉnh lại rồi à?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L806_03','V806','阮明',3,'早上调了震动，没想到震动声响也很明显，干扰全班听课嘛。','zǎo shàng diào le zhèn dòng， méi xiǎng dào zhèn dòng shēng xiǎng yě hěn míng xiǎn， gān rǎo quán bān tīng kè ma。','Sáng nay em để chế độ rung, không ngờ tiếng rung cũng lớn vậy, làm ồn cả lớp nghe giảng luôn ạ.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L806_04','V806','李老师',4,'一次警告不计入扣分，之后如果再出现声响会扣除课堂平时分。','yī cì jǐng gào bù jì rù kòu fēn， zhī hòu rú guǒ zài chū xiàn shēng xiǎng huì kòu chú kè táng píng shí fēn。','Lần này cảnh cáo thôi không tính vào điểm trừ, nhưng sau này nếu còn phát ra tiếng động sẽ bị trừ điểm quá trình trên lớp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L806_05','V806','阮明',5,'我现在直接关机，整节课不再开启手机接收消息。','wǒ xiàn zài zhí jiē guān jī， zhěng jié kè bù zài kāi qǐ shǒu jī jiē shōu xiāo xī。','Em tắt máy luôn bây giờ ạ, cả tiết học em sẽ không mở điện thoại nhận tin nhắn nữa.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L806_06','V806','李老师',6,'课堂需要安静的听讲环境，还请遵守班级课堂规定。','kè táng xū yào ān jìng de tīng jiǎng huán jìng， hái qǐng zūn shǒu bān jí kè táng guī dìng。','Lớp học cần một môi trường yên tĩnh để nghe giảng, mong em tuân thủ đúng quy định của lớp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L806_07','V806','阮明',7,'我记住教训，之后课前一定检查手机静音状态。','wǒ jì zhù jiào xùn， zhī hòu kè qián yí dìng jiǎn chá shǒu jī jìng yīn zhuàng tài。','Em xin ghi nhớ bài học này, sau này trước giờ học nhất định sẽ kiểm tra chế độ im lặng của điện thoại.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT807','SHT1','咨询课程课外拓展阅读书目、图书馆馆藏位置',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V807','SIT807','P1','suon_se','ban_chinh_thuc',NULL,'大学专业课会配套拓展阅读书目，图书馆专业馆藏区集中存放对应书籍，支持学生课外自主拓展学习。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L807_01','V807','阮明',1,'老师，想提升专业水平，请问这门课配套拓展阅读书籍有哪些？','lǎo shī， xiǎng tí shēng zhuān yè shuǐ píng， qǐng wèn zhè mén kè pèi tào tuò zhǎn yuè dú shū jí yǒu nǎ xiē？','Thầy ơi, em muốn nâng cao trình độ chuyên ngành, thầy cho em hỏi môn này có những sách đọc thêm nào ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L807_02','V807','李老师',2,'我列三本核心参考书，全部存放在图书馆三楼外文专业区哦。','wǒ liè sān běn hé xīn cān kǎo shū， quán bù cún fàng zài tú shū guǎn sān lóu wài wén zhuān yè qū ó。','Thầy liệt kê ba cuốn sách tham khảo cốt lõi, tất cả đều để ở khu chuyên ngành ngoại văn tầng ba thư viện nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L807_03','V807','阮明',3,'这几本书可以外借带回家长期阅读，还是只能馆内阅览？','zhè jǐ běn shū kě yǐ wài jiè dài huí jiā zhǎng qī yuè dú， hái shì zhǐ néng guǎn nèi yuè lǎn？','Mấy cuốn này có được mượn về nhà đọc lâu dài không ạ, hay chỉ đọc tại thư viện thôi thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L807_04','V807','李老师',4,'均可借阅三十天，线上系统还能办理续借延长阅读时间。','jūn kě jiè yuè sān shí tiān， xiàn shàng xì tǒng hái néng bàn lǐ xù jiè yán cháng yuè dú shí jiān。','Đều được mượn trong ba mươi ngày, hệ thống online còn cho gia hạn thêm thời gian đọc nữa.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L807_05','V807','阮明',5,'我记下书名，下课直接去图书馆检索借阅。','wǒ jì xià shū míng， xià kè zhí jiē qù tú shū guǎn jiǎn suǒ jiè yuè。','Em ghi lại tên sách rồi, xuống lớp em ra thư viện tra cứu mượn luôn ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L807_06','V807','李老师',6,'阅读完有疑问，随时来办公室和我交流书中观点。','yuè dú wán yǒu yí wèn， suí shí lái bàn gōng shì hé wǒ jiāo liú shū zhōng guān diǎn。','Đọc xong có gì thắc mắc thì cứ lên văn phòng trao đổi quan điểm trong sách với thầy nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L807_07','V807','阮明',7,'感谢老师推荐书目，对我的专业学习帮助很大。','gǎn xiè lǎo shī tuī jiàn shū mù， duì wǒ de zhuān yè xué xí bāng zhù hěn dà。','Em cảm ơn thầy đã gợi ý sách, giúp ích rất nhiều cho việc học chuyên ngành của em ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT808','SHT1','小组讨论时观点分歧，和组员温和协商统一思路',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V808','SIT808','P1','suon_se','tuy_y',NULL,'国内小组作业鼓励充分发表不同观点，通过讨论、分工、投票协商统一方案，不强行听从单一人员想法。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L808_01','V808','阮明',1,'我对小组报告案例选取有不同想法，和大家现在选定的方向不一样。','wǒ duì xiǎo zǔ bào gào àn lì xuǎn qǔ yǒu bù tóng xiǎng fǎ， hé dà jiā xiàn zài xuǎn dìng de fāng xiàng bù yí yàng。','Mình có ý tưởng khác về việc chọn case cho báo cáo nhóm, khác với hướng mà mọi người đang chọn hiện tại.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L808_02','V808','苏雯',2,'你说说你的思路，我们一起对比两个方案的优劣再做决定。','nǐ shuō shuō nǐ de sī lù， wǒ men yì qǐ duì bǐ liǎng gè fāng àn de yōu liè zài zuò jué dìng。','Cậu nói thử ý tưởng của cậu xem, tụi mình so sánh ưu nhược điểm của hai phương án rồi quyết định luôn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L808_03','V808','阮明',3,'我选的案例数据更贴近留学生视角，更容易结合我们课堂所学。','wǒ xuǎn de àn lì shù jù gèng tiē jìn liú xué shēng shì jiǎo， gèng róng yì jié hé wǒ men kè táng suǒ xué。','Case mình chọn có dữ liệu sát với góc nhìn của du học sinh hơn, dễ liên hệ với những gì tụi mình học trên lớp hơn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L808_04','V808','苏雯',4,'原有案例优势是资料充足，你的案例需要额外查找外文资料嘛。','yuán yǒu àn lì yōu shì shì zī liào chōng zú， nǐ de àn lì xū yào é wài chá zhǎo wài wén zī liào ma。','Case ban đầu ưu điểm là tài liệu đầy đủ sẵn, còn case của cậu thì phải tìm thêm tài liệu nước ngoài đó.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L808_05','V808','阮明',5,'我可以负责全部外文资料检索，分担小组搜集素材的工作量。','wǒ kě yǐ fù zé quán bù wài wén zī liào jiǎn suǒ， fēn dān xiǎo zǔ sōu jí sù cái de gōng zuò liàng。','Mình có thể phụ trách toàn bộ phần tra cứu tài liệu nước ngoài, chia sẻ bớt khối lượng công việc thu thập tư liệu cho nhóm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L808_06','V808','苏雯',6,'那我们投票，多数人认可你的方案就调整报告选题。','nà wǒ men tóu piào， duō shù rén rèn kě nǐ de fāng àn jiù tiáo zhěng bào gào xuǎn tí。','Vậy tụi mình biểu quyết nhé, nếu đa số đồng ý phương án của cậu thì tụi mình đổi đề tài báo cáo.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L808_07','V808','阮明',7,'谢谢大家愿意一起讨论，综合所有人想法完善作业。','xiè xiè dà jiā yuàn yì yì qǐ tǎo lùn， zōng hé suǒ yǒu rén xiǎng fǎ wán shàn zuò yè。','Cảm ơn mọi người đã sẵn lòng cùng bàn bạc, tổng hợp ý kiến của mọi người để bài làm hoàn thiện hơn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT809','SHT1','询问老师课堂发言加分规则，主动争取平时分',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V809','SIT809','P1','suon_se','ban_chinh_thuc',NULL,'大学课堂鼓励学生主动发言提问，以此折算平时分，平衡期末试卷单一考核的局限性。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L809_01','V809','阮明',1,'老师，想咨询课堂发言加分的详细规则，我想多争取平时表现分。','lǎo shī， xiǎng zī xún kè táng fā yán jiā fēn de xiáng xì guī zé， wǒ xiǎng duō zhēng qǔ píng shí biǎo xiàn fēn。','Thầy ơi, em muốn hỏi rõ quy định cộng điểm phát biểu trên lớp, em muốn cố gắng kiếm thêm điểm chuyên cần ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L809_02','V809','李老师',2,'主动举手回答、提出有价值疑问、上台简短分享，都能累加课堂分。','zhǔ dòng jǔ shǒu huí dá、 tí chū yǒu jià zhí yí wèn、 shàng tái jiǎn duǎn fēn xiǎng， dōu néng lěi jiā kè táng fēn。','Chủ động giơ tay trả lời, đặt câu hỏi có giá trị, hay lên bảng chia sẻ ngắn gọn, đều được cộng dồn điểm trên lớp cả.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L809_03','V809','阮明',3,'每次发言加分分值相同，还是完整长篇回答分值更高？','měi cì fā yán jiā fēn fēn zhí xiāng tóng， hái shì wán zhěng cháng piān huí dá fēn zhí gèng gāo？','Mỗi lần phát biểu điểm cộng có bằng nhau không thầy, hay trả lời đầy đủ, dài thì điểm cao hơn ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L809_04','V809','李老师',4,'不看长短，只要独立思考、贴合课堂主题，每次统一加2分。','bù kàn cháng duǎn， zhǐ yào dú lì sī kǎo、 tiē hé kè táng zhǔ tí， měi cì tǒng yī jiā 2 fēn。','Không tính dài ngắn đâu, chỉ cần tự suy nghĩ độc lập, bám sát chủ đề bài học là mỗi lần cộng đều 2 điểm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L809_05','V809','阮明',5,'每节课最多能几次发言，有没有单次课堂加分上限？','měi jié kè zuì duō néng jǐ cì fā yán， yǒu méi yǒu dān cì kè táng jiā fēn shàng xiàn？','Mỗi tiết học tối đa được phát biểu mấy lần vậy thầy, có giới hạn điểm cộng cho một buổi không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L809_06','V809','李老师',6,'无次数上限，只要不占用过多课堂时间均可主动发言。','wú cì shù shàng xiàn， zhǐ yào bù zhàn yòng guò duō kè táng shí jiān jūn kě zhǔ dòng fā yán。','Không giới hạn số lần, miễn là đừng chiếm quá nhiều thời gian lớp học thì cứ chủ động phát biểu thoải mái.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L809_07','V809','阮明',7,'之后每节课我主动思考提问、回答，积极参与课堂互动。','zhī hòu měi jié kè wǒ zhǔ dòng sī kǎo tí wèn、 huí dá， jī jí cān yù kè táng hù dòng。','Từ giờ mỗi tiết học em sẽ chủ động suy nghĩ, đặt câu hỏi, trả lời, tích cực tham gia tương tác trên lớp ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT810','SHT2','论文引用格式不懂，请教专业课老师规范要求',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V810','SIT810','P1','twist','chinh_thuc',NULL,'国内高校毕业论文统一执行国家标准参考文献格式，自媒体网络内容认可度低，学术写作优先纸质期刊、专著。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L810_01','V810','阮明',1,'老师，毕业论文参考文献引用格式我始终把握不准，想向您请教标准。','lǎo shī， bì yè lùn wén cān kǎo wén xiàn yǐn yòng gé shì wǒ shǐ zhōng bǎ wò bù zhǔn， xiǎng xiàng nín qǐng jiào biāo zhǔn。','Thưa thầy, em vẫn chưa nắm chắc được cách trích dẫn tài liệu tham khảo trong luận văn tốt nghiệp, mong thầy chỉ dạy cho em chuẩn mực cụ thể ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L810_02','V810','李老师',2,'校内统一使用GB/T7714国家标准格式，课件最后附完整范例。','xiào nèi tǒng yī shǐ yòng GB/T7714 guó jiā biāo zhǔn gé shì， kè jiàn zuì hòu fù wán zhěng fàn lì。','Trong trường thống nhất dùng định dạng theo tiêu chuẩn quốc gia GB/T7714, cuối slide bài giảng có kèm ví dụ đầy đủ rồi đấy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L810_03','V810','阮明',3,'外文书籍、期刊、网页资料三种文献格式区分很大对吗？','wài wén shū jí、 qī kān、 wǎng yè zī liào sān zhǒng wén xiàn gé shì qū fēn hěn dà duì ma？','Ba loại tài liệu là sách nước ngoài, tạp chí và tài liệu trên mạng có cách trình bày khác nhau nhiều đúng không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L810_04','V810','李老师',4,'网页自媒体资源不建议大量引用，书籍、正规期刊优先使用嘛。','wǎng yè zì méi tǐ zī yuán bù jiàn yì dà liàng yǐn yòng， shū jí、 zhèng guī qī kān yōu xiān shǐ yòng ma。','Tài liệu từ các trang mạng tự phát thì không nên trích dẫn nhiều, nên ưu tiên dùng sách và tạp chí chính thống hơn.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L810_05','V810','阮明',5,'我按照课件范例调整格式，修改完成后能麻烦您帮忙检查一遍吗？','wǒ àn zhào kè jiàn fàn lì tiáo zhěng gé shì， xiū gǎi wán chéng hòu néng má fán nín bāng máng jiǎn chá yī biàn ma？','Em sẽ chỉnh sửa theo đúng mẫu trong slide bài giảng, sau khi sửa xong phiền thầy giúp em kiểm tra lại một lượt được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L810_06','V810','李老师',6,'初稿定稿前可以发我线上预览，指出格式错误再修改。','chū gǎo dìng gǎo qián kě yǐ fā wǒ xiàn shàng yù lǎn， zhǐ chū gé shì cuò wù zài xiū gǎi。','Trước khi hoàn thiện bản cuối em có thể gửi bản xem trước cho thầy qua mạng, thầy sẽ chỉ ra chỗ sai định dạng để em sửa lại.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L810_07','V810','阮明',7,'谢谢您耐心指导引用规范，避免论文大量格式扣分。','xiè xiè nín nài xīn zhǐ dǎo yǐn yòng guī fàn， bì miǎn lùn wén dà liàng gé shì kòu fēn。','Em xin cảm ơn thầy đã kiên nhẫn hướng dẫn quy chuẩn trích dẫn, giúp em tránh bị trừ điểm định dạng nhiều trong luận văn ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT811','SHT2','查重重复率超标，咨询老师降重修改方法',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V811','SIT811','P1','that_bai_nhe','ban_chinh_thuc',NULL,'高校毕业论文查重有硬性重复率阈值，复制粘贴原文会判定学术不端，必须自行转述降重。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L811_01','V811','阮明',1,'老师，我的初稿论文查重重复率超过30%，达不到学校合格标准。','lǎo shī， wǒ de chū gǎo lùn wén chá chóng chóng fù lǜ chāo guò 30%， dá bú dào xué xiào hé gé biāo zhǔn。','Thầy ơi, bản nháp luận văn của em bị trùng lặp hơn 30%, chưa đạt tiêu chuẩn của trường ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L811_02','V811','李老师',2,'合格重复率要求控制在20%以内，超标需要大面积改写降重。','hé gé chóng fù lǜ yāo qiú kòng zhì zài 20% yǐ nèi， chāo biāo xū yào dà miàn jī gǎi xiě jiàng zhòng。','Tỷ lệ trùng lặp đạt yêu cầu phải kiểm soát dưới 20%, vượt mức thì phải viết lại phần lớn để giảm trùng lặp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L811_03','V811','阮明',3,'我只是直接摘抄文献句子，不清楚转述改写的技巧啊。','wǒ zhǐ shì zhí jiē zhāi chāo wén xiàn jù zi， bù qīng chǔ zhuǎn shù gǎi xiě de jì qiǎo a。','Em chỉ sao chép trực tiếp câu chữ trong tài liệu thôi, chưa rõ kỹ thuật diễn đạt lại theo ý mình ạ.','AM05') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L811_04','V811','李老师',4,'不能简单替换同义词，要调整句子语序、拆分长句、补充自己的分析嘛。','bù néng jiǎn dān tì huàn tóng yì cí， yào tiáo zhěng jù zi yǔ xù、 chāi fēn cháng jù、 bǔ chōng zì jǐ de fēn xī ma。','Không thể chỉ đơn giản thay từ đồng nghĩa đâu, phải điều chỉnh trật tự câu, tách câu dài ra, rồi bổ sung thêm phân tích của riêng mình vào nữa chứ.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L811_05','V811','阮明',5,'图表数据、公式部分会不会计入重复率，需要重新绘制吗？','tú biǎo shù jù、 gōng shì bù fèn huì bú huì jì rù chóng fù lǜ， xū yào chóng xīn huì zhì ma？','Phần biểu đồ, số liệu, công thức có bị tính vào tỷ lệ trùng lặp không ạ, có cần vẽ lại không thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L811_06','V811','李老师',6,'通用公式不计入，文字分析段落必须全部重新转述改写。','tōng yòng gōng shì bù jì rù， wén zì fēn xī duàn luò bì xū quán bù chóng xīn zhuǎn shù gǎi xiě。','Công thức chung thì không tính vào, còn các đoạn phân tích văn bản thì bắt buộc phải viết lại toàn bộ theo cách diễn đạt riêng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L811_07','V811','阮明',7,'我按照您的方法逐段改写，修改完成后再次提交查重。','wǒ àn zhào nín de fāng fǎ zhú duàn gǎi xiě， xiū gǎi wán chéng hòu zài cì tí jiāo chá zhòng。','Em sẽ viết lại từng đoạn theo cách thầy hướng dẫn, sửa xong sẽ nộp kiểm tra trùng lặp lại lần nữa ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT812','SHT2','找不到外文参考文献，求助图书馆馆员检索外文数据库',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V812','SIT812','P1','suon_se','ban_chinh_thuc',NULL,'高校图书馆购买多语种外文数据库，仅校园内网、校园VPN可免费下载全文外文文献。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L812_01','V812','阮明',1,'老师，我写论文需要越南、东南亚相关外文文献，自己检索不到。','lǎo shī， wǒ xiě lùn wén xū yào yuè nán、 dōng nán yà xiāng guān wài wén wén xiàn， zì jǐ jiǎn suǒ bú dào。','Chị ơi, em cần tài liệu nước ngoài liên quan đến Việt Nam và Đông Nam Á để viết luận văn nhưng tự tìm không ra ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L812_02','V812','王馆员',2,'校内开通多国外文数据库，我带你进入外文检索专属页面。','xiào nèi kāi tōng duō guó wài wén shù jù kù， wǒ dài nǐ jìn rù wài wén jiǎn suǒ zhuān shǔ yè miàn。','Trường mình có mở nhiều cơ sở dữ liệu ngoại văn, chị dẫn em vào trang tìm kiếm ngoại văn chuyên dụng nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L812_03','V812','阮明',3,'输入关键词只能检索中文文献，需要切换语种检索入口对吧？','shū rù guān jiàn cí zhǐ néng jiǎn suǒ zhōng wén wén xiàn， xū yào qiè huàn yǔ zhǒng jiǎn suǒ rù kǒu duì ba？','Em nhập từ khóa chỉ tìm ra tài liệu tiếng Trung thôi, phải chuyển sang cổng tìm kiếm ngôn ngữ khác đúng không chị?','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L812_04','V812','王馆员',4,'没错，切换外文语种后，限定地区、出版年份缩小检索范围。','méi cuò， qiè huàn wài wén yǔ zhǒng hòu， xiàn dìng dì qū、 chū bǎn nián fèn suō xiǎo jiǎn suǒ fàn wéi。','Đúng rồi đó, sau khi chuyển sang ngôn ngữ nước ngoài thì em có thể giới hạn khu vực, năm xuất bản để thu hẹp phạm vi tìm kiếm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L812_05','V812','阮明',5,'检索到的外文文献可以直接下载全文PDF吗？','jiǎn suǒ dào de wài wén wén xiàn kě yǐ zhí jiē xià zài quán wén PDF ma？','Tài liệu tìm được có thể tải trực tiếp bản PDF đầy đủ luôn không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L812_06','V812','王馆员',6,'校内IP可免费下载，校外需要登录校园网VPN访问数据库。','xiào nèi IP kě miǎn fèi xià zài， xiào wài xū yào dēng lù xiào yuán wǎng VPN fǎng wèn shù jù kù。','Dùng IP trong trường thì tải miễn phí, còn ở ngoài trường thì phải đăng nhập VPN mạng trường mới truy cập được cơ sở dữ liệu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L812_07','V812','阮明',7,'麻烦您带我操作一遍检索流程，之后我自己查找文献。','má fán nín dài wǒ cāo zuò yī biàn jiǎn suǒ liú chéng， zhī hòu wǒ zì jǐ chá zhǎo wén xiàn。','Phiền chị dẫn em thao tác thử một lượt quy trình tìm kiếm, sau đó em sẽ tự tìm tài liệu ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT813','SHT2','打印论文装订格式错误，打印店重新调整排版',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V813','SIT813','P1','twist','tuy_y',NULL,'各学院毕业论文有统一打印排版模板，页眉、行距、页边距、装订线均有硬性规范，打印店常备模板供学生使用。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L813_01','V813','阮明',1,'你好，刚打印的毕业论文装订不对，页码、页眉格式不符合学院要求。','nǐ hǎo， gāng dǎ yìn de bì yè lùn wén zhuāng dìng bú duì， yè mǎ、 yè méi gé shì bù fú hé xué yuàn yāo qiú。','Chào anh, luận văn tốt nghiệp em vừa in đóng gáy bị sai rồi, số trang với tiêu đề đầu trang không đúng yêu cầu của khoa.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L813_02','V813','店员',2,'学院有统一排版模板，你刚才直接上传文档没有套用标准模板嘛。','xué yuàn yǒu tǒng yī pái bǎn mú bǎn， nǐ gāng cái zhí jiē shàng chuán wén dàng méi yǒu tào yòng biāo zhǔn mú bǎn ma。','Khoa có mẫu trình bày thống nhất mà, lúc nãy em upload file trực tiếp không dùng mẫu chuẩn nên mới vậy đó.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L813_03','V813','阮明',3,'我不知道学校专用模板，直接用自己电脑里的格式导出打印了。','wǒ bù zhī dào xué xiào zhuān yòng mú bǎn， zhí jiē yòng zì jǐ diàn nǎo lǐ de gé shì dǎo chū dǎ yìn le。','Em không biết trường có mẫu riêng, cứ dùng luôn định dạng trong máy tính của mình để xuất ra in thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L813_04','V813','店员',4,'我现在套用学院官方模板重新调整，页眉、页码、行距全部统一修改。','wǒ xiàn zài tào yòng xué yuàn guān fāng mú bǎn chóng xīn tiáo zhěng， yè méi、 yè mǎ、 háng jù quán bù tǒng yī xiū gǎi。','Giờ anh áp mẫu chính thức của khoa vào chỉnh lại nhé, tiêu đề, số trang, giãn dòng gì cũng sửa lại đồng bộ hết.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L813_05','V813','阮明',5,'重新排版打印会额外收取一次打印费用吗？','chóng xīn pái bǎn dǎ yìn huì é wài shōu qǔ yī cì dǎ yìn fèi yòng ma？','In lại theo bố cục mới thì có tính thêm phí in lần nữa không anh?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L813_06','V813','店员',6,'格式调整失误首次免费重打，多次修改才会叠加收费。','gé shì tiáo zhěng shī wù shǒu cì miǎn fèi zhòng dǎ， duō cì xiū gǎi cái huì dié jiā shōu fèi。','Lỗi định dạng thì lần đầu in lại miễn phí, sửa nhiều lần mới tính thêm phí thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L813_07','V813','阮明',7,'辛苦重新排版，调整完我检查无误再装订成册。','xīn kǔ chóng xīn pái bǎn， tiáo zhěng wán wǒ jiǎn chá wú wù zài zhuāng dìng chéng cè。','Phiền anh trình bày lại giúp em, chỉnh xong em kiểm tra không sai sót gì rồi mới đem đóng thành quyển.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT814','SHT2','小组论文有人拖延进度，和组员沟通制定截止时间表',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V814','SIT814','P1','suon_se','tuy_y',NULL,'国内小组作业普遍设置分段截止日期，避免临近交稿集体赶工、质量粗糙。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L814_01','V814','阮明',1,'距离小组论文提交只剩五天，有部分板块素材还没有收集完成。','jù lí xiǎo zǔ lùn wén tí jiāo zhǐ shèng wǔ tiān， yǒu bù fèn bǎn kuài sù cái hái méi yǒu shōu jí wán chéng。','Chỉ còn năm ngày nữa là nộp bài luận văn nhóm rồi mà vài phần tài liệu vẫn chưa thu thập xong.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L814_02','V814','苏雯',2,'有两位组员进度滞后，我们统一拆分每日任务，设置分段小截止期。','yǒu liǎng wèi zǔ yuán jìn dù zhì hòu， wǒ men tǒng yī chāi fēn měi rì rèn wù， shè zhì fēn duàn xiǎo jié zhǐ qī。','Có hai bạn trong nhóm bị chậm tiến độ, mình chia nhỏ công việc hàng ngày ra, đặt mốc thời hạn nhỏ theo từng giai đoạn nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L814_03','V814','小林',3,'每天晚上八点群内同步当日完成内容，避免最后一天集中赶工。','měi tiān wǎn shàng bā diǎn qún nèi tóng bù dāng rì wán chéng nèi róng， bì miǎn zuì hòu yī tiān jí zhōng gǎn gōng。','Mỗi tối tám giờ báo cáo tiến độ hoàn thành trong ngày trên nhóm, để tránh dồn hết vào ngày cuối làm gấp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L814_04','V814','阮明',4,'我负责外文文献翻译，最晚后天完成全部翻译素材交付。','wǒ fù zé wài wén wén xiàn fān yì， zuì wǎn hòu tiān wán chéng quán bù fān yì sù cái jiāo fù。','Mình phụ trách dịch tài liệu nước ngoài, chậm nhất là ngày kia sẽ hoàn thành nộp toàn bộ tài liệu dịch.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L814_05','V814','苏雯',5,'每人明确标注自己的分工与完成时间，逾期提前在群内说明困难。','měi rén míng què biāo zhù zì jǐ de fēn gōng yǔ wán chéng shí jiān， yú qī tí qián zài qún nèi shuō míng kùn nán。','Mỗi người ghi rõ phần việc và thời gian hoàn thành của mình, nếu trễ thì nói trước trong nhóm để mọi người biết khó khăn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L814_06','V814','阮明',6,'如果有人遇到检索、写作难题，群内大家一起协助解决。','rú guǒ yǒu rén yù dào jiǎn suǒ、 xiě zuò nán tí， qún nèi dà jiā yì qǐ xié zhù jiě jué。','Nếu có bạn nào gặp khó khi tìm tài liệu hay viết bài thì cả nhóm cùng hỗ trợ giải quyết nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L814_07','V814','小林',7,'按时间表分段推进，保证论文完整、高质量按时上交。','àn shí jiān biǎo fēn duàn tuī jìn， bǎo zhèng lùn wén wán zhěng、 gāo zhì liàng àn shí shàng jiāo。','Cứ theo bảng thời gian mà làm từng bước, đảm bảo luận văn hoàn chỉnh, chất lượng và nộp đúng hạn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
