
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT715','SSH2','自带饭盒去食堂打包饭菜，咨询打包收费规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V715','SIT715','P1','suon_se','tuy_y',NULL,'国内倡导减少一次性塑料用品，自带饭盒打包可免收餐盒打包费，是校园食堂环保规定。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_01','V715','阮明',1,'您好，我自带饭盒打包饭菜，还要额外收取打包费吗？','nín hǎo， wǒ zì dài fàn hé dǎ bāo fàn cài， hái yào é wài shōu qǔ dǎ bāo fèi ma？','Chào chị, em tự mang hộp cơm đến gói đồ ăn, vậy có phải trả thêm phí đóng gói không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_02','V715','工作人员',2,'自带容器不使用食堂一次性餐盒，免收打包费哈。','zì dài róng qì bù shǐ yòng shí táng yí cì xìng cān hé， miǎn shōu dǎ bāo fèi hā。','Tự mang hộp không dùng hộp dùng một lần của căng tin thì miễn phí đóng gói luôn.','AM06') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_03','V715','阮明',3,'要是忘记带饭盒，用食堂塑料盒打包多少钱一份？','yào shì wàng jì dài fàn hé， yòng shí táng sù liào hé dǎ bāo duō shǎo qián yī fèn？','Nếu quên mang hộp cơm, dùng hộp nhựa của căng tin để gói thì bao nhiêu tiền một phần vậy chị?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_04','V715','工作人员',4,'一次性餐盒一元一个，筷子、塑料袋免费提供。','yí cì xìng cān hé yī yuán yí gè， kuài zi、 sù liào dài miǎn fèi tí gōng。','Hộp dùng một lần là một tệ một cái, đũa với túi ni lông thì cung cấp miễn phí.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_05','V715','阮明',5,'我以后每天带饭盒，既省钱也更环保。','wǒ yǐ hòu měi tiān dài fàn hé， jì shěng qián yě gèng huán bǎo。','Vậy từ giờ ngày nào em cũng mang hộp cơm theo, vừa tiết kiệm vừa bảo vệ môi trường.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_06','V715','工作人员',6,'自带餐具打包我们十分鼓励，减少塑料垃圾。','zì dài cān jù dǎ bāo wǒ men shí fēn gǔ lì， jiǎn shǎo sù liào lā jī。','Tự mang dụng cụ đến gói đồ thì bên chị rất khuyến khích, giảm bớt rác thải nhựa mà.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_07','V715','阮明',7,'好，我每天自备饭盒来食堂打包饭菜。','hǎo， wǒ měi tiān zì bèi fàn hé lái shí táng dǎ bāo fàn cài。','Vâng, từ nay ngày nào em cũng tự chuẩn bị hộp cơm đến căng tin gói đồ ăn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT716','SSH2','食堂高峰期排队久，和同学交流错峰就餐时段',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V716','SIT716','P1','suon_se','tuy_y',NULL,'国内高校十二点是下课就餐最高峰，提前或延后半小时就餐可大幅缩短排队时长。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L716_01','V716','阮明',1,'中午十二点食堂人挤人，排队二十分钟才能打到饭啊。','zhōng wǔ shí èr diǎn shí táng rén jǐ rén， pái duì èr shí fēn zhōng cái néng dǎ dào fàn a。','Mười hai giờ trưa căng tin đông nghẹt người, xếp hàng hai mươi phút mới lấy được cơm đó.','AM05') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L716_02','V716','苏雯',2,'可以十一点四十提前下课去食堂，几乎不用排队呢。','kě yǐ shí yì diǎn sì shí tí qián xià kè qù shí táng， jī hū bù yòng pái duì ne。','Cậu có thể tan học sớm lúc mười một giờ bốn mươi rồi ra căng tin, gần như không phải xếp hàng luôn đó.','AM04') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L716_03','V716','阮明',3,'要是上午有课走不开，下午一点再去是不是人很少？','yào shì shàng wǔ yǒu kè zǒu bù kāi， xià wǔ yì diǎn zài qù shì bú shì rén hěn shǎo？','Nhưng nếu buổi sáng có tiết không đi được, thì một giờ chiều đi có phải vắng người hơn không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L716_04','V716','苏雯',4,'一点大部分学生吃完回宿舍，窗口菜品选择也还算多。','yì diǎn dà bù fèn xué shēng chī wán huí sù shè， chuāng kǒu cài pǐn xuǎn zé yě hái suàn duō。','Một giờ chiều phần lớn sinh viên ăn xong về ký túc xá rồi, món ở quầy vẫn còn khá nhiều lựa chọn đó.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L716_05','V716','阮明',5,'那我分两种时段，早下课就提前去，晚下课一点再就餐。','nà wǒ fēn liǎng zhǒng shí duàn， zǎo xià kè jiù tí qián qù， wǎn xià kè yì diǎn zài jiù cān。','Vậy mình chia hai khung giờ, hôm nào tan sớm thì đi trước, hôm nào tan muộn thì một giờ đi ăn sau.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L716_06','V716','苏雯',6,'避开十二点整的高峰，能节省很多排队等待时间。','bì kāi shí èr diǎn zhěng de gāo fēng， néng jié shěng hěn duō pái duì děng dài shí jiān。','Tránh đúng lúc cao điểm mười hai giờ, sẽ tiết kiệm được rất nhiều thời gian xếp hàng chờ đợi đó.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L716_07','V716','阮明',7,'我之后错开高峰，不用长时间排队等餐。','wǒ zhī hòu cuò kāi gāo fēng， bù yòng zhǎng shí jiān pái duì děng cān。','Từ giờ tớ sẽ tránh giờ cao điểm, khỏi phải xếp hàng chờ ăn lâu như vậy nữa.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT717','SSH2','咨询食堂清真窗口开放时间、菜品范围',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V717','SIT717','P1','suon_se','ban_chinh_thuc',NULL,'国内高校设有独立清真餐窗口，厨具、食材完全隔离，满足有饮食禁忌的学生就餐需求。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L717_01','V717','阮明',1,'您好，想咨询食堂清真窗口每日开放时段有哪些？','nín hǎo， xiǎng zī xún shí táng qīng zhēn chuāng kǒu měi rì kāi fàng shí duàn yǒu nǎ xiē？','Chào chị, cho em hỏi khung giờ mở cửa hàng ngày của quầy Halal ở căng tin là những khung nào ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L717_02','V717','工作人员',2,'早七点至八点半早餐，十一点到十三点午餐，十七点半至十九点晚餐哦。','zǎo qī diǎn zhì bā diǎn bàn zǎo cān， shí yì diǎn dào shí sān diǎn wǔ cān， shí qī diǎn bàn zhì shí jiǔ diǎn wǎn cān ó。','Bữa sáng từ bảy giờ đến tám rưỡi, bữa trưa từ mười một giờ đến mười ba giờ, bữa tối từ mười bảy rưỡi đến mười chín giờ nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L717_03','V717','阮明',3,'清真窗口只供应牛羊肉、素食，完全不出现猪肉菜品对吧？','qīng zhēn chuāng kǒu zhǐ gōng yìng niú yáng ròu、 sù shí， wán quán bù chū xiàn zhū ròu cài pǐn duì ba？','Quầy Halal chỉ phục vụ thịt bò, thịt cừu và đồ chay, hoàn toàn không có món nào có thịt heo đúng không ạ?','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L717_04','V717','工作人员',4,'没错，厨具、操作台独立分开，杜绝混炒普通菜品。','méi cuò， chú jù、 cāo zuò tái dú lì fēn kāi， dù jué hùn chǎo pǔ tōng cài pǐn。','Đúng vậy, dụng cụ nấu và bàn chế biến đều tách riêng hoàn toàn, không xào chung với món ăn thường.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L717_05','V717','阮明',5,'明天早上我早点过来，去清真窗口吃早餐。','míng tiān zǎo shàng wǒ zǎo diǎn guò lái， qù qīng zhēn chuāng kǒu chī zǎo cān。','Sáng mai em sẽ đến sớm hơn, ra quầy Halal ăn sáng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L717_06','V717','工作人员',6,'窗口每日定时供应，太晚抵达会菜品售罄。','chuāng kǒu měi rì dìng shí gōng yìng， tài wǎn dǐ dá huì cài pǐn shòu qìng。','Quầy phục vụ theo giờ cố định mỗi ngày, đến muộn quá là hết món đấy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L717_07','V717','阮明',7,'我把控好时间，在窗口开放时段内就餐。','wǒ bǎ kòng hǎo shí jiān， zài chuāng kǒu kāi fàng shí duàn nèi jiù cān。','Em sẽ canh giờ cho chuẩn, ăn trong đúng khung giờ quầy mở cửa.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT718','SSH2','餐后忘记归还食堂餐盘，被工作人员提醒规范就餐',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V718','SIT718','P1','that_bai_nhe','tuy_y',NULL,'校园食堂餐盘、汤碗属于公共耗材，禁止带出就餐区域，餐后统一送至店内回收处是通用就餐规范。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L718_01','V718','阮明',1,'阿姨不好意思，吃完饭后我把餐盘直接带出食堂了，现在送回来。','ā yí bù hǎo yì sī， chī wán fàn hòu wǒ bǎ cān pán zhí jiē dài chū shí táng le， xiàn zài sòng huí lái。','Cô ơi, cháu xin lỗi, ăn xong cháu lỡ mang khay ra khỏi căng tin luôn, giờ cháu mang trả lại ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L718_02','V718','保洁李阿姨',2,'食堂规定餐盘必须在店内回收台归还，不能带出就餐区嘛。','shí táng guī dìng cān pán bì xū zài diàn nèi huí shōu tái guī huán， bù néng dài chū jiù cān qū ma。','Căng tin quy định khay phải trả ở quầy thu hồi trong nhà ăn, không được mang ra khỏi khu vực ăn uống mà.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L718_03','V718','阮明',3,'刚才着急赶课，一时忘记食堂就餐规定，下次一定注意。','gāng cái zháo jí gǎn kè， yī shí wàng jì shí táng jiù cān guī dìng， xià cì yí dìng zhù yì。','Lúc nãy cháu vội đi học nên quên mất quy định của căng tin, lần sau cháu để ý ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L718_04','V718','保洁李阿姨',4,'餐盘餐具外流容易丢失、破损，增加食堂耗材成本。','cān pán cān jù wài liú róng yì diū shī、 pò sǔn， zēng jiā shí táng hào cái chéng běn。','Khay với dụng cụ mang ra ngoài dễ bị mất hoặc hỏng, làm tăng chi phí vật tư của căng tin đấy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L718_05','V718','阮明',5,'我之后吃完立刻送到回收台，绝不带出食堂大门。','wǒ zhī hòu chī wán lì kè sòng dào huí shōu tái， jué bù dài chū shí táng dà mén。','Sau này cháu ăn xong là mang trả ngay ở quầy thu hồi, không mang ra khỏi cổng căng tin nữa đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L718_06','V718','保洁李阿姨',6,'记住规则就好，下次不用再特意送回来。','jì zhù guī zé jiù hǎo， xià cì bù yòng zài tè yì sòng huí lái。','Nhớ quy định là được rồi, lần sau không cần cố tình chạy lại trả đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L718_07','V718','阮明',7,'十分抱歉给您增加额外工作，我严格遵守食堂规定。','shí fēn bào qiàn gěi nín zēng jiā é wài gōng zuò， wǒ yán gé zūn shǒu shí táng guī dìng。','Cháu thật sự xin lỗi vì làm cô phải bận thêm, cháu sẽ tuân thủ nghiêm quy định của căng tin.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT719','SSH3','图书馆办理借阅证，学习图书借还、逾期罚款规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V719','SIT719','P1','suon_se','ban_chinh_thuc',NULL,'国内高校图书馆图书超期会收取每日罚金，逾期过久会暂停借阅权限，直至缴清罚款。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L719_01','V719','阮明',1,'老师您好，我是新生留学生，前来办理图书馆借阅证件。','lǎo shī nín hǎo， wǒ shì xīn shēng liú xué shēng， qián lái bàn lǐ tú shū guǎn jiè yuè zhèng jiàn。','Chào thầy/cô, em là sinh viên quốc tế mới nhập học, em đến làm thẻ thư viện ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L719_02','V719','馆员王老师',2,'出示学生证、护照，登记信息后绑定校园卡就能借书哦。','chū shì xué shēng zhèng、 hù zhào， dēng jì xìn xī hòu bǎng dìng xiào yuán kǎ jiù néng jiè shū ó。','Em xuất trình thẻ sinh viên với hộ chiếu, đăng ký thông tin rồi liên kết với thẻ sinh viên là mượn sách được nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L719_03','V719','阮明',3,'单次最多能借几本书，最长借阅期限是多少天？','dān cì zuì duō néng jiè jǐ běn shū， zuì zhǎng jiè yuè qī xiàn shì duō shǎo tiān？','Mỗi lần được mượn tối đa bao nhiêu cuốn, thời hạn mượn lâu nhất là bao nhiêu ngày ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L719_04','V719','馆员王老师',4,'一次六本，三十天借阅期，可线上续借一次延长十五天。','yī cì liù běn， sān shí tiān jiè yuè qī， kě xiàn shàng xù jiè yī cì yán cháng shí wǔ tiān。','Mỗi lần sáu cuốn, thời hạn ba mươi ngày, có thể gia hạn online một lần thêm mười lăm ngày.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L719_05','V719','阮明',5,'超过三十天未续借，每天会产生多少逾期罚款呢？','chāo guò sān shí tiān wèi xù jiè， měi tiān huì chǎn shēng duō shǎo yú qī fá kuǎn ne？','Nếu quá ba mươi ngày mà không gia hạn thì mỗi ngày sẽ bị phạt trễ hạn bao nhiêu ạ?','AM04') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L719_06','V719','馆员王老师',6,'每本书每日零点一元罚款，超期越久费用累加越高。','měi běn shū měi rì líng diǎn yī yuán fá kuǎn， chāo qī yuè jiǔ fèi yòng lěi jiā yuè gāo。','Mỗi cuốn sách phạt không phẩy một tệ mỗi ngày, càng trễ lâu thì tiền phạt càng cộng dồn nhiều.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L719_07','V719','阮明',7,'我会按时续借或者归还，避免产生逾期罚金。','wǒ huì àn shí xù jiè huò zhě guī huán， bì miǎn chǎn shēng yú qī fá jīn。','Em sẽ gia hạn hoặc trả sách đúng hạn, để tránh bị phạt trễ hạn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT720','SSH3','图书馆自习座位被占，咨询管理员占座管理规定',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V720','SIT720','P1','twist','ban_chinh_thuc',NULL,'图书馆严禁用书、水杯长期霸占自习座位，临时离开超过一小时管理员会清理占位物品，保障座位公平使用。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L720_01','V720','阮明',1,'您好，这个自习座位放着书本一整天没人，我可以坐这里吗？','nín hǎo， zhè ge zì xí zuò wèi fàng zhe shū běn yī zhěng tiān méi rén， wǒ kě yǐ zuò zhè lǐ ma？','Chào anh/chị, chỗ tự học này để sách cả ngày không có ai ngồi, em ngồi đây được không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L720_02','V720','管理员',2,'图书馆禁止长期占座，离开超过一小时物品会统一清收。','tú shū guǎn jìn zhǐ cháng qī zhàn zuò， lí kāi chāo guò yī xiǎo shí wù pǐn huì tǒng yī qīng shōu。','Thư viện cấm giữ chỗ lâu dài, rời chỗ quá một tiếng là đồ đạc sẽ bị thu gom hết đấy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L720_03','V720','阮明',3,'书本、水杯全都留在桌面，座位空了整整一下午嘛。','shū běn、 shuǐ bēi quán dōu liú zài zhuō miàn， zuò wèi kōng le zhěng zhěng yī xià wǔ ma。','Sách vở với cốc nước để nguyên trên bàn, chỗ trống suốt cả buổi chiều luôn mà.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L720_04','V720','管理员',4,'我先把占位物品收到失物存放区，你可以正常使用这个座位。','wǒ xiān bǎ zhàn wèi wù pǐn shōu dào shī wù cún fàng qū， nǐ kě yǐ zhèng cháng shǐ yòng zhè ge zuò wèi。','Để tôi mang đồ giữ chỗ đó cất vào khu đồ thất lạc trước, em cứ sử dụng chỗ ngồi này bình thường.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L720_05','V720','阮明',5,'那物品主人回来，去哪里领取自己的书本、水杯？','nà wù pǐn zhǔ rén huí lái， qù nǎ lǐ lǐng qǔ zì jǐ de shū běn、 shuǐ bēi？','Vậy chủ nhân của đồ đó quay lại thì đến đâu để lấy lại sách vở, cốc nước ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L720_06','V720','管理员',6,'一楼服务台报姓名、物品特征就能取回存放物品。','yī lóu fú wù tái bào xìng míng、 wù pǐn tè zhēng jiù néng qǔ huí cún fàng wù pǐn。','Ra quầy phục vụ ở tầng một, báo tên và đặc điểm đồ vật là lấy lại được ngay.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L720_07','V720','阮明',7,'我以后临时离开自习室，随身带走全部私人物品。','wǒ yǐ hòu lín shí lí kāi zì xí shì， suí shēn dài zǒu quán bù sī rén wù pǐn。','Sau này em sẽ mang hết đồ cá nhân theo người mỗi khi rời phòng tự học tạm thời.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT721','SSH3','图书馆电脑无法登录校园内网，求助值班管理员',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V721','SIT721','P1','suon_se','tuy_y',NULL,'校园内网会定期服务器维护，维护期间图书馆电脑无法访问校内论文数据库，属于常规网络维护安排。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L721_01','V721','阮明',1,'你好，图书馆台式机输入学号，一直登录不上校园内网啊。','nǐ hǎo， tú shū guǎn tái shì jī shū rù xué hào， yì zhí dēng lù bù shàng xiào yuán nèi wǎng a。','Chào anh, máy tính bàn ở thư viện em nhập mã số sinh viên vào mà cứ không đăng nhập được mạng nội bộ trường ấy.','AM05') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L721_02','V721','管理员',2,'是不是校园网账号欠费停机，或者密码输入错误呢？','shì bú shì xiào yuán wǎng zhàng hào qiàn fèi tíng jī， huò zhě mì mǎ shū rù cuò wù ne？','Không biết có phải tài khoản mạng trường bị khóa do quá hạn, hay là gõ nhầm mật khẩu không?','AM04') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L721_03','V721','阮明',3,'昨天还正常登录查阅文献，没有修改过账号密码。','zuó tiān hái zhèng cháng dēng lù chá yuè wén xiàn， méi yǒu xiū gǎi guò zhàng hào mì mǎ。','Hôm qua em còn đăng nhập bình thường để tra tài liệu mà, em có sửa tài khoản mật khẩu gì đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L721_04','V721','管理员',4,'今天校内服务器临时维护，部分电脑网络不稳定。','jīn tiān xiào nèi fú wù qì lín shí wéi hù， bù fèn diàn nǎo wǎng luò bù wěn dìng。','Hôm nay máy chủ nội bộ trường đang bảo trì tạm thời, một số máy mạng không ổn định.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L721_05','V721','阮明',5,'那大概多久恢复内网访问，我需要查阅专业论文。','nà dà gài duō jiǔ huī fù nèi wǎng fǎng wèn， wǒ xū yào chá yuè zhuān yè lùn wén。','Vậy khoảng bao lâu nữa thì truy cập mạng nội bộ lại được, em cần tra luận văn chuyên ngành gấp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L721_06','V721','管理员',6,'预计四十分钟维护结束，你可以先用手机流量临时查资料。','yù jì sì shí fēn zhōng wéi hù jié shù， nǐ kě yǐ xiān yòng shǒu jī liú liàng lín shí chá zī liào。','Dự kiến bốn mươi phút nữa bảo trì xong, em cứ tạm dùng 4G điện thoại để tra tài liệu trước nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L721_07','V721','阮明',7,'我先等服务器维护完成，再使用电脑下载文献。','wǒ xiān děng fú wù qì wéi hù wán chéng， zài shǐ yòng diàn nǎo xià zài wén xiàn。','Em đợi máy chủ bảo trì xong rồi mới dùng máy tính để tải tài liệu vậy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT722','SSH3','借阅书籍超期，咨询罚款标准、补缴流程',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V722','SIT722','P1','that_bai_nhe','ban_chinh_thuc',NULL,'图书逾期罚金必须线下结清，未缴清罚款会永久限制图书借阅、数据库使用权限。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L722_01','V722','阮明',1,'老师，我借阅的两本专业书忘记续借，已经超期八天了。','lǎo shī， wǒ jiè yuè de liǎng běn zhuān yè shū wàng jì xù jiè， yǐ jīng chāo qī bā tiān le。','Thầy/cô ơi, hai cuốn sách chuyên ngành em mượn quên gia hạn mất rồi, đã trễ tám ngày rồi ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L722_02','V722','馆员王老师',2,'先把图书归还，系统自动核算每日逾期罚款金额。','xiān bǎ tú shū guī huán， xì tǒng zì dòng hé suàn měi rì yú qī fá kuǎn jīn é。','Em trả sách trước đã, hệ thống sẽ tự động tính tiền phạt trễ hạn theo từng ngày.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L722_03','V722','阮明',3,'两本书分开计算罚金，还是合并统一收取费用？','liǎng běn shū fēn kāi jì suàn fá jīn， hái shì hé bìng tǒng yī shōu qǔ fèi yòng？','Hai cuốn tính tiền phạt riêng, hay là gộp chung lại thu một lần ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L722_04','V722','馆员王老师',4,'每本单独计费，两本书八天一共十六元逾期罚金嘛。','měi běn dān dú jì fèi， liǎng běn shū bā tiān yī gòng shí liù yuán yú qī fá jīn ma。','Mỗi cuốn tính riêng, hai cuốn tám ngày tổng cộng là mười sáu tệ tiền phạt đó nha.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L722_05','V722','阮明',5,'罚金只能线下在图书馆服务台扫码缴纳，不能线上支付吗？','fá jīn zhǐ néng xiàn xià zài tú shū guǎn fú wù tái sǎo mǎ jiǎo nà， bù néng xiàn shàng zhī fù ma？','Tiền phạt chỉ có thể quét mã nộp trực tiếp ở quầy phục vụ thư viện thôi, không thanh toán online được ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L722_06','V722','馆员王老师',6,'仅支持线下现场缴费，缴清罚金才能恢复借阅权限。','jǐn zhī chí xiàn xià xiàn chǎng jiǎo fèi， jiǎo qīng fá jīn cái néng huī fù jiè yuè quán xiàn。','Chỉ nộp trực tiếp tại chỗ thôi, nộp phạt xong mới được khôi phục quyền mượn sách.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L722_07','V722','阮明',7,'我现在扫码缴纳罚金，之后一定记好续借日期。','wǒ xiàn zài sǎo mǎ jiǎo nà fá jīn， zhī hòu yí dìng jì hǎo xù jiè rì qī。','Vậy giờ em quét mã nộp phạt luôn, sau này em nhớ kỹ ngày gia hạn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT723','SSH3','图书馆打印复印设备卡纸，找工作人员维修',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V723','SIT723','P1','suon_se','tuy_y',NULL,'自助打印设备卡纸禁止用户自行拆机拉扯纸张，容易造成硬件损坏，需工作人员专业处理。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L723_01','V723','阮明',1,'你好，自助复印机打印到一半卡纸，纸张卡在机器里面了。','nǐ hǎo， zì zhù fù yìn jī dǎ yìn dào yí bàn kǎ zhǐ， zhǐ zhāng kǎ zài jī qì lǐ miàn le。','Chào anh, máy photocopy tự động in được nửa chừng thì kẹt giấy, giấy kẹt cứng trong máy luôn rồi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L723_02','V723','运维工作人员',2,'别手动拉扯纸张，容易损坏打印机内部齿轮。','bié shǒu dòng lā chě zhǐ zhāng， róng yì sǔn huài dǎ yìn jī nèi bù chǐ lún。','Đừng dùng tay kéo giấy ra, dễ làm hỏng bánh răng bên trong máy in lắm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L723_03','V723','阮明',3,'我只是按了停止键，没有强行拽取卡住的打印纸。','wǒ zhǐ shì àn le tíng zhǐ jiàn， méi yǒu qiáng xíng zhuāi qǔ kǎ zhù de dǎ yìn zhǐ。','Em chỉ bấm nút dừng thôi, không có cố kéo tờ giấy bị kẹt ra đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L723_04','V723','运维工作人员',4,'我打开机盖取出卡纸，清理之后就能恢复打印啦。','wǒ dǎ kāi jī gài qǔ chū kǎ zhǐ， qīng lǐ zhī hòu jiù néng huī fù dǎ yìn la。','Để tôi mở nắp máy lấy giấy kẹt ra, dọn xong là in lại bình thường thôi mà.','AM02') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L723_05','V723','阮明',5,'刚才已经扣取打印费用，卡纸没有完整出纸会返还余额吗？','gāng cái yǐ jīng kòu qǔ dǎ yìn fèi yòng， kǎ zhǐ méi yǒu wán zhěng chū zhǐ huì fǎn huán yú é ma？','Lúc nãy tiền in đã bị trừ rồi, kẹt giấy mà không ra giấy hoàn chỉnh thì có được hoàn lại tiền không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L723_06','V723','运维工作人员',6,'单次卡纸未出纸，系统自动退还本次打印扣费。','dān cì kǎ zhǐ wèi chū zhǐ， xì tǒng zì dòng tuì huán běn cì dǎ yìn kòu fèi。','Kẹt giấy mà không in ra được thì hệ thống tự động hoàn lại tiền lần in đó thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L723_07','V723','阮明',7,'麻烦您检修机器，我等下继续打印复习资料。','má fán nín jiǎn xiū jī qì， wǒ děng xià jì xù dǎ yìn fù xí zī liào。','Phiền anh kiểm tra sửa máy giúp em, lát nữa em in tiếp tài liệu ôn tập ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT724','SSH3','自习到闭馆时间，咨询夜间留校自习申请渠道',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V724','SIT724','P1','twist','ban_chinh_thuc',NULL,'图书馆夜间统一闭馆安保巡查，国内高校单独设置通宵自习教室满足期末备考学生需求。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L724_01','V724','阮明',1,'距离期末考还有两周，图书馆九点闭馆太早，想夜间留校自习。','jù lí qī mò kǎo hái yǒu liǎng zhōu， tú shū guǎn jiǔ diǎn bì guǎn tài zǎo， xiǎng yè jiān liú xiào zì xí。','Còn hai tuần nữa là thi cuối kỳ rồi, thư viện đóng cửa lúc chín giờ sớm quá, em muốn ở lại trường tự học ban đêm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L724_02','V724','管理员',2,'图书馆晚间九点统一闭馆，不允许学生留在馆内过夜自习。','tú shū guǎn wǎn jiān jiǔ diǎn tǒng yī bì guǎn， bù yǔn xǔ xué shēng liú zài guǎn nèi guò yè zì xí。','Thư viện đóng cửa cố định lúc chín giờ tối, không cho phép sinh viên ở lại trong thư viện qua đêm để tự học.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L724_03','V724','阮明',3,'有没有专门通宵自习教室，或者申请延长图书馆开放时间？','yǒu méi yǒu zhuān mén tōng xiāo zì xí jiào shì， huò zhě shēn qǐng yán cháng tú shū guǎn kāi fàng shí jiān？','Vậy có phòng tự học thâu đêm riêng nào không, hay là có thể xin gia hạn giờ mở cửa thư viện không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L724_04','V724','管理员',4,'教学楼有两间通宵自习室，图书馆无延时开放审批通道嘛。','jiào xué lóu yǒu liǎng jiān tōng xiāo zì xí shì， tú shū guǎn wú yán shí kāi fàng shěn pī tōng dào ma。','Tòa nhà giảng đường có hai phòng tự học thâu đêm, còn thư viện thì không có kênh xin gia hạn giờ mở cửa đâu.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L724_05','V724','阮明',5,'教学楼通宵教室晚上十一点之后还能正常开灯自习吗？','jiào xué lóu tōng xiāo jiào shì wǎn shàng shí yì diǎn zhī hòu hái néng zhèng cháng kāi dēng zì xí ma？','Phòng tự học thâu đêm ở tòa giảng đường sau mười một giờ đêm vẫn bật đèn học bình thường được chứ ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L724_06','V724','管理员',6,'全天供电，门禁可刷校园卡二十四小时自由进出。','quán tiān gōng diàn， mén jìn kě shuā xiào yuán kǎ èr shí sì xiǎo shí zì yóu jìn chū。','Có điện cả ngày, cửa ra vào quẹt thẻ sinh viên là ra vào tự do hai mươi bốn tiếng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L724_07','V724','阮明',7,'今晚开始转移到教学楼通宵教室复习备考。','jīn wǎn kāi shǐ zhuǎn yí dào jiào xué lóu tōng xiāo jiào shì fù xí bèi kǎo。','Vậy tối nay em chuyển sang phòng tự học thâu đêm ở tòa giảng đường để ôn thi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT725','SSH3','借阅外文专业参考书，咨询馆员查找馆藏方法',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V725','SIT725','P1','suon_se','ban_chinh_thuc',NULL,'高校图书馆外文藏书单独分区管理，为保护原版书籍，不开放学生自行入内取阅，由馆员统一调取。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L725_01','V725','阮明',1,'老师，我需要越南语原版专业参考书，不知道怎么检索馆藏。','lǎo shī， wǒ xū yào yuè nán yǔ yuán bǎn zhuān yè cān kǎo shū， bù zhī dào zěn me jiǎn suǒ guǎn cáng。','Thầy ơi, em cần tìm sách tham khảo chuyên ngành bản gốc tiếng Việt, mà không biết tra cứu sách trong thư viện kiểu gì.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L725_02','V725','馆员王老师',2,'图书馆检索系统左上角切换外文分类，输入语种关键词即可。','tú shū guǎn jiǎn suǒ xì tǒng zuǒ shàng jiǎo qiè huàn wài wén fēn lèi， shū rù yǔ zhǒng guān jiàn cí jí kě。','Ở góc trên bên trái hệ thống tra cứu của thư viện có mục chuyển sang phân loại sách ngoại văn, em chỉ cần nhập từ khóa ngôn ngữ vào là được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L725_03','V725','阮明',3,'检索出来显示在三楼外文馆藏区，需要凭借阅证入内取书对吧？','jiǎn suǒ chū lái xiǎn shì zài sān lóu wài wén guǎn cáng qū， xū yào píng jiè yuè zhèng rù nèi qǔ shū duì ba？','Tra ra thì thấy sách nằm ở khu sách ngoại văn tầng ba, vậy em phải có thẻ mượn sách mới vào lấy được đúng không ạ?','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L725_04','V725','馆员王老师',4,'外文图书区域不对外开放自由取书，报书名由我调取。','wài wén tú shū qū yù bú duì wài kāi fàng zì yóu qǔ shū， bào shū míng yóu wǒ diào qǔ。','Khu sách ngoại văn không mở cửa cho tự do vào lấy đâu, em báo tên sách để cô lấy giúp cho.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L725_05','V725','阮明',5,'那我把书籍编号发给您，麻烦帮忙调取这本参考书。','nà wǒ bǎ shū jí biān hào fā gěi nín， má fán bāng máng diào qǔ zhè běn cān kǎo shū。','Vậy em gửi mã số sách cho cô nhé, phiền cô lấy giúp em cuốn sách tham khảo này.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L725_06','V725','馆员王老师',6,'十分钟内找到书籍，你在服务台等候领取。','shí fēn zhōng nèi zhǎo dào shū jí， nǐ zài fú wù tái děng hòu lǐng qǔ。','Trong vòng mười phút cô sẽ tìm được sách, em ra quầy phục vụ đợi lấy nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L725_07','V725','阮明',7,'好，我在这里等候，感谢协助查找外文藏书。','hǎo， wǒ zài zhè lǐ děng hòu， gǎn xiè xié zhù chá zhǎo wài wén cáng shū。','Dạ vâng, em đợi ở đây, cảm ơn cô đã giúp em tìm sách ngoại văn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT726','SSH4','办理校园统一公交优惠学生卡，提交证件材料',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V726','SIT726','P1','suon_se','ban_chinh_thuc',NULL,'国内在校学生可办理公交学生卡，市内通勤公交享受半价优惠，长途客运不参与学生折扣政策。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L726_01','V726','阮明',1,'老师您好，想办理公交学生优惠卡，出门乘坐公交半价乘车。','lǎo shī nín hǎo， xiǎng bàn lǐ gōng jiāo xué shēng yōu huì kǎ， chū mén chéng zuò gōng jiāo bàn jià chéng chē。','Chào thầy, em muốn làm thẻ ưu đãi xe buýt học sinh, để đi xe buýt được giảm nửa giá ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L726_02','V726','办事老师',2,'准备好护照、学生证、一寸证件照，填写办卡申请表哦。','zhǔn bèi hǎo hù zhào、 xué shēng zhèng、 yī cùn zhèng jiàn zhào， tián xiě bàn kǎ shēn qǐng biǎo ó。','Em chuẩn bị hộ chiếu, thẻ sinh viên, ảnh thẻ cỡ 3x4, rồi điền tờ đăng ký làm thẻ nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L726_03','V726','阮明',3,'办好公交卡，全市所有公交线路都能享受学生折扣吗？','bàn hǎo gōng jiāo kǎ， quán shì suǒ yǒu gōng jiāo xiàn lù dōu néng xiǎng shòu xué shēng zhé kòu ma？','Làm thẻ xe buýt xong thì tất cả các tuyến xe buýt trong thành phố đều được hưởng ưu đãi học sinh phải không thầy?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L726_04','V726','办事老师',4,'市内常规公交全部半价，长途城际公交不适用优惠。','shì nèi cháng guī gōng jiāo quán bù bàn jià， cháng tú chéng jì gōng jiāo bù shì yòng yōu huì。','Xe buýt thường trong nội thành thì được giảm nửa giá hết, còn xe buýt liên tỉnh đường dài thì không áp dụng ưu đãi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L726_05','V726','阮明',5,'公交卡丢失可以挂失转移余额，和校园饭卡规则一样？','gōng jiāo kǎ diū shī kě yǐ guà shī zhuǎn yí yú é， hé xiào yuán fàn kǎ guī zé yī yàng？','Nếu mất thẻ xe buýt thì báo mất và chuyển số dư được, giống quy định thẻ ăn của trường đúng không ạ?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L726_06','V726','办事老师',6,'没错，携带证件到服务中心挂失补办，余额完整保留。','méi cuò， xié dài zhèng jiàn dào fú wù zhōng xīn guà shī bǔ bàn， yú é wán zhěng bǎo liú。','Đúng vậy, em mang giấy tờ đến trung tâm dịch vụ báo mất và làm lại thẻ, số dư vẫn giữ nguyên đầy đủ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L726_07','V726','阮明',7,'我备齐材料，今天办理学生公交优惠卡。','wǒ bèi qí cái liào， jīn tiān bàn lǐ xué shēng gōng jiāo yōu huì kǎ。','Em chuẩn bị đủ giấy tờ rồi, hôm nay em làm thẻ ưu đãi xe buýt học sinh luôn.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT727','SSH4','共享单车扫码失败、车辆故障，咨询换车流程',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V727','SIT727','P1','twist','tuy_y',NULL,'共享单车故障车辆免费换车，短时间内切换新车不重复收取起步费用，是平台通用售后规则。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L727_01','V727','阮明',1,'师傅，这辆单车扫码开锁一直失败，页面提示车辆故障啊。','shī fù， zhè liàng dān chē sǎo mǎ kāi suǒ yì zhí shī bài， yè miàn tí shì chē liàng gù zhàng a。','Anh ơi, chiếc xe đạp này em quét mã mở khóa mãi không được, màn hình báo xe bị hỏng.','AM05') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L727_02','V727','运维员',2,'故障车辆后台锁定无法解锁，直接在APP点更换车辆按钮。','gù zhàng chē liàng hòu tái suǒ dìng wú fǎ jiě suǒ， zhí jiē zài APP diǎn gēng huàn chē liàng àn niǔ。','Xe hỏng thì hệ thống đã khóa lại rồi, không mở khóa được đâu, em bấm nút đổi xe trên app là được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L727_03','V727','阮明',3,'换车会不会重复收取骑行起步费，两辆车分开计费吗？','huàn chē huì bú huì chóng fù shōu qǔ qí xíng qǐ bù fèi， liǎng liàng chē fēn kāi jì fèi ma？','Đổi xe như vậy có bị tính lại phí mở chuyến không, hai xe có tính tiền riêng không anh?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L727_04','V727','运维员',4,'故障换车十分钟内切换新车，不会二次扣费，自动取消订单嘛。','gù zhàng huàn chē shí fēn zhōng nèi qiè huàn xīn chē， bú huì èr cì kòu fèi， zì dòng qǔ xiāo dìng dān ma。','Đổi xe do lỗi trong vòng mười phút thì không bị tính phí lần hai đâu, đơn cũ tự động hủy mà.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L727_05','V727','阮明',5,'那我直接换旁边完好单车，不用手动结束当前订单？','nà wǒ zhí jiē huàn páng biān wán hǎo dān chē， bù yòng shǒu dòng jié shù dāng qián dìng dān？','Vậy em cứ đổi luôn sang chiếc xe bên cạnh còn tốt, không cần tự tay kết thúc chuyến đang mở à?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L727_06','V727','运维员',6,'APP一键换车系统自动处理，不用额外操作订单。','APP yī jiàn huàn chē xì tǒng zì dòng chǔ lǐ， bù yòng é wài cāo zuò dìng dān。','App đổi xe một chạm là hệ thống tự xử lý hết, em không cần thao tác thêm gì với đơn cũ đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L727_07','V727','阮明',7,'我现在操作更换车辆，正常骑行前往教学楼。','wǒ xiàn zài cāo zuò gēng huàn chē liàng， zhèng cháng qí xíng qián wǎng jiào xué lóu。','Giờ em thao tác đổi xe đây, rồi đi bình thường lên nhà giảng đường.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT728','SSH4','校内电动车限速规定，被安保提醒减速慢行',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V728','SIT728','P1','that_bai_nhe','tuy_y',NULL,'国内大学校园非机动车统一低速限速，保护步行学生安全，多次超速会暂扣车辆进行安全教育。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L728_01','V728','阮明',1,'保安大叔，怎么拦下我，是电动车行驶有违规地方吗？','bǎo ān dà shū， zěn me lán xià wǒ， shì diàn dòng chē háng shǐ yǒu wéi guī dì fāng ma？','Chú bảo vệ ơi, sao chú chặn cháu lại vậy, xe điện cháu chạy có gì sai quy định à?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L728_02','V728','安保大叔',2,'校内道路限速十五公里每小时，你车速过快存在安全隐患。','xiào nèi dào lù xiàn sù shí wǔ gōng lǐ měi xiǎo shí， nǐ chē sù guò kuài cún zài ān quán yǐn huàn。','Đường trong trường quy định tốc độ tối đa mười lăm cây số một giờ, cháu chạy nhanh quá là có nguy cơ mất an toàn đấy.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L728_03','V728','阮明',3,'我赶去上课没留意限速标识，没有注意控制骑行速度嘛。','wǒ gǎn qù shàng kè méi liú yì xiàn sù biāo shí， méi yǒu zhù yì kòng zhì qí xíng sù dù ma。','Cháu vội đi học nên không để ý biển báo giới hạn tốc độ, không chú ý giữ tốc độ chậm lại ấy mà.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L728_04','V728','安保大叔',4,'校园行人多，电动车超速容易撞到散步、赶路的学生。','xiào yuán xíng rén duō， diàn dòng chē chāo sù róng yì zhuàng dào sàn bù、 gǎn lù de xué shēng。','Trong trường người đi bộ đông, xe điện chạy quá tốc độ dễ tông phải học sinh đang dạo bộ hay đang vội đi đâu đó lắm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L728_05','V728','阮明',5,'第一次超速提醒，会不会扣除校园通行积分或者罚款？','dì yī cì chāo sù tí xǐng， huì bú huì kòu chú xiào yuán tōng xíng jī fēn huò zhě fá kuǎn？','Lần đầu bị nhắc chạy quá tốc độ thế này có bị trừ điểm ra vào trường hay bị phạt tiền không chú?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L728_06','V728','安保大叔',6,'首次口头警告，多次超速会暂扣电动车半天教育。','shǒu cì kǒu tóu jǐng gào， duō cì chāo sù huì zàn kòu diàn dòng chē bàn tiān jiào yù。','Lần đầu thì chỉ nhắc nhở bằng lời thôi, chạy quá tốc độ nhiều lần thì sẽ bị giữ xe điện nửa ngày để giáo dục.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L728_07','V728','阮明',7,'之后在校内骑行放慢车速，严格遵守限速规定。','zhī hòu zài xiào nèi qí xíng fàng màn chē sù， yán gé zūn shǒu xiàn sù guī dìng。','Từ giờ cháu sẽ đi xe chậm lại trong trường, tuân thủ nghiêm quy định giới hạn tốc độ ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT729','SSH4','快递驿站取件忘记取件码，凭护照核对身份取件',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V729','SIT729','P1','suon_se','tuy_y',NULL,'快递驿站可凭实名有效证件核对身份取件，不止局限于短信取件码，方便遗失短信的顾客。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L729_01','V729','阮明',1,'你好，我网购的快递到驿站，但是手机弄丢取件短信码了。','nǐ hǎo， wǒ wǎng gòu de kuài dì dào yì zhàn， dàn shì shǒu jī nòng diū qǔ jiàn duǎn xìn mǎ le。','Chào chị, em có đơn hàng online gửi về bưu cục, nhưng em làm mất tin nhắn mã lấy hàng trong điện thoại rồi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L729_02','V729','驿站店员',2,'报你的收件姓名、手机号，出示有效证件就能核对包裹。','bào nǐ de shōu jiàn xìng míng、 shǒu jī hào， chū shì yǒu xiào zhèng jiàn jiù néng hé duì bāo guǒ。','Em đọc tên người nhận, số điện thoại, rồi xuất trình giấy tờ tùy thân hợp lệ là chị đối chiếu được ngay.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L729_03','V729','阮明',3,'我出示留学生护照，上面有我的姓名拼音可以核对身份吗？','wǒ chū shì liú xué shēng hù zhào， shàng miàn yǒu wǒ de xìng míng pīn yīn kě yǐ hé duì shēn fèn ma？','Em xuất trình hộ chiếu du học sinh, trên đó có tên phiên âm của em, vậy có đối chiếu được không chị?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L729_04','V729','驿站店员',4,'可以，姓名、手机号匹配无误就能直接找出快递包裹。','kě yǐ， xìng míng、 shǒu jī hào pǐ pèi wú wù jiù néng zhí jiē zhǎo chū kuài dì bāo guǒ。','Được chứ, tên với số điện thoại khớp là chị tìm ra được kiện hàng của em ngay.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L729_05','V729','阮明',5,'麻烦帮我查找今天送达的小件包裹，是学习文具。','má fán bāng wǒ chá zhǎo jīn tiān sòng dá de xiǎo jiàn bāo guǒ， shì xué xí wén jù。','Phiền chị tìm giúp em kiện hàng nhỏ gửi đến hôm nay, đồ dùng học tập ấy ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L729_06','V729','驿站店员',6,'查到了，这个快递，你核对包裹面单信息再拿走。','chá dào le， zhè ge kuài dì， nǐ hé duì bāo guǒ miàn dān xìn xī zài ná zǒu。','Tìm ra rồi đây, kiện hàng này, em kiểm tra lại thông tin trên phiếu gửi rồi lấy về nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L729_07','V729','阮明',7,'信息全部匹配，感谢不用取件码也能取件。','xìn xī quán bù pǐ pèi， gǎn xiè bù yòng qǔ jiàn mǎ yě néng qǔ jiàn。','Thông tin khớp hết rồi, cảm ơn chị đã cho em lấy hàng dù không nhớ mã ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT730','SSH4','大件快递无法上楼，和驿站协商送货上门服务',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V730','SIT730','P1','twist','ban_chinh_thuc',NULL,'校园快递驿站以自取为主，大件重物单独上门配送会收取少量配送服务费，用于补贴人工运力。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L730_01','V730','阮明',1,'我这个纸箱是被褥大件，楼梯没有电梯，自己搬不动上楼。','wǒ zhè ge zhǐ xiāng shì bèi rù dà jiàn， lóu tī méi yǒu diàn tī， zì jǐ bān bù dòng shàng lóu。','Thùng các tông này của em là chăn đệm cồng kềnh, cầu thang lại không có thang máy, tự em không khiêng lên được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L730_02','V730','驿站店员',2,'校园驿站规定小件自取，大件上门需要额外支付配送服务费。','xiào yuán yì zhàn guī dìng xiǎo jiàn zì qǔ， dà jiàn shàng mén xū yào é wài zhī fù pèi sòng fú wù fèi。','Theo quy định của bưu cục trong trường, hàng nhỏ thì tự lấy, còn hàng cồng kềnh muốn giao tận nơi thì phải trả thêm phí giao hàng.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L730_03','V730','阮明',3,'宿舍就在校内宿舍楼，距离驿站步行三分钟也要额外收费嘛？','sù shè jiù zài xiào nèi sù shè lóu， jù lí yì zhàn bù xíng sān fēn zhōng yě yào é wài shōu fèi ma？','Ký túc xá em ở ngay trong khuôn viên trường, đi bộ từ bưu cục có ba phút mà cũng phải trả thêm phí sao?','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L730_04','V730','驿站店员',4,'配送人员批量派送楼栋，单独上门单件加收三元配送费嘛。','pèi sòng rén yuán pī liàng pài sòng lóu dòng， dān dú shàng mén dān jiàn jiā shōu sān yuán pèi sòng fèi ma。','Nhân viên giao hàng giao theo lô cho cả tòa nhà, còn giao riêng lẻ từng đơn thì tính thêm ba tệ phí giao hàng.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L730_05','V730','阮明',5,'那我今天下午有空，能不能傍晚统一顺路送货上门？','nà wǒ jīn tiān xià wǔ yǒu kòng， néng bù néng bàng wǎn tǒng yī shùn lù sòng huò shàng mén？','Vậy chiều nay em rảnh, có thể chiều tối gộp giao luôn tiện đường được không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L730_06','V730','驿站店员',6,'傍晚六点批量配送，你留好宿舍房间号等候送货。','bàng wǎn liù diǎn pī liàng pèi sòng， nǐ liú hǎo sù shè fáng jiān hào děng hòu sòng huò。','Sáu giờ chiều bên em giao hàng theo lô, em nhớ để lại số phòng ký túc xá rồi đợi giao hàng nhé.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L730_07','V730','阮明',7,'我同意支付配送费，傍晚等工作人员送被褥上楼。','wǒ tóng yì zhī fù pèi sòng fèi， bàng wǎn děng gōng zuò rén yuán sòng bèi rù shàng lóu。','Em đồng ý trả phí giao hàng, chiều tối em đợi nhân viên mang chăn đệm lên phòng giúp em.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT731','SSH4','咨询校园医务室就诊流程、医保报销范围',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V731','SIT731','P1','suon_se','ban_chinh_thuc',NULL,'国内高校统一购买大学生医保，校内医务室基础诊疗、常用药品可按比例报销，大幅降低就医开支。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L731_01','V731','阮明',1,'护士您好，轻微咳嗽不舒服，想咨询医务室就诊流程。','hù shì nín hǎo， qīng wēi ké sòu bù shū fú， xiǎng zī xún yī wù shì jiù zhěn liú chéng。','Chào cô y tá, em bị ho nhẹ khó chịu trong người, muốn hỏi quy trình khám ở phòng y tế trường.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L731_02','V731','护士',2,'携带校园医保凭证、学生证，一楼分诊台登记排队就诊哦。','xié dài xiào yuán yī bǎo píng zhèng、 xué shēng zhèng， yī lóu fēn zhěn tái dēng jì pái duì jiù zhěn ó。','Em mang theo thẻ bảo hiểm y tế của trường, thẻ sinh viên, rồi đăng ký xếp hàng ở bàn phân loại tầng một để khám nhé.','AM03') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L731_03','V731','阮明',3,'校内医务室拿药可以直接医保报销，不用全额自费吗？','xiào nèi yī wù shì ná yào kě yǐ zhí jiē yī bǎo bào xiāo， bù yòng quán é zì fèi ma？','Lấy thuốc ở phòng y tế trong trường có được bảo hiểm y tế thanh toán luôn không, hay em phải trả toàn bộ tiền túi?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L731_04','V731','护士',4,'基础感冒、消炎药品报销七成，美容、滋补类药品不参与报销。','jī chǔ gǎn mào、 xiāo yán yào pǐn bào xiāo qī chéng， měi róng、 zī bǔ lèi yào pǐn bù cān yù bào xiāo。','Thuốc cảm cúm cơ bản, thuốc kháng viêm thì bảo hiểm chi trả bảy mươi phần trăm, còn thuốc làm đẹp, thuốc bổ thì không nằm trong diện thanh toán.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L731_05','V731','阮明',5,'就诊之后如果需要输液，也是同样报销比例对吗？','jiù zhěn zhī hòu rú guǒ xū yào shū yè， yě shì tóng yàng bào xiāo bǐ lì duì ma？','Sau khi khám nếu cần truyền dịch thì cũng được thanh toán theo tỷ lệ như vậy đúng không cô?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L731_06','V731','护士',6,'普通诊疗、输液均纳入医保报销，仅自费耗材除外。','pǔ tōng zhěn liáo、 shū yè jūn nà rù yī bǎo bào xiāo， jǐn zì fèi hào cái chú wài。','Khám bệnh thông thường và truyền dịch đều được đưa vào diện bảo hiểm chi trả, chỉ có vật tư tự chi trả là ngoại lệ thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L731_07','V731','阮明',7,'我带好证件，现在登记排队问诊拿药。','wǒ dài hǎo zhèng jiàn， xiàn zài dēng jì pái duì wèn zhěn ná yào。','Em mang đủ giấy tờ rồi, giờ em đi đăng ký xếp hàng khám và lấy thuốc đây ạ.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT732','SSH5','宿舍线上缴纳水电费，系统缴费失败咨询后勤',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V732','SIT732','P1','twist','ban_chinh_thuc',NULL,'校园线上缴费系统夜间服务器负载高容易卡顿，水电欠费设有三天缓冲期，不会立刻断供。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L732_01','V732','阮明',1,'您好，线上小程序缴纳宿舍电费，提交支付一直提示缴费失败。','nín hǎo， xiàn shàng xiǎo chéng xù jiǎo nà sù shè diàn fèi， tí jiāo zhī fù yì zhí tí shì jiǎo fèi shī bài。','Chào chị, em đóng tiền điện ký túc xá qua mini app trên mạng, mà bấm thanh toán cứ báo lỗi đóng tiền không được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L732_02','V732','后勤客服',2,'核对宿舍房间编号，近期是否输入错误楼栋号导致匹配失败？','hé duì sù shè fáng jiān biān hào， jìn qī shì fǒu shū rù cuò wù lóu dòng hào dǎo zhì pǐ pèi shī bài？','Em kiểm tra lại số phòng ký túc xá xem, gần đây có nhập nhầm số tòa nhà nên không khớp được không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L732_03','V732','阮明',3,'楼栋、房间号全部核对无误，银行卡扣款短信也没有收到嘛。','lóu dòng、 fáng jiān hào quán bù hé duì wú wù， yín háng kǎ kòu kuǎn duǎn xìn yě méi yǒu shōu dào ma。','Tòa nhà, số phòng em đối chiếu lại hết rồi, không sai đâu, mà tin nhắn trừ tiền từ thẻ ngân hàng cũng không nhận được luôn.','AM09') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L732_04','V732','后勤客服',4,'小程序晚间服务器拥堵，夜间零点至早八点系统不稳定。','xiǎo chéng xù wǎn jiān fú wù qì yōng dǔ， yè jiān líng diǎn zhì zǎo bā diǎn xì tǒng bù wěn dìng。','Buổi tối máy chủ mini app hay bị nghẽn, từ nửa đêm đến tám giờ sáng hệ thống không ổn định lắm.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L732_05','V732','阮明',5,'那我明天上午再重新提交缴费，不会产生停水断电吧？','nà wǒ míng tiān shàng wǔ zài chóng xīn tí jiāo jiǎo fèi， bú huì chǎn shēng tíng shuǐ duàn diàn ba？','Vậy sáng mai em nộp lại tiền, chắc không bị cắt nước cắt điện chứ chị?','AM07') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L732_06','V732','后勤客服',6,'宿舍水电欠费缓冲三天，三天内缴费不会切断供应。','sù shè shuǐ diàn qiàn fèi huǎn chōng sān tiān， sān tiān nèi jiǎo fèi bú huì qiē duàn gōng yìng。','Tiền điện nước ký túc xá có thời gian gia hạn ba ngày, trong ba ngày đóng tiền thì không bị cắt cung cấp đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L732_07','V732','阮明',7,'明天一早完成缴费，避免宿舍水电临时关停。','míng tiān yī zǎo wán chéng jiǎo fèi， bì miǎn sù shè shuǐ diàn lín shí guān tíng。','Sáng mai em đóng tiền xong sớm luôn, để tránh bị cắt điện nước ký túc xá tạm thời.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT733','SSH5','校园校园网账号欠费断网，线上续费恢复网络',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V733','SIT733','P1','suon_se','tuy_y',NULL,'校园内网按月计费，欠费立刻断网，校内图书馆、论文数据库均依托校园网访问。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L733_01','V733','阮明',1,'电脑显示校园网欠费停机，网页视频、学习软件全都打不开。','diàn nǎo xiǎn shì xiào yuán wǎng qiàn fèi tíng jī， wǎng yè shì pín、 xué xí ruǎn jiàn quán dōu dǎ bù kāi。','Máy tính báo mạng trường bị nợ phí nên bị cắt kết nối, web, video, phần mềm học tập gì cũng không mở được.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L733_02','V733','小林',2,'打开校园网小程序，输入学号就能线上充值续费啦。','dǎ kāi xiào yuán wǎng xiǎo chéng xù， shū rù xué hào jiù néng xiàn shàng chōng zhí xù fèi la。','Cậu mở app mạng trường lên, nhập mã số sinh viên vào là nạp tiền gia hạn online được ngay.','AM02') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L733_03','V733','阮明',3,'包月套餐三十元，充值之后是立刻恢复网络吗？','bāo yuè tào cān sān shí yuán， chōng zhí zhī hòu shì lì kè huī fù wǎng luò ma？','Gói cước tháng ba mươi tệ, nạp xong là mạng có lại liền hả?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L733_04','V733','小林',4,'充值成功十秒内自动联网，不用重启电脑路由器。','chōng zhí chéng gōng shí miǎo nèi zì dòng lián wǎng， bù yòng chóng qǐ diàn nǎo lù yóu qì。','Nạp thành công là trong vòng mười giây tự động có mạng lại, không cần khởi động lại máy tính hay router đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L733_05','V733','阮明',5,'要是忘记续费，断网之后校内论文数据库也没法访问？','yào shì wàng jì xù fèi， duàn wǎng zhī hòu xiào nèi lùn wén shù jù kù yě méi fǎ fǎng wèn？','Nếu lỡ quên gia hạn, mất mạng rồi thì thư viện luận văn nội bộ trong trường cũng không vào được luôn hả?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L733_06','V733','小林',6,'没错，内网文献库依赖校园网，断网完全无法登录查阅。','méi cuò， nèi wǎng wén xiàn kù yī lài xiào yuán wǎng， duàn wǎng wán quán wú fǎ dēng lù chá yuè。','Đúng vậy đó, kho tài liệu nội bộ phụ thuộc vào mạng trường, mất mạng là chịu, không đăng nhập tra cứu được đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L733_07','V733','阮明',7,'我现在线上充值续费，恢复网络继续写作业。','wǒ xiàn zài xiàn shàng chōng zhí xù fèi， huī fù wǎng luò jì xù xiě zuò yè。','Giờ tớ nạp tiền gia hạn online luôn đây, có mạng lại rồi làm bài tiếp.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT734','SSH5','手机话费余额不足停机，便利店线下充值缴费',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V734','SIT734','P1','suon_se','tuy_y',NULL,'国内线下便利店可办理手机话费充值，适合线上支付故障、手机停机无法收验证码的情况。') ON CONFLICT (id) DO UPDATE SET situation_id=EXCLUDED.situation_id,persona_id=EXCLUDED.persona_id,outcome_type=EXCLUDED.outcome_type,register_level=EXCLUDED.register_level,context_note=EXCLUDED.context_note,cultural_note=EXCLUDED.cultural_note;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L734_01','V734','阮明',1,'你好，手机停机没法收短信，能不能线下充值话费？','nǐ hǎo， shǒu jī tíng jī méi fǎ shōu duǎn xìn， néng bù néng xiàn xià chōng zhí huà fèi？','Chào chị, điện thoại em bị khóa máy không nhận được tin nhắn, chị cho em nạp tiền trực tiếp ở đây được không?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L734_02','V734','便利店店员',2,'支持五十、一百面额线下充值，输入手机号就能充值哈。','zhī chí wǔ shí、 yì bǎi miàn é xiàn xià chōng zhí， shū rù shǒu jī hào jiù néng chōng zhí hā。','Chỗ chị nhận nạp mệnh giá năm mươi, một trăm trực tiếp, cứ đọc số điện thoại là nạp được liền nha.','AM06') ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L734_03','V734','阮明',3,'充值成功之后，多久手机能恢复通话、短信功能？','chōng zhí chéng gōng zhī hòu， duō jiǔ shǒu jī néng huī fù tōng huà、 duǎn xìn gōng néng？','Nạp xong thì bao lâu máy mới gọi được, nhắn tin lại được vậy chị?',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L734_04','V734','便利店店员',4,'充值到账两分钟内自动复机，不用重启手机。','chōng zhí dào zhàng liǎng fēn zhōng nèi zì dòng fù jī， bù yòng chóng qǐ shǒu jī。','Tiền vào tài khoản là trong hai phút tự động mở máy lại, không cần khởi động lại điện thoại đâu.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L734_05','V734','阮明',5,'那充值一百元，报我的手机号码给你。','nà chōng zhí yì bǎi yuán， bào wǒ de shǒu jī hào mǎ gěi nǐ。','Vậy chị nạp cho em một trăm, em đọc số điện thoại cho chị nha.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L734_06','V734','便利店店员',6,'充值完成，手机很快就能恢复正常通讯。','chōng zhí wán chéng， shǒu jī hěn kuài jiù néng huī fù zhèng cháng tōng xùn。','Nạp xong rồi đó, máy sẽ nhanh chóng liên lạc bình thường trở lại thôi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L734_07','V734','阮明',7,'太好了，终于可以联系家人和同学。','tài hǎo le， zhōng yú kě yǐ lián xì jiā rén hé tóng xué。','Tuyệt quá, cuối cùng cũng liên lạc được với gia đình với bạn học rồi.',NULL) ON CONFLICT (id) DO UPDATE SET variant_id=EXCLUDED.variant_id,speaker=EXCLUDED.speaker,order_index=EXCLUDED.order_index,text_zh=EXCLUDED.text_zh,pinyin=EXCLUDED.pinyin,text_vi=EXCLUDED.text_vi,attitude_marker_id=EXCLUDED.attitude_marker_id;
