INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L316_07','V316','阮明',7,'听完我完全懂了，谢谢老师！','tīng wán wǒ wán quán dǒng le， xiè xiè lǎo shī！','Nghe xong em hiểu hết rồi ạ, cảm ơn thầy/cô!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT317','S108','Hỏi quy định phòng thi',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V317','SIT317','P1','suon_se','chinh_thuc',NULL,'国内标准化考试严禁携带私人物品入场，违规携带会被判定为考试违纪。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L317_01','V317','阮明',1,'老师您好，我想咨询一下本次期末考试的考场规则。','lǎo shī nín hǎo， wǒ xiǎng zī xún yī xià běn cì qī mò kǎo shì de kǎo chǎng guī zé。','Thầy/cô ơi, em muốn hỏi về quy định phòng thi cho kỳ thi cuối kỳ lần này ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L317_02','V317','监考老师',2,'你有不清楚的地方可以直接提问。','nǐ yǒu bù qīng chǔ de dì fāng kě yǐ zhí jiē tí wèn。','Có chỗ nào chưa rõ em cứ hỏi thẳng luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L317_03','V317','阮明',3,'请问考试期间可以自带草稿纸和文具吗？','qǐng wèn kǎo shì qī jiān kě yǐ zì dài cǎo gǎo zhǐ hé wén jù ma？','Dạ cho em hỏi trong lúc thi có được mang theo giấy nháp và dụng cụ học tập riêng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L317_04','V317','监考老师',4,'不可以，考场会统一发放所有考试用品。','bù kě yǐ， kǎo chǎng huì tǒng yī fā fàng suǒ yǒu kǎo shì yòng pǐn。','Không được, phòng thi sẽ phát thống nhất mọi vật dụng cần thiết cho thi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L317_05','V317','阮明',5,'那电子手表需要摘下来存放吗？','nà diàn zi shǒu biǎo xū yào zhāi xià lái cún fàng ma？','Vậy đồng hồ điện tử thì có cần tháo ra cất riêng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L317_06','V317','监考老师',6,'是的，所有电子设备都需统一收纳。','shì de， suǒ yǒu diàn zi shè bèi dōu xū tǒng yī shōu nà。','Đúng vậy, tất cả thiết bị điện tử đều phải cất riêng theo quy định chung.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L317_07','V317','阮明',7,'我清楚所有规则了，谢谢老师！','wǒ qīng chǔ suǒ yǒu guī zé le， xiè xiè lǎo shī！','Em nắm rõ hết các quy định rồi ạ, cảm ơn thầy/cô!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT318','S108','Xem điểm thi trên hệ thống bị sai, hỏi lại giáo viên',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V318','SIT318','P1','twist','ban_chinh_thuc',NULL,'校园教务系统偶有BUG，学生成绩最终以老师线下备案记录为准，可随时核实修正。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L318_01','V318','阮明',1,'老师您好，我想核实一下我的课程期末成绩。','lǎo shī nín hǎo， wǒ xiǎng hé shí yī xià wǒ de kè chéng qī mò chéng jì。','Thầy/cô ơi, em muốn xác nhận lại điểm cuối kỳ môn học của em ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L318_02','V318','老师',2,'好的，具体是什么问题？','hǎo de， jù tǐ shì shén me wèn tí？','Được, cụ thể là vấn đề gì vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L318_03','V318','阮明',3,'我所有作业、考勤、考试都正常完成，但系统显示无成绩。','wǒ suǒ yǒu zuò yè、 kǎo qín、 kǎo shì dōu zhèng cháng wán chéng， dàn xì tǒng xiǎn shì wú chéng jì。','Em đã hoàn thành đầy đủ bài tập, điểm danh, thi cử bình thường, nhưng hệ thống lại hiện chưa có điểm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L318_04','V318','老师',4,'应该是教务系统录入卡顿，出现数据异常了。','yīng gāi shì jiào wù xì tǒng lù rù kǎ dùn， chū xiàn shù jù yì cháng le。','Chắc là hệ thống giáo vụ bị lỗi khi nhập liệu nên dữ liệu bị sai lệch đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L318_05','V318','阮明',5,'我一直担心是自己漏交作业，心里很不安。','wǒ yì zhí dān xīn shì zì jǐ lòu jiāo zuò yè， xīn lǐ hěn bù ān。','Em cứ lo là do mình quên nộp bài tập nào đó, trong lòng thấy bất an quá.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L318_06','V318','老师',6,'你放心，我手动核对备案，重新给你录入成绩。','nǐ fàng xīn， wǒ shǒu dòng hé duì bèi àn， chóng xīn gěi nǐ lù rù chéng jì。','Em cứ yên tâm, thầy/cô sẽ đối chiếu hồ sơ thủ công và nhập lại điểm cho em.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L318_07','V318','阮明',7,'太感谢老师帮忙处理了！','tài gǎn xiè lǎo shī bāng máng chǔ lǐ le！','Em cảm ơn thầy/cô nhiều lắm vì đã giúp em xử lý việc này!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT319','S108','Xin phúc khảo bài thi',NULL,'C1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V319','SIT319','P1','suon_se','chinh_thuc',NULL,'国内高校成绩复核仅核查卷面分数统计错误，不重新评判答题内容，是正规申诉渠道；复核结果统一公示，具备官方效力。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_01','V319','阮明',1,'老师您好，今天来找您，是想正式提交本次期末试卷成绩复核申请。','lǎo shī nín hǎo， jīn tiān lái zhǎo nín， shì xiǎng zhèng shì tí jiāo běn cì qī mò shì juàn chéng jì fù hé shēn qǐng。','Thầy/cô ơi, hôm nay em đến gặp là muốn chính thức nộp đơn xin phúc khảo điểm bài thi cuối kỳ lần này ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_02','V319','老师',2,'先坐，我先跟你确认，你清楚学校成绩复核的具体范围和规则吗？','xiān zuò， wǒ xiān gēn nǐ què rèn， nǐ qīng chǔ xué xiào chéng jì fù hé de jù tǐ fàn wéi hé guī zé ma？','Em ngồi đi đã, thầy/cô hỏi trước, em có nắm rõ phạm vi và quy định phúc khảo điểm của trường không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_03','V319','阮明',3,'只听说可以核对卷面总分统计，不能重新评判答题内容，细节了解不多。','zhǐ tīng shuō kě yǐ hé duì juàn miàn zǒng fēn tǒng jì， bù néng chóng xīn píng pàn dá tí nèi róng， xì jié liǎo jiě bù duō。','Em chỉ nghe nói là được đối chiếu lại tổng điểm trên bài thi, chứ không được chấm lại nội dung bài làm, còn chi tiết thì em chưa rõ lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_04','V319','老师',4,'没错，复核仅检查每道小题得分相加是否计算错误，不会更改主观题打分。','méi cuò， fù hé jǐn jiǎn chá měi dào xiǎo tí dé fēn xiāng jiā shì fǒu jì suàn cuò wù， bú huì gēng gǎi zhǔ guān tí dǎ fēn。','Đúng vậy, phúc khảo chỉ kiểm tra xem tổng điểm cộng từ các câu nhỏ có tính sai không, chứ không thay đổi điểm chấm các câu tự luận.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_05','V319','阮明',5,'我自己对照参考答案预估的分数，和最终系统录入成绩差距很大，心里比较疑惑。','wǒ zì jǐ duì zhào cān kǎo dá àn yù gū de fēn shù， hé zuì zhōng xì tǒng lù rù chéng jì chā jù hěn dà， xīn lǐ bǐ jiào yí huò。','Em tự đối chiếu với đáp án tham khảo rồi ước tính điểm, thấy chênh lệch khá nhiều so với điểm hệ thống ghi cuối cùng, nên trong lòng em khá thắc mắc.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_06','V319','老师',6,'我理解你的顾虑，我可以协助你向学院教学办提交官方书面复核申请。','wǒ lǐ jiě nǐ de gù lǜ， wǒ kě yǐ xié zhù nǐ xiàng xué yuàn jiào xué bàn tí jiāo guān fāng shū miàn fù hé shēn qǐng。','Thầy/cô hiểu băn khoăn của em, thầy/cô có thể hỗ trợ em nộp đơn phúc khảo chính thức bằng văn bản lên phòng đào tạo của khoa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_07','V319','阮明',7,'提交申请的时候，需要附带什么证明材料，填写专用表格吗？','tí jiāo shēn qǐng de shí hòu， xū yào fù dài shén me zhèng míng cái liào， tián xiě zhuān yòng biǎo gé ma？','Vậy khi nộp đơn thì em cần đính kèm giấy tờ gì, hay điền vào mẫu đơn riêng ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_08','V319','老师',8,'我这边给你打印统一的复核申请表，填写姓名、学号、科目和申请理由即可。','wǒ zhè biān gěi nǐ dǎ yìn tǒng yī de fù hé shēn qǐng biǎo， tián xiě xìng míng、 xué hào、 kē mù hé shēn qǐng lǐ yóu jí kě。','Thầy/cô sẽ in cho em mẫu đơn phúc khảo chung, em chỉ cần điền họ tên, mã số sinh viên, môn học và lý do xin phúc khảo là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_09','V319','阮明',9,'请问提交申请表之后，大概多久可以出具最终复核结果呢？','qǐng wèn tí jiāo shēn qǐng biǎo zhī hòu， dà gài duō jiǔ kě yǐ chū jù zuì zhōng fù hé jié guǒ ne？','Cho em hỏi sau khi nộp đơn thì khoảng bao lâu sẽ có kết quả phúc khảo cuối cùng ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_10','V319','老师',10,'学院统一收集申请，三个工作日内完成卷面核对并公示修正后的成绩。','xué yuàn tǒng yī shōu jí shēn qǐng， sān gè gōng zuò rì nèi wán chéng juàn miàn hé duì bìng gōng shì xiū zhèng hòu de chéng jì。','Khoa sẽ thu thập đơn thống nhất, trong vòng ba ngày làm việc sẽ hoàn tất đối chiếu bài thi và công bố điểm đã điều chỉnh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_11','V319','阮明',11,'如果复核后分数有调整，系统成绩会同步更新对吧？','rú guǒ fù hé hòu fēn shù yǒu tiáo zhěng， xì tǒng chéng jì huì tóng bù gēng xīn duì ba？','Nếu sau phúc khảo điểm có thay đổi thì hệ thống cũng sẽ tự động cập nhật đúng không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_12','V319','老师',12,'是的，核对出计算失误会直接修改教务系统内你的期末分数。','shì de， hé duì chū jì suàn shī wù huì zhí jiē xiū gǎi jiào wù xì tǒng nèi nǐ de qī mò fēn shù。','Đúng vậy, nếu phát hiện tính sai thì sẽ chỉnh sửa trực tiếp điểm cuối kỳ của em trong hệ thống giáo vụ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_13','V319','阮明',13,'我现在填写申请表，麻烦老师帮忙转交教学办。','wǒ xiàn zài tián xiě shēn qǐng biǎo， má fán lǎo shī bāng máng zhuǎn jiāo jiào xué bàn。','Vậy giờ em điền đơn luôn, phiền thầy/cô chuyển giúp em lên phòng đào tạo ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_14','V319','老师',14,'放心，流程我全程跟进，有结果第一时间通知你。','fàng xīn， liú chéng wǒ quán chéng gēn jìn， yǒu jié guǒ dì yī shí jiān tōng zhī nǐ。','Yên tâm đi, thầy/cô sẽ theo sát toàn bộ quy trình, có kết quả sẽ báo cho em ngay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L319_15','V319','阮明',15,'辛苦老师费心办理，非常感谢！','xīn kǔ lǎo shī fèi xīn bàn lǐ， fēi cháng gǎn xiè！','Cảm ơn thầy/cô đã vất vả lo liệu việc này giúp em, em cảm kích lắm ạ!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT320','S106','Mượn vở ghi chép của bạn vì nghỉ học',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V320','SIT320','P1','suon_se','tuy_y',NULL,'同学之间互借笔记、补全知识点是国内大学校园最普遍的互助行为。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L320_01','V320','阮明',1,'琪琪，我昨天请假缺课了，能借我一下你的课堂笔记吗？','qí qí， wǒ zuó tiān qǐng jià quē kè le， néng jiè wǒ yī xià nǐ de kè táng bǐ jì ma？','Kỳ Kỳ ơi, hôm qua tớ xin nghỉ nên lỡ mất buổi học, cho tớ mượn vở ghi chép của cậu được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L320_02','V320','李琪',2,'当然可以，我记得特别详细，重难点都标出来了。','dāng rán kě yǐ， wǒ jì de tè bié xiáng xì， zhòng nán diǎn dōu biāo chū lái le。','Đương nhiên được, tớ ghi khá chi tiết đó, chỗ trọng tâm khó đều đánh dấu hết rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L320_03','V320','阮明',3,'太好了，我刚好错过最重要的知识点。','tài hǎo le， wǒ gāng hǎo cuò guò zuì zhòng yào de zhī shí diǎn。','Tuyệt quá, tớ đúng lúc bị lỡ mất phần kiến thức quan trọng nhất luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L320_04','V320','李琪',4,'没事，你慢慢看，看完再还我就行。','méi shì， nǐ màn màn kàn， kàn wán zài hái wǒ jiù xíng。','Không sao đâu, cậu cứ từ từ xem, xem xong trả lại tớ là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L320_05','V320','阮明',5,'太感谢了，有不懂的地方我再问你哈。','tài gǎn xiè le， yǒu bù dǒng de dì fāng wǒ zài wèn nǐ hā。','Cảm ơn cậu nhiều lắm, chỗ nào không hiểu tớ hỏi cậu tiếp nha.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L320_06','V320','李琪',6,'没问题，同学之间本来就该互相帮忙。','méi wèn tí， tóng xué zhī jiān běn lái jiù gāi hù xiāng bāng máng。','Không vấn đề gì, bạn bè với nhau vốn dĩ phải giúp đỡ nhau mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L320_07','V320','阮明',7,'真的太贴心啦！','zhēn de tài tiē xīn la！','Cậu tốt bụng thật đấy!','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT321','S109','Đặt lịch khám qua ứng dụng',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V321','SIT321','P1','twist','ban_chinh_thuc',NULL,'国内公立医院热门科室号源紧张，必须提前线上预约，现场基本无剩余号。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L321_01','V321','阮明',1,'你好，我想在APP上预约今天的内科门诊。','nǐ hǎo， wǒ xiǎng zài APP shàng yù yuē jīn tiān de nèi kē mén zhěn。','Chào bạn, mình muốn đặt lịch khám nội khoa hôm nay trên ứng dụng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L321_02','V321','客服',2,'您好，请问您需要普通号还是专家号？','nín hǎo， qǐng wèn nín xū yào pǔ tōng hào hái shì zhuān jiā hào？','Dạ chào anh/chị, anh/chị muốn đặt số khám thường hay số khám chuyên gia ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L321_03','V321','阮明',3,'普通号就可以，我只是轻微头晕乏力。','pǔ tōng hào jiù kě yǐ， wǒ zhǐ shì qīng wēi tóu yūn fá lì。','Số khám thường là được rồi, mình chỉ hơi chóng mặt và mệt mỏi thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L321_04','V321','客服',4,'非常抱歉，今天内科普通号已经全部约满了。','fēi cháng bào qiàn， jīn tiān nèi kē pǔ tōng hào yǐ jīng quán bù yuē mǎn le。','Dạ em rất xin lỗi, số khám nội khoa thường hôm nay đã kín hết rồi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L321_05','V321','阮明',5,'这样啊，那明天的号还有空位吗？','zhè yàng a， nà míng tiān de hào hái yǒu kòng wèi ma？','Vậy à, thế ngày mai còn số trống không?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L321_06','V321','客服',6,'明天上午号源充足，我可以指导您预约。','míng tiān shàng wǔ hào yuán chōng zú， wǒ kě yǐ zhǐ dǎo nín yù yuē。','Sáng mai còn nhiều số trống ạ, em có thể hướng dẫn anh/chị đặt lịch.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L321_07','V321','阮明',7,'好的，麻烦你教我操作一下！','hǎo de， má fán nǐ jiāo wǒ cāo zuò yī xià！','Được, phiền bạn hướng dẫn mình thao tác nhé!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT322','S109','Đăng ký khoa khám phù hợp tại quầy',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V322','SIT322','P1','suon_se','ban_chinh_thuc',NULL,'医院科室划分精细，身体不适不确定科室，可咨询挂号窗口精准分诊，避免挂错号。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L322_01','V322','阮明',1,'你好，我最近经常头晕、睡眠不好，该挂什么科室？','nǐ hǎo， wǒ zuì jìn jīng cháng tóu yūn、 shuì mián bù hǎo， gāi guà shén me kē shì？','Chào chị, dạo này em hay bị chóng mặt, ngủ không ngon, vậy em nên khám khoa gì ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L322_02','V322','工作人员',2,'你这个症状挂神经内科是最合适的。','nǐ zhè ge zhèng zhuàng guà shén jīng nèi kē shì zuì hé shì de。','Triệu chứng của em thì khám khoa nội thần kinh là hợp lý nhất.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L322_03','V322','阮明',3,'那帮我挂一个今天下午的普通门诊吧。','nà bāng wǒ guà yí gè jīn tiān xià wǔ de pǔ tōng mén zhěn ba。','Vậy chị đăng ký giúp em suất khám thường chiều nay nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L322_04','V322','工作人员',4,'好的，请问使用医保结算还是自费？','hǎo de， qǐng wèn shǐ yòng yī bǎo jié suàn hái shì zì fèi？','Được rồi, em thanh toán bằng bảo hiểm y tế hay tự trả phí ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L322_05','V322','阮明',5,'我用学生医保结算。','wǒ yòng xué shēng yī bǎo jié suàn。','Em dùng bảo hiểm y tế sinh viên để thanh toán ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L322_06','V322','工作人员',6,'已为您挂号成功，请前往二楼诊室等候。','yǐ wèi nín guà hào chéng gōng， qǐng qián wǎng èr lóu zhěn shì děng hòu。','Em đã đăng ký thành công rồi, mời em lên phòng khám tầng hai chờ nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L322_07','V322','阮明',7,'好的，谢谢你！','hǎo de， xiè xiè nǐ！','Dạ vâng, em cảm ơn chị nhiều!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT323','S109','Miêu tả triệu chứng với bác sĩ',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V323','SIT323','P1','suon_se','ban_chinh_thuc',NULL,'就医时清晰说明症状时长、频率和状态，能帮助医生快速、精准判断病情。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L323_01','V323','阮明',1,'医生您好，我这三四天一直头晕、浑身没力气。','yī shēng nín hǎo， wǒ zhè sān sì tiān yì zhí tóu yūn、 hún shēn méi lì qì。','Bác sĩ ơi, mấy ngày nay em cứ bị chóng mặt với người mệt rũ suốt.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L323_02','V323','医生',2,'是一直晕，还是偶尔一阵一阵的？','shì yì zhí yūn， hái shì ǒu ěr yī zhèn yī zhèn de？','Là chóng mặt liên tục hay thỉnh thoảng mới bị từng cơn?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L323_03','V323','阮明',3,'偶尔发作，尤其是晚上，还经常失眠睡不着。','ǒu ěr fā zuò， yóu qí shì wǎn shàng， hái jīng cháng shī mián shuì bù zhe。','Thỉnh thoảng thôi ạ, nhất là buổi tối, với lại em còn hay mất ngủ, không ngủ được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L323_04','V323','医生',4,'有没有发烧、恶心或者其他不舒服？','yǒu méi yǒu fā shāo、 ě xīn huò zhě qí tā bù shū fú？','Em có bị sốt, buồn nôn hay khó chịu gì khác không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L323_05','V323','阮明',5,'没有的，就只有头晕和乏力这两个症状。','méi yǒu de， jiù zhǐ yǒu tóu yūn hé fá lì zhè liǎng gè zhèng zhuàng。','Không ạ, chỉ có mỗi hai triệu chứng chóng mặt với mệt mỏi thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L323_06','V323','医生',6,'我大概清楚了，我给你简单检查一下。','wǒ dà gài qīng chǔ le， wǒ gěi nǐ jiǎn dān jiǎn chá yī xià。','Được rồi, bác sĩ hiểu sơ bộ rồi, để bác sĩ khám qua cho em nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L323_07','V323','阮明',7,'好的，麻烦医生了！','hǎo de， má fán yī shēng le！','Dạ vâng, phiền bác sĩ rồi ạ!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT324','S109','Báo dị ứng thuốc trước khi được kê đơn',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V324','SIT324','P1','suon_se','chinh_thuc',NULL,'国内就医开药必须主动申报过敏史，是保障用药安全的重要医疗规范。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L324_01','V324','阮明',1,'医生，我需要提前告知您我的药物过敏史。','yī shēng， wǒ xū yào tí qián gào zhī nín wǒ de yào wù guò mǐn shǐ。','Thưa bác sĩ, tôi cần báo trước với bác sĩ về tiền sử dị ứng thuốc của tôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L324_02','V324','医生',2,'好的，你具体对哪种药物过敏？','hǎo de， nǐ jù tǐ duì nǎ zhǒng yào wù guò mǐn？','Được, vậy cụ thể anh dị ứng với loại thuốc nào?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L324_03','V324','阮明',3,'我对青霉素类药物过敏，绝对不能使用这类药。','wǒ duì qīng méi sù lèi yào wù guò mǐn， jué duì bù néng shǐ yòng zhè lèi yào。','Tôi dị ứng với nhóm thuốc penicillin, tuyệt đối không được dùng loại này.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L324_04','V324','医生',4,'我记下了，开药时会完全避开致敏药物。','wǒ jì xià le， kāi yào shí huì wán quán bì kāi zhì mǐn yào wù。','Tôi đã ghi lại rồi, khi kê đơn sẽ tránh hoàn toàn loại thuốc gây dị ứng đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L324_05','V324','阮明',5,'我之前过敏反应很严重，所以特别谨慎。','wǒ zhī qián guò mǐn fǎn yìng hěn yán zhòng， suǒ yǐ tè bié jǐn shèn。','Trước đây tôi từng bị phản ứng dị ứng rất nặng nên tôi đặc biệt thận trọng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L324_06','V324','医生',6,'我明白，用药安全是第一位的，你放心。','wǒ míng bái， yòng yào ān quán shì dì yī wèi de， nǐ fàng xīn。','Tôi hiểu, an toàn dùng thuốc là ưu tiên hàng đầu, anh cứ yên tâm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L324_07','V324','阮明',7,'感谢医生细心负责！','gǎn xiè yī shēng xì xīn fù zé！','Cảm ơn bác sĩ đã cẩn thận và chu đáo!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT325','S110','Mua thuốc theo đơn tại nhà thuốc',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V325','SIT325','P1','suon_se','ban_chinh_thuc',NULL,'医院取药后，药师会逐一告知用法、用量、保存方式，务必严格遵照执行。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L325_01','V325','阮明',1,'你好，这是我的处方单，麻烦帮我取一下药。','nǐ hǎo， zhè shì wǒ de chǔ fāng dān， má fán bāng wǒ qǔ yī xià yào。','Chào chị, đây là đơn thuốc của em, phiền chị lấy giúp em thuốc với ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L325_02','V325','药师',2,'好的，请稍等，我核对一下药品信息。','hǎo de， qǐng shāo děng， wǒ hé duì yī xià yào pǐn xìn xī。','Được rồi, em chờ chút, chị kiểm tra lại thông tin thuốc đã.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L325_03','V325','阮明',3,'没问题，这些药具体怎么服用呀？','méi wèn tí， zhè xiē yào jù tǐ zěn me fú yòng ya？','Dạ không sao ạ, mấy loại thuốc này uống cụ thể thế nào vậy chị?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L325_04','V325','药师',4,'都是一日三次，饭后温水服用，说明书也有标注。','dōu shì yī rì sān cì， fàn hòu wēn shuǐ fú yòng， shuō míng shū yě yǒu biāo zhù。','Đều uống ngày ba lần, sau ăn với nước ấm, trên tờ hướng dẫn cũng có ghi rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L325_05','V325','阮明',5,'需要低温冷藏保存吗？','xū yào dī wēn lěng cáng bǎo cún ma？','Vậy có cần bảo quản lạnh không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L325_06','V325','药师',6,'不用，常温避光存放就可以。','bù yòng， cháng wēn bì guāng cún fàng jiù kě yǐ。','Không cần đâu, để nơi thoáng mát, tránh ánh sáng là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L325_07','V325','阮明',7,'明白了，谢谢药师！','míng bái le， xiè xiè yào shī！','Dạ em hiểu rồi, em cảm ơn chị nhé!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT326','S109','Hỏi bảo hiểm có chi trả loại thuốc này không',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V326','SIT326','P1','twist','ban_chinh_thuc',NULL,'国内医保仅覆盖基础刚需药品，进口药、高端特效药大多需要个人自费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L326_01','V326','阮明',1,'你好，我想问一下我开的这些药能不能医保报销？','nǐ hǎo， wǒ xiǎng wèn yī xià wǒ kāi de zhè xiē yào néng bù néng yī bǎo bào xiāo？','Chào chị, em muốn hỏi mấy loại thuốc bác sĩ kê cho em có được bảo hiểm y tế thanh toán không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L326_02','V326','工作人员',2,'我帮你查询一下药品医保目录。','wǒ bāng nǐ chá xún yī xià yào pǐn yī bǎo mù lù。','Để chị tra giúp em danh mục thuốc bảo hiểm y tế nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L326_03','V326','工作人员',3,'查到了，其中两款基础药可以报销，一款进口药不行。','chá dào le， qí zhōng liǎng kuǎn jī chǔ yào kě yǐ bào xiāo， yī kuǎn jìn kǒu yào bù xíng。','Tra ra rồi này, trong đó có hai loại thuốc cơ bản được thanh toán, còn một loại thuốc nhập khẩu thì không.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L326_04','V326','阮明',4,'这样啊，进口药需要全额自费是吗？','zhè yàng a， jìn kǒu yào xū yào quán é zì fèi shì ma？','Vậy à, tức là thuốc nhập khẩu em phải tự trả toàn bộ phải không ạ?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L326_05','V326','工作人员',5,'对的，进口特效药不在医保报销范围内。','duì de， jìn kǒu tè xiào yào bù zài yī bǎo bào xiāo fàn wéi nèi。','Đúng vậy, thuốc đặc trị nhập khẩu không nằm trong phạm vi bảo hiểm y tế chi trả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L326_06','V326','阮明',6,'我了解了，那麻烦你分开结算吧。','wǒ liǎo jiě le， nà má fán nǐ fēn kāi jié suàn ba。','Dạ em hiểu rồi, vậy phiền chị tách riêng ra khi thanh toán giúp em nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L326_07','V326','工作人员',7,'没问题，我帮你区分清楚。','méi wèn tí， wǒ bāng nǐ qū fēn qīng chǔ。','Không vấn đề gì, chị sẽ tách rõ ràng cho em.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT327','S109','Đặt lịch tái khám',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V327','SIT327','P1','suon_se','ban_chinh_thuc',NULL,'慢性病、短期病症恢复都需要复诊，携带既往病历是医院常规要求。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L327_01','V327','阮明',1,'你好，我想预约下周的复诊门诊。','nǐ hǎo， wǒ xiǎng yù yuē xià zhōu de fù zhěn mén zhěn。','Chào chị, em muốn đặt lịch khám tái khám tuần sau ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L327_02','V327','工作人员',2,'可以的，你想预约周几的时间段？','kě yǐ de， nǐ xiǎng yù yuē zhōu jǐ de shí jiān duàn？','Được chứ, em muốn đặt vào khung giờ nào, thứ mấy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L327_03','V327','阮明',3,'下周二下午吧，我下午没有课程安排。','xià zhōu èr xià wǔ ba， wǒ xià wǔ méi yǒu kè chéng ān pái。','Chiều thứ ba tuần sau ạ, chiều đó em không có lịch học.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L327_04','V327','工作人员',4,'好的，已经为你预约成功。','hǎo de， yǐ jīng wèi nǐ yù yuē chéng gōng。','Được rồi, chị đã đặt lịch thành công cho em rồi nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L327_05','V327','阮明',5,'复诊的时候需要带这次的病历本吗？','fù zhěn de shí hòu xū yào dài zhè cì de bìng lì běn ma？','Khi tái khám em có cần mang theo sổ bệnh án lần này không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L327_06','V327','工作人员',6,'需要的，务必携带方便医生对比恢复情况。','xū yào de， wù bì xié dài fāng biàn yī shēng duì bǐ huī fù qíng kuàng。','Cần chứ, nhất định phải mang theo để bác sĩ tiện so sánh tình hình hồi phục.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L327_07','V327','阮明',7,'好的，我会妥善保管，谢谢你！','hǎo de， wǒ huì tuǒ shàn bǎo guǎn， xiè xiè nǐ！','Dạ vâng, em sẽ giữ cẩn thận, cảm ơn chị nhé!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT328','S109','Xin giấy chứng nhận nghỉ bệnh cho trường',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V328','SIT328','P1','suon_se','chinh_thuc',NULL,'国内高校只认可医院机打正规病假证明，手写证明无效，是统一考勤制度。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L328_01','V328','阮明',1,'医生您好，我身体不适需要请假，麻烦您开具一张病假证明。','yī shēng nín hǎo， wǒ shēn tǐ bù shì xū yào qǐng jià， má fán nín kāi jù yī zhāng bìng jià zhèng míng。','Thưa bác sĩ, tôi thấy trong người không khỏe cần xin nghỉ, phiền bác sĩ viết giúp tôi một giấy chứng nhận nghỉ bệnh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L328_02','V328','医生',2,'没问题，你需要请假休养几天？','méi wèn tí， nǐ xū yào qǐng jià xiū yǎng jǐ tiān？','Không vấn đề gì, anh cần nghỉ dưỡng bao nhiêu ngày?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L328_03','V328','阮明',3,'我身体比较虚弱，想请假两天调整状态。','wǒ shēn tǐ bǐ jiào xū ruò， xiǎng qǐng jià liǎng tiān tiáo zhěng zhuàng tài。','Tôi thấy trong người khá yếu nên muốn xin nghỉ hai ngày để điều chỉnh lại sức khỏe.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L328_04','V328','医生',4,'可以，我给你开具正规机打病假证明。','kě yǐ， wǒ gěi nǐ kāi jù zhèng guī jī dǎ bìng jià zhèng míng。','Được, tôi sẽ viết cho anh giấy chứng nhận nghỉ bệnh in chính thức.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L328_05','V328','阮明',5,'证明上会标注就诊时间和请假时长对吧？','zhèng míng shàng huì biāo zhù jiù zhěn shí jiān hé qǐng jià shí cháng duì ba？','Trên giấy có ghi rõ thời gian khám và số ngày nghỉ đúng không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L328_06','V328','医生',6,'是的，信息齐全，学校可以直接认可。','shì de， xìn xī qí quán， xué xiào kě yǐ zhí jiē rèn kě。','Đúng vậy, thông tin đầy đủ, nhà trường có thể công nhận trực tiếp.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L328_07','V328','阮明',7,'太感谢医生了！','tài gǎn xiè yī shēng le！','Tôi cảm ơn bác sĩ nhiều lắm!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT329','S111','Tự giới thiệu trong buổi sinh hoạt đầu năm',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V329','SIT329','P1','suon_se','ban_chinh_thuc',NULL,'新生自我介绍简洁谦逊即可，"多多指教"是国内年轻人社交最常用的礼貌用语。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L329_01','V329','阮明',1,'大家好，我是阮明，一名来自越南的留学生，今年22岁。','dà jiā hǎo， wǒ shì ruǎn míng， yī míng lái zì yuè nán de liú xué shēng， jīn nián 22 suì。','Chào mọi người, mình là Nguyễn Minh, du học sinh đến từ Việt Nam, năm nay mình 22 tuổi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L329_02','V329','阮明',2,'目前就读于汉语言文学专业，非常开心加入这个集体。','mù qián jiù dú yú hàn yǔ yán wén xué zhuān yè， fēi cháng kāi xīn jiā rù zhè ge jí tǐ。','Hiện tại mình đang học chuyên ngành Ngôn ngữ và Văn học Trung Quốc, rất vui khi được gia nhập tập thể mình.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L329_03','V329','阮明',3,'平时我喜欢读书和慢跑，性格比较随和开朗。','píng shí wǒ xǐ huān dú shū hé màn pǎo， xìng gé bǐ jiào suí hé kāi lǎng。','Bình thường mình thích đọc sách và chạy bộ, tính cách khá dễ gần và cởi mở.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L329_04','V329','阮明',4,'我刚来中国，对这边的学习和生活还在适应中。','wǒ gāng lái zhōng guó， duì zhè biān de xué xí hé shēng huó hái zài shì yìng zhōng。','Mình mới sang Trung Quốc nên vẫn đang dần thích nghi với việc học và cuộc sống ở đây.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L329_05','V329','阮明',5,'往后希望可以和各位同学友好相处，互相学习、多多指教。','wǎng hòu xī wàng kě yǐ hé gè wèi tóng xué yǒu hǎo xiāng chǔ， hù xiāng xué xí、 duō duō zhǐ jiào。','Sau này mong được hòa đồng với các bạn, cùng nhau học hỏi, mong mọi người chỉ bảo thêm nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L329_06','V329','辅导员',6,'欢迎阮明加入我们的大家庭！','huān yíng ruǎn míng jiā rù wǒ men de dà jiā tíng！','Chào mừng Nguyễn Minh gia nhập đại gia đình của chúng ta!',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L329_07','V329','阮明',7,'谢谢大家！','xiè xiè dà jiā！','Em cảm ơn mọi người!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT330','S111','Hỏi thông tin liên hệ để giữ kết nối',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V330','SIT330','P1','suon_se','tuy_y',NULL,'微信是国内学生唯一主流沟通工具，学习通知、日常交友、小组协作均依托微信完成。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L330_01','V330','阮明',1,'今天认识你真的太开心了！我们可以加个微信吗？','jīn tiān rèn shí nǐ zhēn de tài kāi xīn le！ wǒ men kě yǐ jiā gè wēi xìn ma？','Hôm nay quen được cậu vui thật đấy! Tụi mình kết bạn Wechat nhé?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L330_02','V330','林溪',2,'当然可以呀，以后我们就是同班同学了。','dāng rán kě yǐ ya， yǐ hòu wǒ men jiù shì tóng bān tóng xué le。','Đương nhiên là được rồi, sau này tụi mình là bạn cùng lớp mà.','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L330_03','V330','阮明',3,'太好了，我刚来这边，以后还要多向你请教呢。','tài hǎo le， wǒ gāng lái zhè biān， yǐ hòu hái yào duō xiàng nǐ qǐng jiào ne。','Tuyệt quá, mình mới đến đây, sau này còn phải nhờ cậu chỉ bảo nhiều nhé.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L330_04','V330','林溪',4,'不用客气，我们互相帮忙、共同进步。','bù yòng kè qì， wǒ men hù xiāng bāng máng、 gòng tóng jìn bù。','Khỏi khách sáo, tụi mình giúp đỡ nhau cùng tiến bộ mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L330_05','V330','阮明',5,'那我扫你的二维码加好友哈。','nà wǒ sǎo nǐ de èr wéi mǎ jiā hǎo yǒu hā。','Vậy để mình quét mã QR kết bạn với cậu nha.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L330_06','V330','林溪',6,'好嘞，以后常联系，有空一起学习！','hǎo lei， yǐ hòu cháng lián xì， yǒu kòng yì qǐ xué xí！','Ok đó, sau này liên lạc thường xuyên nhé, rảnh thì học chung!','AM08') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L330_07','V330','阮明',7,'太好啦，谢谢你！','tài hǎo la， xiè xiè nǐ！','Tuyệt vời, cảm ơn cậu nha!','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT331','S112','Mời bạn cùng lớp đi ăn',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V331','SIT331','P1','suon_se','tuy_y',NULL,'中国大学生下课常结伴去食堂就餐，主动邀约同学吃饭是很常见的社交方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L331_01','V331','阮明',1,'下课啦，等下要不要一起去食堂吃饭啊？','xià kè la， děng xià yào bù yào yì qǐ qù shí táng chī fàn a？','Tan học rồi, lát nữa cùng đi ăn ở căng tin không?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L331_02','V331','王浩',2,'可以呀，我正愁一个人吃饭没意思呢。','kě yǐ ya， wǒ zhèng chóu yí gè rén chī fàn méi yì si ne。','Được chứ, mình đang buồn vì ăn một mình chán muốn chết đây.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L331_03','V331','阮明',3,'食堂今天有米线，听说味道很不错的。','shí táng jīn tiān yǒu mǐ xiàn， tīng shuō wèi dào hěn bú cuò de。','Căng tin hôm nay có bún, nghe nói ngon lắm đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L331_04','V331','王浩',4,'刚好我也想吃米线，咱们现在就走吧。','gāng hǎo wǒ yě xiǎng chī mǐ xiàn， zán men xiàn zài jiù zǒu ba。','Đúng lúc mình cũng thèm ăn bún, đi luôn bây giờ nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L331_05','V331','阮明',5,'行，那我收拾一下书本，马上就好。','xíng， nà wǒ shōu shí yī xià shū běn， mǎ shàng jiù hǎo。','Được, để mình thu dọn sách vở tí, xong ngay thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L331_06','V331','王浩',6,'没事，我在教室门口等你就行啦。','méi shì， wǒ zài jiào shì mén kǒu děng nǐ jiù xíng la。','Không sao, mình đợi cậu ở cửa lớp là được rồi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L331_07','V331','阮明',7,'太感谢啦，有同学一起吃饭热闹多了。','tài gǎn xiè la， yǒu tóng xué yì qǐ chī fàn rè nào duō le。','Cảm ơn nhiều nha, có bạn cùng ăn vui hơn hẳn.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT332','S112','Từ chối lời mời một cách lịch sự',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V332','SIT332','P1','suon_se','tuy_y',NULL,'拒绝他人邀约时，中国人习惯说明合理理由并主动提出下次赴约，显得有礼貌不扫兴。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L332_01','V332','林晓',1,'晚上我们宿舍一起去校外吃火锅，你也来吧？','wǎn shàng wǒ men sù shè yì qǐ qù xiào wài chī huǒ guō， nǐ yě lái ba？','Tối nay phòng ký túc mình rủ nhau ra ngoài ăn lẩu, cậu cũng đi luôn nhé?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L332_02','V332','阮明',2,'真的很谢谢你邀请我，不过我今晚不行呢。','zhēn de hěn xiè xiè nǐ yāo qǐng wǒ， bù guò wǒ jīn wǎn bù xíng ne。','Thật sự cảm ơn cậu đã rủ, nhưng tối nay mình không đi được rồi.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L332_03','V332','林晓',3,'怎么啦，是有别的安排吗？','zěn me la， shì yǒu bié de ān pái ma？','Sao vậy, có việc gì khác à?','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L332_04','V332','阮明',4,'我要完成一篇汉语作文，明天就得提交的。','wǒ yào wán chéng yī piān hàn yǔ zuò wén， míng tiān jiù dé tí jiāo de。','Mình phải hoàn thành một bài văn tiếng Trung, mai phải nộp rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L332_05','V332','林晓',5,'原来是这样，学习要紧，那下次再约吧。','yuán lái shì zhè yàng， xué xí yào jǐn， nà xià cì zài yuē ba。','Ra là vậy, học hành quan trọng hơn, vậy lần sau hẹn lại nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L332_06','V332','阮明',6,'好，下次我一定主动找你们，实在抱歉啦。','hǎo， xià cì wǒ yí dìng zhǔ dòng zhǎo nǐ men， shí zài bào qiàn la。','Được, lần sau mình nhất định chủ động rủ mọi người, thật ngại quá.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L332_07','V332','林晓',7,'没关系，学习完早点休息。','méi guān xì， xué xí wán zǎo diǎn xiū xī。','Không sao đâu, học xong nhớ nghỉ ngơi sớm nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT333','S112','Xin lỗi vì đến muộn buổi hẹn',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V333','SIT333','P1','twist','ban_chinh_thuc',NULL,'与人线下见面迟到，中国人会主动诚恳道歉，还会主动提出买单、请客作为补偿。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L333_01','V333','阮明',1,'实在对不起，我路上堵车，迟到二十分钟了。','shí zài duì bù qǐ， wǒ lù shàng dǔ chē， chí dào èr shí fēn zhōng le。','Thật sự xin lỗi, mình bị kẹt xe nên trễ hai mươi phút rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L333_02','V333','陈悦',2,'没事，我也刚到一会儿，不用这么愧疚。','méi shì， wǒ yě gāng dào yī huì er， bù yòng zhè me kuì jiù。','Không sao, mình cũng vừa mới đến thôi, đừng áy náy quá vậy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L333_03','V333','阮明',3,'都怪我没提前出门，让你在这里干等啊。','dōu guài wǒ méi tí qián chū mén， ràng nǐ zài zhè lǐ gàn děng a。','Đều tại mình không ra khỏi nhà sớm hơn, để cậu phải đợi không vậy.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L333_04','V333','陈悦',4,'还好，这家咖啡店座位挺多，我先点了两杯饮品。','hái hǎo， zhè jiā kā fēi diàn zuò wèi tǐng duō， wǒ xiān diǎn le liǎng bēi yǐn pǐn。','May mà quán cà phê này khá nhiều chỗ ngồi, mình gọi trước hai ly rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L333_05','V333','阮明',5,'太不好意思了，这杯饮品我来付钱吧。','tài bù hǎo yì sī le， zhè bēi yǐn pǐn wǒ lái fù qián ba。','Ngại quá, để mình trả tiền ly nước này nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L333_06','V333','陈悦',6,'不用啦，下次见面你请我就可以咯。','bù yòng la， xià cì jiàn miàn nǐ qǐng wǒ jiù kě yǐ gē。','Khỏi cần đâu, lần sau gặp lại cậu mời mình là được rồi.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L333_07','V333','阮明',7,'好，下次我一定提前半小时出门，绝不迟到。','hǎo， xià cì wǒ yí dìng tí qián bàn xiǎo shí chū mén， jué bù chí dào。','Được, lần sau mình nhất định ra khỏi nhà sớm nửa tiếng, tuyệt đối không trễ nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT334','S112','Cảm ơn khi được giúp đỡ đặc biệt',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V334','SIT334','P1','suon_se','ban_chinh_thuc',NULL,'得到他人较大帮助后，中国人常会赠送小零食、小礼物表达谢意，不会只口头道谢。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L334_01','V334','阮明',1,'班长，这次真的太谢谢你帮我补办签证材料了。','bān zhǎng， zhè cì zhēn de tài xiè xiè nǐ bāng wǒ bǔ bàn qiān zhèng cái liào le。','Lớp trưởng ơi, lần này thật sự cảm ơn cậu đã giúp mình làm lại giấy tờ visa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L334_02','V334','周宇',2,'小事而已，留学生办理手续本来就麻烦嘛。','xiǎo shì ér yǐ， liú xué shēng bàn lǐ shǒu xù běn lái jiù má fán ma。','Chuyện nhỏ thôi mà, du học sinh làm thủ tục vốn dĩ đã phiền phức rồi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L334_03','V334','阮明',3,'要是没有你带路讲解，我肯定跑好多趟。','yào shì méi yǒu nǐ dài lù jiǎng jiě， wǒ kěn dìng pǎo hǎo duō tàng。','Nếu không có cậu dẫn đường giải thích, chắc mình phải chạy tới chạy lui bao nhiêu lần.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L334_04','V334','周宇',4,'不用放在心上，班里同学互相帮忙是应该的。','bù yòng fàng zài xīn shàng， bān lǐ tóng xué hù xiāng bāng máng shì yīng gāi de。','Đừng để bụng làm gì, bạn cùng lớp giúp đỡ nhau là chuyện nên làm mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L334_05','V334','阮明',5,'下周我买了家乡小零食，带给你尝尝吧。','xià zhōu wǒ mǎi le jiā xiāng xiǎo líng shí， dài gěi nǐ cháng cháng ba。','Tuần sau mình mua ít đồ ăn vặt quê nhà, mang đến cho cậu thử nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L334_06','V334','周宇',6,'不用这么客气，能帮上忙我也很高兴。','bù yòng zhè me kè qì， néng bāng shàng máng wǒ yě hěn gāo xìng。','Không cần khách sáo vậy đâu, giúp được cậu mình cũng thấy vui rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L334_07','V334','阮明',7,'一定要收下，不然我心里过意不去呢。','yí dìng yào shōu xià， bù rán wǒ xīn lǐ guò yì bù qù ne。','Cậu phải nhận đấy, không thì mình áy náy trong lòng lắm.','AM04') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT335','S113','Hỏi sở thích để tìm điểm chung với bạn mới',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V335','SIT335','P1','suon_se','tuy_y',NULL,'初次认识的年轻人会通过爱好聊天，找到共同兴趣能快速拉近彼此距离。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_01','V335','阮明',1,'课余时间你平时都喜欢做什么呀？','kè yú shí jiān nǐ píng shí dōu xǐ huān zuò shén me ya？','Bình thường ngoài giờ học cậu hay thích làm gì vậy?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_02','V335','苏雯',2,'我有空就会追剧、出门爬山，你呢？','wǒ yǒu kòng jiù huì zhuī jù、 chū mén pá shān， nǐ ne？','Mình rảnh thì hay xem phim, đi leo núi, còn cậu thì sao?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_03','V335','阮明',3,'我也很喜欢爬山，只是刚来还不熟悉周边路线。','wǒ yě hěn xǐ huān pá shān， zhǐ shì gāng lái hái bù shú xī zhōu biān lù xiàn。','Mình cũng rất thích leo núi, chỉ là mới đến đây nên chưa rành đường xá xung quanh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_04','V335','苏雯',4,'学校附近有一座小山，周末可以一起去的。','xué xiào fù jìn yǒu yī zuò xiǎo shān， zhōu mò kě yǐ yì qǐ qù de。','Gần trường có một ngọn núi nhỏ, cuối tuần có thể đi chung đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_05','V335','阮明',5,'太棒了，我还担心找不到同好呢。','tài bàng le， wǒ hái dān xīn zhǎo bú dào tóng hào ne。','Tuyệt quá, mình còn đang lo không tìm được ai hợp gu nữa chứ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_06','V335','苏雯',6,'那我们加个微信，周末约着一起出发吧。','nà wǒ men jiā gè wēi xìn， zhōu mò yuē zhe yì qǐ chū fā ba。','Vậy tụi mình kết bạn Wechat, cuối tuần hẹn nhau cùng đi nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_07','V335','阮明',7,'好呀，终于找到一样爱好的朋友啦。','hǎo ya， zhōng yú zhǎo dào yī yàng ài hào de péng yǒu la。','Được đó, cuối cùng cũng tìm được người bạn cùng sở thích rồi.','AM02') ON CONFLICT DO NOTHING;

