INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_01','V929','阮明',1,'班长，出游采购零食、清点人数的活我可以帮忙分担。','bān zhǎng， chū yóu cǎi gòu líng shí、 qīng diǎn rén shù de huó wǒ kě yǐ bāng máng fēn dān。','Lớp trưởng ơi, việc mua đồ ăn vặt với điểm danh số người khi đi chơi để mình phụ giúp cho.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_02','V929','班长',2,'太好了，全班三十人，清点人数很耗费精力。','tài hǎo le， quán bān sān shí rén， qīng diǎn rén shù hěn hào fèi jīng lì。','Tốt quá, cả lớp ba mươi người, điểm danh mệt lắm luôn.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_03','V929','阮明',3,'我统计所有人忌口，采购零食避开辣椒、坚果过敏原。','wǒ tǒng jì suǒ yǒu rén jì kǒu， cǎi gòu líng shí bì kāi là jiāo、 jiān guǒ guò mǐn yuán。','Mình sẽ thống kê xem ai kiêng món gì, mua đồ ăn vặt tránh ớt cay với hạt gây dị ứng.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_04','V929','班长',4,'采购费用全班AA，我把预算清单发到班级群公示。','cǎi gòu fèi yòng quán bān AA， wǒ bǎ yù suàn qīng dān fā dào bān jí qún gōng shì。','Tiền mua đồ chia đều cả lớp, mình sẽ đăng bảng dự chi lên nhóm lớp công khai.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_05','V929','阮明',5,'集合时我站队伍末尾，确保没有人掉队遗漏。','jí hé shí wǒ zhàn duì wǔ mò wěi， què bǎo méi yǒu rén diào duì yí lòu。','Lúc tập trung mình đứng cuối hàng, để chắc chắn không ai bị lạc hay sót lại.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_06','V929','班长',6,'有你分担工作，集体出游组织轻松很多。','yǒu nǐ fēn dān gōng zuò， jí tǐ chū yóu zǔ zhī qīng sōng hěn duō。','Có cậu phụ giúp, tổ chức đi chơi tập thể nhẹ nhàng hơn nhiều luôn.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_07','V929','阮明',7,'班级集体活动大家互相搭把手，出行更顺利。','bān jí jí tǐ huó dòng dà jiā hù xiāng dā bǎ shǒu， chū xíng gèng shùn lì。','Hoạt động tập thể của lớp mà, mọi người cùng giúp nhau tay một tí thì chuyến đi sẽ suôn sẻ hơn.',NULL);
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT930','SXH5','社团线下团建，协调时间冲突无法到场，提前说明并托人转达祝福',NULL,'B1');
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V930','SIT930','P1','that_bai_nhe','ban_chinh_thuc',NULL,'社团团建无法到场需要提前说明缘由，准备小礼物托人转交表达心意，体现重视社团集体、不失礼。');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_01','V930','阮明',1,'学姐，团建当天我有汉语等级考试，没办法到场参与活动。','xué jiě， tuán jiàn dàng tiān wǒ yǒu hàn yǔ děng jí kǎo shì， méi bàn fǎ dào chǎng cān yù huó dòng。','Chị ơi, hôm sinh hoạt tập thể em có kỳ thi năng lực tiếng Trung, không thể có mặt tham gia được ạ.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_02','V930','学姐',2,'团建一年只有一次，错过这次集体聚餐有点可惜。','tuán jiàn yī nián zhǐ yǒu yī cì， cuò guò zhè cì jí tǐ jù cān yǒu diǎn kě xī。','Sinh hoạt tập thể một năm chỉ có một lần, bỏ lỡ bữa liên hoan lần này thì tiếc thật đấy.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_03','V930','阮明',3,'我提前买好社团小伴手礼，托到场的同学分给大家，转达我的祝福。','wǒ tí qián mǎi hǎo shè tuán xiǎo bàn shǒu lǐ， tuō dào chǎng de tóng xué fēn gěi dà jiā， zhuǎn dá wǒ de zhù fú。','Em đã mua sẵn chút quà nhỏ của câu lạc bộ, nhờ bạn nào đi hôm đó chia lại cho mọi người, chuyển lời chúc của em tới ạ.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_04','V930','学姐',4,'心意我们收下，考试优先，学业比团建重要。','xīn yì wǒ men shōu xià， kǎo shì yōu xiān， xué yè bǐ tuán jiàn zhòng yào。','Tấm lòng của em bọn chị nhận rồi, thi cử là ưu tiên, việc học quan trọng hơn sinh hoạt tập thể mà.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_05','V930','阮明',5,'下次社团小型聚会我一定到场，补上这次缺席。','xià cì shè tuán xiǎo xíng jù huì wǒ yí dìng dào chǎng， bǔ shàng zhè cì quē xí。','Lần sinh hoạt nhỏ tiếp theo của câu lạc bộ em nhất định sẽ có mặt, để bù lại lần vắng này ạ.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_06','V930','学姐',6,'祝你等级考试顺利，不用惦记团建的事。','zhù nǐ děng jí kǎo shì shùn lì， bù yòng diàn jì tuán jiàn de shì。','Chúc em thi năng lực suôn sẻ, đừng bận tâm chuyện sinh hoạt tập thể nữa nhé.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_07','V930','阮明',7,'十分抱歉错过集体团建，麻烦学姐代为向大家致歉。','shí fēn bào qiàn cuò guò jí tǐ tuán jiàn， má fán xué jiě dài wéi xiàng dà jiā zhì qiàn。','Em thật sự xin lỗi vì bỏ lỡ buổi sinh hoạt tập thể, phiền chị nói giúp em một lời xin lỗi với mọi người ạ.',NULL);
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT931','SXH6','朋友频繁借大额现金，委婉说明自身开销，拒绝频繁借钱',NULL,'B1');
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V931','SIT931','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内朋友之间小额应急可互相周转，频繁大额借钱会明确划定边界委婉拒绝，避免金钱损耗友情。');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_01','V931','阮明',1,'你最近频繁借大额生活费，我每月家里汇款固定，结余不多。','nǐ zuì jìn pín fán jiè dà é shēng huó fèi， wǒ měi yuè jiā lǐ huì kuǎn gù dìng， jié yú bù duō。','Dạo này cậu hay mượn mình một khoản lớn tiền sinh hoạt, mỗi tháng nhà gửi tiền cho mình cố định, dư ra không nhiều đâu.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_02','V931','小杨',2,'我临时手头周转不开，才一次次找你借钱应急。','wǒ lín shí shǒu tóu zhōu zhuǎn bù kāi， cái yī cì cì zhǎo nǐ jiè qián yìng jí。','Mình đang kẹt tiền tạm thời nên mới phải hỏi mượn cậu để xoay xở gấp thôi.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_03','V931','阮明',3,'小额应急可以帮忙，但大额资金我自身学费、教材开销压力大嘛。','xiǎo é yìng jí kě yǐ bāng máng， dàn dà é zī jīn wǒ zì shēn xué fèi、 jiào cái kāi xiāo yā lì dà ma。','Khoản nhỏ khẩn cấp thì mình giúp được, chứ khoản lớn thì bản thân mình còn áp lực học phí, tiền sách vở nữa mà.','AM09');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_04','V931','小杨',4,'明白你的难处，之后我尽量自己规划开支不再频繁借钱。','míng bái nǐ de nán chǔ， zhī hòu wǒ jǐn liàng zì jǐ guī huà kāi zhī bù zài pín fán jiè qián。','Mình hiểu khó khăn của cậu, sau này mình sẽ cố tự sắp xếp chi tiêu, không mượn tiền thường xuyên nữa.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_05','V931','阮明',5,'如果是紧急看病这种急事我一定尽力帮忙，日常消费没法长期出借。','rú guǒ shì jǐn jí kàn bìng zhè zhǒng jí shì wǒ yí dìng jìn lì bāng máng， rì cháng xiāo fèi méi fǎ cháng qī chū jiè。','Nếu là chuyện khẩn cấp như đi khám bệnh gấp thì mình nhất định sẽ cố hết sức giúp, còn chi tiêu hàng ngày thì mình không thể cho mượn dài dài được.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_06','V931','小杨',6,'我理解你的边界，不会再频繁向你借大额钱款。','wǒ lǐ jiě nǐ de biān jiè， bú huì zài pín fán xiàng nǐ jiè dà é qián kuǎn。','Mình hiểu giới hạn của cậu, sẽ không mượn khoản lớn từ cậu thường xuyên nữa đâu.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_07','V931','阮明',7,'我们维持轻松的朋友关系，不用因为金钱产生隔阂。','wǒ men wéi chí qīng sōng de péng yǒu guān xì， bù yòng yīn wèi jīn qián chǎn shēng gé hé。','Tụi mình cứ giữ tình bạn thoải mái vậy thôi, đừng vì chuyện tiền bạc mà xa cách nhau nhé.',NULL);
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT932','SXH6','他人强行推销商品、邀约兼职，礼貌拉开距离明确拒绝',NULL,'B1');
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V932','SIT932','P1','suon_se','ban_chinh_thuc',NULL,'校园内推销、兼职邀约十分常见，礼貌温和但态度明确拒绝，对方不会持续纠缠。');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_01','V932','阮明',1,'不好意思，我没有购买护肤品、参与兼职的打算。','bù hǎo yì sī， wǒ méi yǒu gòu mǎi hù fū pǐn、 cān yù jiān zhí de dǎ suàn。','Xin lỗi, tôi không có ý định mua mỹ phẩm chăm sóc da hay tham gia làm thêm đâu ạ.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_02','V932','推销人员',2,'这款产品留学生用很合适，兼职还能赚取生活费。','zhè kuǎn chǎn pǐn liú xué shēng yòng hěn hé shì， jiān zhí hái néng zhuàn qǔ shēng huó fèi。','Sản phẩm này rất hợp với du học sinh, làm thêm cũng kiếm thêm được tiền sinh hoạt đấy.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_03','V932','阮明',3,'我课余全部用来复习汉语考试，没有时间做副业兼职嘛。','wǒ kè yú quán bù yòng lái fù xí hàn yǔ kǎo shì， méi yǒu shí jiān zuò fù yè jiān zhí ma。','Ngoài giờ học tôi dành hết thời gian ôn thi tiếng Trung, không có thời gian làm thêm đâu.','AM09');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_04','V932','推销人员',4,'耽误五分钟简单了解一下，不会占用你太久时间。','dān wù wǔ fēn zhōng jiǎn dān liǎo jiě yī xià， bú huì zhàn yòng nǐ tài jiǔ shí jiān。','Chỉ mất năm phút tìm hiểu qua thôi, không chiếm nhiều thời gian của bạn đâu.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_05','V932','阮明',5,'实在没有需求，我要赶回图书馆自习，先失陪了。','shí zài méi yǒu xū qiú， wǒ yào gǎn huí tú shū guǎn zì xí， xiān shī péi le。','Thật sự tôi không có nhu cầu, tôi phải về thư viện tự học gấp, xin phép đi trước ạ.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_06','V932','推销人员',6,'好吧，不打扰你学习，有需要再联系我。','hǎo ba， bù dǎ rǎo nǐ xué xí， yǒu xū yào zài lián xì wǒ。','Thôi được, không làm phiền bạn học nữa, khi nào cần thì liên hệ lại tôi nhé.','AM07');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_07','V932','阮明',7,'感谢介绍，我确实没有相关需求。','gǎn xiè jiè shào， wǒ què shí méi yǒu xiāng guān xū qiú。','Cảm ơn đã giới thiệu, nhưng tôi thật sự không có nhu cầu này.',NULL);
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT933','SXH6','很久没联系的老友，主动发消息分享日常、维系友谊',NULL,'B1');
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V933','SIT933','P1','suon_se','tuy_y',NULL,'国内友情不会因为许久不联络直接变淡，主动分享日常、约定线上聊天是维系远距离友谊常用方式。');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_01','V933','阮明',1,'好久不见，最近刷到你朋友圈，想起之前我们一起打球的日子。','hǎo jiǔ bú jiàn， zuì jìn shuā dào nǐ péng yǒu quān， xiǎng qǐ zhī qián wǒ men yì qǐ dǎ qiú de rì zi。','Lâu rồi không gặp, hôm nay lướt thấy dòng thời gian của cậu, lại nhớ những ngày mình cùng chơi bóng với nhau.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_02','V933','阿凯',2,'确实很久没聊天，你在中国留学生活还适应吗？','què shí hěn jiǔ méi liáo tiān， nǐ zài zhōng guó liú xué shēng huó hái shì yìng ma？','Đúng là lâu rồi mình chưa trò chuyện, cậu sống và học ở Trung Quốc quen chưa?',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_03','V933','阮明',3,'一切顺利，汉语进步不少，拍了很多校园风景照片。','yī qiè shùn lì， hàn yǔ jìn bù bù shǎo， pāi le hěn duō xiào yuán fēng jǐng zhào piān。','Mọi thứ đều ổn cả, tiếng Trung tiến bộ nhiều, mình còn chụp được bao nhiêu ảnh cảnh trường đẹp nữa.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_04','V933','阿凯',4,'有空周末线上视频，聊聊各自近期的学习生活。','yǒu kòng zhōu mò xiàn shàng shì pín， liáo liáo gè zì jìn qī de xué xí shēng huó。','Cuối tuần rảnh thì gọi video nói chuyện nhé, kể cho nhau nghe chuyện học hành gần đây.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_05','V933','阮明',5,'这周日晚上七点我有空，准时线上跟你聊天叙旧。','zhè zhōu rì wǎn shàng qī diǎn wǒ yǒu kòng， zhǔn shí xiàn shàng gēn nǐ liáo tiān xù jiù。','Chủ nhật tuần này bảy giờ tối mình rảnh, đúng giờ lên mạng ôn lại chuyện xưa với cậu nhé.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_06','V933','阿凯',6,'好，到时候线上碰面，多聊聊近况。','hǎo， dào shí hòu xiàn shàng pèng miàn， duō liáo liáo jìn kuàng。','Được, lúc đó gặp nhau online, tha hồ tám chuyện gần đây nha.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_07','V933','阮明',7,'许久不联系也要偶尔分享日常，别慢慢疏远。','xǔ jiǔ bù lián xì yě yào ǒu ěr fēn xiǎng rì cháng， bié màn màn shū yuǎn。','Lâu không liên lạc thì thỉnh thoảng cũng nên chia sẻ chuyện thường ngày, đừng để xa nhau dần nhé.',NULL);
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT934','SXH6','朋友过度打探家庭、生活费隐私，温和转移话题守住边界',NULL,'B1');
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V934','SIT934','P1','twist','tuy_y',NULL,'国内社交不会过度追问收入、家庭条件等隐私，若对方过度打探，温和转移话题是委婉守住边界的礼貌方式。');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_01','V934','阮明',1,'生活费够用就行，我们换个话题聊聊周末去哪游玩吧。','shēng huó fèi gòu yòng jiù xíng， wǒ men huàn gè huà tí liáo liáo zhōu mò qù nǎ yóu wán ba。','Tiền sinh hoạt đủ dùng là được rồi, mình đổi chủ đề nói chuyện cuối tuần đi đâu chơi đi.','AM07');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_02','V934','小周',2,'只是好奇问问，你家里每月给你汇多少越南盾？','zhǐ shì hào qí wèn wèn， nǐ jiā lǐ měi yuè gěi nǐ huì duō shǎo yuè nán dùn？','Tớ chỉ tò mò hỏi thôi, mỗi tháng nhà cậu gửi cho cậu bao nhiêu tiền Việt vậy?',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_03','V934','阮明',3,'各国家庭收支习惯不一样，不太习惯细说家庭财务情况嘛。','gè guó jiā tíng shōu zhī xí guàn bù yí yàng， bù tài xí guàn xì shuō jiā tíng cái wù qíng kuàng ma。','Mỗi nhà mỗi nước có thói quen chi tiêu khác nhau, mình không quen kể chi tiết chuyện tài chính gia đình lắm.','AM09');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_04','V934','小周',4,'抱歉，我不知道这是你的隐私，我之后不会再追问这类问题。','bào qiàn， wǒ bù zhī dào zhè shì nǐ de yǐn sī， wǒ zhī hòu bú huì zài zhuī wèn zhè lèi wèn tí。','Xin lỗi cậu, tớ không biết đây là chuyện riêng tư của cậu, sau này tớ sẽ không hỏi thêm mấy chuyện này nữa.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_05','V934','阮明',5,'没关系，我们聊聊校园文艺晚会的节目更有意思。','méi guān xì， wǒ men liáo liáo xiào yuán wén yì wǎn huì de jié mù gèng yǒu yì si。','Không sao đâu, mình nói chuyện về chương trình văn nghệ của trường thú vị hơn nè.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_06','V934','小周',6,'好，我们聊晚会，不聊私人家庭收支话题。','hǎo， wǒ men liáo wǎn huì， bù liáo sī rén jiā tíng shōu zhī huà tí。','Ừ, mình nói về buổi văn nghệ thôi, không bàn chuyện thu chi riêng tư nữa.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_07','V934','阮明',7,'感谢理解，各自保留一点私人空间相处更舒服。','gǎn xiè lǐ jiě， gè zì bǎo liú yì diǎn sī rén kōng jiān xiāng chǔ gèng shū fú。','Cảm ơn cậu đã hiểu, ai cũng giữ chút không gian riêng thì chơi với nhau thoải mái hơn.',NULL);
INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT935','SXH6','毕业前夕和要好的朋友约定，回国后定期线上联络',NULL,'B1');
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V935','SIT935','P1','suon_se','ban_chinh_thuc',NULL,'毕业分离时好友会主动约定长期联络方式，国内年轻人十分看重长久稳定的友谊，不会因异地轻易断联。');
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_01','V935','阮明',1,'等我毕业回越南，我们也要保持联系，不能慢慢断了往来。','děng wǒ bì yè huí yuè nán， wǒ men yě yào bǎo chí lián xì， bù néng màn màn duàn le wǎng lái。','Đợi mình tốt nghiệp về Việt Nam rồi, tụi mình vẫn phải giữ liên lạc, không thể để dần dần mất liên lạc được.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_02','V935','苏雯',2,'放心，每月固定一次线上视频，分享各自工作、生活近况。','fàng xīn， měi yuè gù dìng yī cì xiàn shàng shì pín， fēn xiǎng gè zì gōng zuò、 shēng huó jìn kuàng。','Cứ yên tâm, mỗi tháng cố định gọi video một lần, kể cho nhau nghe chuyện công việc, cuộc sống của mỗi người.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_03','V935','阮明',3,'节假日互相寄本国小特产，线上聊天弥补不能线下见面的遗憾。','jié jià rì hù xiāng jì běn guó xiǎo tè chǎn， xiàn shàng liáo tiān mí bǔ bù néng xiàn xià jiàn miàn de yí hàn。','Dịp lễ tết thì gửi cho nhau chút đặc sản quê mình, trò chuyện online để bù đắp phần nào việc không gặp trực tiếp được.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_04','V935','苏雯',4,'不管距离多远，我们的友谊不会因为回国分开变淡。','bù guǎn jù lí duō yuǎn， wǒ men de yǒu yì bú huì yīn wèi huí guó fēn kāi biàn dàn。','Dù có xa cách bao nhiêu, tình bạn của tụi mình cũng sẽ không nhạt đi vì chuyện về nước đâu.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_05','V935','阮明',5,'回国之后时差一小时，提前约定双方都空闲的视频时段。','huí guó zhī hòu shí chà yī xiǎo shí， tí qián yuē dìng shuāng fāng dōu kòng xián de shì pín shí duàn。','Sau khi về nước lệch múi giờ một tiếng, mình hẹn trước khung giờ mà cả hai đều rảnh để gọi video nhé.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_06','V935','苏雯',6,'我记好约定，毕业之后按时线上叙旧。','wǒ jì hǎo yuē dìng， bì yè zhī hòu àn shí xiàn shàng xù jiù。','Mình ghi nhớ lời hẹn rồi, sau khi tốt nghiệp sẽ đúng giờ lên mạng ôn chuyện cũ.',NULL);
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_07','V935','阮明',7,'很幸运在校期间认识你，长久维持这份跨国友谊。','hěn xìng yùn zài xiào qī jiān rèn shí nǐ， cháng jiǔ wéi chí zhè fèn kuà guó yǒu yì。','Mình thấy may mắn vì được quen cậu hồi còn đi học, mong tình bạn xuyên quốc gia này sẽ bền lâu.',NULL);
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT203','CP_M');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT204','CP_F');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT205','CP_H');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT206','CP_H');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT207','CP_H');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT214','CP_A');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT215','CP_A');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT216','CP_B');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT219','CP_C');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT220','CP_D');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT222','CP_E');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT224','CP_F');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT225','CP_B');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT226','CP_E');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT227','CP_G');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT236','CP_J');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT237','CP_B');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT238','CP_D');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT239','CP_I');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT240','CP_K');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT243','CP_C');
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT244','CP_G');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J1','Đến nơi & ổn định ban đầu','P1','Từ lúc lên máy bay đến khi ổn định chỗ ở, mở tài khoản, có SIM/thanh toán điện tử');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J2','Nhập học','P1','Báo danh, chọn môn, làm thẻ, thư viện, email/LMS, bảo hiểm, khám sức khỏe');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J3','Sinh hoạt hằng ngày','P1','Journey mở rộng: Sinh hoạt hằng ngày');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J4','Học tập','P1','Journey mở rộng: Học tập');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J5','Khám bệnh','P1','Journey mở rộng: Khám bệnh');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J6','Cuộc sống xã hội','P1','Journey mở rộng: Cuộc sống xã hội');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J7','Công nghệ','P1','Journey mở rộng: Công nghệ');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J8','Tài chính','P1','Journey mở rộng: Tài chính');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J9','Di chuyển','P1','Journey mở rộng: Di chuyển');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J10','Khẩn cấp','P1','Journey mở rộng: Khẩn cấp');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J11','Thực tập & làm thêm','P1','Journey mở rộng: Thực tập & làm thêm');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J12','Kết thúc khóa học','P1','Journey mở rộng: Kết thúc khóa học');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J13','Visa & pháp lý dài hạn','P1','Đăng ký lưu trú, gia hạn, mất giấy tờ, chuyển trường, làm thêm hợp pháp, tốt nghiệp và rời khỏi Trung Quốc');
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J14','Liên lạc với gia đình ở xa','P1','Duy trì liên lạc, báo bình an, chuyển tiền, chia sẻ đời sống, xử lý khẩn cấp và lên kế hoạch dài hạn cùng gia đình');
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_01','J1','SIT201',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_02','J1','SIT202',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_03','J1','SIT203',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_04','J1','SIT204',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_05','J1','SIT205',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_06','J1','SIT206',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_07','J1','SIT207',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_08','J1','SIT208',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_09','J1','SIT209',9);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_10','J1','SIT210',10);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_11','J1','SIT211',11);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_12','J1','SIT212',12);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_13','J1','SIT213',13);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_14','J1','SIT214',14);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_15','J1','SIT215',15);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_16','J1','SIT216',16);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_17','J1','SIT217',17);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_18','J1','SIT218',18);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_19','J1','SIT219',19);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_20','J1','SIT220',20);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_21','J1','SIT221',21);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_22','J1','SIT222',22);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_23','J1','SIT223',23);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_24','J1','SIT224',24);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_25','J1','SIT225',25);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_01','J2','SIT226',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_02','J2','SIT227',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_03','J2','SIT228',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_04','J2','SIT229',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_05','J2','SIT230',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_06','J2','SIT231',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_07','J2','SIT232',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_08','J2','SIT233',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_09','J2','SIT234',9);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_10','J2','SIT235',10);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_01','J3','SIT301',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_02','J3','SIT302',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_03','J3','SIT303',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_04','J3','SIT304',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_05','J3','SIT305',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_06','J3','SIT306',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_07','J3','SIT307',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_08','J3','SIT308',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_09','J3','SIT309',9);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_10','J3','SIT310',10);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_01','J4','SIT311',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_02','J4','SIT312',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_03','J4','SIT313',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_04','J4','SIT314',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_05','J4','SIT315',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_06','J4','SIT316',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_07','J4','SIT317',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_08','J4','SIT318',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_09','J4','SIT319',9);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_10','J4','SIT320',10);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_01','J5','SIT321',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_02','J5','SIT322',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_03','J5','SIT323',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_04','J5','SIT324',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_05','J5','SIT325',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_06','J5','SIT326',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_07','J5','SIT327',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_08','J5','SIT328',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_01','J6','SIT329',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_02','J6','SIT330',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_03','J6','SIT331',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_04','J6','SIT332',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_05','J6','SIT333',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_06','J6','SIT334',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_07','J6','SIT335',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_08','J6','SIT336',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_09','J6','SIT337',9);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_10','J6','SIT338',10);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_11','J6','SIT339',11);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_12','J6','SIT340',12);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_13','J6','SIT341',13);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_14','J6','SIT342',14);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_01','J7','SIT343',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_02','J7','SIT344',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_03','J7','SIT345',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_04','J7','SIT346',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_05','J7','SIT347',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_06','J7','SIT348',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_07','J7','SIT349',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_08','J7','SIT350',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_01','J8','SIT351',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_02','J8','SIT352',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_03','J8','SIT353',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_04','J8','SIT354',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_05','J8','SIT355',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_06','J8','SIT356',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_07','J8','SIT357',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_08','J8','SIT358',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_01','J9','SIT359',1);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_02','J9','SIT360',2);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_03','J9','SIT361',3);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_04','J9','SIT362',4);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_05','J9','SIT363',5);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_06','J9','SIT364',6);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_07','J9','SIT365',7);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_08','J9','SIT366',8);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_09','J9','SIT367',9);
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_10','J9','SIT368',10);
