INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT220','CP_D') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT222','CP_E') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT224','CP_F') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT225','CP_B') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT226','CP_E') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT227','CP_G') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT236','CP_J') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT237','CP_B') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT238','CP_D') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT239','CP_I') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT240','CP_K') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT243','CP_C') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT244','CP_G') ON CONFLICT DO NOTHING;



INSERT INTO journeys (id,name,target_persona,description) VALUES ('J1','Đến nơi & ổn định ban đầu','P1','Từ lúc lên máy bay đến khi ổn định chỗ ở, mở tài khoản, có SIM/thanh toán điện tử') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J2','Nhập học','P1','Báo danh, chọn môn, làm thẻ, thư viện, email/LMS, bảo hiểm, khám sức khỏe') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J3','Sinh hoạt hằng ngày','P1','Journey mở rộng: Sinh hoạt hằng ngày') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J4','Học tập','P1','Journey mở rộng: Học tập') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J5','Khám bệnh','P1','Journey mở rộng: Khám bệnh') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J6','Cuộc sống xã hội','P1','Journey mở rộng: Cuộc sống xã hội') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J7','Công nghệ','P1','Journey mở rộng: Công nghệ') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J8','Tài chính','P1','Journey mở rộng: Tài chính') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J9','Di chuyển','P1','Journey mở rộng: Di chuyển') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J10','Khẩn cấp','P1','Journey mở rộng: Khẩn cấp') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J11','Thực tập & làm thêm','P1','Journey mở rộng: Thực tập & làm thêm') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J12','Kết thúc khóa học','P1','Journey mở rộng: Kết thúc khóa học') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J13','Visa & pháp lý dài hạn','P1','Đăng ký lưu trú, gia hạn, mất giấy tờ, chuyển trường, làm thêm hợp pháp, tốt nghiệp và rời khỏi Trung Quốc') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J14','Liên lạc với gia đình ở xa','P1','Duy trì liên lạc, báo bình an, chuyển tiền, chia sẻ đời sống, xử lý khẩn cấp và lên kế hoạch dài hạn cùng gia đình') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J15','Du lịch & khám phá Trung Quốc','P1','Vé tàu, khách sạn, thắng cảnh, mặc cả, xử lý sự cố khi đi du lịch trong kỳ nghỉ') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J16','Học thuật nâng cao','P1','Học bổng, hội nghị khoa học, thi cao học, liên hệ giáo sư, đăng bài báo khoa học') ON CONFLICT DO NOTHING;
INSERT INTO journeys (id,name,target_persona,description) VALUES ('J17','Ẩm thực & văn hoá ẩm thực','P1','Nhà hàng cao cấp, quy tắc bàn ăn, món ăn đặc sản vùng miền, văn hoá mời khách') ON CONFLICT DO NOTHING;

INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_01','J1','SIT201',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_02','J1','SIT202',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_03','J1','SIT203',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_04','J1','SIT204',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_05','J1','SIT205',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_06','J1','SIT206',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_07','J1','SIT207',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_08','J1','SIT208',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_09','J1','SIT209',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_10','J1','SIT210',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_11','J1','SIT211',11) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_12','J1','SIT212',12) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_13','J1','SIT213',13) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_14','J1','SIT214',14) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_15','J1','SIT215',15) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_16','J1','SIT216',16) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_17','J1','SIT217',17) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_18','J1','SIT218',18) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_19','J1','SIT219',19) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_20','J1','SIT220',20) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_21','J1','SIT221',21) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_22','J1','SIT222',22) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_23','J1','SIT223',23) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_24','J1','SIT224',24) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS1_25','J1','SIT225',25) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_01','J2','SIT226',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_02','J2','SIT227',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_03','J2','SIT228',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_04','J2','SIT229',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_05','J2','SIT230',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_06','J2','SIT231',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_07','J2','SIT232',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_08','J2','SIT233',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_09','J2','SIT234',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS2_10','J2','SIT235',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_01','J3','SIT301',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_02','J3','SIT302',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_03','J3','SIT303',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_04','J3','SIT304',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_05','J3','SIT305',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_06','J3','SIT306',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_07','J3','SIT307',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_08','J3','SIT308',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_09','J3','SIT309',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J3_10','J3','SIT310',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_01','J4','SIT311',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_02','J4','SIT312',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_03','J4','SIT313',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_04','J4','SIT314',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_05','J4','SIT315',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_06','J4','SIT316',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_07','J4','SIT317',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_08','J4','SIT318',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_09','J4','SIT319',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J4_10','J4','SIT320',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_01','J5','SIT321',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_02','J5','SIT322',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_03','J5','SIT323',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_04','J5','SIT324',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_05','J5','SIT325',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_06','J5','SIT326',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_07','J5','SIT327',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J5_08','J5','SIT328',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_01','J6','SIT329',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_02','J6','SIT330',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_03','J6','SIT331',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_04','J6','SIT332',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_05','J6','SIT333',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_06','J6','SIT334',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_07','J6','SIT335',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_08','J6','SIT336',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_09','J6','SIT337',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_10','J6','SIT338',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_11','J6','SIT339',11) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_12','J6','SIT340',12) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_13','J6','SIT341',13) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J6_14','J6','SIT342',14) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_01','J7','SIT343',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_02','J7','SIT344',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_03','J7','SIT345',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_04','J7','SIT346',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_05','J7','SIT347',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_06','J7','SIT348',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_07','J7','SIT349',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J7_08','J7','SIT350',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_01','J8','SIT351',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_02','J8','SIT352',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_03','J8','SIT353',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_04','J8','SIT354',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_05','J8','SIT355',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_06','J8','SIT356',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_07','J8','SIT357',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J8_08','J8','SIT358',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_01','J9','SIT359',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_02','J9','SIT360',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_03','J9','SIT361',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_04','J9','SIT362',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_05','J9','SIT363',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_06','J9','SIT364',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_07','J9','SIT365',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_08','J9','SIT366',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_09','J9','SIT367',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J9_10','J9','SIT368',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_01','J10','SIT369',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_02','J10','SIT370',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_03','J10','SIT371',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_04','J10','SIT372',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_05','J10','SIT373',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_06','J10','SIT374',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_07','J10','SIT375',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_08','J10','SIT376',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_09','J10','SIT377',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J10_10','J10','SIT378',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_01','J11','SIT379',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_02','J11','SIT380',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_03','J11','SIT381',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_04','J11','SIT382',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_05','J11','SIT383',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_06','J11','SIT384',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_07','J11','SIT385',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_08','J11','SIT386',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_09','J11','SIT387',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_10','J11','SIT388',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_11','J11','SIT389',11) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J11_12','J11','SIT390',12) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_01','J12','SIT391',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_02','J12','SIT392',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_03','J12','SIT393',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_04','J12','SIT394',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_05','J12','SIT395',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_06','J12','SIT396',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_07','J12','SIT397',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_08','J12','SIT398',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_09','J12','SIT399',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JS_J12_10','J12','SIT400',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV1','J13','SIT501',1) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV2','J13','SIT502',2) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV3','J13','SIT503',3) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV4','J13','SIT504',4) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV5','J13','SIT505',5) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV6','J13','SIT506',6) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV7','J13','SIT507',7) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV8','J13','SIT508',8) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV9','J13','SIT509',9) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV10','J13','SIT510',10) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV11','J13','SIT511',11) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV12','J13','SIT512',12) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV13','J13','SIT513',13) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV14','J13','SIT514',14) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV15','J13','SIT515',15) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV16','J13','SIT516',16) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV17','J13','SIT517',17) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV18','J13','SIT518',18) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV19','J13','SIT519',19) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV20','J13','SIT520',20) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV21','J13','SIT521',21) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV22','J13','SIT522',22) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV23','J13','SIT523',23) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV24','J13','SIT524',24) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV25','J13','SIT525',25) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV26','J13','SIT526',26) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV27','J13','SIT527',27) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV28','J13','SIT528',28) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV29','J13','SIT529',29) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV30','J13','SIT530',30) ON CONFLICT DO NOTHING;
INSERT INTO journey_steps (id,journey_id,situation_id,step_order) VALUES ('JSV31','J13','SIT531',31) ON CONFLICT DO NOTHING;
