INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1202_04','V1202','小张',4,'不好意思啦，景区规定必须出示实体学生证件才能享受优惠。','bù hǎo yì sī la ， jǐng qū guī dìng bì xū chū shì shí tǐ xué shēng zhèng jiàn cái néng xiǎng shòu yōu huì 。','Xin lỗi bạn nhé, quy định khu du lịch là phải xuất trình thẻ sinh viên bản gốc mới được hưởng ưu đãi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1202_05','V1202','阮明',5,'那出示手机里证件照片也不行吗？','nà chū shì shǒu jī lǐ zhèng jiàn zhào piān yě bù xíng ma ？','Vậy cho xem ảnh chụp giấy tờ trong điện thoại cũng không được ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1202_06','V1202','小张',6,'不行哦，照片无法核实原件，只能购买全价成人票咯。','bù xíng ó ， zhào piān wú fǎ hé shí yuán jiàn ， zhǐ néng gòu mǎi quán jià chéng rén piào gē 。','Không được đâu, ảnh chụp không thể xác minh được bản gốc, bạn chỉ có thể mua vé người lớn giá đầy đủ thôi.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1202_07','V1202','阮明',7,'好吧，那我买一张全价票，下次出门一定记得带证件。','hǎo ba ， nà wǒ mǎi yī zhāng quán jià piào ， xià cì chū mén yí dìng jì de dài zhèng jiàn 。','Thôi được, vậy em mua một vé giá đầy đủ vậy, lần sau ra ngoài nhất định phải nhớ mang giấy tờ.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1203','SDL1','民宿前台办理入住，房东要求登记外籍护照',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1203','SIT1203','P1','suon_se','tuy_y',NULL,'国内民宿、酒店法律规定外籍入住必须实名登记护照，同步上传公安系统。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1203_01','V1203','王阿姨',1,'小伙子来啦，提前预约好房间了吧？','xiǎo huǒ zi lái la ， tí qián yù yuē hǎo fáng jiān le ba ？','Cháu đến rồi à, đặt phòng trước rồi chứ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1203_02','V1203','阮明',2,'是的阿姨，我叫阮明，今天过来办理入住啦。','shì de ā yí ， wǒ jiào ruǎn míng ， jīn tiān guò lái bàn lǐ rù zhù la 。','Vâng ạ cô, cháu tên Nguyễn Minh, hôm nay đến làm thủ tục nhận phòng ạ.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1203_03','V1203','王阿姨',3,'外籍客人要登记护照信息哦，把护照给我复印一下行吗？','wài jí kè rén yào dēng jì hù zhào xìn xī ó ， bǎ hù zhào gěi wǒ fù yìn yī xià xíng ma ？','Khách nước ngoài phải đăng ký thông tin hộ chiếu đó, đưa hộ chiếu cho cô photo một chút nhé?','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1203_04','V1203','阮明',4,'没问题，护照在这里，登记大概要多久啊？','méi wèn tí ， hù zhào zài zhè lǐ ， dēng jì dà gài yào duō jiǔ a ？','Dạ được, hộ chiếu đây ạ, đăng ký khoảng bao lâu vậy cô?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1203_05','V1203','王阿姨',5,'几分钟就搞定啦，登记完我把房门钥匙给你。','jǐ fēn zhōng jiù gǎo dìng la ， dēng jì wán wǒ bǎ fáng mén yào shi gěi nǐ 。','Vài phút là xong thôi, đăng ký xong cô đưa chìa khóa phòng cho cháu.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1203_06','V1203','阮明',6,'辛苦您啦，请问房间WiFi密码是多少呢？','xīn kǔ nín la ， qǐng wèn fáng jiān WiFi mì mǎ shì duō shǎo ne ？','Cô vất vả rồi ạ, cho cháu hỏi mật khẩu WiFi phòng là gì ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1203_07','V1203','王阿姨',7,'密码贴在房间门后，有任何事直接微信喊我就行咯。','mì mǎ tiē zài fáng jiān mén hòu ， yǒu rèn hé shì zhí jiē wēi xìn hǎn wǒ jiù xíng gē 。','Mật khẩu dán ở sau cửa phòng đó, có việc gì cứ nhắn WeChat gọi cô là được.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1204','SDL1','旅游景区迷路，向本地中老年路人问路',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1204','SIT1204','P1','suon_se','tuy_y',NULL,'国内中老年路人大多热心指路，聊天时常会主动夸赞外国人中文，拉近距离。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1204_01','V1204','阮明',1,'大爷您好，打扰一下，请问山顶观景台往哪边走呀？','dà yé nín hǎo ， dǎ rǎo yī xià ， qǐng wèn shān dǐng guān jǐng tái wǎng nǎ biān zǒu ya ？','Chào ông ạ, làm phiền ông một chút, cho cháu hỏi đài ngắm cảnh trên đỉnh núi đi hướng nào ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1204_02','V1204','大爷',2,'小伙子是外国来的留学生吧，普通话讲得挺标准嘛！','xiǎo huǒ zi shì wài guó lái de liú xué shēng ba ， pǔ tōng huà jiǎng dé tǐng biāo zhǔn ma ！','Cậu là du học sinh nước ngoài đúng không, nói tiếng phổ thông chuẩn ghê!','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1204_03','V1204','阮明',3,'谢谢您夸奖，我来中国读书两年啦，今天第一次来这个景区。','xiè xiè nín kuā jiǎng ， wǒ lái zhōng guó dú shū liǎng nián la ， jīn tiān dì yī cì lái zhè ge jǐng qū 。','Cảm ơn ông khen ạ, cháu sang Trung Quốc học đã hai năm rồi, hôm nay là lần đầu cháu đến khu du lịch này.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1204_04','V1204','大爷',4,'你顺着这条石板路一直往上走，看见红色亭子右转就是咯。','nǐ shùn zhe zhè tiáo shí bǎn lù yì zhí wǎng shàng zǒu ， kàn jiàn hóng sè tíng zi yòu zhuǎn jiù shì gē 。','Cậu cứ theo con đường lát đá này đi thẳng lên, thấy cái đình màu đỏ thì rẽ phải là tới.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1204_05','V1204','阮明',5,'大概还要走多久才能到呢？','dà gài hái yào zǒu duō jiǔ cái néng dào ne ？','Còn phải đi khoảng bao lâu nữa mới tới ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1204_06','V1204','大爷',6,'二十分钟左右，路上台阶有点陡，慢慢走别着急哈。','èr shí fēn zhōng zuǒ yòu ， lù shàng tái jiē yǒu diǎn dǒu ， màn màn zǒu bié zháo jí hā 。','Khoảng hai mươi phút, đường có mấy bậc thang hơi dốc, cứ đi từ từ đừng vội nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1204_07','V1204','阮明',7,'太感谢您啦，不然我还要绕好久弯路呢。','tài gǎn xiè nín la ， bù rán wǒ hái yào rào hǎo jiǔ wān lù ne 。','Cháu cảm ơn ông nhiều lắm, không thì cháu còn phải đi vòng vèo lâu lắm.','AM04') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1205','SDL1','网红小吃店排队点餐，看不懂中文手写菜单',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1205','SIT1205','P1','twist','tuy_y',NULL,'街边小店多用手写毛笔菜单，字体潦草，外国游客看不懂很常见，店员一般会耐心介绍菜品。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1205_01','V1205','阮明',1,'你好，墙上手写菜单我好多字看不懂，可以给我推荐招牌吗？','nǐ hǎo ， qiáng shàng shǒu xiě cài dān wǒ hǎo duō zì kàn bù dǒng ， kě yǐ gěi wǒ tuī jiàn zhāo pái ma ？','Chào bạn, thực đơn viết tay trên tường mình không hiểu nhiều chữ lắm, bạn giới thiệu giúp mình món đặc trưng được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1205_02','V1205','小林',2,'当然可以啦，咱们店招牌酸辣粉、红糖糍粑都很好卖的。','dāng rán kě yǐ la ， zán men diàn zhāo pái suān là fěn 、 hóng táng cí bā dōu hěn hǎo mài de 。','Được chứ, quán mình món tủ là mì chua cay và bánh nếp đường đỏ đều bán chạy lắm.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1205_03','V1205','阮明',3,'酸辣粉会不会特别辣呀，我不太能吃辣呢。','suān là fěn huì bú huì tè bié là ya ， wǒ bù tài néng chī là ne 。','Mì chua cay có cay lắm không, mình không ăn cay giỏi lắm.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1205_04','V1205','小林',4,'没关系嘛，我可以给你做微辣，几乎没什么辣味。','méi guān xì ma ， wǒ kě yǐ gěi nǐ zuò wēi là ， jī hū méi shén me là wèi 。','Không sao đâu, mình có thể làm cho bạn vị hơi cay thôi, gần như không cay mấy.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1205_05','V1205','阮明',5,'那我一份微辣酸辣粉，再加一份糍粑吧。','nà wǒ yī fèn wēi là suān là fěn ， zài jiā yī fèn cí bā ba 。','Vậy cho mình một phần mì chua cay hơi cay, thêm một phần bánh nếp nữa nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1205_06','V1205','小林',6,'好嘞，一共二十二元，扫码付款就行啦。','hǎo lei ， yī gòng èr shí èr yuán ， sǎo mǎ fù kuǎn jiù xíng la 。','Được luôn, tổng cộng hai mươi hai tệ, quét mã thanh toán là xong.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1205_07','V1205','阮明',7,'麻烦稍微快一点哦，我等下还要去逛隔壁古街。','má fán shāo wēi kuài yì diǎn ó ， wǒ děng xià hái yào qù guàng gé bì gǔ jiē 。','Phiền bạn làm nhanh giúp mình chút nhé, lát nữa mình còn phải đi dạo phố cổ bên cạnh.','AM03') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1206','SDL1','景区卫生间找不到，询问保洁阿姨',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1206','SIT1206','P1','suon_se','tuy_y',NULL,'国内公立景区公共卫生间全部免费，街边部分私人厕所才会收费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1206_01','V1206','阮明',1,'阿姨不好意思，想问一下洗手间在哪里呀？','ā yí bù hǎo yì sī ， xiǎng wèn yī xià xǐ shǒu jiān zài nǎ lǐ ya ？','Cô ơi cho cháu hỏi, nhà vệ sinh ở đâu vậy ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1206_02','V1206','刘阿姨',2,'往前直走五十米，大树旁边那个小房子就是啦。','wǎng qián zhí zǒu wǔ shí mǐ ， dà shù páng biān nà ge xiǎo fáng zi jiù shì la 。','Đi thẳng về phía trước năm mươi mét, cái nhà nhỏ cạnh cây to đó là đúng rồi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1206_03','V1206','阮明',3,'是免费使用的卫生间吗，要不要扫码付费呢？','shì miǎn fèi shǐ yòng de wèi shēng jiān ma ， yào bù yào sǎo mǎ fù fèi ne ？','Đây là nhà vệ sinh miễn phí phải không cô, có cần quét mã trả tiền không ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1206_04','V1206','刘阿姨',4,'景区里面卫生间全都免费，不用花钱的哈。','jǐng qū lǐ miàn wèi shēng jiān quán dōu miǎn fèi ， bù yòng huā qián de hā 。','Nhà vệ sinh trong khu du lịch đều miễn phí hết, không cần trả tiền đâu.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1206_05','V1206','阮明',5,'太谢谢您啦，我找半天都没看见指示牌呢。','tài xiè xiè nín la ， wǒ zhǎo bàn tiān dōu méi kàn jiàn zhǐ shì pái ne 。','Cháu cảm ơn cô nhiều lắm, cháu tìm mãi mà không thấy biển chỉ dẫn gì cả.','AM04') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1207','SDL1','乘坐市内旅游公交，不会刷外籍电子乘车码',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1207','SIT1207','P1','twist','ban_chinh_thuc',NULL,'国内公交电子乘车码大多绑定国内手机号、银行卡，外籍游客很难直接开通，现金零钱是备用方案。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1207_01','V1207','阮明',1,'师傅您好，我的手机弄不出乘车码，刷不了车怎么办啊？','shī fù nín hǎo ， wǒ de shǒu jī nòng bù chū chéng chē mǎ ， shuā bù liǎo chē zěn me bàn a ？','Chào bác tài, điện thoại em không hiện được mã lên xe, không quẹt được thì phải làm sao ạ?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1207_02','V1207','陈师傅',2,'小伙子是外国留学生吧，没有国内银行卡办不了乘车码呢。','xiǎo huǒ zi shì wài guó liú xué shēng ba ， méi yǒu guó nèi yín háng kǎ bàn bù liǎo chéng chē mǎ ne 。','Cậu là du học sinh nước ngoài đúng không, không có thẻ ngân hàng trong nước thì không làm được mã lên xe đâu.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1207_03','V1207','阮明',3,'那我只能投现金吗，我身上只有一百块的纸币，没有零钱。','nà wǒ zhǐ néng tóu xiàn jīn ma ， wǒ shēn shàng zhǐ yǒu yì bǎi kuài de zhǐ bì ， méi yǒu líng qián 。','Vậy em chỉ có thể bỏ tiền mặt thôi ạ, em chỉ có tờ một trăm tệ, không có tiền lẻ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1207_04','V1207','陈师傅',4,'公交不找零哦，前面站台有便利店，你去换两块零钱再来吧。','gōng jiāo bù zhǎo líng ó ， qián miàn zhàn tái yǒu biàn lì diàn ， nǐ qù huàn liǎng kuài líng qián zài lái ba 。','Xe buýt không thối tiền đâu, phía trước có trạm có cửa hàng tiện lợi, cậu qua đó đổi vài đồng tiền lẻ rồi quay lại nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1207_05','V1207','阮明',5,'可是车马上要开了，我赶时间去博物馆呢。','kě shì chē mǎ shàng yào kāi le ， wǒ gǎn shí jiān qù bó wù guǎn ne 。','Nhưng xe sắp chạy rồi ạ, em đang gấp giờ đi bảo tàng.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1207_06','V1207','陈师傅',6,'没关系，这次你先上车，下次提前备好零钱就行啦。','méi guān xì ， zhè cì nǐ xiān shàng chē ， xià cì tí qián bèi hǎo líng qián jiù xíng la 。','Không sao, lần này cậu cứ lên xe trước đi, lần sau chuẩn bị sẵn tiền lẻ là được.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1207_07','V1207','阮明',7,'太感谢您了，下次我一定提前换好零钱。','tài gǎn xiè nín le ， xià cì wǒ yí dìng tí qián huàn hǎo líng qián 。','Em cảm ơn bác nhiều lắm, lần sau em nhất định sẽ đổi sẵn tiền lẻ trước.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1208','SDL1','古镇街边小店想买手工纪念品，和老板砍价',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1208','SIT1208','P1','suon_se','tuy_y',NULL,'古镇小商品店铺都可以议价，明码标价商场不能砍价，街边小店默认对半还价再协商。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1208_01','V1208','阮明',1,'老板，这个木雕小摆件多少钱一个呀？','lǎo bǎn ， zhè ge mù diāo xiǎo bǎi jiàn duō shǎo qián yí gè ya ？','Anh chủ ơi, cái tượng gỗ chạm nhỏ này bao nhiêu tiền một cái vậy?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1208_02','V1208','老周',2,'原价八十，喜欢的话给你算七十吧。','yuán jià bā shí ， xǐ huān de huà gěi nǐ suàn qī shí ba 。','Giá gốc tám mươi, nếu thích thì tính cho cậu bảy mươi vậy.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1208_03','V1208','阮明',3,'七十有点贵咯，五十块我直接拿两个行不行？','qī shí yǒu diǎn guì gē ， wǔ shí kuài wǒ zhí jiē ná liǎng gè xíng bù xíng ？','Bảy mươi hơi đắt đó, năm mươi tệ em lấy luôn hai cái được không anh?','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1208_04','V1208','老周',4,'小伙子还挺会砍价，五十本钱都不够，六十两个给你啦。','xiǎo huǒ zi hái tǐng huì kǎn jià ， wǔ shí běn qián dōu bù gòu ， liù shí liǎng gè gěi nǐ la 。','Cậu này mặc cả giỏi thật đấy, năm mươi thì không đủ vốn đâu, sáu mươi hai cái tính cho cậu vậy.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1208_05','V1208','阮明',5,'六十可以，我多拿一个送给国内同学嘛。','liù shí kě yǐ ， wǒ duō ná yí gè sòng gěi guó nèi tóng xué ma 。','Sáu mươi được đó, em lấy thêm một cái để tặng bạn học người Trung Quốc.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1208_06','V1208','老周',6,'行嘞，我给你包装好看一点，送人有面子哈。','xíng lei ， wǒ gěi nǐ bāo zhuāng hǎo kàn yì diǎn ， sòng rén yǒu miàn zi hā 。','Được luôn, anh gói cho cậu đẹp một chút, tặng người ta cho có mặt mũi.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1208_07','V1208','阮明',7,'麻烦您啦，以后我带同学再来光顾您小店。','má fán nín la ， yǐ hòu wǒ dài tóng xué zài lái guāng gù nín xiǎo diàn 。','Cảm ơn anh nhiều ạ, sau này em sẽ dẫn bạn học đến ủng hộ tiệm anh nữa.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1209','SDL1','预约博物馆线上门票，选错参观日期无法入场',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1209','SIT1209','P1','that_bai_nhe','ban_chinh_thuc',NULL,'公立博物馆免费预约票严格限定参观日期，过期作废，不支持改签、退票。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1209_01','V1209','阮明',1,'您好，我扫码检票怎么显示门票日期不对呢？','nín hǎo ， wǒ sǎo mǎ jiǎn piào zěn me xiǎn shì mén piào rì qī bú duì ne ？','Chào chị, em quét mã kiểm vé sao cứ hiện ngày trên vé không đúng vậy ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1209_02','V1209','小吴',2,'我帮你看一下，你预约的是昨天的票，今天已经过期啦。','wǒ bāng nǐ kàn yī xià ， nǐ yù yuē de shì zuó tiān de piào ， jīn tiān yǐ jīng guò qī la 。','Để chị xem cho nhé, vé em đặt là của ngày hôm qua, hôm nay hết hạn rồi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1209_03','V1209','阮明',3,'哎呀，我昨天记错时间没来，以为门票可以改期呢。','āi yā ， wǒ zuó tiān jì cuò shí jiān méi lái ， yǐ wéi mén piào kě yǐ gǎi qī ne 。','Ôi, hôm qua em nhớ nhầm giờ nên không đến, cứ tưởng vé đổi ngày được cơ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1209_04','V1209','小吴',4,'博物馆线上预约票一旦选定日期不能更改，过期直接作废咯。','bó wù guǎn xiàn shàng yù yuē piào yí dàn xuǎn dìng rì qī bù néng gēng gǎi ， guò qī zhí jiē zuò fèi gē 。','Vé đặt online của bảo tàng một khi đã chọn ngày là không đổi được đâu, hết hạn là hủy luôn.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1209_05','V1209','阮明',5,'那我现在能现场重新买票进去参观吗？','nà wǒ xiàn zài néng xiàn chǎng chóng xīn mǎi piào jìn qù cān guān ma ？','Vậy giờ em có thể mua vé tại chỗ để vào tham quan không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1209_06','V1209','小吴',6,'今天名额已经约满，只能明天再来预约啦。','jīn tiān míng é yǐ jīng yuē mǎn ， zhǐ néng míng tiān zài lái yù yuē la 。','Suất hôm nay kín chỗ hết rồi, em chỉ có thể mai quay lại đặt vé thôi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1209_07','V1209','阮明',7,'好吧，都怪我自己粗心看错日期，明天我一定记准时间。','hǎo ba ， dōu guài wǒ zì jǐ cū xīn kàn cuò rì qī ， míng tiān wǒ yí dìng jì zhǔn shí jiān 。','Thôi vậy, tại em bất cẩn xem nhầm ngày, mai em sẽ nhớ kỹ giờ giấc.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1210','SDL1','爬山途中下雨，在山顶小卖部临时买雨衣',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1210','SIT1210','P1','suon_se','tuy_y',NULL,'山顶、景区制高点商品运输困难，物价普遍高于市区，属于正常现象。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1210_01','V1210','阮明',1,'老板娘，外面突然下雨啦，一次性雨衣多少钱一件？','lǎo bǎn niáng ， wài miàn tū rán xià yǔ la ， yí cì xìng yǔ yī duō shǎo qián yī jiàn ？','Cô ơi, bên ngoài trời mưa bất chợt quá, áo mưa dùng một lần bao nhiêu tiền một cái vậy cô?','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1210_02','V1210','老板娘',2,'山上雨水大，雨衣十元一件，质量厚实不容易破哦。','shān shàng yǔ shuǐ dà ， yǔ yī shí yuán yī jiàn ， zhì liàng hòu shí bù róng yì pò ó 。','Trên núi mưa to lắm, áo mưa mười tệ một cái, chất dày dặn không dễ rách đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1210_03','V1210','阮明',3,'给我来两件吧，等下下山山路滑，怕淋湿手机。','gěi wǒ lái liǎng jiàn ba ， děng xià xià shān shān lù huá ， pà lín shī shǒu jī 。','Cô cho cháu lấy hai cái đi, lát xuống núi đường trơn, cháu sợ ướt điện thoại.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1210_04','V1210','老板娘',4,'好嘞，两件二十，雨衣口袋还能装手机呢。','hǎo lei ， liǎng jiàn èr shí ， yǔ yī kǒu dài hái néng zhuāng shǒu jī ne 。','Được rồi, hai cái hai mươi tệ, túi áo mưa còn để vừa điện thoại đấy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1210_05','V1210','阮明',5,'山顶东西价格比山下贵好多，没办法应急只能买啦。','shān dǐng dōng xī jià gé bǐ shān xià guì hǎo duō ， méi bàn fǎ yìng jí zhǐ néng mǎi la 。','Đồ trên đỉnh núi giá đắt hơn dưới chân núi nhiều thật, nhưng cần gấp nên đành mua thôi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1210_06','V1210','老板娘',6,'山上运输不方便，成本高一点，多多理解哈。','shān shàng yùn shū bù fāng biàn ， chéng běn gāo yì diǎn ， duō duō lǐ jiě hā 。','Trên núi vận chuyển bất tiện, chi phí cao hơn một chút, mong cháu thông cảm nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1210_07','V1210','阮明',7,'没关系，谢谢您，这下下山不会淋雨咯。','méi guān xì ， xiè xiè nín ， zhè xià xià shān bú huì lín yǔ gē 。','Không sao đâu cô, cảm ơn cô, lần này xuống núi khỏi lo bị ướt mưa rồi.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1211','SDL1','打车去景点，司机听不懂地名开错路线',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1211','SIT1211','P1','twist','ban_chinh_thuc',NULL,'网约车司机走错路线，多出路费一般由司机自行承担，乘客无需额外付费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1211_01','V1211','阮明',1,'师傅，我要去城南古戏台景区，导航定位发给您啦。','shī fù ， wǒ yào qù chéng nán gǔ xì tái jǐng qū ， dǎo háng dìng wèi fā gěi nín la 。','Anh ơi, em muốn đến khu du lịch sân khấu cổ ở phía nam thành phố, em gửi định vị chỉ đường cho anh rồi ạ.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1211_02','V1211','赵师傅',2,'我看看，这地方名字有点绕，我刚才开岔路口咯。','wǒ kàn kàn ， zhè dì fāng míng zì yǒu diǎn rào ， wǒ gāng cái kāi chà lù kǒu gē 。','Để anh xem, tên chỗ này hơi rối, vừa nãy anh chạy nhầm ngã rẽ rồi.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1211_03','V1211','阮明',3,'那现在绕回去会不会耽误很久啊，我预约了下午的讲解。','nà xiàn zài rào huí qù huì bú huì dān wù hěn jiǔ a ， wǒ yù yuē le xià wǔ de jiǎng jiě 。','Vậy giờ vòng lại có mất nhiều thời gian không ạ, em có hẹn giờ nghe thuyết minh buổi chiều.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1211_04','V1211','赵师傅',4,'放心，绕路不远，十分钟就能到，多出来的路费算我的。','fàng xīn ， rào lù bù yuǎn ， shí fēn zhōng jiù néng dào ， duō chū lái de lù fèi suàn wǒ de 。','Yên tâm đi, đường vòng không xa đâu, mười phút là tới, tiền cước phát sinh anh chịu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1211_05','V1211','阮明',5,'不用您承担全部，咱们一人一半也行吧？','bù yòng nín chéng dān quán bù ， zán men yī rén yí bàn yě xíng ba ？','Không cần anh chịu hết đâu, hay mình chia đôi vậy được không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1211_06','V1211','赵师傅',6,'不用不用，是我没看清定位，不能多收你的钱嘛。','bù yòng bù yòng ， shì wǒ méi kàn qīng dìng wèi ， bù néng duō shōu nǐ de qián ma 。','Thôi khỏi khỏi, tại anh xem định vị không kỹ, không thể thu thêm tiền của em được.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1211_07','V1211','阮明',7,'您人真好，下次打车我还会选您的车。','nín rén zhēn hǎo ， xià cì dǎ chē wǒ hái huì xuǎn nín de chē 。','Anh tốt bụng quá, lần sau đi taxi em sẽ chọn xe anh nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1212','SDL1','景区文创店商品破损，申请更换新品',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1212','SIT1212','P1','suon_se','ban_chinh_thuc',NULL,'线下实体店当日未使用破损商品，凭购物小票大多支持免费更换，无小票很难售后。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1212_01','V1212','阮明',1,'你好，我刚买单的陶瓷书签边缘裂了，能换一个吗？','nǐ hǎo ， wǒ gāng mǎi dān de táo cí shū qiān biān yuán liè le ， néng huàn yí gè ma ？','Chào chị, thẻ đánh dấu sách bằng gốm em vừa thanh toán bị nứt ở mép, đổi cái khác được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1212_02','V1212','小苏',2,'先给我看看破损的地方，还有购物小票带来了吧？','xiān gěi wǒ kàn kàn pò sǔn de dì fāng ， hái yǒu gòu wù xiǎo piào dài lái le ba ？','Em cho chị xem chỗ bị hỏng trước đã, với lại em có mang theo hóa đơn mua hàng không?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1212_03','V1212','阮明',3,'小票在这里，我刚拆开包装就发现坏掉啦，还没带出店铺呢。','xiǎo piào zài zhè lǐ ， wǒ gāng chāi kāi bāo zhuāng jiù fā xiàn huài diào la ， hái méi dài chū diàn pù ne 。','Hóa đơn đây ạ, em vừa mở gói ra là thấy hỏng rồi, còn chưa mang ra khỏi cửa hàng nữa.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1212_04','V1212','小苏',4,'原来是运输磕碰造成的，没关系，我给你拿全新的一款吧。','yuán lái shì yùn shū kē pèng zào chéng de ， méi guān xì ， wǒ gěi nǐ ná quán xīn de yī kuǎn ba 。','Thì ra là do va đập lúc vận chuyển, không sao, để chị lấy cho em một cái mới hoàn toàn nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1212_05','V1212','阮明',5,'太好啦，我还担心不能退换，白花钱了呢。','tài hǎo la ， wǒ hái dān xīn bù néng tuì huàn ， bái huā qián le ne 。','May quá, em còn lo không đổi được, phí tiền oan.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1212_06','V1212','小苏',6,'店内商品当天破损凭小票都能换，放心哈。','diàn nèi shāng pǐn dàng tiān pò sǔn píng xiǎo piào dōu néng huàn ， fàng xīn hā 。','Hàng trong cửa hàng nếu hỏng trong ngày, có hóa đơn là đổi được hết, em yên tâm nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1212_07','V1212','阮明',7,'麻烦你啦，这款文创我特别喜欢，还好能换新。','má fán nǐ la ， zhè kuǎn wén chuàng wǒ tè bié xǐ huān ， hái hǎo néng huàn xīn 。','Phiền chị rồi ạ, món đồ lưu niệm này em thích lắm, may mà đổi được cái mới.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1213','SDL1','街边面馆点餐，不清楚本地面食辣度分级',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1213','SIT1213','P1','twist','tuy_y',NULL,'中式面馆辣度分微辣、中辣、特辣，点餐时可以主动要求少油少辣，老板会按需调整。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1213_01','V1213','阮明',1,'老板，来一碗牛肉拉面，微辣是放多少辣椒啊？','lǎo bǎn ， lái yī wǎn niú ròu lā miàn ， wēi là shì fàng duō shǎo là jiāo a ？','Chú ơi, cho một tô mì bò kéo tay, cay nhẹ là bỏ bao nhiêu ớt vậy chú?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1213_02','V1213','李叔',2,'微辣只放一勺辣椒油，中辣三勺，特辣满碗都是哦。','wēi là zhǐ fàng yī sháo là jiāo yóu ， zhōng là sān sháo ， tè là mǎn wǎn dōu shì ó 。','Cay nhẹ chỉ bỏ một muỗng dầu ớt thôi, cay vừa ba muỗng, cay đặc biệt thì đầy tô luôn đó.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1213_03','V1213','阮明',3,'我不太能吃辣，那就微辣，一点辣椒都别多放嘛。','wǒ bù tài néng chī là ， nà jiù wēi là ， yì diǎn là jiāo dōu bié duō fàng ma 。','Cháu không ăn cay được mấy, vậy cho cay nhẹ thôi, ớt cũng đừng bỏ nhiều nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1213_04','V1213','李叔',4,'明白啦，我给你少放，要不要加一份煎蛋呢？','míng bái la ， wǒ gěi nǐ shǎo fàng ， yào bù yào jiā yī fèn jiān dàn ne ？','Được rồi, chú bỏ ít cho, cháu có muốn thêm một quả trứng ốp la không?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1213_05','V1213','阮明',5,'加一个煎蛋，面条煮软一点行不行？','jiā yí gè jiān dàn ， miàn tiáo zhǔ ruǎn yì diǎn xíng bù xíng ？','Cho cháu thêm một quả trứng ốp la, mì luộc mềm hơn chút được không chú?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1213_06','V1213','李叔',6,'没问题，面煮软一点适合外国朋友吃，马上给你做咯。','méi wèn tí ， miàn zhǔ ruǎn yì diǎn shì hé wài guó péng yǒu chī ， mǎ shàng gěi nǐ zuò gē 。','Không thành vấn đề, mì mềm hơn hợp với người nước ngoài ăn, chú làm ngay cho cháu đây.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1213_07','V1213','阮明',7,'谢谢老板，等下吃完我还要去逛老街。','xiè xiè lǎo bǎn ， děng xià chī wán wǒ hái yào qù guàng lǎo jiē 。','Cảm ơn chú, lát ăn xong cháu còn phải đi dạo phố cổ nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1214','SDL1','森林公园徒步，半路丢失随身背包求助保安',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1214','SIT1214','P1','twist','ban_chinh_thuc',NULL,'国内公园、景区保安有巡逻寻物职责，遗失证件优先找安保，比报警处理更快。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_01','V1214','阮明',1,'保安大哥，我徒步丢了背包，里面有护照手机，帮帮我吧！','bǎo ān dà gē ， wǒ tú bù diū le bēi bāo ， lǐ miàn yǒu hù zhào shǒu jī ， bāng bāng wǒ ba ！','Anh bảo vệ ơi, em đi bộ đường dài bị mất balo rồi, trong đó có hộ chiếu với điện thoại, giúp em với!','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_02','V1214','老王',2,'别慌，你大概在哪个路段弄丢的，背包是什么颜色呢？','bié huāng ， nǐ dà gài zài nǎ ge lù duàn nòng diū de ， bēi bāo shì shén me yán sè ne ？','Đừng hoảng, em nhớ đại khái là mất ở đoạn đường nào, balo màu gì vậy?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_03','V1214','阮明',3,'十分钟前在木栈道休息区，黑色双肩包，有白色挂饰。','shí fēn zhōng qián zài mù zhàn dào xiū xī qū ， hēi sè shuāng jiān bāo ， yǒu bái sè guà shì 。','Mười phút trước ở khu nghỉ chân trên đường ván gỗ, balo hai quai màu đen, có móc treo màu trắng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_04','V1214','老王',4,'我联系巡逻同事去那段路查找，你在这里等我消息行吗？','wǒ lián xì xún luó tóng shì qù nà duàn lù chá zhǎo ， nǐ zài zhè lǐ děng wǒ xiāo xī xíng ma ？','Anh sẽ liên hệ đồng nghiệp tuần tra đến đoạn đó tìm giúp, em đợi tin ở đây được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_05','V1214','阮明',5,'好，我不敢走远，护照丢了补办特别麻烦呢。','hǎo ， wǒ bù gǎn zǒu yuǎn ， hù zhào diū le bǔ bàn tè bié má fán ne 。','Dạ được, em không dám đi xa, hộ chiếu mất làm lại phiền phức lắm ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_06','V1214','老王',6,'园区游客丢东西很常见，大概率能找到，先别着急哈。','yuán qū yóu kè diū dōng xī hěn cháng jiàn ， dà gài lǜ néng zhǎo dào ， xiān bié zháo jí hā 。','Khách tham quan làm mất đồ ở khu này cũng thường gặp thôi, khả năng cao là tìm lại được, em đừng lo lắng quá.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_07','V1214','阮明',7,'真的拜托您了，如果找回来我一定好好感谢你们。','zhēn de bài tuō nín le ， rú guǒ zhǎo huí lái wǒ yí dìng hǎo hǎo gǎn xiè nǐ men 。','Thật sự cảm ơn anh nhiều, nếu tìm lại được em nhất định sẽ cảm ơn mọi người thật chu đáo.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1214_08','V1214','老王',8,'分内工作不用客气，有消息我马上喊你。','fèn nèi gōng zuò bù yòng kè qì ， yǒu xiāo xī wǒ mǎ shàng hǎn nǐ 。','Đây là việc trong trách nhiệm của anh mà, không cần khách sáo, có tin gì anh gọi em ngay.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1215','SDL1','景区寄存行李，返程超时产生额外寄存费',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1215','SIT1215','P1','that_bai_nhe','ban_chinh_thuc',NULL,'景区行李寄存分限时基础价，超时会额外收费，寄存前务必留意墙上须知。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1215_01','V1215','阮明',1,'你好，我取寄存的行李箱，寄存小票在这里。','nǐ hǎo ， wǒ qǔ jì cún de xíng lǐ xiāng ， jì cún xiǎo piào zài zhè lǐ 。','Chào chị, em đến lấy vali đã gửi, phiếu gửi đồ đây ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1215_02','V1215','管理员',2,'我扫一下小票，你超时两个小时啦，需要补交十元超时费。','wǒ sǎo yī xià xiǎo piào ， nǐ chāo shí liǎng gè xiǎo shí la ， xū yào bǔ jiāo shí yuán chāo shí fèi 。','Để chị quét phiếu xem, em gửi quá giờ hai tiếng rồi, cần đóng thêm mười tệ phí quá giờ.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1215_03','V1215','阮明',3,'寄存不是全天统一收费吗，怎么还有超时费呢？','jì cún bú shì quán tiān tǒng yī shōu fèi ma ， zěn me hái yǒu chāo shí fèi ne ？','Gửi đồ không phải tính phí trọn ngày sao, sao còn có phí quá giờ vậy ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1215_04','V1215','管理员',4,'基础费用仅限四小时游览，超出时长按小时计费哦。','jī chǔ fèi yòng jǐn xiàn sì xiǎo shí yóu lǎn ， chāo chū shí cháng àn xiǎo shí jì fèi ó 。','Phí cơ bản chỉ tính cho bốn tiếng tham quan thôi, quá thời gian đó sẽ tính thêm theo giờ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1215_05','V1215','阮明',5,'我刚才逛景区忘记看时间，没留意时限呢。','wǒ gāng cái guàng jǐng qū wàng jì kàn shí jiān ， méi liú yì shí xiàn ne 。','Em vừa nãy mải đi tham quan quên xem giờ, không để ý đến giới hạn thời gian.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1215_06','V1215','管理员',6,'规则贴在寄存柜旁边，寄存前都会提醒游客的。','guī zé tiē zài jì cún guì páng biān ， jì cún qián dōu huì tí xǐng yóu kè de 。','Quy định có dán ngay cạnh tủ gửi đồ, lúc gửi đồ đều có nhắc khách rồi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1215_07','V1215','阮明',7,'好吧，我补交费用，下次一定看好寄存时长。','hǎo ba ， wǒ bǔ jiāo fèi yòng ， xià cì yí dìng kàn hǎo jì cún shí cháng 。','Thôi vậy, em đóng thêm phí, lần sau nhất định sẽ để ý thời gian gửi đồ.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1216','SDL1','参加本地一日游小团，集合迟到错过大巴',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1216','SIT1216','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内短途旅行团有固定发车时间，迟到不等人，车费多为打包套餐，迟到一般不予退还。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_01','V1216','阮明',1,'导游不好意思，我路上堵车迟到，大巴车开走了吗？','dǎo yóu bù hǎo yì sī ， wǒ lù shàng dǔ chē chí dào ， dà bā chē kāi zǒu le ma ？','Chị hướng dẫn viên ơi, em xin lỗi, đường tắc nên em đến trễ, xe buýt chạy mất rồi ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_02','V1216','小秦',2,'全车游客等了你二十分钟，按照规定我们不能继续等候啦。','quán chē yóu kè děng le nǐ èr shí fēn zhōng ， àn zhào guī dìng wǒ men bù néng jì xù děng hòu la 。','Cả xe khách đã đợi em hai mươi phút rồi, theo quy định bọn chị không thể tiếp tục chờ nữa.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_03','V1216','阮明',3,'能不能麻烦大巴停下来等我一小会儿，我跑过去很快的？','néng bù néng má fán dà bā tíng xià lái děng wǒ yī xiǎo huì er ， wǒ pǎo guò qù hěn kuài de ？','Chị có thể phiền cho xe dừng lại đợi em một chút được không ạ, em chạy qua rất nhanh thôi?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_04','V1216','小秦',4,'景区盘山公路不能随意停车，全车行程会全部延后呢。','jǐng qū pán shān gōng lù bù néng suí yì tíng chē ， quán chē háng chéng huì quán bù yán hòu ne 。','Đường núi trong khu du lịch không được tùy tiện dừng xe, cả đoàn sẽ bị trễ hết lịch trình đấy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_05','V1216','阮明',5,'那我今天还能跟团游玩吗，报名费可以退一部分吗？','nà wǒ jīn tiān hái néng gēn tuán yóu wán ma ， bào míng fèi kě yǐ tuì yī bù fèn ma ？','Vậy hôm nay em còn theo đoàn tham quan được không ạ, phí đăng ký có thể hoàn lại một phần không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_06','V1216','小秦',6,'团费包含车费和门票，门票可以单独留给你，车费无法退款咯。','tuán fèi bāo hán chē fèi hé mén piào ， mén piào kě yǐ dān dú liú gěi nǐ ， chē fèi wú fǎ tuì kuǎn gē 。','Phí đoàn bao gồm tiền xe và vé vào cửa, vé vào cửa chị có thể để riêng cho em, còn tiền xe thì không hoàn được.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_07','V1216','阮明',7,'都怪我出门晚了，只能自己单独进景区参观啦。','dōu guài wǒ chū mén wǎn le ， zhǐ néng zì jǐ dān dú jìn jǐng qū cān guān la 。','Tại em ra cửa trễ, giờ chỉ còn cách tự mình vào tham quan riêng thôi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1216_08','V1216','小秦',8,'下次跟团一定要提前半小时抵达集合点，避免错过行程哈。','xià cì gēn tuán yí dìng yào tí qián bàn xiǎo shí dǐ dá jí hé diǎn ， bì miǎn cuò guò xíng chéng hā 。','Lần sau đi theo đoàn nhớ đến điểm tập trung sớm nửa tiếng, tránh bị lỡ lịch trình nhé.','AM06') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1217','SDL1','寺庙游览，不清楚上香礼仪询问义工',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1217','SIT1217','P1','suon_se','ban_chinh_thuc',NULL,'国内寺庙上香取三支，禁止嘴吹香火、踩踏寺庙门槛，属于传统礼仪。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1217_01','V1217','阮明',1,'姐姐您好，我第一次来寺庙，上香有什么讲究吗？','jiě jiě nín hǎo ， wǒ dì yī cì lái sì miào ， shàng xiāng yǒu shén me jiǎng jiū ma ？','Chị ơi, đây là lần đầu em đến chùa, thắp hương có cần chú ý gì không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1217_02','V1217','慧姐',2,'门口可以免费领三支清香，三支代表平安健康，不用多拿。','mén kǒu kě yǐ miǎn fèi lǐng sān zhī qīng xiāng ， sān zhī dài biǎo píng ān jiàn kāng ， bù yòng duō ná 。','Ở cổng có thể lấy miễn phí ba nén hương thơm, ba nén tượng trưng cho bình an và sức khỏe, không cần lấy nhiều đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1217_03','V1217','阮明',3,'点燃香之后要怎么做呢，可以直接插香炉里吗？','diǎn rán xiāng zhī hòu yào zěn me zuò ne ， kě yǐ zhí jiē chā xiāng lú lǐ ma ？','Sau khi thắp hương thì làm thế nào ạ, có thể cắm thẳng vào lư hương không?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1217_04','V1217','慧姐',4,'点燃后双手举香鞠躬三下，再插进香炉，不要用嘴吹灭香火嘛。','diǎn rán hòu shuāng shǒu jǔ xiāng jū gōng sān xià ， zài chā jìn xiāng lú ， bú yào yòng zuǐ chuī miè xiāng huǒ ma 。','Thắp xong thì hai tay nâng hương cúi lạy ba lần, rồi cắm vào lư hương, không được dùng miệng thổi tắt lửa hương đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1217_05','V1217','阮明',5,'不能吹，那火苗怎么熄灭呀？','bù néng chuī ， nà huǒ miáo zěn me xī miè ya ？','Không được thổi, vậy ngọn lửa dập tắt bằng cách nào ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1217_06','V1217','慧姐',6,'轻轻左右晃动香火，火苗自然熄灭就可以啦。','qīng qīng zuǒ yòu huàng dòng xiāng huǒ ， huǒ miáo zì rán xī miè jiù kě yǐ la 。','Nhẹ nhàng lắc qua lắc lại que hương, ngọn lửa sẽ tự tắt thôi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1217_07','V1217','阮明',7,'学到很多规矩，谢谢您耐心跟我讲解咯。','xué dào hěn duō guī jǔ ， xiè xiè nín nài xīn gēn wǒ jiǎng jiě gē 。','Em học được nhiều quy tắc quá, cảm ơn chị đã kiên nhẫn giải thích cho em ạ.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1218','SDL1','夜市买水果，摊主称重计价产生价格误会',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1218','SIT1218','P1','twist','tuy_y',NULL,'国内市场水果统一按斤（500克）计价，不是按盒/个固定标价，购买前问清单价。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1218_01','V1218','阮明',1,'老板，这个草莓多少钱一斤，我想买一点尝尝。','lǎo bǎn ， zhè ge cǎo méi duō shǎo qián yī jīn ， wǒ xiǎng mǎi yì diǎn cháng cháng 。','Anh ơi, dâu tây này bao nhiêu tiền một cân, tôi muốn mua một ít ăn thử.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1218_02','V1218','阿明',2,'十五块一斤，你挑一点，我帮你称重算总价哈。','shí wǔ kuài yī jīn ， nǐ tiāo yì diǎn ， wǒ bāng nǐ chēng zhòng suàn zǒng jià hā 。','Mười lăm tệ một cân, cậu chọn đi, tôi cân giúp rồi tính tổng tiền nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1218_03','V1218','阮明',3,'好，我挑一小盒，大概多少钱呢？','hǎo ， wǒ tiāo yī xiǎo hé ， dà gài duō shǎo qián ne ？','Được, tôi chọn một hộp nhỏ, khoảng bao nhiêu tiền vậy?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1218_04','V1218','阿明',4,'一共一斤二两，十八块，我给你装盒子里。','yī gòng yī jīn èr liǎng ， shí bā kuài ， wǒ gěi nǐ zhuāng hé zi lǐ 。','Tổng cộng một cân hai lạng, mười tám tệ, tôi cho vào hộp cho cậu nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1218_05','V1218','阮明',5,'我以为按一盒固定价格卖，原来是按斤称重算钱呀。','wǒ yǐ wéi àn yī hé gù dìng jià gé mài ， yuán lái shì àn jīn chēng zhòng suàn qián ya 。','Tôi cứ tưởng bán theo giá cố định một hộp, hóa ra là tính theo cân à.','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1218_06','V1218','阿明',6,'夜市水果都是现称现卖，没有打包固定价的哦。','yè shì shuǐ guǒ dōu shì xiàn chēng xiàn mài ， méi yǒu dǎ bāo gù dìng jià de ó 。','Trái cây ở chợ đêm đều cân xong mới bán, không có giá cố định đóng gói sẵn đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1218_07','V1218','阮明',7,'明白啦，付款给您，下次再来买别的水果。','míng bái la ， fù kuǎn gěi nín ， xià cì zài lái mǎi bié de shuǐ guǒ 。','Hiểu rồi, gửi tiền cho anh nhé, lần sau tôi lại đến mua trái cây khác.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1219','SDL1','乘坐轮渡观光，分不清普通舱与观景舱票价',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1219','SIT1219','P1','suon_se','ban_chinh_thuc',NULL,'观光轮渡分层定价，顶层观景舱溢价更高，适合拍照游客，预算有限可选底层普通舱。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1219_01','V1219','阮明',1,'你好，轮渡观光票有两种，普通舱和观景舱差别大吗？','nǐ hǎo ， lún dù guān guāng piào yǒu liǎng zhǒng ， pǔ tōng cāng hé guān jǐng cāng chā bié dà ma ？','Chào anh, vé phà tham quan có hai loại, khoang thường và khoang ngắm cảnh khác nhau nhiều không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1219_02','V1219','小周',2,'普通舱在底层，观景舱顶层露天，视野好看风景嘛。','pǔ tōng cāng zài dǐ céng ， guān jǐng cāng dǐng céng lù tiān ， shì yě hǎo kàn fēng jǐng ma 。','Khoang thường ở tầng dưới, khoang ngắm cảnh ở tầng trên lộ thiên, tầm nhìn đẹp ngắm cảnh rất tốt ạ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1219_03','V1219','阮明',3,'两者票价分别是多少，航行时长一样吗？','liǎng zhě piào jià fēn bié shì duō shǎo ， háng xíng shí cháng yī yàng ma ？','Vé hai loại giá bao nhiêu, thời gian di chuyển có giống nhau không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1219_04','V1219','小周',4,'普通舱三十，观景舱六十，航行时间都是一小时二十分钟。','pǔ tōng cāng sān shí ， guān jǐng cāng liù shí ， háng xíng shí jiān dōu shì yī xiǎo shí èr shí fēn zhōng 。','Khoang thường ba mươi tệ, khoang ngắm cảnh sáu mươi tệ, thời gian di chuyển đều là một tiếng hai mươi phút.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1219_05','V1219','阮明',5,'我想拍照看江景，那我买两张观景舱票吧。','wǒ xiǎng pāi zhào kàn jiāng jǐng ， nà wǒ mǎi liǎng zhāng guān jǐng cāng piào ba 。','Em muốn chụp ảnh ngắm cảnh sông, vậy em mua hai vé khoang ngắm cảnh nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1219_06','V1219','小周',6,'好嘞，两张一百二十，拿好船票，十分钟后登船啦。','hǎo lei ， liǎng zhāng yì bǎi èr shí ， ná hǎo chuán piào ， shí fēn zhōng hòu dēng chuán la 。','Được ạ, hai vé một trăm hai mươi tệ, cầm vé cẩn thận, mười phút nữa lên tàu ạ.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1219_07','V1219','阮明',7,'顶层视野肯定很棒，还好提前问清楚区别咯。','dǐng céng shì yě kěn dìng hěn bàng ， hái hǎo tí qián wèn qīng chǔ qū bié gē 。','Tầng trên chắc chắn tầm nhìn rất đẹp, may mà em hỏi rõ sự khác biệt trước.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1220','SDL1','酒店早餐结束时间快到，下楼没吃到餐食',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1220','SIT1220','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内酒店自助早餐有固定结束时段，超时不再提供，无临时加餐服务。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1220_01','V1220','阮明',1,'你好，我想来吃早餐，怎么餐台都收干净了呀？','nǐ hǎo ， wǒ xiǎng lái chī zǎo cān ， zěn me cān tái dōu shōu gān jìng le ya ？','Chào chị, em muốn ăn sáng, sao bàn ăn dọn sạch hết rồi ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1220_02','V1220','小兰',2,'酒店早餐九点半结束，现在已经十点十五分啦。','jiǔ diàn zǎo cān jiǔ diǎn bàn jié shù ， xiàn zài yǐ jīng shí diǎn shí wǔ fēn la 。','Bữa sáng khách sạn kết thúc lúc chín rưỡi, bây giờ đã mười giờ mười lăm rồi ạ.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1220_03','V1220','阮明',3,'我昨天玩到很晚，早上睡过头，不知道结束这么早呢。','wǒ zuó tiān wán dào hěn wǎn ， zǎo shàng shuì guò tóu ， bù zhī dào jié shù zhè me zǎo ne 。','Hôm qua em chơi khuya quá, sáng nay ngủ quên, không biết là kết thúc sớm vậy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1220_04','V1220','小兰',4,'实在不好意思，厨房已经全部收餐清洗，没有食物咯。','shí zài bù hǎo yì sī ， chú fáng yǐ jīng quán bù shōu cān qīng xǐ ， méi yǒu shí wù gē 。','Thật xin lỗi, nhà bếp đã dọn hết và rửa sạch rồi, không còn đồ ăn nữa ạ.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1220_05','V1220','阮明',5,'那酒店还有其他付费早餐可以买吗？','nà jiǔ diàn hái yǒu qí tā fù fèi zǎo cān kě yǐ mǎi ma ？','Vậy khách sạn còn bữa sáng trả phí nào khác để mua không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1220_06','V1220','小兰',6,'餐厅上午只供应自助早餐，中午十二点才有正餐供应。','cān tīng shàng wǔ zhǐ gōng yìng zì zhù zǎo cān ， zhōng wǔ shí èr diǎn cái yǒu zhèng cān gōng yìng 。','Buổi sáng nhà hàng chỉ phục vụ buffet sáng thôi, mười hai giờ trưa mới có bữa chính ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1220_07','V1220','阮明',7,'好吧，只能出门去街边小店吃早饭了，下次一定早起。','hǎo ba ， zhǐ néng chū mén qù jiē biān xiǎo diàn chī zǎo fàn le ， xià cì yí dìng zǎo qǐ 。','Thôi được, đành ra ngoài ăn sáng ở quán vỉa hè vậy, lần sau nhất định dậy sớm.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1221','SDL1','景区扫码讲解器租借，手机无法识别国内小程序',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1221','SIT1221','P1','twist','ban_chinh_thuc',NULL,'国内各类景区小程序大多需要大陆手机号注册，境外手机系统常会加载失败。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1221_01','V1221','阮明',1,'您好，我想租景区电子讲解器，但是扫二维码打不开小程序。','nín hǎo ， wǒ xiǎng zū jǐng qū diàn zi jiǎng jiě qì ， dàn shì sǎo èr wéi mǎ dǎ bù kāi xiǎo chéng xù 。','Chào anh/chị, em muốn thuê máy thuyết minh điện tử của khu du lịch nhưng quét mã QR không mở được ứng dụng nhỏ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1221_02','V1221','工作人员',2,'你的手机是境外系统吧，没有国内手机号登录不了呢。','nǐ de shǒu jī shì jìng wài xì tǒng ba ， méi yǒu guó nèi shǒu jī hào dēng lù bù liǎo ne 。','Điện thoại của bạn dùng hệ thống nước ngoài đúng không, không có số điện thoại trong nước thì không đăng nhập được đâu.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1221_03','V1221','阮明',3,'那我没法线上扫码，能直接租实体手持讲解器吗？','nà wǒ méi fǎ xiàn shàng sǎo mǎ ， néng zhí jiē zū shí tǐ shǒu chí jiǎng jiě qì ma ？','Vậy em không thể quét mã trực tuyến được, có thể thuê trực tiếp máy thuyết minh cầm tay không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1221_04','V1221','工作人员',4,'可以的，线下登记护照就能租，押金一百元，归还退押金。','kě yǐ de ， xiàn xià dēng jì hù zhào jiù néng zū ， yā jīn yì bǎi yuán ， guī huán tuì yā jīn 。','Được chứ, đăng ký trực tiếp bằng hộ chiếu là thuê được, tiền đặt cọc một trăm tệ, trả máy sẽ hoàn cọc.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1221_05','V1221','阮明',5,'那就租一台，押金微信支付没问题吧？','nà jiù zū yī tái ， yā jīn wēi xìn zhī fù méi wèn tí ba ？','Vậy em thuê một máy, đặt cọc thanh toán qua WeChat được không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1221_06','V1221','工作人员',6,'支持微信支付宝，拿好讲解器，每个景点会自动讲解咯。','zhī chí wēi xìn zhī fù bǎo ， ná hǎo jiǎng jiě qì ， měi gè jǐng diǎn huì zì dòng jiǎng jiě gē 。','Hỗ trợ cả WeChat Pay và Alipay, cầm máy thuyết minh cẩn thận, đến mỗi điểm tham quan sẽ tự động thuyết minh nhé.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1221_07','V1221','阮明',7,'太好啦，还好有实体设备，不然看不懂景点历史呢。','tài hǎo la ， hái hǎo yǒu shí tǐ shè bèi ， bù rán kàn bù dǒng jǐng diǎn lì shǐ ne 。','Tuyệt quá, may mà có thiết bị thực tế, không thì em chẳng hiểu được lịch sử của các điểm tham quan.','AM04') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1222','SDL1','高铁站安检，随身携带液体超出规定容量被扣留',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1222','SIT1222','P1','that_bai_nhe','ban_chinh_thuc',NULL,'高铁、地铁随身液体单瓶容积不得超100ml，超标无法随身携带，可邮寄或当场舍弃。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1222_01','V1222','阮明',1,'安检您好，我的护肤品怎么被机器拦下来了呢？','ān jiǎn nín hǎo ， wǒ de hù fū pǐn zěn me bèi jī qì lán xià lái le ne ？','Chào anh, đồ dưỡng da của em sao lại bị máy giữ lại vậy ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1222_02','V1222','小林',2,'你这瓶保湿乳液一百五十毫升，高铁单瓶液体不能超过一百毫升哦。','nǐ zhè píng bǎo shī rǔ yè yì bǎi wǔ shí háo shēng ， gāo tiě dān píng yè tǐ bù néng chāo guò yì bǎi háo shēng ó 。','Chai sữa dưỡng ẩm này của bạn một trăm năm mươi ml, tàu cao tốc quy định mỗi chai chất lỏng không được quá một trăm ml đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1222_03','V1222','阮明',3,'我不知道这个规定，放在行李箱里忘记拿出来啦。','wǒ bù zhī dào zhè ge guī dìng ， fàng zài háng lǐ xiāng lǐ wàng jì ná chū lái la 。','Em không biết quy định này, để trong vali quên lấy ra mất rồi.','AM02') ON CONFLICT DO NOTHING;
