INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_06','V335','苏雯',6,'那我们加个微信，周末约着一起出发吧。','nà wǒ men jiā gè wēi xìn， zhōu mò yuē zhe yì qǐ chū fā ba。','Vậy tụi mình kết bạn Wechat, cuối tuần hẹn nhau cùng đi nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L335_07','V335','阮明',7,'好呀，终于找到一样爱好的朋友啦。','hǎo ya， zhōng yú zhǎo dào yī yàng ài hào de péng yǒu la。','Được đó, cuối cùng cũng tìm được người bạn cùng sở thích rồi.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT336','S114','Đăng ký tham gia câu lạc bộ sinh viên',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V336','SIT336','P1','twist','ban_chinh_thuc',NULL,'国内高校社团统一在开学招新，多数社团有活动人数限制，需要提前登记报名。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L336_01','V336','阮明',1,'学姐你好，我想报名加入咱们汉服社团可以吗？','xué jiě nǐ hǎo， wǒ xiǎng bào míng jiā rù zán men hàn fú shè tuán kě yǐ ma？','Chào chị, em muốn đăng ký tham gia câu lạc bộ Hán phục của tụi mình có được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L336_02','V336','学姐',2,'当然可以，先填一张信息登记表哦。','dāng rán kě yǐ， xiān tián yī zhāng xìn xī dēng jì biǎo ó。','Được chứ, em điền vào một tờ đăng ký thông tin trước đã nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L336_03','V336','阮明',3,'好的，我平时很喜欢中国传统服饰和文化。','hǎo de， wǒ píng shí hěn xǐ huān zhōng guó chuán tǒng fú shì hé wén huà。','Dạ được, em rất thích trang phục và văn hóa truyền thống Trung Quốc.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L336_04','V336','学姐',4,'咱们每周有线下活动，不过本周活动名额满了。','zán men měi zhōu yǒu xiàn xià huó dòng， bù guò běn zhōu huó dòng míng é mǎn le。','Tụi chị mỗi tuần có hoạt động ngoại tuyến, nhưng tuần này hết chỗ rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L336_05','V336','阮明',5,'啊？那我下周能正常参与活动吗？','a？ nà wǒ xià zhōu néng zhèng cháng cān yù huó dòng ma？','Ơ? Vậy tuần sau em có thể tham gia bình thường không ạ?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L336_06','V336','学姐',6,'没问题，下周名额会重新开放，记得准时来。','méi wèn tí， xià zhōu míng é huì chóng xīn kāi fàng， jì de zhǔn shí lái。','Không vấn đề gì, tuần sau sẽ mở lại chỗ trống, nhớ đến đúng giờ nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L336_07','V336','阮明',7,'好，我会记好时间，麻烦学姐啦。','hǎo， wǒ huì jì hǎo shí jiān， má fán xué jiě la。','Dạ, em sẽ ghi nhớ thời gian, phiền chị nhiều rồi ạ.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT337','S112','Giải thích khi hiểu nhầm ý của bạn',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V337','SIT337','P1','suon_se','ban_chinh_thuc',NULL,'朋友产生隔阂后，中国人会主动沟通解释，厘清误会后不会一直记在心里。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L337_01','V337','阮明',1,'昨天那件事你是不是误会我了，我跟你解释一下吧。','zuó tiān nà jiàn shì nǐ shì bú shì wù huì wǒ le， wǒ gēn nǐ jiě shì yī xià ba。','Chuyện hôm qua chắc cậu hiểu lầm mình rồi, để mình giải thích nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L337_02','V337','李然',2,'我昨天确实有点生气，你说说是什么情况。','wǒ zuó tiān què shí yǒu diǎn shēng qì， nǐ shuō shuō shì shén me qíng kuàng。','Hôm qua mình đúng là có hơi giận, cậu nói xem là chuyện gì vậy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L337_03','V337','阮明',3,'我不是故意放你鸽子，是老师临时留我补作业呢。','wǒ bú shì gù yì fàng nǐ gē zi， shì lǎo shī lín shí liú wǒ bǔ zuò yè ne。','Mình không cố ý cho cậu leo cây đâu, là thầy giữ mình lại làm bù bài tập đột xuất đó.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L337_04','V337','李然',4,'原来是这样，我还以为你不想跟我出门。','yuán lái shì zhè yàng， wǒ hái yǐ wéi nǐ bù xiǎng gēn wǒ chū mén。','Ra là vậy, mình còn tưởng cậu không muốn đi chơi với mình chứ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L337_05','V337','阮明',5,'怎么会，我一直很期待和你逛街的。','zěn me huì， wǒ yì zhí hěn qī dài hé nǐ guàng jiē de。','Sao lại thế được, mình luôn mong được đi dạo phố với cậu mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L337_06','V337','李然',6,'行，我明白啦，这件事就翻篇不提了。','xíng， wǒ míng bái la， zhè jiàn shì jiù fān piān bù tí le。','Được rồi, mình hiểu rồi, chuyện này coi như bỏ qua không nhắc lại nữa.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L337_07','V337','阮明',7,'太好了，下次出门我提前跟你确认时间。','tài hǎo le， xià cì chū mén wǒ tí qián gēn nǐ què rèn shí jiān。','Tuyệt quá, lần sau đi đâu mình sẽ báo trước giờ giấc với cậu.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT338','S112','Chúc mừng sinh nhật bạn cùng phòng',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V338','SIT338','P1','suon_se','tuy_y',NULL,'大学生宿舍室友常会合伙买蛋糕、礼物一起过生日，是宿舍常见暖心活动。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L338_01','V338','阮明',1,'张明，生日快乐！快拆开我们准备的蛋糕吧。','zhāng míng， shēng rì kuài lè！ kuài chāi kāi wǒ men zhǔn bèi de dàn gāo ba。','Trương Minh, chúc mừng sinh nhật nha! Mở cái bánh kem tụi mình chuẩn bị ra đi.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L338_02','V338','张明',2,'哇，你们居然还记得我的生日，太惊喜了。','wa， nǐ men jū rán hái jì de wǒ de shēng rì， tài jīng xǐ le。','Ồ, tụi cậu còn nhớ sinh nhật mình cơ à, bất ngờ quá đi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L338_03','V338','阮明',3,'我们悄悄凑钱买的，还有小礼物送给你呢。','wǒ men qiāo qiāo còu qián mǎi de， hái yǒu xiǎo lǐ wù sòng gěi nǐ ne。','Tụi mình lén góp tiền mua đó, còn có quà nhỏ tặng cậu nữa nè.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L338_04','V338','张明',4,'真的不用这么破费，有你们陪伴就足够啦。','zhēn de bù yòng zhè me pò fèi， yǒu nǐ men péi bàn jiù zú gòu la。','Thật sự không cần tốn kém vậy đâu, có tụi cậu ở bên là đủ rồi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L338_05','V338','阮明',5,'室友之间不用客气，赶紧许愿吹蜡烛哦。','shì yǒu zhī jiān bù yòng kè qì， gǎn jǐn xǔ yuàn chuī là zhú ó。','Bạn cùng phòng với nhau khách sáo gì, mau ước nguyện rồi thổi nến đi.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L338_06','V338','张明',6,'好，我许个愿，希望我们宿舍一直和睦。','hǎo， wǒ xǔ gè yuàn， xī wàng wǒ men sù shè yì zhí hé mù。','Được, mình ước nè, mong phòng mình lúc nào cũng hòa thuận.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L338_07','V338','阮明',7,'一定会的，咱们切蛋糕一起分享！','yí dìng huì de， zán men qiè dàn gāo yì qǐ fēn xiǎng！','Chắc chắn rồi, giờ cắt bánh cùng ăn thôi!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT339','S112','Hỏi mượn đồ dùng cá nhân từ bạn cùng lớp',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V339','SIT339','P1','twist','tuy_y',NULL,'向他人借私人物品需要主动询问，用完及时归还，很多人会用小饮品、零食答谢对方。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L339_01','V339','阮明',1,'菲菲，能不能借你的笔记本电脑用半小时啊？','fēi fēi， néng bù néng jiè nǐ de bǐ jì běn diàn nǎo yòng bàn xiǎo shí a？','Phi Phi, cho mình mượn laptop dùng nửa tiếng được không?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L339_02','V339','刘菲',2,'不好意思，我电脑拿去图书馆充电了嘛。','bù hǎo yì sī， wǒ diàn nǎo ná qù tú shū guǎn chōng diàn le ma。','Xin lỗi nha, máy tính mình đem ra thư viện sạc pin mất rồi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L339_03','V339','阮明',3,'这样啊，那你有多余的U盘借我拷贝文件吗？','zhè yàng a， nà nǐ yǒu duō yú de U pán jiè wǒ kǎo bèi wén jiàn ma？','Vậy à, thế cậu có USB dư cho mình mượn copy tài liệu không?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L339_04','V339','刘菲',4,'这个可以，我包里刚好有一个全新的。','zhè ge kě yǐ， wǒ bāo lǐ gāng hǎo yǒu yí gè quán xīn de。','Cái này thì được, trong cặp mình vừa hay có một cái mới toanh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L339_05','V339','阮明',5,'太感谢了，用完我马上还给你，绝不弄丢。','tài gǎn xiè le， yòng wán wǒ mǎ shàng huán gěi nǐ， jué bù nòng diū。','Cảm ơn nhiều lắm, dùng xong mình trả lại ngay, tuyệt đối không làm mất đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L339_06','V339','刘菲',6,'没关系，你慢慢用，不用着急归还。','méi guān xì， nǐ màn màn yòng， bù yòng zháo jí guī huán。','Không sao đâu, cậu cứ dùng thoải mái, không cần vội trả đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L339_07','V339','阮明',7,'好嘞，等下请你喝奶茶作为答谢。','hǎo lei， děng xià qǐng nǐ hē nǎi chá zuò wéi dá xiè。','Được rồi, lát nữa mời cậu uống trà sữa để cảm ơn nhé.','AM08') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT340','S112','Đề nghị đổi lịch hẹn vì bận đột xuất',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V340','SIT340','P1','suon_se','ban_chinh_thuc',NULL,'临时无法赴约，中国人会第一时间告知对方，主动协商新时间，避免对方空等。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L340_01','V340','阮明',1,'实在抱歉，我们下午约好逛书店得改时间了。','shí zài bào qiàn， wǒ men xià wǔ yuē hǎo guàng shū diàn dé gǎi shí jiān le。','Thật sự xin lỗi, buổi chiều mình hẹn đi nhà sách với cậu phải đổi giờ rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L340_02','V340','吴桐',2,'怎么了，是临时有突发事情吗？','zěn me le， shì lín shí yǒu tū fā shì qíng ma？','Sao vậy, có chuyện gì đột xuất à?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L340_03','V340','阮明',3,'辅导员通知我去办公室提交留学材料呢。','fǔ dǎo yuán tōng zhī wǒ qù bàn gōng shì tí jiāo liú xué cái liào ne。','Cố vấn lớp báo mình lên văn phòng nộp hồ sơ du học đó.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L340_04','V340','吴桐',4,'没事，正事要紧，我们改到明天下午行吗？','méi shì， zhèng shì yào jǐn， wǒ men gǎi dào míng tiān xià wǔ xíng ma？','Không sao, việc chính quan trọng hơn, mình đổi sang chiều mai được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L340_05','V340','阮明',5,'明天下午我全天有空，完全没问题的。','míng tiān xià wǔ wǒ quán tiān yǒu kòng， wán quán méi wèn tí de。','Chiều mai cả buổi mình đều rảnh, hoàn toàn không vấn đề gì.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L340_06','V340','吴桐',6,'那就定明天三点，咱们校门口碰面吧。','nà jiù dìng míng tiān sān diǎn， zán men xiào mén kǒu pèng miàn ba。','Vậy hẹn ba giờ chiều mai nhé, tụi mình gặp nhau trước cổng trường.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L340_07','V340','阮明',7,'好，明天我提前十分钟在门口等你啦。','hǎo， míng tiān wǒ tí qián shí fēn zhōng zài mén kǒu děng nǐ la。','Được, mai mình sẽ đến sớm mười phút đợi cậu ở cổng nhé.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT341','S114','Xin nghỉ một buổi sinh hoạt câu lạc bộ',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V341','SIT341','P1','suon_se','ban_chinh_thuc',NULL,'学生社团有事无法参与活动，需要提前向负责人报备请假，不能无故缺席。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L341_01','V341','阮明',1,'学姐，我想跟你请假，本周的社团活动没法参加了。','xué jiě， wǒ xiǎng gēn nǐ qǐng jià， běn zhōu de shè tuán huó dòng méi fǎ cān jiā le。','Chị ơi, em muốn xin phép nghỉ, buổi sinh hoạt câu lạc bộ tuần này em không tham gia được ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L341_02','V341','学姐',2,'可以，你是有什么重要的事情耽误了吗？','kě yǐ， nǐ shì yǒu shén me zhòng yào de shì qíng dān wù le ma？','Được, em có việc gì quan trọng nên bị vướng à?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L341_03','V341','阮明',3,'下周有汉语考试，我需要全天在家复习嘛。','xià zhōu yǒu hàn yǔ kǎo shì， wǒ xū yào quán tiān zài jiā fù xí ma。','Tuần sau em có kỳ thi tiếng Trung, em cần ở nhà ôn tập cả ngày ạ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L341_04','V341','学姐',4,'原来是备考，学习优先，我帮你登记请假。','yuán lái shì bèi kǎo， xué xí yōu xiān， wǒ bāng nǐ dēng jì qǐng jià。','Thì ra là chuẩn bị thi, học hành ưu tiên trước, chị giúp em ghi phép nghỉ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L341_05','V341','阮明',5,'活动的任务我下周会主动补上，不会落下进度。','huó dòng de rèn wù wǒ xià zhōu huì zhǔ dòng bǔ shàng， bú huì là xià jìn dù。','Nhiệm vụ của hoạt động tuần sau em sẽ chủ động bù lại, không để tiến độ bị chậm đâu ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L341_06','V341','学姐',6,'不用着急，等你考完试再来参与就行。','bù yòng zháo jí， děng nǐ kǎo wán shì zài lái cān yù jiù xíng。','Không cần gấp đâu, đợi em thi xong rồi tham gia lại cũng được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L341_07','V341','阮明',7,'辛苦学姐体谅我啦，非常感谢。','xīn kǔ xué jiě tǐ liàng wǒ la， fēi cháng gǎn xiè。','Cảm ơn chị đã thông cảm cho em nhiều lắm ạ, em cảm ơn chị thật sự.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT342','S112','Khen món ăn bạn Trung Quốc nấu, đáp lại khi được khen',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V342','SIT342','P1','suon_se','tuy_y',NULL,'品尝他人亲手做的饭菜，中国人会真诚夸赞，还会互相邀约交换拿手菜。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L342_01','V342','阮明',1,'你做的番茄炒蛋也太好吃了吧，味道超正宗！','nǐ zuò de fān qié chǎo dàn yě tài hǎo chī le ba， wèi dào chāo zhèng zōng！','Món trứng xào cà chua cậu làm ngon quá trời, đúng vị chuẩn luôn!','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L342_02','V342','小雅',2,'没有啦，就是简单家常菜，你喜欢就多吃点。','méi yǒu la， jiù shì jiǎn dān jiā cháng cài， nǐ xǐ huān jiù duō chī diǎn。','Có gì đâu, chỉ là món nhà làm đơn giản thôi, cậu thích thì ăn nhiều vào.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L342_03','V342','阮明',3,'比校外餐馆做得还香，你厨艺也太好了啊。','bǐ xiào wài cān guǎn zuò dé hái xiāng， nǐ chú yì yě tài hǎo le a。','Còn thơm hơn cả quán ăn ngoài trường ấy, tay nghề nấu ăn của cậu giỏi thật đó.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L342_04','V342','小雅',4,'谢谢你夸奖，下次我教你一起做呢。','xiè xiè nǐ kuā jiǎng， xià cì wǒ jiāo nǐ yì qǐ zuò ne。','Cảm ơn cậu khen, lần sau mình dạy cậu làm cùng nhé.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L342_05','V342','阮明',5,'那太好了，我还怕自己学不会。','nà tài hǎo le， wǒ hái pà zì jǐ xué bú huì。','Vậy thì tốt quá, mình còn sợ mình không học được cơ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L342_06','V342','小雅',6,'不难的，下次你做家乡菜给我尝尝吧。','bù nán de， xià cì nǐ zuò jiā xiāng cài gěi wǒ cháng cháng ba。','Không khó đâu, lần sau cậu nấu món quê hương cho mình nếm thử nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L342_07','V342','阮明',7,'没问题，下次我带食材过来，一定露一手！','méi wèn tí， xià cì wǒ dài shí cái guò lái， yí dìng lòu yī shǒu！','Được luôn, lần sau mình mang nguyên liệu qua, nhất định trổ tài cho xem!',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT343','S115','Mua điện thoại mới, hỏi thông số',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V343','SIT343','P1','suon_se','tuy_y',NULL,'线下买电子产品，顾客可以自由询问全部参数，对比多款机型，店家不会催促下单。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L343_01','V343','阮明',1,'你好，这款新款手机内存和电池容量是多少啊？','nǐ hǎo， zhè kuǎn xīn kuǎn shǒu jī nèi cún hé diàn chí róng liàng shì duō shǎo a？','Chào anh/chị, cái điện thoại mới này bộ nhớ với dung lượng pin bao nhiêu vậy ạ?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L343_02','V343','销售员',2,'这款手机256G内存，电池续航一整天没问题。','zhè kuǎn shǒu jī 256G nèi cún， diàn chí xù háng yī zhěng tiān méi wèn tí。','Máy này bộ nhớ 256G, pin dùng cả ngày thoải mái không lo hết.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L343_03','V343','阮明',3,'拍照像素高吗？我平时很喜欢出门拍照呢。','pāi zhào xiàng sù gāo ma？ wǒ píng shí hěn xǐ huān chū mén pāi zhào ne。','Chụp ảnh độ phân giải cao không ạ? Em hay đi ra ngoài chụp ảnh lắm.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L343_04','V343','销售员',4,'后置五千万像素，夜景拍摄效果特别清晰。','hòu zhì wǔ qiān wàn xiàng sù， yè jǐng pāi shè xiào guǒ tè bié qīng xī。','Camera sau 50 triệu điểm ảnh, chụp cảnh đêm rõ nét lắm luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L343_05','V343','阮明',5,'那处理器运行会不会卡顿，适合学习软件吗？','nà chǔ lǐ qì yùn xíng huì bú huì kǎ dùn， shì hé xué xí ruǎn jiàn ma？','Vậy chip xử lý chạy có bị giật lag không, có hợp để học phần mềm không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L343_06','V343','销售员',6,'配置足够流畅运行各类软件，学生用很合适。','pèi zhì zú gòu liú chàng yùn xíng gè lèi ruǎn jiàn， xué shēng yòng hěn hé shì。','Cấu hình đủ sức chạy mượt mọi loại phần mềm, học sinh sinh viên dùng rất hợp.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L343_07','V343','阮明',7,'行，那我再对比一下另一款，等下再来找你。','xíng， nà wǒ zài duì bǐ yī xià lìng yī kuǎn， děng xià zài lái zhǎo nǐ。','Vâng, để em so sánh thêm một mẫu nữa, lát em quay lại tìm anh/chị.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT344','S115','Mang điện thoại đi sửa màn hình vỡ',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V344','SIT344','P1','twist','ban_chinh_thuc',NULL,'手机维修更换配件分原装和平价配件，店家会主动区分报价，配件缺货会告知顾客取机时间。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L344_01','V344','阮明',1,'师傅，我的手机屏幕摔碎了，能帮忙更换吗？','shī fù， wǒ de shǒu jī píng mù shuāi suì le， néng bāng máng gēng huàn ma？','Anh ơi, màn hình điện thoại em bị vỡ do rớt, anh đổi giúp em được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L344_02','V344','维修师傅',2,'可以，先看看型号，原装屏幕价格贵一点哈。','kě yǐ， xiān kàn kàn xíng hào， yuán zhuāng píng mù jià gé guì yì diǎn hā。','Được, để anh xem đời máy trước đã, màn zin giá hơi cao một chút nha.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L344_03','V344','阮明',3,'原装的大概多少钱，维修需要等多久呢？','yuán zhuāng de dà gài duō shǎo qián， wéi xiū xū yào děng duō jiǔ ne？','Màn zin khoảng bao nhiêu tiền vậy anh, sửa thì phải đợi lâu không ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L344_04','V344','维修师傅',4,'三百五十元，可惜现在店里没有现货屏幕。','sān bǎi wǔ shí yuán， kě xī xiàn zài diàn lǐ méi yǒu xiàn huò píng mù。','Ba trăm năm mươi tệ, tiếc là bên tiệm hiện chưa có sẵn màn hình.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L344_05','V344','阮明',5,'啊？那什么时候能到货，我手机每天都要用。','a？ nà shén me shí hòu néng dào huò， wǒ shǒu jī měi tiān dōu yào yòng。','Ơ? Vậy chừng nào có hàng vậy anh, điện thoại em ngày nào cũng phải dùng.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L344_06','V344','维修师傅',6,'明天中午到货，你明天下午过来取就行。','míng tiān zhōng wǔ dào huò， nǐ míng tiān xià wǔ guò lái qǔ jiù xíng。','Trưa mai hàng về, em chiều mai qua lấy là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L344_07','V344','阮明',7,'好，我明天准时过来，麻烦师傅预留屏幕。','hǎo， wǒ míng tiān zhǔn shí guò lái， má fán shī fù yù liú píng mù。','Dạ, mai em qua đúng giờ, phiền anh giữ màn hình giúp em nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT345','S116','Mua laptop, hỏi bảo hành',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V345','SIT345','P1','suon_se','ban_chinh_thuc',NULL,'国内数码产品均提供全国联保服务，门店会清晰告知保修时长、售后范围。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L345_01','V345','阮明',1,'这款笔记本适合留学生写论文、做PPT吗？','zhè kuǎn bǐ jì běn shì hé liú xué shēng xiě lùn wén、 zuò PPT ma？','Mẫu laptop này có hợp cho du học sinh viết luận văn, làm PPT không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L345_02','V345','导购',2,'完全适配，轻薄便携，性能足够日常学习的。','wán quán shì pèi， qīng bó biàn xié， xìng néng zú gòu rì cháng xué xí de。','Hoàn toàn hợp luôn, mỏng nhẹ dễ mang theo, hiệu năng đủ dùng cho việc học hằng ngày.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L345_03','V345','阮明',3,'那整机官方保修时长是多久呀？','nà zhěng jī guān fāng bǎo xiū shí cháng shì duō jiǔ ya？','Vậy thời hạn bảo hành chính hãng của cả máy là bao lâu vậy ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L345_04','V345','导购',4,'基础全国联保一年，加钱可以升级到三年哦。','jī chǔ quán guó lián bǎo yī nián， jiā qián kě yǐ shēng jí dào sān nián ó。','Bảo hành toàn quốc cơ bản là một năm, trả thêm phí có thể nâng lên ba năm đó ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L345_05','V345','阮明',5,'保修期内系统故障能免费上门维修吗？','bǎo xiū qī nèi xì tǒng gù zhàng néng miǎn fèi shàng mén wéi xiū ma？','Trong thời gian bảo hành nếu hệ thống lỗi có được sửa tận nơi miễn phí không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L345_06','V345','导购',6,'市区范围内可以免费上门，超出范围需要送店。','shì qū fàn wéi nèi kě yǐ miǎn fèi shàng mén， chāo chū fàn wéi xū yào sòng diàn。','Trong nội thành thì được sửa tận nơi miễn phí, ngoài phạm vi thì phải mang ra tiệm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L345_07','V345','阮明',7,'了解了，我考虑一下，晚点过来付款吧。','liǎo jiě le， wǒ kǎo lǜ yī xià， wǎn diǎn guò lái fù kuǎn ba。','Em hiểu rồi, để em suy nghĩ thêm, lát em quay lại thanh toán ạ.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT346','S117','Đăng ký lắp Internet cho phòng trọ',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V346','SIT346','P1','twist','ban_chinh_thuc',NULL,'租房办理宽带需要核验房屋地址，小区宽带端口有限，满员只能排队等待新端口。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L346_01','V346','阮明',1,'你好，我租的单间想办理宽带安装业务。','nǐ hǎo， wǒ zū de dān jiān xiǎng bàn lǐ kuān dài ān zhuāng yè wù。','Chào chị, em thuê phòng đơn, muốn đăng ký lắp mạng băng rộng ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L346_02','V346','客服',2,'您好，请提供详细地址，我查询线路覆盖情况。','nín hǎo， qǐng tí gōng xiáng xì dì zhǐ， wǒ chá xún xiàn lù fù gài qíng kuàng。','Chào em, em cho chị xin địa chỉ chi tiết để chị kiểm tra tình trạng phủ sóng đường truyền.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L346_03','V346','阮明',3,'地址是大学周边小区3栋502室，麻烦查一下。','dì zhǐ shì dà xué zhōu biān xiǎo qū 3 dòng 502 shì， má fán chá yī xià。','Địa chỉ là căn hộ số 502, tòa 3, khu gần trường đại học, phiền chị kiểm tra giúp em.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L346_04','V346','客服',4,'不好意思，您小区本周宽带端口已经全部用完了嘛。','bù hǎo yì sī， nín xiǎo qū běn zhōu kuān dài duān kǒu yǐ jīng quán bù yòng wán le ma。','Xin lỗi em, cổng mạng ở khu em tuần này đã dùng hết sạch rồi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L346_05','V346','阮明',5,'这样啊，那下一批端口什么时候开放呢？','zhè yàng a， nà xià yī pī duān kǒu shén me shí hòu kāi fàng ne？','Vậy à, thế đợt cổng tiếp theo mở khi nào ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L346_06','V346','客服',6,'三天后重新放号，到时候我可以提醒您预约。','sān tiān hòu chóng xīn fàng hào， dào shí hòu wǒ kě yǐ tí xǐng nín yù yuē。','Ba ngày nữa sẽ mở lại đợt số mới, lúc đó chị có thể nhắc em đặt trước.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L346_07','V346','阮明',7,'好，那麻烦三天后联系我，辛苦你啦。','hǎo， nà má fán sān tiān hòu lián xì wǒ， xīn kǔ nǐ la。','Vâng, vậy ba ngày nữa phiền chị liên hệ em nhé, cảm ơn chị nhiều ạ.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT347','S115','Chuyển dữ liệu sang điện thoại mới',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V347','SIT347','P1','suon_se','tuy_y',NULL,'国产手机自带一键换机功能，年轻人大多会互相帮忙操作数据迁移。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L347_01','V347','阮明',1,'我刚换了新手机，不知道怎么转移旧手机数据啊。','wǒ gāng huàn le xīn shǒu jī， bù zhī dào zěn me zhuǎn yí jiù shǒu jī shù jù a。','Tao vừa đổi điện thoại mới, chẳng biết chuyển dữ liệu từ máy cũ sang thế nào cả.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L347_02','V347','小杨',2,'很简单，手机自带换机软件，跟着步骤操作就行啦。','hěn jiǎn dān， shǒu jī zì dài huàn jī ruǎn jiàn， gēn zhe bù zhòu cāo zuò jiù xíng la。','Đơn giản mà, điện thoại có sẵn phần mềm chuyển máy, cứ theo từng bước làm là được ấy.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L347_03','V347','阮明',3,'聊天记录、照片和文件都能完整复制过去吗？','liáo tiān jì lù、 zhào piān hé wén jiàn dōu néng wán zhěng fù zhì guò qù ma？','Tin nhắn, ảnh với file có sao chép nguyên vẹn qua được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L347_04','V347','小杨',4,'全部可以，就是两台手机都要连接同一个WiFi呢。','quán bù kě yǐ， jiù shì liǎng tái shǒu jī dōu yào lián jiē tóng yī gè WiFi ne。','Được hết luôn, chỉ cần hai máy cùng kết nối chung một WiFi thôi.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L347_05','V347','阮明',5,'我还担心会丢失重要的学习资料。','wǒ hái dān xīn huì diū shī zhòng yào de xué xí zī liào。','Tao còn hơi lo bị mất mấy tài liệu học tập quan trọng nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L347_06','V347','小杨',6,'放心，我上次换机一点资料都没漏掉。','fàng xīn， wǒ shàng cì huàn jī yì diǎn zī liào dōu méi lòu diào。','Yên tâm đi, lần trước tao đổi máy chẳng thiếu tí tài liệu nào cả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L347_07','V347','阮明',7,'太谢谢你了，等下我操作有问题再来问你吧。','tài xiè xiè nǐ le， děng xià wǒ cāo zuò yǒu wèn tí zài lái wèn nǐ ba。','Cảm ơn mày nhiều nha, lát tao làm mà có gì thắc mắc lại hỏi mày tiếp nhé.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT348','S118','Cài đặt và đăng ký app dịch tiếng Trung',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V348','SIT348','P1','suon_se','tuy_y',NULL,'留学生常用翻译APP辅助学习中文，国内软件支持微信、QQ快捷登录，注册流程简单。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L348_01','V348','阮明',1,'有没有好用的翻译软件推荐我下载一下啊？','yǒu méi yǒu hǎo yòng de fān yì ruǎn jiàn tuī jiàn wǒ xià zài yī xià a？','Có app dịch nào ngon giới thiệu tao tải về không?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L348_02','V348','小林',2,'这款翻译APP特别适合留学生，离线也能用呢。','zhè kuǎn fān yì APP tè bié shì hé liú xué shēng， lí xiàn yě néng yòng ne。','Cái app dịch này hợp với du học sinh lắm, offline vẫn dùng được luôn.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L348_03','V348','阮明',3,'下载之后注册需要绑定手机号吗？','xià zài zhī hòu zhù cè xū yào bǎng dìng shǒu jī hào ma？','Tải xong đăng ký có cần liên kết số điện thoại không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L348_04','V348','小林',4,'只用微信一键登录就可以，不用额外注册啦。','zhǐ yòng wēi xìn yī jiàn dēng lù jiù kě yǐ， bù yòng é wài zhù cè la。','Chỉ cần đăng nhập bằng WeChat một chạm là xong, không cần đăng ký thêm gì cả.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L348_05','V348','阮明',5,'还能拍照翻译课本上的汉字，对吗？','hái néng pāi zhào fān yì kè běn shàng de hàn zì， duì ma？','Còn chụp ảnh dịch chữ Hán trong sách giáo khoa được nữa đúng không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L348_06','V348','小林',6,'没错，拍照翻译准确度很高，日常学习够用。','méi cuò， pāi zhào fān yì zhǔn què dù hěn gāo， rì cháng xué xí gòu yòng。','Đúng rồi, chụp ảnh dịch độ chính xác cao lắm, học hành hàng ngày dùng tẹt ga luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L348_07','V348','阮明',7,'太好了，我现在就下载安装试试吧。','tài hǎo le， wǒ xiàn zài jiù xià zài ān zhuāng shì shì ba。','Tuyệt quá, để tao tải về cài thử ngay đây.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT349','S115','Gia hạn gói cước SIM khi hết hạn',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V349','SIT349','P1','twist','ban_chinh_thuc',NULL,'国内手机运营商会推出专属学生优惠套餐，优惠到期或活动结束就无法办理。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L349_01','V349','阮明',1,'您好，我的手机流量套餐今天到期，想现场续费。','nín hǎo， wǒ de shǒu jī liú liàng tào cān jīn tiān dào qī， xiǎng xiàn chǎng xù fèi。','Chào anh, gói cước data điện thoại của em hôm nay hết hạn, em muốn gia hạn luôn tại đây ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L349_02','V349','工作人员',2,'可以，出示手机卡号，我帮你查询套餐选项。','kě yǐ， chū shì shǒu jī kǎ hào， wǒ bāng nǐ chá xún tào cān xuǎn xiàng。','Được, em cho xem số sim để anh kiểm tra các gói cước nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L349_03','V349','阮明',3,'我平时流量用得多，有没有不限流量的学生套餐？','wǒ píng shí liú liàng yòng dé duō， yǒu méi yǒu bù xiàn liú liàng de xué shēng tào cān？','Em thường dùng data nhiều, có gói sinh viên không giới hạn dung lượng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L349_04','V349','工作人员',4,'学生专属套餐本月已经下架，只能选普通套餐嘛。','xué shēng zhuān shǔ tào cān běn yuè yǐ jīng xià jià， zhǐ néng xuǎn pǔ tōng tào cān ma。','Gói dành riêng cho sinh viên tháng này ngừng bán rồi, chỉ còn gói thường thôi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L349_05','V349','阮明',5,'啊，那普通套餐每月多少流量，多少钱月租？','a， nà pǔ tōng tào cān měi yuè duō shǎo liú liàng， duō shǎo qián yuè zū？','À, vậy gói thường mỗi tháng bao nhiêu dung lượng, cước tháng bao nhiêu ạ?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L349_06','V349','工作人员',6,'每月40G流量，月租三十九元，性价比很高。','měi yuè 40G liú liàng， yuè zū sān shí jiǔ yuán， xìng jià bǐ hěn gāo。','Mỗi tháng 40G, cước tháng ba mươi chín tệ, khá đáng đồng tiền đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L349_07','V349','阮明',7,'行，那就办理这个普通套餐续费吧。','xíng， nà jiù bàn lǐ zhè ge pǔ tōng tào cān xù fèi ba。','Được ạ, vậy đăng ký gia hạn gói thường này cho em.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT350','S116','Nhờ sửa lỗi kết nối wifi trong phòng',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V350','SIT350','P1','suon_se','ban_chinh_thuc',NULL,'宽带套餐保修期内，线路、WiFi故障可免费上门维修，无需支付人工费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L350_01','V350','阮明',1,'师傅，我房间WiFi突然连不上了，麻烦上门看看吧。','shī fù， wǒ fáng jiān WiFi tū rán lián bù shàng le， má fán shàng mén kàn kàn ba。','Anh ơi, WiFi phòng em tự dưng không kết nối được nữa, phiền anh qua xem giúp em với.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L350_02','V350','维修师傅',2,'好，我先检查光猫和路由器，大概率是线路松动。','hǎo， wǒ xiān jiǎn chá guāng māo hé lù yóu qì， dà gài lǜ shì xiàn lù sōng dòng。','Được, để anh kiểm tra modem quang với router trước đã, chắc là do đường dây bị lỏng thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L350_03','V350','阮明',3,'昨天网络还很流畅，今天一早直接断网了呢。','zuó tiān wǎng luò hái hěn liú chàng， jīn tiān yī zǎo zhí jiē duàn wǎng le ne。','Hôm qua mạng vẫn chạy êm ru mà, sáng nay tự dưng mất mạng luôn.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L350_04','V350','维修师傅',4,'我重新插紧线路，再重置路由器就能恢复。','wǒ chóng xīn chā jǐn xiàn lù， zài zhòng zhì lù yóu qì jiù néng huī fù。','Anh cắm chặt lại dây, rồi reset lại router là sẽ hoạt động lại thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L350_05','V350','阮明',5,'维修需要额外收取服务费吗？','wéi xiū xū yào é wài shōu qǔ fú wù fèi ma？','Sửa như vậy có tính thêm phí dịch vụ không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L350_06','V350','维修师傅',6,'在宽带保修期内，上门检修完全免费。','zài kuān dài bǎo xiū qī nèi， shàng mén jiǎn xiū wán quán miǎn fèi。','Còn trong thời hạn bảo hành mạng thì đến kiểm tra hoàn toàn miễn phí.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L350_07','V350','阮明',7,'太好了，辛苦师傅帮忙处理啦。','tài hǎo le， xīn kǔ shī fù bāng máng chǔ lǐ la。','Tuyệt quá, cảm ơn anh đã giúp em xử lý nhé.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT351','S119','Chuyển tiền cho bạn qua app ngân hàng',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V351','SIT351','P1','suon_se','ban_chinh_thuc',NULL,'国内手机银行转账实时到账，会自动发送短信通知，转账前务必核对姓名卡号。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L351_01','V351','阮明',1,'你好，我想在手机银行APP给同学转账。','nǐ hǎo， wǒ xiǎng zài shǒu jī yín háng APP gěi tóng xué zhuǎn zhàng。','Chào chị, em muốn chuyển tiền cho bạn học qua app ngân hàng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L351_02','V351','客服',2,'您好，您需要输入对方银行卡号和姓名核对哦。','nín hǎo， nín xū yào shū rù duì fāng yín háng kǎ hào hé xìng míng hé duì ó。','Chào em, em cần nhập số thẻ ngân hàng và tên của người nhận để đối chiếu nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L351_03','V351','阮明',3,'转账有限额吗，我一次转三千元可以吗？','zhuǎn zhàng yǒu xiàn é ma， wǒ yī cì zhuǎn sān qiān yuán kě yǐ ma？','Chuyển khoản có giới hạn không ạ, em chuyển một lần ba nghìn tệ được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L351_04','V351','客服',4,'学生一类银行卡单日转账限额五万元，完全没问题。','xué shēng yī lèi yín háng kǎ dān rì zhuǎn zhàng xiàn é wǔ wàn yuán， wán quán méi wèn tí。','Thẻ ngân hàng loại dành cho sinh viên hạn mức chuyển khoản một ngày là năm mươi nghìn tệ, hoàn toàn không vấn đề gì.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L351_05','V351','阮明',5,'转账成功之后会有短信通知双方吗？','zhuǎn zhàng chéng gōng zhī hòu huì yǒu duǎn xìn tōng zhī shuāng fāng ma？','Chuyển thành công rồi thì có tin nhắn báo cho cả hai bên không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L351_06','V351','客服',6,'双方都会收到提醒，方便核对交易记录呢。','shuāng fāng dōu huì shōu dào tí xǐng， fāng biàn hé duì jiāo yì jì lù ne。','Cả hai bên đều sẽ nhận được thông báo, tiện đối chiếu giao dịch luôn.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L351_07','V351','阮明',7,'清楚操作流程了，谢谢你的讲解吧。','qīng chǔ cāo zuò liú chéng le， xiè xiè nǐ de jiǎng jiě ba。','Em hiểu rõ quy trình rồi ạ, cảm ơn chị đã hướng dẫn nhé.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT352','S119','Nhận tiền gia đình gửi từ nước ngoài',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V352','SIT352','P1','twist','chinh_thuc',NULL,'境外跨境汇款需要银行系统清算，无法实时兑换人民币取现，留学生需携带护照办理外汇业务。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L352_01','V352','阮明',1,'您好，我家人从境外给我汇了一笔生活费，我来办理结汇。','nín hǎo， wǒ jiā rén cóng jìng wài gěi wǒ huì le yī bǐ shēng huó fèi， wǒ lái bàn lǐ jié huì。','Chào chị, gia đình tôi từ nước ngoài chuyển cho tôi một khoản sinh hoạt phí, tôi đến làm thủ tục đổi ngoại tệ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L352_02','V352','柜员',2,'请出示你的护照和银行卡，我先查询外汇到账状态。','qǐng chū shì nǐ de hù zhào hé yín háng kǎ， wǒ xiān chá xún wài huì dào zhàng zhuàng tài。','Anh vui lòng cho xem hộ chiếu và thẻ ngân hàng, tôi kiểm tra tình trạng tiền về trước đã.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L352_03','V352','阮明',3,'好，证件都在这里，大概昨天傍晚汇出的。','hǎo， zhèng jiàn dōu zài zhè lǐ， dà gài zuó tiān bàng wǎn huì chū de。','Vâng, giấy tờ đây đủ cả, khoảng chiều tối hôm qua thì tiền được chuyển đi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L352_04','V352','柜员',4,'抱歉，这笔汇款还未清算，今天暂时无法提取嘛。','bào qiàn， zhè bǐ huì kuǎn hái wèi qīng suàn， jīn tiān zàn shí wú fǎ tí qǔ ma。','Xin lỗi anh, khoản tiền này chưa được thanh toán bù trừ xong, hôm nay tạm thời chưa rút được.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L352_05','V352','阮明',5,'啊？那要等到什么时候才能兑换人民币？','a？ nà yào děng dào shén me shí hòu cái néng duì huàn rén mín bì？','Ơ? Vậy phải đợi đến khi nào mới đổi được sang nhân dân tệ ạ?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L352_06','V352','柜员',6,'明天上午系统完成清算，你再来柜台办理就行。','míng tiān shàng wǔ xì tǒng wán chéng qīng suàn， nǐ zài lái guì tái bàn lǐ jiù xíng。','Sáng mai hệ thống hoàn tất thanh toán bù trừ, anh quay lại quầy làm thủ tục là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L352_07','V352','阮明',7,'好，我明天一早过来，麻烦你登记一下。','hǎo， wǒ míng tiān yī zǎo guò lái， má fán nǐ dēng jì yī xià。','Vâng, mai tôi qua từ sáng sớm, phiền chị đăng ký giúp tôi trước nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT353','S119','Rút tiền tại ATM',NULL,'A2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V353','SIT353','P1','suon_se','tuy_y',NULL,'国内ATM取款有现金上限，忘记取卡会被机器回收，需要带身份证去柜台取回。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L353_01','V353','阮明',1,'学长，这个ATM机怎么取款，我不太会操作啊。','xué zhǎng， zhè ge ATM jī zěn me qǔ kuǎn， wǒ bù tài huì cāo zuò a。','Anh ơi, cái máy ATM này rút tiền kiểu gì thế, em không rành thao tác lắm.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L353_02','V353','学长',2,'先插银行卡，输入密码，再选择取款金额就行啦。','xiān chā yín háng kǎ， shū rù mì mǎ， zài xuǎn zé qǔ kuǎn jīn é jiù xíng la。','Cắm thẻ ngân hàng vào trước, nhập mật khẩu, rồi chọn số tiền cần rút là xong ấy mà.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L353_03','V353','阮明',3,'单日最多能取多少现金，会不会有限制？','dān rì zuì duō néng qǔ duō shǎo xiàn jīn， huì bú huì yǒu xiàn zhì？','Một ngày rút tối đa được bao nhiêu tiền mặt, có bị giới hạn gì không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L353_04','V353','学长',4,'ATM单日限额两万，日常取生活费完全够用呢。','ATM dān rì xiàn é liǎng wàn， rì cháng qǔ shēng huó fèi wán quán gòu yòng ne。','ATM giới hạn hai vạn tệ một ngày, đủ xài thoải mái cho sinh hoạt phí hàng ngày luôn.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L353_05','V353','阮明',5,'取完钱之后一定要记得拔卡对吧？','qǔ wán qián zhī hòu yí dìng yào jì de bá kǎ duì ba？','Rút tiền xong nhất định phải nhớ rút thẻ ra đúng không?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L353_06','V353','学长',6,'没错，超时不取卡机器会自动吞卡的。','méi cuò， chāo shí bù qǔ kǎ jī qì huì zì dòng tūn kǎ de。','Đúng rồi, để quá lâu không rút thẻ là máy tự động nuốt thẻ luôn đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L353_07','V353','阮明',7,'太感谢你提醒我，不然我很容易忘啦。','tài gǎn xiè nǐ tí xǐng wǒ， bù rán wǒ hěn róng yì wàng la。','Cảm ơn anh nhắc em nhiều nha, không thì em kiểu gì cũng quên mất.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT354','S119','Báo mất thẻ và xin khóa thẻ khẩn cấp',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V354','SIT354','P1','suon_se','chinh_thuc',NULL,'银行卡丢失第一时间电话挂失锁卡，能保障账户资金安全，补办卡片必须线下网点办理。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L354_01','V354','阮明',1,'您好，我的银行卡遗失了，申请紧急挂失锁卡。','nín hǎo， wǒ de yín háng kǎ yí shī le， shēn qǐng jǐn jí guà shī suǒ kǎ。','Chào chị, tôi bị mất thẻ ngân hàng, tôi muốn xin khóa thẻ khẩn cấp ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L354_02','V354','客服',2,'请告知您姓名、银行卡尾号以及身份证号吧。','qǐng gào zhī nín xìng míng、 yín háng kǎ wěi hào yǐ jí shēn fèn zhèng hào ba。','Anh vui lòng cho biết họ tên, 4 số cuối của thẻ và số CMND/CCCD ạ.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L354_03','V354','阮明',3,'全部信息我都记好了，现在报给你核对。','quán bù xìn xī wǒ dōu jì hǎo le， xiàn zài bào gěi nǐ hé duì。','Tất cả thông tin tôi đã ghi sẵn rồi, để tôi đọc cho chị đối chiếu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L354_04','V354','客服',4,'已经为您临时冻结卡片，资金不会被盗刷呢。','yǐ jīng wèi nín lín shí dòng jié kǎ piàn， zī jīn bú huì bèi dào shuā ne。','Chúng tôi đã tạm khóa thẻ cho anh rồi, tiền trong tài khoản sẽ không bị mất đâu ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L354_05','V354','阮明',5,'那之后补办新卡需要去线下柜台办理吗？','nà zhī hòu bǔ bàn xīn kǎ xū yào qù xiàn xià guì tái bàn lǐ ma？','Vậy sau này muốn làm lại thẻ mới thì có phải ra quầy giao dịch không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L354_06','V354','客服',6,'是的，携带护照前往就近网点即可补办。','shì de， xié dài hù zhào qián wǎng jiù jìn wǎng diǎn jí kě bǔ bàn。','Vâng, anh mang theo hộ chiếu đến chi nhánh gần nhất là làm lại được ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L354_07','V354','阮明',7,'太感谢了，还好及时打电话挂失啦。','tài gǎn xiè le， hái hǎo jí shí dǎ diàn huà guà shī la。','Cảm ơn chị nhiều, may mà tôi gọi điện báo mất kịp thời.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT355','S119','Yêu cầu in sao kê giao dịch',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V355','SIT355','P1','suon_se','ban_chinh_thuc',NULL,'留学生打印银行卡流水用于留学报备，多数银行免费办理，打印文件加盖公章才具备证明效力。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L355_01','V355','阮明',1,'你好，我需要打印近半年的银行卡交易流水。','nǐ hǎo， wǒ xū yào dǎ yìn jìn bàn nián de yín háng kǎ jiāo yì liú shuǐ。','Chào chị, tôi cần in sao kê giao dịch thẻ ngân hàng khoảng nửa năm gần đây.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L355_02','V355','柜员',2,'可以，出示你的银行卡和护照，我帮你调取记录哦。','kě yǐ， chū shì nǐ de yín háng kǎ hé hù zhào， wǒ bāng nǐ diào qǔ jì lù ó。','Được ạ, anh cho em xin thẻ ngân hàng và hộ chiếu, em tra giúp anh nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L355_03','V355','阮明',3,'打印流水需要收取手续费吗？','dǎ yìn liú shuǐ xū yào shōu qǔ shǒu xù fèi ma？','In sao kê thì có tính phí không vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L355_04','V355','柜员',4,'留学生办理留学相关流水打印是免费的呢。','liú xué shēng bàn lǐ liú xué xiāng guān liú shuǐ dǎ yìn shì miǎn fèi de ne。','Du học sinh in sao kê phục vụ mục đích du học thì được miễn phí ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L355_05','V355','阮明',5,'太好了，我要交给学校作为资金证明材料。','tài hǎo le， wǒ yào jiāo gěi xué xiào zuò wéi zī jīn zhèng míng cái liào。','Tốt quá, tôi cần nộp cho trường làm giấy chứng minh tài chính.',NULL) ON CONFLICT DO NOTHING;
