INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT626','SF5','签证续签材料资金不足，远程和父母沟通加急汇款',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V626','SIT626','P1','suon_se','chinh_thuc',NULL,'签证材料资金不达标会直接驳回续签申请，遇到资金缺口家人会优先选择加急汇款渠道，不计较高额手续费保障证件办理。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L626_01','V626','阮明',1,'爸，下周就要递交居留续签材料，活期存款余额还差一部分标准。','bà， xià zhōu jiù yào dì jiāo jū liú xù qiān cái liào， huó qī cún kuǎn yú é hái chà yī bù fèn biāo zhǔn。','Bố ơi, tuần sau con phải nộp hồ sơ gia hạn cư trú rồi, mà số dư tài khoản vẫn còn thiếu một phần so với mức yêu cầu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L626_02','V626','父亲',2,'还差多少，我今天立刻走加急跨境电汇给你补足流水。','hái chà duō shǎo， wǒ jīn tiān lì kè zǒu jiā jí kuà jìng diàn huì gěi nǐ bǔ zú liú shuǐ。','Còn thiếu bao nhiêu, để bố chuyển khoản quốc tế hỏa tốc bù đủ số dư cho con ngay hôm nay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L626_03','V626','阮明',3,'还差四千元，加急汇款隔天就能到账，刚好赶上办理日期。','hái chà sì qiān yuán， jiā jí huì kuǎn gé tiān jiù néng dào zhàng， gāng hǎo gǎn shàng bàn lǐ rì qī。','Còn thiếu bốn nghìn tệ ạ, chuyển gấp thì hôm sau là vào tài khoản rồi, vừa kịp ngày làm thủ tục luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L626_04','V626','父亲',4,'加急渠道手续费更高，但是能保证不耽误你的签证办理。','jiā jí qú dào shǒu xù fèi gèng gāo， dàn shì néng bǎo zhèng bù dān wù nǐ de qiān zhèng bàn lǐ。','Chuyển qua kênh hỏa tốc thì phí cao hơn, nhưng đảm bảo không làm trễ việc xin visa của con.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L626_05','V626','阮明',5,'我计算好金额，等资金到账次日立刻打印银行流水。','wǒ jì suàn hǎo jīn é， děng zī jīn dào zhàng cì rì lì kè dǎ yìn yín háng liú shuǐ。','Con tính toán số tiền rồi ạ, đợi tiền vào tài khoản là hôm sau con in sao kê ngay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L626_06','V626','父亲',6,'收到汇款短信第一时间告知我，确认入账再去大厅办手续。','shōu dào huì kuǎn duǎn xìn dì yī shí jiān gào zhī wǒ， què rèn rù zhàng zài qù dà tīng bàn shǒu xù。','Nhận được tin nhắn báo có tiền chuyển vào thì báo bố biết ngay, xác nhận tiền vào rồi mới đến quầy làm thủ tục nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L626_07','V626','阮明',7,'感谢您加急处理汇款，避免签证断签影响在校学习。','gǎn xiè nín jiā jí chǔ lǐ huì kuǎn， bì miǎn qiān zhèng duàn qiān yǐng xiǎng zài xiào xué xí。','Cảm ơn bố đã chuyển tiền gấp giúp con, để visa không bị gián đoạn ảnh hưởng đến việc học ở trường.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT627','SF5','航班延误、行程变动，立刻发消息同步家人避免担忧',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V627','SIT627','P1','suon_se','tuy_y',NULL,'出行航班延误、取消属于高频突发变动，国内家长十分在意行程实时动态，子女必须第一时间同步变动消息。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L627_01','V627','阮明',1,'妈，我原定今天返程航班大面积延误，起飞推迟六个小时。','mā， wǒ yuán dìng jīn tiān fǎn chéng háng bān dà miàn jī yán wù， qǐ fēi tuī chí liù gè xiǎo shí。','Mẹ ơi, chuyến bay về nước hôm nay của con bị delay diện rộng, giờ cất cánh lùi lại sáu tiếng luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L627_02','V627','母亲',2,'还好你及时发消息，我一直在盯着航班时刻表担心你落地太晚。','hái hǎo nǐ jí shí fā xiāo xī， wǒ yì zhí zài dīng zhe háng bān shí kè biǎo dān xīn nǐ luò dì tài wǎn。','May mà con báo tin kịp thời, mẹ cứ dán mắt vào lịch bay lo con hạ cánh muộn quá đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L627_03','V627','阮明',3,'机场安排临时休息区域，提供简餐，不会让我长时间干等。','jī chǎng ān pái lín shí xiū xī qū yù， tí gōng jiǎn cān， bú huì ràng wǒ zhǎng shí jiān gàn děng。','Sân bay bố trí khu nghỉ tạm, có phục vụ đồ ăn nhẹ nên con không phải chờ suông cả đống thời gian đâu mẹ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L627_04','V627','母亲',4,'落地到达目的地之后，第一时间给我发一条平安消息吧。','luò dì dào dá mù dì dì zhī hòu， dì yī shí jiān gěi wǒ fā yī tiáo píng ān xiāo xī ba。','Hạ cánh tới nơi rồi thì nhắn ngay một tin báo bình an cho mẹ nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L627_05','V627','阮明',5,'落地取完行李、坐上交通车辆，立刻同步文字报平安。','luò dì qǔ wán xíng lǐ、 zuò shàng jiāo tōng chē liàng， lì kè tóng bù wén zì bào píng ān。','Con hạ cánh lấy hành lý xong, lên xe rồi là con nhắn tin báo bình an ngay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L627_06','V627','母亲',6,'路途奔波注意休息，不用硬撑着长时间跟我们视频。','lù tú bēn bō zhù yì xiū xī， bù yòng yìng chēng zhe zhǎng shí jiān gēn wǒ men shì pín。','Đường xa vất vả thì nhớ nghỉ ngơi, đừng cố gọi video dài với bố mẹ làm gì cho mệt.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L627_07','V627','阮明',7,'我会随时同步航班动态，不让您一直悬着心。','wǒ huì suí shí tóng bù háng bān dòng tài， bù ràng nín yì zhí xuán zhe xīn。','Con sẽ cập nhật tình hình chuyến bay liên tục, không để mẹ cứ thấp thỏm mãi đâu.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT628','SF6','和父母商量寒暑假回国机票时间，对比价格选择合适航班',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V628','SIT628','P1','twist','tuy_y',NULL,'家长选购国际机票会同时考量票价、落地时段、夜间出行安全，不会单纯选择最低价航班。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L628_01','V628','阮明',1,'寒暑假有两档回国机票，早一点的班次价格贵三成，晚班性价比更高。','hán shǔ jià yǒu liǎng dàng huí guó jī piào， zǎo yì diǎn de bān cì jià gé guì sān chéng， wǎn bān xìng jià bǐ gèng gāo。','Kỳ nghỉ hè đông có hai khung giờ vé máy bay về nước, chuyến sớm giá đắt hơn ba phần, chuyến muộn thì hời hơn nhiều.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L628_02','V628','母亲',2,'晚班抵达越南是深夜，独自打车回家安全方面我们不放心嘛。','wǎn bān dǐ dá yuè nán shì shēn yè， dú zì dǎ chē huí jiā ān quán fāng miàn wǒ men bù fàng xīn ma。','Chuyến muộn thì tới Việt Nam là nửa đêm rồi, một mình bắt taxi về nhà bố mẹ không yên tâm về khoản an toàn đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L628_03','V628','阮明',3,'深夜机场有正规接驳大巴直达市区，比单独打车安全很多。','shēn yè jī chǎng yǒu zhèng guī jiē bó dà bā zhí dá shì qū， bǐ dān dú dǎ chē ān quán hěn duō。','Nửa đêm sân bay vẫn có xe buýt trung chuyển chính quy chạy thẳng vào trung tâm, an toàn hơn tự bắt taxi nhiều mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L628_04','V628','父亲',4,'差价不小，如果接驳交通稳妥，可以选择平价晚班航班。','chā jià bù xiǎo， rú guǒ jiē bó jiāo tōng wěn tuǒ， kě yǐ xuǎn zé píng jià wǎn bān háng bān。','Chênh lệch giá cũng không nhỏ, nếu xe trung chuyển đáng tin cậy thì chọn chuyến muộn giá rẻ hơn cũng được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L628_05','V628','阮明',5,'我查询了机场大巴运营时间，深夜落地仍有专线班车运行。','wǒ chá xún le jī chǎng dà bā yùn yíng shí jiān， shēn yè luò dì réng yǒu zhuān xiàn bān chē yùn xíng。','Con tra giờ hoạt động của xe buýt sân bay rồi, nửa đêm hạ cánh vẫn có tuyến xe chuyên chạy bình thường ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L628_06','V628','母亲',6,'那我们折中选择午间航班，价格适中、落地时间也安全。','nà wǒ men zhé zhōng xuǎn zé wǔ jiān háng bān， jià gé shì zhōng、 luò dì shí jiān yě ān quán。','Vậy thôi mình chọn dung hòa chuyến bay giữa trưa, giá vừa phải mà giờ hạ cánh cũng an toàn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L628_07','V628','阮明',7,'我对比三个航班价格与落地时段，把最优方案发给你们确认。','wǒ duì bǐ sān gè háng bān jià gé yǔ luò dì shí duàn， bǎ zuì yōu fāng àn fā gěi nǐ men què rèn。','Con so sánh giá cả và giờ hạ cánh của ba chuyến bay rồi, để con gửi phương án tốt nhất cho bố mẹ duyệt nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT629','SF6','讨论毕业后规划（留华深造/回国工作），和家人交换想法',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V629','SIT629','P1','suon_se','ban_chinh_thuc',NULL,'中国家庭在子女升学、就业选择上，大多会先倾听子女自身意愿，共同商量长远规划，不强行安排人生道路。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L629_01','V629','阮明',1,'毕业有两条路线，留在中国读硕士，或者直接回国找相关工作。','bì yè yǒu liǎng tiáo lù xiàn， liú zài zhōng guó dú shuò shì， huò zhě zhí jiē huí guó zhǎo xiāng guān gōng zuò。','Sau khi tốt nghiệp có hai hướng, hoặc là ở lại Trung Quốc học thạc sĩ, hoặc là về nước tìm việc luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L629_02','V629','父亲',2,'留在国内深造汉语专业，未来就业选择会更广阔一些。','liú zài guó nèi shēn zào hàn yǔ zhuān yè， wèi lái jiù yè xuǎn zé huì gèng guǎng kuò yī xiē。','Ở lại trong nước học sâu thêm chuyên ngành tiếng Trung thì sau này cơ hội việc làm sẽ rộng mở hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L629_03','V629','阮明',3,'回国本地外贸行业也有对口岗位，离家近方便照顾你们。','huí guó běn dì wài mào háng yè yě yǒu duì kǒu gǎng wèi， lí jiā jìn fāng biàn zhào gù nǐ men。','Về nước thì ngành ngoại thương ở địa phương cũng có vị trí phù hợp, lại gần nhà tiện chăm sóc bố mẹ nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L629_04','V629','母亲',4,'我们尊重你的个人发展意愿，不会强迫你固定选择一条路。','wǒ men zūn zhòng nǐ de gè rén fā zhǎn yì yuàn， bú huì qiǎng pò nǐ gù dìng xuǎn zé yī tiáo lù。','Bố mẹ tôn trọng nguyện vọng phát triển của con, sẽ không ép con phải chọn cố định một hướng đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L629_05','V629','阮明',5,'我先实习半年，感受两边行业环境，再确定最终发展方向。','wǒ xiān shí xí bàn nián， gǎn shòu liǎng biān háng yè huán jìng， zài què dìng zuì zhōng fā zhǎn fāng xiàng。','Con định thực tập nửa năm trước, để cảm nhận môi trường ngành nghề cả hai bên rồi mới quyết định hướng đi cuối cùng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L629_06','V629','父亲',6,'实习期间每月同步你的感受，我们一起分析利弊再做决定。','shí xí qī jiān měi yuè tóng bù nǐ de gǎn shòu， wǒ men yì qǐ fēn xī lì bì zài zuò jué dìng。','Trong thời gian thực tập con cập nhật cảm nhận cho bố mẹ hàng tháng nhé, cả nhà cùng phân tích lợi hại rồi quyết định.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L629_07','V629','阮明',7,'谢谢爸妈尊重我的规划，有想法第一时间和你们沟通。','xiè xiè bà mā zūn zhòng wǒ de guī huà， yǒu xiǎng fǎ dì yī shí jiān hé nǐ men gōu tōng。','Cảm ơn bố mẹ đã tôn trọng kế hoạch của con, có ý tưởng gì con sẽ trao đổi với bố mẹ ngay ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT630','SF6','签证有效期快到期，视频和父母说明续办流程、所需资金',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V630','SIT630','P1','twist','chinh_thuc',NULL,'居留续签存在固定办理周期，证件上交期间无法出行，留学生需要提前和家人沟通资金、时间安排，预留充足缓冲时间。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L630_01','V630','阮明',1,'我的学生居留许可还有三十天到期，现在开始准备续签全套材料。','wǒ de xué shēng jū liú xǔ kě hái yǒu sān shí tiān dào qī， xiàn zài kāi shǐ zhǔn bèi xù qiān quán tào cái liào。','Giấy phép cư trú diện học sinh của con còn ba mươi ngày nữa là hết hạn, giờ con bắt đầu chuẩn bị đầy đủ hồ sơ gia hạn ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L630_02','V630','父亲',2,'续签需要额外支付手续费，存款流水也有最低余额要求对吧？','xù qiān xū yào é wài zhī fù shǒu xù fèi， cún kuǎn liú shuǐ yě yǒu zuì dī yú é yāo qiú duì ba？','Gia hạn cần đóng thêm lệ phí thủ tục, và số dư tài khoản cũng có yêu cầu tối thiểu đúng không?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L630_03','V630','阮明',3,'工本费金额不高，但是活期流水需要稳定一万元以上留存三个月嘛。','gōng běn fèi jīn é bù gāo， dàn shì huó qī liú shuǐ xū yào wěn dìng yī wàn yuán yǐ shàng liú cún sān gè yuè ma。','Lệ phí thủ tục thì không cao đâu ạ, nhưng số dư tài khoản cần duy trì ổn định trên một vạn tệ trong ba tháng ạ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L630_04','V630','父亲',4,'卡里流动资金不足的话，提前一周告诉我，我提前汇款补足。','kǎ lǐ liú dòng zī jīn bù zú de huà， tí qián yī zhōu gào sù wǒ， wǒ tí qián huì kuǎn bǔ zú。','Nếu trong tài khoản không đủ tiền lưu động thì báo bố trước một tuần, bố sẽ chuyển tiền bù đủ trước.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L630_05','V630','阮明',5,'材料齐全七个工作日办结，办理期间护照要上交出入境大厅。','cái liào qí quán qī gè gōng zuò rì bàn jié， bàn lǐ qī jiān hù zhào yào shàng jiāo chū rù jìng dà tīng。','Hồ sơ đầy đủ thì bảy ngày làm việc là xong, trong thời gian xử lý phải nộp hộ chiếu cho phòng xuất nhập cảnh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L630_06','V630','父亲',6,'上交护照期间出行不方便，记得提前办好临时出行证明。','shàng jiāo hù zhào qī jiān chū xíng bù fāng biàn， jì de tí qián bàn hǎo lín shí chū xíng zhèng míng。','Trong lúc nộp hộ chiếu thì đi lại sẽ bất tiện, nhớ làm sẵn giấy thông hành tạm thời trước nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L630_07','V630','阮明',7,'我会把控办理时间，预留缓冲期，不会出现签证断签的情况。','wǒ huì bǎ kòng bàn lǐ shí jiān， yù liú huǎn chōng qī， bú huì chū xiàn qiān zhèng duàn qiān de qíng kuàng。','Con sẽ kiểm soát thời gian làm thủ tục, để dành thời gian dự phòng, sẽ không để xảy ra chuyện visa bị gián đoạn đâu.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT701','SSH1','入住新生宿舍，向宿管领取钥匙、核对宿舍物品清单',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V701','SIT701','P1','suon_se','ban_chinh_thuc',NULL,'高校宿舍入住必须现场核验室内设施并签字登记，人为损坏物品退房会从住宿押金扣除维修费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L701_01','V701','阮明',1,'阿姨您好，今天办理入住，麻烦给我宿舍钥匙和门禁卡吧。','ā yí nín hǎo， jīn tiān bàn lǐ rù zhù， má fán gěi wǒ sù shè yào shi hé mén jìn kǎ ba。','Cô ơi, hôm nay em làm thủ tục nhập ở, phiền cô đưa cho em chìa khóa phòng và thẻ ra vào ạ.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L701_02','V701','宿管阿姨',2,'先出示你的录取证件，我们一起进屋核对屋内家具清单哦。','xiān chū shì nǐ de lù qǔ zhèng jiàn， wǒ men yì qǐ jìn wū hé duì wū nèi jiā jù qīng dān ó。','Em xuất trình giấy báo trúng tuyển trước đã, rồi mình cùng vào phòng kiểm tra danh sách đồ đạc trong phòng nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L701_03','V701','阮明',3,'清单上写书桌、衣柜、椅子、空调，我需要逐一检查完好度吗？','qīng dān shàng xiě shū zhuō、 yī guì、 yǐ zi、 kōng tiáo， wǒ xū yào zhú yī jiǎn chá wán hǎo dù ma？','Trong danh sách ghi bàn học, tủ quần áo, ghế, điều hòa, em có cần kiểm tra từng món xem còn nguyên vẹn không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L701_04','V701','宿管阿姨',4,'对，有划痕、损坏当场标注，退房时就不会扣押金了。','duì， yǒu huà hén、 sǔn huài dāng chǎng biāo zhù， tuì fáng shí jiù bú huì kòu yā jīn le。','Đúng rồi, nếu có vết xước hay hư hỏng thì ghi chú ngay tại chỗ, để lúc trả phòng không bị trừ tiền cọc.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L701_05','V701','阮明',5,'墙面很干净，家电都能正常使用，没有破损地方。','qiáng miàn hěn gān jìng， jiā diàn dōu néng zhèng cháng shǐ yòng， méi yǒu pò sǔn dì fāng。','Tường rất sạch, các thiết bị điện đều dùng bình thường, không có chỗ nào hỏng cả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L701_06','V701','宿管阿姨',6,'确认无误就在物品清单签字，钥匙一共两把收好。','què rèn wú wù jiù zài wù pǐn qīng dān qiān zì， yào shi yī gòng liǎng bǎ shōu hǎo。','Xác nhận không có vấn đề gì thì ký vào danh sách đồ đạc, chìa khóa có hai chiếc nhớ giữ cẩn thận.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L701_07','V701','阮明',7,'好的，清单我签字，后续宿舍有问题再来找您报修。','hǎo de， qīng dān wǒ qiān zì， hòu xù sù shè yǒu wèn tí zài lái zhǎo nín bào xiū。','Vâng ạ, em ký vào danh sách, sau này phòng có vấn đề gì em sẽ lại tìm cô báo sửa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT702','SSH1','宿舍空调故障不制冷，报修物业上门检修',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V702','SIT702','P1','twist','tuy_y',NULL,'校内宿舍家电基础检修、滤网清洗免费，制冷剂、配件更换属于耗材，会统一登记收费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L702_01','V702','阮明',1,'师傅，我宿舍空调吹出来全是热风，完全没法制冷啊。','shī fù， wǒ sù shè kōng tiáo chuī chū lái quán shì rè fēng， wán quán méi fǎ zhì lěng a。','Chú ơi, máy lạnh phòng em thổi ra toàn hơi nóng, chẳng làm mát được tí nào luôn.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L702_02','V702','维修师傅',2,'我先开机检测，大概率滤网积灰堵塞，也可能缺制冷剂。','wǒ xiān kāi jī jiǎn cè， dà gài lǜ lǜ wǎng jī huī dǔ sè， yě kě néng quē zhì lěng jì。','Để chú bật máy kiểm tra trước, khả năng cao là lưới lọc bám bụi bị nghẹt, cũng có thể thiếu gas làm lạnh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L702_03','V702','阮明',3,'上周还正常使用，昨晚突然出故障，没有人为磕碰损坏嘛。','shàng zhōu hái zhèng cháng shǐ yòng， zuó wǎn tū rán chū gù zhàng， méi yǒu rén wéi kē pèng sǔn huài ma。','Tuần trước còn dùng bình thường mà, tối qua tự dưng hỏng, đâu có ai va đập làm hỏng đâu nhỉ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L702_04','V702','维修师傅',4,'滤网我拆下来清洗，如果缺氟就要登记预约次日加制冷剂。','lǜ wǎng wǒ chāi xià lái qīng xǐ， rú guǒ quē fú jiù yào dēng jì yù yuē cì rì jiā zhì lěng jì。','Lưới lọc chú tháo ra rửa cho, nếu thiếu gas thì phải đăng ký hẹn hôm sau bơm gas thêm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L702_05','V702','阮明',5,'清洗滤网免费吗，加制冷剂需要我额外支付费用？','qīng xǐ lǜ wǎng miǎn fèi ma， jiā zhì lěng jì xū yào wǒ é wài zhī fù fèi yòng？','Rửa lưới lọc có miễn phí không chú, bơm gas thì em có phải trả thêm tiền không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L702_06','V702','维修师傅',6,'日常清洗免费，制冷剂损耗需要统一走后勤耗材计费。','rì cháng qīng xǐ miǎn fèi， zhì lěng jì sǔn hào xū yào tǒng yī zǒu hòu qín hào cái jì fèi。','Vệ sinh định kỳ thì miễn phí, còn hao gas thì phải tính chung vào chi phí vật tư hậu cần.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L702_07','V702','阮明',7,'先清洗滤网看看效果，不够制冷再预约加氟。','xiān qīng xǐ lǜ wǎng kàn kàn xiào guǒ， bù gòu zhì lěng zài yù yuē jiā fú。','Vậy chú rửa lưới lọc trước xem sao đã, không đủ mát thì em hẹn bơm gas sau.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT703','SSH1','宿舍断电跳闸，找宿管排查电路、恢复供电',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V703','SIT703','P1','that_bai_nhe','tuy_y',NULL,'高校宿舍限制大功率电器，多设备同时使用极易触发过载保护跳闸，违规电器引发故障需学生承担维修费用。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L703_01','V703','阮明',1,'阿姨，我宿舍突然全屋断电，插座和顶灯全都没电了。','ā yí， wǒ sù shè tū rán quán wū duàn diàn， chā zuò hé dǐng dēng quán dōu méi diàn le。','Cô ơi, phòng em tự nhiên mất điện cả phòng, ổ cắm với đèn trần đều không có điện luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L703_02','V703','宿管阿姨',2,'是不是同时使用吹风机、电煮锅大功率电器跳闸？','shì bú shì tóng shí shǐ yòng chuī fēng jī、 diàn zhǔ guō dà gōng lǜ diàn qì tiào zhá？','Có phải cùng lúc dùng máy sấy tóc, nồi điện công suất lớn nên bị nhảy aptomat không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L703_03','V703','阮明',3,'我只用电脑和台灯，没有违规大功率电器，不清楚原因。','wǒ zhǐ yòng diàn nǎo hé tái dēng， méi yǒu wéi guī dà gōng lǜ diàn qì， bù qīng chǔ yuán yīn。','Em chỉ dùng máy tính với đèn bàn thôi, không có thiết bị công suất lớn gì vi phạm cả, không rõ vì sao luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L703_04','V703','宿管阿姨',4,'宿舍总闸在楼道配电箱，我去合闸，如果再次跳闸就要断电检修线路。','sù shè zǒng zhá zài lóu dào pèi diàn xiāng， wǒ qù hé zhá， rú guǒ zài cì tiào zhá jiù yào duàn diàn jiǎn xiū xiàn lù。','Cầu dao tổng của phòng ở tủ điện hành lang, để cô đi đóng lại, nếu nhảy tiếp thì phải cắt điện kiểm tra đường dây.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L703_05','V703','阮明',5,'合闸之后要是反复断电，今晚没法开灯学习怎么办？','hé zhá zhī hòu yào shì fǎn fù duàn diàn， jīn wǎn méi fǎ kāi dēng xué xí zěn me bàn？','Đóng cầu dao xong mà cứ bị mất điện liên tục thì tối nay em không bật đèn học bài được, biết làm sao đây?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L703_06','V703','宿管阿姨',6,'反复跳闸说明线路隐患，今晚临时安排隔壁空宿舍让你自习。','fǎn fù tiào zhá shuō míng xiàn lù yǐn huàn， jīn wǎn lín shí ān pái gé bì kōng sù shè ràng nǐ zì xí。','Nhảy liên tục thì chứng tỏ đường dây có vấn đề tiềm ẩn, tối nay cô sắp xếp tạm cho em sang phòng trống bên cạnh tự học.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L703_07','V703','阮明',7,'麻烦您先合闸恢复供电，我之后不用多余电器避免跳闸。','má fán nín xiān hé zhá huī fù gōng diàn， wǒ zhī hòu bù yòng duō yú diàn qì bì miǎn tiào zhá。','Phiền cô đóng cầu dao cho có điện lại trước đã, sau này em không dùng thêm thiết bị điện gì để khỏi bị nhảy nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT704','SSH1','宿舍楼道公共热水机不出热水，咨询宿管使用规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V704','SIT704','P1','suon_se','tuy_y',NULL,'校园公共热水设备统一定时启停，夜间停止加热节约水电，是国内高校通用管理方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L704_01','V704','阮明',1,'阿姨，楼道热水机按了出水键，一直没有热水流出呢。','ā yí， lóu dào rè shuǐ jī àn le chū shuǐ jiàn， yì zhí méi yǒu rè shuǐ liú chū ne。','Cô ơi, máy nước nóng ở hành lang em bấm nút xả nước rồi mà mãi không thấy nước nóng chảy ra gì cả.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L704_02','V704','宿管阿姨',2,'机器有定时加热时段，早上六点到晚上十一点才有热水哦。','jī qì yǒu dìng shí jiā rè shí duàn， zǎo shàng liù diǎn dào wǎn shàng shí yì diǎn cái yǒu rè shuǐ ó。','Máy có giờ hẹn đun nước, chỉ từ sáu giờ sáng đến mười một giờ tối mới có nước nóng thôi đó.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L704_03','V704','阮明',3,'现在十一点半，刚好过了加热时段，难怪不出热水。','xiàn zài shí yì diǎn bàn， gāng hǎo guò le jiā rè shí duàn， nán guài bù chū rè shuǐ。','Giờ là mười một rưỡi, vừa đúng qua giờ đun nước, thảo nào không có nước nóng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L704_04','V704','宿管阿姨',4,'如果中途停水，机器缺水也会暂停出水，明天一早恢复。','rú guǒ zhōng tú tíng shuǐ， jī qì quē shuǐ yě huì zàn tíng chū shuǐ， míng tiān yī zǎo huī fù。','Nếu giữa chừng bị cúp nước, máy thiếu nước cũng sẽ tạm ngừng xả, sáng mai là có lại thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L704_05','V704','阮明',5,'那我只能明天早上再来接热水洗漱、泡热水杯。','nà wǒ zhǐ néng míng tiān zǎo shàng zài lái jiē rè shuǐ xǐ shù、 pào rè shuǐ bēi。','Vậy chắc mai em phải sáng sớm ra lấy nước nóng để rửa mặt với pha cốc nước nóng rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L704_06','V704','宿管阿姨',6,'尽量避开晚间高峰，八点左右热水出水最稳定。','jǐn liàng bì kāi wǎn jiān gāo fēng， bā diǎn zuǒ yòu rè shuǐ chū shuǐ zuì wěn dìng。','Em cố tránh giờ cao điểm buổi tối nhé, khoảng tám giờ là nước nóng chảy ổn định nhất.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L704_07','V704','阮明',7,'我记好热水供应时间，不再错过取水时段。','wǒ jì hǎo rè shuǐ gōng yìng shí jiān， bù zài cuò guò qǔ shuǐ shí duàn。','Em ghi nhớ giờ có nước nóng rồi, sẽ không bỏ lỡ giờ lấy nước nữa đâu.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT705','SSH1','想加装简易收纳架，询问宿管宿舍墙面能否打孔粘贴',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V705','SIT705','P1','twist','ban_chinh_thuc',NULL,'学生宿舍墙面严禁打孔、钉钉子，保护墙体完整，避免退房产生墙面修补扣款。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L705_01','V705','阮明',1,'阿姨，我想买墙上收纳架，能不能在墙面打孔固定？','ā yí， wǒ xiǎng mǎi qiáng shàng shōu nà jià， néng bù néng zài qiáng miàn dǎ kǒng gù dìng？','Cô ơi, em muốn mua giá kệ treo tường, có được khoan lỗ để cố định vào tường không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L705_02','V705','宿管阿姨',2,'宿舍墙体不能打孔，打孔留下孔洞退房要扣修补押金。','sù shè qiáng tǐ bù néng dǎ kǒng， dǎ kǒng liú xià kǒng dòng tuì fáng yào kòu xiū bǔ yā jīn。','Tường phòng không được khoan lỗ, khoan để lại lỗ thì lúc trả phòng sẽ bị trừ tiền cọc sửa chữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L705_03','V705','阮明',3,'那无痕粘钩、免钉粘贴式置物架可以使用吗？','nà wú hén zhān gōu、 miǎn dīng zhān tiē shì zhì wù jià kě yǐ shǐ yòng ma？','Vậy loại móc dán không để lại vết, kệ dán không cần đóng đinh thì dùng được chứ ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L705_04','V705','宿管阿姨',4,'无痕粘胶可以，但退房必须完整撕掉，不能残留胶印嘛。','wú hén zhān jiāo kě yǐ， dàn tuì fáng bì xū wán zhěng sī diào， bù néng cán liú jiāo yìn ma。','Keo dán không để lại vết thì được, nhưng lúc trả phòng phải bóc sạch hoàn toàn, không được để lại vết keo nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L705_05','V705','阮明',5,'如果粘胶撕掉留有痕迹，会收取墙面清洁费对吗？','rú guǒ zhān jiāo sī diào liú yǒu hén jì， huì shōu qǔ qiáng miàn qīng jié fèi duì ma？','Nếu bóc keo mà vẫn còn để lại vết, thì có bị tính phí vệ sinh tường không cô?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L705_06','V705','宿管阿姨',6,'少量胶印擦拭干净即可，大面积顽固污渍才收费。','shǎo liàng jiāo yìn cā shì gān jìng jí kě， dà miàn jī wán gù wū zì cái shōu fèi。','Vết keo ít thì lau sạch là được, chỉ khi nào vết bẩn cứng đầu diện tích lớn mới bị tính phí.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L705_07','V705','阮明',7,'我只买免钉粘贴款收纳架，不破坏墙面墙体。','wǒ zhǐ mǎi miǎn dīng zhān tiē kuǎn shōu nà jià， bù pò huài qiáng miàn qiáng tǐ。','Vậy em chỉ mua loại kệ dán không cần đóng đinh thôi, không làm hỏng tường đâu.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT706','SSH1','室友作息差异，协商关灯、安静学习的作息时间',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V706','SIT706','P1','suon_se','tuy_y',NULL,'多人宿舍室友作息不同是普遍情况，国内学生一般会互相协商灯光、噪音、休息时间，彼此迁就包容。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L706_01','V706','阮明',1,'小林，我习惯十一点关灯休息，你晚上复习灯光会影响我睡觉。','xiǎo lín， wǒ xí guàn shí yì diǎn guān dēng xiū xī， nǐ wǎn shàng fù xí dēng guāng huì yǐng xiǎng wǒ shuì jiào。','Tiểu Lâm ơi, mình quen tắt đèn nghỉ lúc mười một giờ, tối cậu ôn bài để đèn sáng sẽ ảnh hưởng đến giấc ngủ của mình đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L706_02','V706','小林',2,'我专业课作业多，经常要学到十二点，咱们折中调整一下吧。','wǒ zhuān yè kè zuò yè duō， jīng cháng yào xué dào shí èr diǎn， zán men zhé zhōng tiáo zhěng yī xià ba。','Môn chuyên ngành của mình bài tập nhiều lắm, thường phải học đến mười hai giờ, thôi mình điều chỉnh dung hòa một chút đi.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L706_03','V706','阮明',3,'那你用桌面小台灯，十一点后关掉头顶大灯可以吗？','nà nǐ yòng zhuō miàn xiǎo tái dēng， shí yì diǎn hòu guān diào tóu dǐng dà dēng kě yǐ ma？','Vậy cậu dùng đèn bàn nhỏ, sau mười một giờ tắt đèn trần lớn được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L706_04','V706','小林',4,'没问题，我搭配静音鼠标，不发出敲击键盘噪音打扰你。','méi wèn tí， wǒ dā pèi jìng yīn shǔ biāo， bù fā chū qiāo jī jiàn pán zào yīn dǎ rǎo nǐ。','Không vấn đề gì, mình sẽ dùng chuột im lặng, không gõ bàn phím gây tiếng ồn làm phiền cậu nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L706_05','V706','阮明',5,'早上七点我会早起洗漱，我动作轻一点不吵醒你休息。','zǎo shàng qī diǎn wǒ huì zǎo qǐ xǐ shù， wǒ dòng zuò qīng yì diǎn bù chǎo xǐng nǐ xiū xī。','Sáng bảy giờ mình dậy sớm rửa mặt, mình sẽ nhẹ nhàng để không đánh thức cậu dậy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L706_06','V706','小林',6,'互相体谅作息，宿舍居住才能舒服不产生矛盾。','hù xiāng tǐ liàng zuò xī， sù shè jū zhù cái néng shū fú bù chǎn shēng máo dùn。','Thông cảm cho nhau về giờ giấc sinh hoạt thì ở phòng mới thoải mái, không nảy sinh mâu thuẫn được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L706_07','V706','阮明',7,'太好了，咱们就按这个作息约定长期配合。','tài hǎo le， zán men jiù àn zhè ge zuò xī yuē dìng cháng qī pèi hé。','Tuyệt quá, vậy mình cứ theo thỏa thuận giờ giấc này mà phối hợp lâu dài nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT707','SSH1','宿舍晾晒衣物空间不足，咨询楼顶晾晒区开放时段',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V707','SIT707','P1','twist','tuy_y',NULL,'楼顶露天晾晒区夜间关闭，防止衣物夜间受潮、丢失，同时避免高空坠物安全隐患。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L707_01','V707','阮明',1,'阿姨，阳台晾衣杆挂满衣服，没有位置晾晒刚洗的床单。','ā yí， yáng tái liàng yī gān guà mǎn yī fú， méi yǒu wèi zhì liàng shài gāng xǐ de chuáng dān。','Cô ơi, dây phơi ở ban công treo kín quần áo rồi, không còn chỗ nào phơi ga giường mới giặt cả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L707_02','V707','宿管阿姨',2,'宿舍楼顶有公共晾晒区，但是只白天七点到十八点开放。','sù shè lóu dǐng yǒu gōng gòng liàng shài qū， dàn shì zhǐ bái tiān qī diǎn dào shí bā diǎn kāi fàng。','Sân thượng ký túc xá có khu phơi chung, nhưng chỉ mở cửa ban ngày từ bảy giờ sáng đến sáu giờ chiều thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L707_03','V707','阮明',3,'现在傍晚六点半，马上到关闭时间，今天还能上楼顶晾衣服吗？','xiàn zài bàng wǎn liù diǎn bàn， mǎ shàng dào guān bì shí jiān， jīn tiān hái néng shàng lóu dǐng liàng yī fú ma？','Bây giờ là sáu rưỡi chiều, sắp đến giờ đóng cửa rồi, hôm nay em còn lên sân thượng phơi đồ được không cô?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L707_04','V707','宿管阿姨',4,'十八点保洁会收回露天衣物，晚一点容易夜间受潮发霉嘛。','shí bā diǎn bǎo jié huì shōu huí lù tiān yī wù， wǎn yì diǎn róng yì yè jiān shòu cháo fā méi ma。','Sáu giờ chiều là nhân viên vệ sinh sẽ thu đồ phơi ngoài trời rồi, để muộn dễ bị ẩm ướt mốc meo qua đêm lắm.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L707_05','V707','阮明',5,'那我明天一早七点上楼顶，抢占晾晒位置晒大件被褥。','nà wǒ míng tiān yī zǎo qī diǎn shàng lóu dǐng， qiǎng zhàn liàng shài wèi zhì shài dà jiàn bèi rù。','Vậy mai em lên sân thượng từ sớm bảy giờ, tranh chỗ phơi để phơi mấy món chăn đệm to.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L707_06','V707','宿管阿姨',6,'楼顶风大，记得带夹子固定衣物，防止被风吹落丢失。','lóu dǐng fēng dà， jì de dài jiā zi gù dìng yī wù， fáng zhǐ bèi fēng chuī luò diū shī。','Trên sân thượng gió lớn lắm, nhớ mang kẹp để cố định quần áo, tránh bị gió thổi bay mất đồ nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L707_07','V707','阮明',7,'好，我明天提前上楼晾晒大件床上用品。','hǎo， wǒ míng tiān tí qián shàng lóu liàng shài dà jiàn chuáng shàng yòng pǐn。','Vâng, mai em lên sớm phơi mấy món đồ dùng giường chiếu to đó.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT708','SSH1','宿舍公共垃圾桶满溢，询问保洁阿姨清运时间',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V708','SIT708','P1','suon_se','tuy_y',NULL,'国内校园推行垃圾分类，楼道垃圾桶定时清运，满溢时可使用楼下备用分类垃圾桶。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L708_01','V708','阮明',1,'阿姨，楼道垃圾桶全部装满垃圾，没法再投放废弃物了。','ā yí， lóu dào lā jī tǒng quán bù zhuāng mǎn lā jī， méi fǎ zài tóu fàng fèi qì wù le。','Cô ơi, thùng rác chung ở hành lang đầy ắp rác rồi, không thể bỏ thêm rác vào được nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L708_02','V708','保洁李阿姨',2,'我每天上午九点、下午四点各清运一次垃圾哈。','wǒ měi tiān shàng wǔ jiǔ diǎn、 xià wǔ sì diǎn gè qīng yùn yī cì lā jī hā。','Mỗi ngày cô thu gom rác một lần vào chín giờ sáng và bốn giờ chiều đó.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L708_03','V708','阮明',3,'现在下午两点，还要等两小时才能清空垃圾桶吗？','xiàn zài xià wǔ liǎng diǎn， hái yào děng liǎng xiǎo shí cái néng qīng kōng lā jī tǒng ma？','Bây giờ hai giờ chiều, vậy phải chờ thêm hai tiếng nữa mới dọn sạch thùng rác được ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L708_04','V708','保洁李阿姨',4,'楼下门口有备用分类垃圾桶，可以暂时投放垃圾。','lóu xià mén kǒu yǒu bèi yòng fēn lèi lā jī tǒng， kě yǐ zàn shí tóu fàng lā jī。','Dưới cổng có thùng rác phân loại dự phòng, em có thể tạm bỏ rác vào đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L708_05','V708','阮明',5,'我先把垃圾带到楼下备用桶，等您四点再来清运。','wǒ xiān bǎ lā jī dài dào lóu xià bèi yòng tǒng， děng nín sì diǎn zài lái qīng yùn。','Vậy em đem rác xuống thùng dự phòng dưới đó trước, đợi bốn giờ cô lên thu gom nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L708_06','V708','保洁李阿姨',6,'垃圾分类记得分开投放，纸类、塑料不要混在一起。','lā jī fēn lèi jì de fēn kāi tóu fàng， zhǐ lèi、 sù liào bú yào hùn zài yì qǐ。','Nhớ phân loại rác rồi bỏ riêng nhé, giấy với nhựa đừng để lẫn lộn với nhau.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L708_07','V708','阮明',7,'我会做好垃圾分类投放，不给您增加分拣工作量。','wǒ huì zuò hǎo lā jī fēn lèi tóu fàng， bù gěi nín zēng jiā fēn jiǎn gōng zuò liàng。','Em sẽ phân loại rác cẩn thận rồi mới bỏ, không để cô phải mất công phân loại thêm đâu.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT709','SSH1','宿舍门禁卡丢失，到宿管处挂失补办门禁卡',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V709','SIT709','P1','that_bai_nhe','ban_chinh_thuc',NULL,'宿舍门禁卡丢失必须第一时间挂失锁卡，保障宿舍财物安全；补办卡片统一收取工本费，制卡设备故障会发放临时通行凭证。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L709_01','V709','阮明',1,'阿姨，我的宿舍门禁卡昨天外出弄丢了，前来挂失补办。','ā yí， wǒ de sù shè mén jìn kǎ zuó tiān wài chū nòng diū le， qián lái guà shī bǔ bàn。','Cô ơi, thẻ ra vào ký túc xá của em hôm qua đi ra ngoài bị làm mất rồi, em đến báo mất để làm lại thẻ ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L709_02','V709','宿管阿姨',2,'先登记挂失，旧卡立刻锁死，防止别人开门进入宿舍。','xiān dēng jì guà shī， jiù kǎ lì kè suǒ sǐ， fáng zhǐ bié rén kāi mén jìn rù sù shè。','Đăng ký báo mất trước đã, thẻ cũ sẽ bị khóa ngay lập tức, để tránh người khác dùng thẻ mở cửa vào ký túc xá.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L709_03','V709','阮明',3,'补办新门禁卡需要支付工本费吗，当场就能拿到卡片？','bǔ bàn xīn mén jìn kǎ xū yào zhī fù gōng běn fèi ma， dāng chǎng jiù néng ná dào kǎ piàn？','Làm lại thẻ mới có phải đóng phí làm thẻ không cô, và có lấy được thẻ ngay không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L709_04','V709','宿管阿姨',4,'补办一张门禁卡二十元工本费，制卡机器今天故障维修嘛。','bǔ bàn yī zhāng mén jìn kǎ èr shí yuán gōng běn fèi， zhì kǎ jī qì jīn tiān gù zhàng wéi xiū ma。','Làm lại một thẻ mới là hai mươi tệ phí làm thẻ, nhưng máy làm thẻ hôm nay đang hỏng phải sửa chữa đó.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L709_05','V709','阮明',5,'那今天拿不到新卡，晚上怎么刷卡回宿舍休息？','nà jīn tiān ná bú dào xīn kǎ， wǎn shàng zěn me shuā kǎ huí sù shè xiū xī？','Vậy hôm nay không lấy được thẻ mới, tối nay em quẹt thẻ kiểu gì để về ký túc xá nghỉ ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L709_06','V709','宿管阿姨',6,'我给你开具临时纸质通行条，今晚凭纸条进出楼栋。','wǒ gěi nǐ kāi jù lín shí zhǐ zhì tōng xíng tiáo， jīn wǎn píng zhǐ tiáo jìn chū lóu dòng。','Cô sẽ viết cho em một tờ giấy thông hành tạm thời, tối nay cứ cầm tờ giấy đó ra vào tòa nhà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L709_07','V709','阮明',7,'明天机器修好我再来缴费领新门禁卡。','míng tiān jī qì xiū hǎo wǒ zài lái jiǎo fèi lǐng xīn mén jìn kǎ。','Mai máy sửa xong em sẽ quay lại đóng tiền lấy thẻ mới ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT710','SSH1','校外租房看房，和房东核对家具家电完好情况',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V710','SIT710','P1','suon_se','ban_chinh_thuc',NULL,'校外租房入住前必须逐项核对房屋设施并书面记录原有损坏，避免退租时房东以破损为由克扣押金。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L710_01','V710','阮明',1,'刘哥，我们一起核对屋内家电、家具，记录破损地方吧。','liú gē， wǒ men yì qǐ hé duì wū nèi jiā diàn、 jiā jù， jì lù pò sǔn dì fāng ba。','Anh Lưu ơi, mình cùng kiểm tra lại đồ điện, đồ nội thất trong phòng rồi ghi lại chỗ nào hư hỏng nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L710_02','V710','房东',2,'冰箱、洗衣机、空调全部试机，有问题当场写进租房合同。','bīng xiāng、 xǐ yī jī、 kōng tiáo quán bù shì jī， yǒu wèn tí dāng chǎng xiě jìn zū fáng hé tóng。','Tủ lạnh, máy giặt, điều hòa đều chạy thử hết, có vấn đề gì thì ghi ngay vào hợp đồng thuê nhà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L710_03','V710','阮明',3,'衣柜门板有一道小划痕，墙面墙角轻微掉皮，我标注下来。','yī guì mén bǎn yǒu yī dào xiǎo huà hén， qiáng miàn qiáng jiǎo qīng wēi diào pí， wǒ biāo zhù xià lái。','Cánh tủ quần áo có một vết xước nhỏ, góc tường bị bong sơn nhẹ, để em ghi chú lại.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L710_04','V710','房东',4,'这些原有轻微损伤全部备注，退房不会扣你的押金。','zhè xiē yuán yǒu qīng wēi sǔn shāng quán bù bèi zhù， tuì fáng bú huì kòu nǐ de yā jīn。','Những chỗ hư hỏng nhẹ có sẵn này đều được ghi chú hết, khi trả nhà sẽ không bị trừ tiền cọc của em đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L710_05','V710','阮明',5,'水电表初始读数也一起记录，避免结算时产生争议。','shuǐ diàn biǎo chū shǐ dú shù yě yì qǐ jì lù， bì miǎn jié suàn shí chǎn shēng zhēng yì。','Chỉ số điện nước ban đầu cũng ghi lại luôn, để tránh sau này thanh toán bị tranh cãi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L710_06','V710','房东',6,'没问题，所有物品、读数核对完，我们签署纸质租房合同。','méi wèn tí， suǒ yǒu wù pǐn、 dú shù hé duì wán， wǒ men qiān shǔ zhǐ zhì zū fáng hé tóng。','Không vấn đề gì, kiểm tra hết đồ đạc, chỉ số xong thì mình ký hợp đồng thuê nhà bằng giấy nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L710_07','V710','阮明',7,'全部设备正常使用，破损全部登记，可以签约入住。','quán bù shè bèi zhèng cháng shǐ yòng， pò sǔn quán bù dēng jì， kě yǐ qiān yuē rù zhù。','Tất cả thiết bị đều dùng bình thường, chỗ hư hỏng cũng ghi lại hết rồi, có thể ký hợp đồng dọn vào ở được rồi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT711','SSH2','食堂充值机无法读卡，找食堂工作人员处理饭卡故障',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V711','SIT711','P1','twist','tuy_y',NULL,'校园饭卡内置磁条，手机、钥匙长期放在一起容易消磁失效，消磁卡片无法修复只能补办。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L711_01','V711','阮明',1,'你好，校园饭卡放到充值机，机器完全识别不出卡片啊。','nǐ hǎo， xiào yuán fàn kǎ fàng dào chōng zhí jī， jī qì wán quán shí bié bù chū kǎ piàn a。','Chào chị, em để thẻ ăn của trường vào máy nạp tiền mà máy không nhận ra thẻ gì cả.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L711_02','V711','工作人员',2,'是不是卡片弯折、消磁了，放到读卡窗口多试两次。','shì bú shì kǎ piàn wān zhé、 xiāo cí le， fàng dào dú kǎ chuāng kǒu duō shì liǎng cì。','Có phải thẻ bị cong hay mất từ không, thử đặt vào khe đọc thẻ vài lần xem sao.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L711_03','V711','阮明',3,'反复摆放五次都无反应，昨天还正常充值用餐嘛。','fǎn fù bǎi fàng wǔ cì dōu wú fǎn yìng， zuó tiān hái zhèng cháng chōng zhí yòng cān ma。','Em thử đi thử lại năm lần rồi vẫn không có phản ứng gì, hôm qua vẫn nạp tiền ăn bình thường mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L711_04','V711','工作人员',4,'卡片消磁只能补办新卡，旧卡余额可以转移到新卡里。','kǎ piàn xiāo cí zhǐ néng bǔ bàn xīn kǎ， jiù kǎ yú é kě yǐ zhuǎn yí dào xīn kǎ lǐ。','Thẻ mất từ rồi thì chỉ có cách làm lại thẻ mới thôi, số dư trong thẻ cũ có thể chuyển sang thẻ mới.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L711_05','V711','阮明',5,'补办饭卡需要携带什么证件，多久能拿到新卡片？','bǔ bàn fàn kǎ xū yào xié dài shén me zhèng jiàn， duō jiǔ néng ná dào xīn kǎ piàn？','Làm lại thẻ ăn cần mang theo giấy tờ gì, bao lâu thì lấy được thẻ mới ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L711_06','V711','工作人员',6,'带护照、学生证，十分钟制卡完成，当场转移余额。','dài hù zhào、 xué shēng zhèng， shí fēn zhōng zhì kǎ wán chéng， dāng chǎng zhuǎn yí yú é。','Mang hộ chiếu, thẻ sinh viên, mười phút là làm xong thẻ, chuyển số dư ngay tại chỗ luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L711_07','V711','阮明',7,'我现在回宿舍拿证件，过来补办饭卡转移余额。','wǒ xiàn zài huí sù shè ná zhèng jiàn， guò lái bǔ bàn fàn kǎ zhuǎn yí yú é。','Vậy giờ em về ký túc xá lấy giấy tờ, rồi quay lại làm lại thẻ ăn chuyển số dư nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT712','SSH2','丢失校园饭卡，挂失冻结余额、补办新饭卡',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V712','SIT712','P1','suon_se','ban_chinh_thuc',NULL,'饭卡丢失第一时间挂失可保护卡内余额，挂失后旧卡永久失效，余额完整迁移至新卡片。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L712_01','V712','阮明',1,'您好，我的校园饭卡丢失，麻烦先帮我挂失冻结余额。','nín hǎo， wǒ de xiào yuán fàn kǎ diū shī， má fán xiān bāng wǒ guà shī dòng jié yú é。','Chào chị, thẻ ăn của trường em bị mất rồi, phiền chị giúp em báo mất khóa số dư trước ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L712_02','V712','工作人员',2,'报你的姓名、学号，系统马上锁定旧卡，无法刷卡消费。','bào nǐ de xìng míng、 xué hào， xì tǒng mǎ shàng suǒ dìng jiù kǎ， wú fǎ shuā kǎ xiāo fèi。','Em cho biết tên, mã số sinh viên, hệ thống sẽ khóa thẻ cũ ngay, không quẹt thẻ tiêu được nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L712_03','V712','阮明',3,'卡里还有一百二十元余额，挂失后能完整转移到新卡吗？','kǎ lǐ hái yǒu yì bǎi èr shí yuán yú é， guà shī hòu néng wán zhěng zhuǎn yí dào xīn kǎ ma？','Trong thẻ còn một trăm hai mươi tệ, báo mất xong có chuyển hết được sang thẻ mới không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L712_04','V712','工作人员',4,'全部余额无损转移，仅收取十元新卡工本费。','quán bù yú é wú sǔn zhuǎn yí， jǐn shōu qǔ shí yuán xīn kǎ gōng běn fèi。','Toàn bộ số dư sẽ được chuyển nguyên vẹn, chỉ thu mười tệ phí làm thẻ mới thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L712_05','V712','阮明',5,'挂失之后如果有人捡到旧卡，也不能刷卡消费了对吧？','guà shī zhī hòu rú guǒ yǒu rén jiǎn dào jiù kǎ， yě bù néng shuā kǎ xiāo fèi le duì ba？','Sau khi báo mất, nếu có ai nhặt được thẻ cũ thì cũng không quẹt tiêu được nữa đúng không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L712_06','V712','工作人员',6,'没错，挂失永久锁死旧卡，捡到也无法使用。','méi cuò， guà shī yǒng jiǔ suǒ sǐ jiù kǎ， jiǎn dào yě wú fǎ shǐ yòng。','Đúng vậy, báo mất là khóa vĩnh viễn thẻ cũ, có nhặt được cũng không dùng được đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L712_07','V712','阮明',7,'我现在补办新卡，今晚就能正常去食堂吃饭。','wǒ xiàn zài bǔ bàn xīn kǎ， jīn wǎn jiù néng zhèng cháng qù shí táng chī fàn。','Vậy giờ em làm lại thẻ mới, tối nay là có thể đi ăn ở căng tin bình thường rồi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT713','SSH2','食堂错打不喜欢的菜品，询问能否免费更换菜品',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V713','SIT713','P1','twist','tuy_y',NULL,'食堂菜品盛出后无法回收更换，防止交叉污染、食品安全问题，点餐提前告知忌口是更稳妥的方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L713_01','V713','阮明',1,'阿姨，我不爱吃青椒，刚刚窗口误打了青椒炒肉，能换一份别的菜吗？','ā yí， wǒ bù ài chī qīng jiāo， gāng gāng chuāng kǒu wù dǎ le qīng jiāo chǎo ròu， néng huàn yī fèn bié de cài ma？','Cô ơi, con không ăn được ớt xanh, lúc nãy quầy múc nhầm cho con món thịt xào ớt xanh, đổi cho con món khác được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L713_02','V713','打菜阿姨',2,'已经盛到餐盘里的菜品，没法回收更换，会影响食品安全嘛。','yǐ jīng shèng dào cān pán lǐ de cài pǐn， méi fǎ huí shōu gēng huàn， huì yǐng xiǎng shí pǐn ān quán ma。','Món đã múc vào khay rồi thì không thu hồi đổi lại được đâu, sẽ ảnh hưởng đến an toàn thực phẩm đó.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L713_03','V713','阮明',3,'我一口都没动，只是拿到手才发现里面全是青椒。','wǒ yī kǒu dōu méi dòng， zhǐ shì ná dào shǒu cái fā xiàn lǐ miàn quán shì qīng jiāo。','Con chưa động đũa miếng nào cả, chỉ là cầm lên tay mới phát hiện toàn là ớt xanh thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L713_04','V713','打菜阿姨',4,'未食用也不能退回，下次排队提前跟我说避开青椒菜品。','wèi shí yòng yě bù néng tuì huí， xià cì pái duì tí qián gēn wǒ shuō bì kāi qīng jiāo cài pǐn。','Chưa ăn cũng không trả lại được, lần sau xếp hàng thì nói trước với cô để tránh món có ớt xanh nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L713_05','V713','阮明',5,'那只能下次点餐提前说明忌口，这份我打包送给同学。','nà zhǐ néng xià cì diǎn cān tí qián shuō míng jì kǒu， zhè fèn wǒ dǎ bāo sòng gěi tóng xué。','Vậy chỉ đành lần sau gọi món nói trước là kiêng gì thôi, phần này con gói mang cho bạn ăn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L713_06','V713','打菜阿姨',6,'下次点餐提前告知忌口食材，我给你单独打别的菜品。','xià cì diǎn cān tí qián gào zhī jì kǒu shí cái， wǒ gěi nǐ dān dú dǎ bié de cài pǐn。','Lần sau gọi món cứ nói trước là kiêng nguyên liệu gì, cô sẽ múc riêng cho con món khác.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L713_07','V713','阮明',7,'我记住了，下次打菜提前说明不吃的食材。','wǒ jì zhù le， xià cì dǎ cài tí qián shuō míng bù chī de shí cái。','Con nhớ rồi ạ, lần sau múc đồ ăn con sẽ nói trước là không ăn được gì.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT714','SSH2','校园奶茶店点单，询问甜度、冰度可选标准',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V714','SIT714','P1','suon_se','tuy_y',NULL,'国内奶茶饮品可自由调整甜度、冰量，基础小料大多免费添加，是茶饮店通用服务。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L714_01','V714','阮明',1,'你好，一杯原味奶茶，甜度和冰度有几种选择呢？','nǐ hǎo， yī bēi yuán wèi nǎi chá， tián dù hé bīng dù yǒu jǐ zhǒng xuǎn zé ne？','Chào anh, cho em một ly trà sữa nguyên vị, độ ngọt với độ đá có mấy mức để chọn vậy ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L714_02','V714','店员',2,'甜度分无糖、三分糖、五分糖、七分糖、全糖五档哦。','tián dù fēn wú táng、 sān fēn táng、 wǔ fēn táng、 qī fēn táng、 quán táng wǔ dàng ó。','Độ ngọt có năm mức: không đường, ba phần đường, năm phần đường, bảy phần đường, đường đầy đủ nha.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L714_03','V714','阮明',3,'冰度常温、少冰、正常冰、去冰，全部都能选吗？','bīng dù cháng wēn、 shǎo bīng、 zhèng cháng bīng、 qù bīng， quán bù dōu néng xuǎn ma？','Độ đá thường, ít đá, đá bình thường, không đá, đều chọn được hết đúng không anh?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L714_04','V714','店员',4,'是的，任意搭配，另外可以免费加珍珠、椰果两种小料。','shì de， rèn yì dā pèi， lìng wài kě yǐ miǎn fèi jiā zhēn zhū、 yē guǒ liǎng zhǒng xiǎo liào。','Đúng vậy, kết hợp tùy ý, ngoài ra còn được thêm miễn phí trân châu hoặc thạch dừa hai loại topping.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L714_05','V714','阮明',5,'那五分糖、少冰，再加一份珍珠，麻烦帮我制作。','nà wǔ fēn táng、 shǎo bīng， zài jiā yī fèn zhēn zhū， má fán bāng wǒ zhì zuò。','Vậy cho em năm phần đường, ít đá, thêm một phần trân châu nhé, làm giúp em với.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L714_06','V714','店员',6,'好的，一共八元，扫码付款后在取餐口等候就行。','hǎo de， yī gòng bā yuán， sǎo mǎ fù kuǎn hòu zài qǔ cān kǒu děng hòu jiù xíng。','Được rồi, tổng cộng tám tệ, quét mã thanh toán xong thì đợi ở quầy lấy đồ nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L714_07','V714','阮明',7,'好，我扫码支付，在这里等奶茶做好。','hǎo， wǒ sǎo mǎ zhī fù， zài zhè lǐ děng nǎi chá zuò hǎo。','Vâng, em quét mã thanh toán rồi, em đợi ở đây chờ trà sữa làm xong.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT715','SSH2','自带饭盒去食堂打包饭菜，咨询打包收费规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V715','SIT715','P1','suon_se','tuy_y',NULL,'国内倡导减少一次性塑料用品，自带饭盒打包可免收餐盒打包费，是校园食堂环保规定。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_01','V715','阮明',1,'您好，我自带饭盒打包饭菜，还要额外收取打包费吗？','nín hǎo， wǒ zì dài fàn hé dǎ bāo fàn cài， hái yào é wài shōu qǔ dǎ bāo fèi ma？','Chào chị, em tự mang hộp cơm đến gói đồ ăn, vậy có phải trả thêm phí đóng gói không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_02','V715','工作人员',2,'自带容器不使用食堂一次性餐盒，免收打包费哈。','zì dài róng qì bù shǐ yòng shí táng yí cì xìng cān hé， miǎn shōu dǎ bāo fèi hā。','Tự mang hộp không dùng hộp dùng một lần của căng tin thì miễn phí đóng gói luôn.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_03','V715','阮明',3,'要是忘记带饭盒，用食堂塑料盒打包多少钱一份？','yào shì wàng jì dài fàn hé， yòng shí táng sù liào hé dǎ bāo duō shǎo qián yī fèn？','Nếu quên mang hộp cơm, dùng hộp nhựa của căng tin để gói thì bao nhiêu tiền một phần vậy chị?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_04','V715','工作人员',4,'一次性餐盒一元一个，筷子、塑料袋免费提供。','yí cì xìng cān hé yī yuán yí gè， kuài zi、 sù liào dài miǎn fèi tí gōng。','Hộp dùng một lần là một tệ một cái, đũa với túi ni lông thì cung cấp miễn phí.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_05','V715','阮明',5,'我以后每天带饭盒，既省钱也更环保。','wǒ yǐ hòu měi tiān dài fàn hé， jì shěng qián yě gèng huán bǎo。','Vậy từ giờ ngày nào em cũng mang hộp cơm theo, vừa tiết kiệm vừa bảo vệ môi trường.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_06','V715','工作人员',6,'自带餐具打包我们十分鼓励，减少塑料垃圾。','zì dài cān jù dǎ bāo wǒ men shí fēn gǔ lì， jiǎn shǎo sù liào lā jī。','Tự mang dụng cụ đến gói đồ thì bên chị rất khuyến khích, giảm bớt rác thải nhựa mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L715_07','V715','阮明',7,'好，我每天自备饭盒来食堂打包饭菜。','hǎo， wǒ měi tiān zì bèi fàn hé lái shí táng dǎ bāo fàn cài。','Vâng, từ nay ngày nào em cũng tự chuẩn bị hộp cơm đến căng tin gói đồ ăn.',NULL) ON CONFLICT DO NOTHING;

