INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1312_01','V1312','阮明',1,'学姐，我下午要去拜访硕导，不知道有什么需要留意的礼仪吗？','xué jiě ， wǒ xià wǔ yào qù bài fǎng shuò dǎo ， bù zhī dào yǒu shén me xū yào liú yì de lǐ yí ma ？','Chị ơi, chiều nay em phải đi gặp thầy hướng dẫn thạc sĩ, không biết có phép tắc gì cần chú ý không chị?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1312_02','V1312','苏学姐',2,'进办公室先轻轻敲门，得到允许再进去，别直接推门啦。','jìn bàn gōng shì xiān qīng qīng qiāo mén ， dé dào yǔn xǔ zài jìn qù ， bié zhí jiē tuī mén la 。','Vào phòng thì gõ cửa nhẹ trước, được phép rồi mới vào, đừng đẩy cửa vào thẳng nhé.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1312_03','V1312','阮明',3,'沟通科研问题的时候，能不能打断老师讲话提出疑问呢？','gōu tōng kē yán wèn tí de shí hòu ， néng bù néng dǎ duàn lǎo shī jiǎng huà tí chū yí wèn ne ？','Lúc trao đổi vấn đề nghiên cứu, em có được ngắt lời thầy để hỏi luôn không chị?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1312_04','V1312','苏学姐',4,'等老师说完一段再提问，中途打断会显得不够尊重嘛。','děng lǎo shī shuō wán yī duàn zài tí wèn ， zhōng tú dǎ duàn huì xiǎn de bù gòu zūn zhòng ma 。','Đợi thầy nói xong một đoạn rồi mới hỏi, ngắt lời giữa chừng sẽ có vẻ thiếu tôn trọng đấy.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1312_05','V1312','阮明',5,'离开的时候需要主动收拾座椅，简单道谢再出门对吧？','lí kāi de shí hòu xū yào zhǔ dòng shōu shí zuò yǐ ， jiǎn dān dào xiè zài chū mén duì ba ？','Lúc ra về em có cần chủ động dọn lại ghế, chào cảm ơn rồi mới ra ngoài đúng không chị?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1312_06','V1312','苏学姐',6,'没错，谈话控制在二十分钟以内，不要占用老师太久时间哈。','méi cuò ， tán huà kòng zhì zài èr shí fēn zhōng yǐ nèi ， bú yào zhàn yòng lǎo shī tài jiǔ shí jiān hā 。','Đúng rồi, buổi nói chuyện thì giữ trong khoảng hai mươi phút thôi, đừng chiếm quá nhiều thời gian của thầy nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1312_07','V1312','阮明',7,'多谢学姐提醒，我记住所有细节，下午礼貌拜访导师。','duō xiè xué jiě tí xǐng ， wǒ jì zhù suǒ yǒu xì jié ， xià wǔ lǐ mào bài fǎng dǎo shī 。','Em cảm ơn chị đã nhắc, em ghi nhớ hết mọi chi tiết rồi, chiều nay sẽ đến gặp thầy thật lễ phép.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1313','SHTN1','学术会议海报展示环节，听不懂国内学者提问，请求主持人帮忙转述通俗中文',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1313','SIT1313','P1','twist','ban_chinh_thuc',NULL,'国内学术会议包容外籍参会者语言短板，主持人可协助转述问题，允许中英文混合讲解海报内容。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1313_01','V1313','阮明',1,'刘学长，刚才那位老师提问语速太快，很多专业词汇我没听懂呢。','liú xué zhǎng ， gāng cái nà wèi lǎo shī tí wèn yǔ sù tài kuài ， hěn duō zhuān yè cí huì wǒ méi tīng dǒng ne 。','Anh Lưu ơi, thầy vừa hỏi nói nhanh quá, nhiều từ chuyên môn em không nghe kịp.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1313_02','V1313','刘学长',2,'没关系，我把他的问题用简单词汇重新跟你复述一遍吧。','méi guān xì ， wǒ bǎ tā de wèn tí yòng jiǎn dān cí huì chóng xīn gēn nǐ fù shù yī biàn ba 。','Không sao, để anh dùng từ đơn giản diễn đạt lại câu hỏi của thầy cho em nghe nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1313_03','V1313','阮明',3,'实在不好意思，我的中文听力应对快速专业对话还有点吃力。','shí zài bù hǎo yì sī ， wǒ de zhōng wén tīng lì yìng duì kuài sù zhuān yè duì huà hái yǒu diǎn chī lì 。','Em thật sự ngại quá, khả năng nghe tiếng Trung của em với những đoạn hội thoại chuyên môn nhanh vẫn còn hơi khó khăn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1313_04','V1313','刘学长',4,'参会老师都能理解留学生语言情况，不用觉得尴尬的。','cān huì lǎo shī dōu néng lǐ jiě liú xué shēng yǔ yán qíng kuàng ， bù yòng jué de gān gà de 。','Các thầy dự hội thảo đều hiểu tình hình ngôn ngữ của lưu học sinh mà, em không cần thấy ngại đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1313_05','V1313','阮明',5,'麻烦你转述完，我可以结合英文辅助说明我的实验结论吗？','má fán nǐ zhuǎn shù wán ， wǒ kě yǐ jié hé yīng wén fǔ zhù shuō míng wǒ de shí yàn jié lùn ma ？','Anh diễn đạt lại xong, em có thể dùng thêm tiếng Anh để giải thích rõ hơn kết luận thực nghiệm của mình được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1313_06','V1313','刘学长',6,'完全没问题，中英结合讲解大家更容易听懂你的研究。','wán quán méi wèn tí ， zhōng yīng jié hé jiǎng jiě dà jiā gèng róng yì tīng dǒng nǐ de yán jiū 。','Hoàn toàn được, kết hợp cả tiếng Trung lẫn tiếng Anh thì mọi người sẽ dễ hiểu nghiên cứu của em hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1313_07','V1313','阮明',7,'太感谢你帮忙，不然我没办法完整回应老师的提问啦。','tài gǎn xiè nǐ bāng máng ， bù rán wǒ méi bàn fǎ wán zhěng huí yìng lǎo shī de tí wèn la 。','Em cảm ơn anh giúp đỡ nhiều lắm, không thì em không cách nào trả lời trọn vẹn câu hỏi của thầy được.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1314','SHTN1','申请公派联合培养硕士项目，公证护照学历材料时遗漏中英文翻译件',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1314','SIT1314','P1','that_bai_nhe','chinh_thuc',NULL,'国内公派留学、联合培养项目所有外籍学历、护照公证，必须搭配公证处出具标准双语翻译件，缺一不可。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1314_01','V1314','阮明',1,'王老师，我提交公派联合培养材料，系统提示公证材料审核失败了。','wáng lǎo shī ， wǒ tí jiāo gōng pài lián hé péi yǎng cái liào ， xì tǒng tí shì gōng zhèng cái liào shěn hé shī bài le 。','Thưa cô Vương, em vừa nộp hồ sơ chương trình đào tạo liên kết công phái, hệ thống báo là hồ sơ công chứng không qua được thẩm định ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1314_02','V1314','王老师',2,'你的学历公证只有中文原件，缺少正规机构出具的英文翻译件呢。','nǐ de xué lì gōng zhèng zhǐ yǒu zhōng wén yuán jiàn ， quē shǎo zhèng guī jī gòu chū jù de yīng wén fān yì jiàn ne 。','Bản công chứng học vị của em chỉ có bản gốc tiếng Trung, thiếu bản dịch tiếng Anh do cơ quan chính quy cấp.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1314_03','V1314','阮明',3,'我以为只需要公证纸质证件，没想到还要配套翻译文件啊。','wǒ yǐ wéi zhǐ xū yào gōng zhèng zhǐ zhì zhèng jiàn ， méi xiǎng dào hái yào pèi tào fān yì wén jiàn a 。','Em cứ nghĩ chỉ cần công chứng bản giấy tờ gốc thôi, không ngờ còn phải có thêm bản dịch kèm theo.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1314_04','V1314','王老师',4,'公派项目要求所有外籍证件、学历都附带官方双语翻译公证件。','gōng pài xiàng mù yāo qiú suǒ yǒu wài jí zhèng jiàn 、 xué lì dōu fù dài guān fāng shuāng yǔ fān yì gōng zhèng jiàn 。','Chương trình công phái yêu cầu mọi giấy tờ và văn bằng của người nước ngoài đều phải kèm bản dịch song ngữ đã được công chứng chính thức.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1314_05','V1314','阮明',5,'公证机构今天下班了，是不是赶不上本周申报批次了？','gōng zhèng jī gòu jīn tiān xià bān le ， shì bú shì gǎn bù shàng běn zhōu shēn bào pī cì le ？','Cơ quan công chứng hôm nay đã đóng cửa rồi, liệu em có kịp nộp trong đợt xét duyệt tuần này không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1314_06','V1314','王老师',6,'是的，这批申报今天截止，你只能等下一批开放再提交咯。','shì de ， zhè pī shēn bào jīn tiān jié zhǐ ， nǐ zhǐ néng děng xià yī pī kāi fàng zài tí jiāo gē 。','Đúng vậy, đợt nộp hồ sơ này chốt hạn hôm nay rồi, em chỉ có thể chờ đợt tiếp theo mở ra mới nộp được thôi.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1314_07','V1314','阮明',7,'都怪我没有仔细阅读申报须知，只能下次再申请项目了。','dōu guài wǒ méi yǒu zǐ xì yuè dú shēn bào xū zhī ， zhǐ néng xià cì zài shēn qǐng xiàng mù le 。','Đều tại em không đọc kỹ hướng dẫn nộp hồ sơ, thôi thì em đành đợi đợt sau nộp lại vậy.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1315','SHTN1','竞赛申报系统填报外籍证件拼音，和护照拼写不一致导致提交失败',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1315','SIT1315','P1','twist','ban_chinh_thuc',NULL,'国内所有面向留学生的竞赛、科研申报系统实名核验严格，姓名拼音大小写、字母拼写必须与护照完全统一。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1315_01','V1315','阮明',1,'你好，我提交竞赛申报表单一直失败，提示证件信息不匹配呢。','nǐ hǎo ， wǒ tí jiāo jìng sài shēn bào biǎo dān yī zhí shī bài ， tí shì zhèng jiàn xìn xī bù pǐ pèi ne 。','Chào chị, em nộp biểu mẫu đăng ký cuộc thi mãi không được, hệ thống báo thông tin giấy tờ không khớp ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1315_02','V1315','小唐',2,'我后台核对一下，你填写的姓名拼音和护照上拼写有一处字母不同。','wǒ hòu tái hé duì yī xià ， nǐ tián xiě de xìng míng pīn yīn hé hù zhào shàng pīn xiě yǒu yī chù zì mǔ bù tóng 。','Để chị kiểm tra lại trên hệ thống xem, tên phiên âm em điền và trên hộ chiếu có một chữ cái không trùng khớp.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1315_03','V1315','阮明',3,'我输入时手滑打错字母，没想到系统会严格比对每一个字符啊。','wǒ shū rù shí shǒu huá dǎ cuò zì mǔ ， méi xiǎng dào xì tǒng huì yán gé bǐ duì měi yí gè zì fú a 。','Lúc nhập em bấm nhầm tay gõ sai chữ cái, không ngờ hệ thống lại so khớp chặt chẽ từng ký tự như vậy.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1315_04','V1315','小唐',4,'留学生参赛实行实名核验，拼音必须和护照完全一致才行。','liú xué shēng cān sài shí xíng shí míng hé yàn ， pīn yīn bì xū hé hù zhào wán quán yí zhì cái xíng 。','Lưu học sinh dự thi phải thực hiện xác thực danh tính thật, nên phiên âm bắt buộc phải khớp hoàn toàn với hộ chiếu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1315_05','V1315','阮明',5,'那我直接修改表单拼音，刷新页面就能重新提交吗？','nà wǒ zhí jiē xiū gǎi biǎo dān pīn yīn ， shuā xīn yè miàn jiù néng chóng xīn tí jiāo ma ？','Vậy em sửa lại phần phiên âm trên biểu mẫu, rồi tải lại trang là có thể nộp lại được luôn phải không chị?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1315_06','V1315','小唐',6,'是的，修改完成保存，五分钟后再提交系统就能核验通过哈。','shì de ， xiū gǎi wán chéng bǎo cún ， wǔ fēn zhōng hòu zài tí jiāo xì tǒng jiù néng hé yàn tōng guò hā 。','Đúng rồi, sửa xong lưu lại, khoảng năm phút sau nộp lại thì hệ thống sẽ xác thực qua thôi.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1315_07','V1315','阮明',7,'好嘞，我马上修正拼写，尽快完成申报。','hǎo lei ， wǒ mǎ shàng xiū zhèng pīn xiě ， jǐn kuài wán chéng shēn bào 。','Dạ được, em sửa lại chính tả ngay đây, cố gắng hoàn thành đăng ký sớm nhất có thể.','AM08') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1316','SHTN1','完成实验论文数据，想挂国内导师一作、自己二作，和导师沟通署名规范',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1316','SIT1316','P1','suon_se','ban_chinh_thuc',NULL,'国内学术论文署名遵循实际贡献排序，学生独立完成核心实验可列为一作，导师通常担任通讯作者，强行争抢一作不符合学术规范。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1316_01','V1316','阮明',1,'张老师，论文数据全部整理完毕，想跟您沟通一下作者署名顺序。','zhāng lǎo shī ， lùn wén shù jù quán bù zhěng lǐ wán bì ， xiǎng gēn nín gōu tōng yī xià zuò zhě shǔ míng shùn xù 。','Thưa thầy Trương, dữ liệu bài báo em đã xử lý xong hết rồi, em muốn trao đổi với thầy về thứ tự tác giả ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1316_02','V1316','张导师',2,'你全程主导实验设计与数据采集，按惯例你放第一作者就行啦。','nǐ quán chéng zhǔ dǎo shí yàn shè jì yǔ shù jù cǎi jí ， àn guàn lì nǐ fàng dì yī zuò zhě jiù xíng la 。','Em là người chủ trì toàn bộ thiết kế thí nghiệm và thu thập dữ liệu, theo thông lệ thì em đứng tên tác giả thứ nhất là được rồi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1316_03','V1316','阮明',3,'可是国内期刊是不是更看重导师一作，对论文影响力更好呢？','kě shì guó nèi qī kān shì bú shì gèng kàn zhòng dǎo shī yī zuò ， duì lùn wén yǐng xiǎng lì gèng hǎo ne ？','Nhưng tạp chí trong nước có phải là coi trọng tên thầy đứng đầu hơn không ạ, vậy sẽ tốt cho sức ảnh hưởng của bài báo hơn?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1316_04','V1316','张导师',4,'留学生独立完成实验，学生一作完全符合期刊署名规范，不用谦让嘛。','liú xué shēng dú lì wán chéng shí yàn ， xué shēng yī zuò wán quán fú hé qī kān shǔ míng guī fàn ， bù yòng qiān ràng ma 。','Lưu học sinh tự mình hoàn thành thí nghiệm thì em đứng tên tác giả thứ nhất hoàn toàn đúng quy định của tạp chí, không cần nhường đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1316_05','V1316','阮明',5,'那我二作标注您，感谢您全程指导实验设计可以吗？','nà wǒ èr zuò biāo zhù nín ， gǎn xiè nín quán chéng zhǐ dǎo shí yàn shè jì kě yǐ ma ？','Vậy em ghi tên thầy là đồng tác giả thứ hai, để cảm ơn thầy đã hướng dẫn toàn bộ thiết kế thí nghiệm, được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1316_06','V1316','张导师',6,'当然，通讯作者留我的名字，后续期刊对接由我处理哈。','dāng rán ， tōng xùn zuò zhě liú wǒ de míng zì ， hòu xù qī kān duì jiē yóu wǒ chǔ lǐ hā 。','Được chứ, còn tác giả liên hệ thì cứ để tên thầy, việc liên hệ với tạp chí sau này thầy lo cho.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1316_07','V1316','阮明',7,'太感谢您体谅留学生，我现在就调整论文作者信息。','tài gǎn xiè nín tǐ liàng liú xué shēng ， wǒ xiàn zài jiù tiáo zhěng lùn wén zuò zhě xìn xī 。','Em cảm ơn thầy đã thông cảm cho lưu học sinh nhiều lắm, để em điều chỉnh lại thông tin tác giả bài báo ngay bây giờ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1317','SHTN1','受邀做校内留学生学术分享，不知道汇报时长、评分标准咨询学院教务老师',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1317','SIT1317','P1','suon_se','ban_chinh_thuc',NULL,'校内留学生学术分享会对语言表达包容度高，评审核心考察科研创新内容，不会因普通话不流利压低分数。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1317_01','V1317','阮明',1,'李老师您好，学院邀请我做留学生学术分享，想确认汇报相关要求啊。','lǐ lǎo shī nín hǎo ， xué yuàn yāo qǐng wǒ zuò liú xué shēng xué shù fēn xiǎng ， xiǎng què rèn huì bào xiāng guān yāo qiú a 。','Thưa cô Lý, khoa mời em làm buổi chia sẻ học thuật cho lưu học sinh, em muốn xác nhận lại các yêu cầu liên quan đến bài báo cáo ạ.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1317_02','V1317','李老师',2,'单人汇报严格控制在十五分钟，之后五分钟留给台下师生提问呢。','dān rén huì bào yán gé kòng zhì zài shí wǔ fēn zhōng ， zhī hòu wǔ fēn zhōng liú gěi tái xià shī shēng tí wèn ne 。','Mỗi người báo cáo được khống chế nghiêm ngặt trong mười lăm phút, sau đó dành năm phút cho thầy cô và sinh viên phía dưới đặt câu hỏi.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1317_03','V1317','阮明',3,'评分重点看研究成果，还是我的中文表达流畅程度呀？','píng fēn zhòng diǎn kàn yán jiū chéng guǒ ， hái shì wǒ de zhōng wén biǎo dá liú chàng chéng dù ya ？','Việc chấm điểm chủ yếu xem trọng kết quả nghiên cứu, hay là mức độ trôi chảy trong cách diễn đạt tiếng Trung của em ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1317_04','V1317','李老师',4,'更看重科研内容，语言表达只做参考，外籍学生不会刻意扣分的。','gèng kàn zhòng kē yán nèi róng ， yǔ yán biǎo dá zhǐ zuò cān kǎo ， wài jí xué shēng bú huì kè yì kòu fēn de 。','Chủ yếu xem trọng nội dung nghiên cứu, phần diễn đạt ngôn ngữ chỉ mang tính tham khảo thôi, sinh viên nước ngoài sẽ không bị trừ điểm cố ý đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1317_05','V1317','阮明',5,'PPT页面数量有没有限制，多放几张实验图可以吗？','PPT yè miàn shù liàng yǒu méi yǒu xiàn zhì ， duō fàng jǐ zhāng shí yàn tú kě yǐ ma ？','Số trang PPT có bị giới hạn không ạ, em cho thêm vài trang hình ảnh thực nghiệm được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1317_06','V1317','李老师',6,'没有页数限制，简洁清晰为主，不用堆砌大量文字哦。','méi yǒu yè shù xiàn zhì ， jiǎn jié qīng xī wéi zhǔ ， bù yòng duī qì dà liàng wén zì ó 。','Không giới hạn số trang, chủ yếu là ngắn gọn rõ ràng, không cần nhồi nhét quá nhiều chữ đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1317_07','V1317','阮明',7,'清楚啦，我按照十五分钟时长准备分享内容。','qīng chǔ la ， wǒ àn zhào shí wǔ fēn zhōng shí cháng zhǔn bèi fēn xiǎng nèi róng 。','Em rõ rồi ạ, em sẽ chuẩn bị nội dung chia sẻ theo đúng thời lượng mười lăm phút.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1318','SHTN1','申报校级海外交流科研基金，过往竞赛获奖证书无中文翻译无法通过初审',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1318','SIT1318','P1','twist','ban_chinh_thuc',NULL,'国内各类科研基金申报，境外获奖证明必须校内官方翻译机构出具中文译本，个人手写翻译不具备审核效力。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1318_01','V1318','阮明',1,'赵老师，我的海外科研基金初审被驳回，能告知具体问题在哪吗？','zhào lǎo shī ， wǒ de hǎi wài kē yán jī jīn chū shěn bèi bó huí ， néng gào zhī jù tǐ wèn tí zài nǎ ma ？','Thưa thầy Triệu, hồ sơ quỹ nghiên cứu khoa học ở nước ngoài của em bị trả lại ở vòng sơ khảo, thầy có thể cho em biết vấn đề cụ thể ở đâu không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1318_02','V1318','赵老师',2,'你提交的海外竞赛证书全是越南语，没有中文翻译无法核实奖项等级。','nǐ tí jiāo de hǎi wài jìng sài zhèng shū quán shì yuè nán yǔ ， méi yǒu zhōng wén fān yì wú fǎ hé shí jiǎng xiàng děng jí 。','Chứng chỉ giải thưởng các cuộc thi nước ngoài em nộp toàn bằng tiếng Việt, không có bản dịch tiếng Trung nên không thể xác minh hạng giải.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1318_03','V1318','阮明',3,'我自己手写翻译一份证书内容，能不能临时上传凑合用呢？','wǒ zì jǐ shǒu xiě fān yì yī fèn zhèng shū nèi róng ， néng bù néng lín shí shàng chuán còu hé yòng ne ？','Em tự tay dịch một bản nội dung chứng chỉ, liệu có thể tạm thời tải lên dùng tạm được không ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1318_04','V1318','赵老师',4,'不行哦，基金申报只认可学校翻译中心出具的正规翻译件嘛。','bù xíng ó ， jī jīn shēn bào zhǐ rèn kě xué xiào fān yì zhōng xīn chū jù de zhèng guī fān yì jiàn ma 。','Không được đâu, hồ sơ quỹ chỉ công nhận bản dịch chính quy do trung tâm dịch thuật của trường cấp thôi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1318_05','V1318','阮明',5,'翻译中心明天上午开门，我明天一早去办理翻译来得及吗？','fān yì zhōng xīn míng tiān shàng wǔ kāi mén ， wǒ míng tiān yī zǎo qù bàn lǐ fān yì lái de jí ma ？','Trung tâm dịch thuật sáng mai mở cửa, em đến làm dịch thuật sáng sớm mai thì có kịp không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1318_06','V1318','赵老师',6,'申报还有四天截止，完全来得及，办好立刻上传系统就行。','shēn bào hái yǒu sì tiān jié zhǐ ， wán quán lái de jí ， bàn hǎo lì kè shàng chuán xì tǒng jiù xíng 。','Hồ sơ còn bốn ngày nữa mới hết hạn, hoàn toàn kịp, làm xong tải lên hệ thống ngay là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1318_07','V1318','阮明',7,'好，我明天第一时间去翻译中心处理证书。','hǎo ， wǒ míng tiān dì yī shí jiān qù fān yì zhōng xīn chǔ lǐ zhèng shū 。','Dạ vâng, sáng mai em sẽ đến trung tâm dịch thuật xử lý chứng chỉ ngay đầu tiên.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1319','SHTN1','研究生预报名系统无法识别外籍身份证，找研究生院办公室人工核验信息',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1319','SIT1319','P1','suon_se','chinh_thuc',NULL,'国内研究生报名系统默认适配内地身份证，外籍留学生均需前往研究生院线下人工备案护照信息。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1319_01','V1319','阮明',1,'刘老师您好，硕士预报名系统识别不了我的外籍护照，一直提交失败。','liú lǎo shī nín hǎo ， shuò shì yù bào míng xì tǒng shí bié bù liǎo wǒ de wài jí hù zhào ， yì zhí tí jiāo shī bài 。','Chào thầy Lưu, hệ thống đăng ký sơ bộ thạc sĩ không nhận diện được hộ chiếu nước ngoài của em, cứ nộp là báo lỗi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1319_02','V1319','刘老师',2,'境外证件系统数据库匹配有限，你带护照原件来做人工核验吧。','jìng wài zhèng jiàn xì tǒng shù jù kù pǐ pèi yǒu xiàn ， nǐ dài hù zhào yuán jiàn lái zuò rén gōng hé yàn ba 。','Cơ sở dữ liệu hệ thống với giấy tờ nước ngoài khớp còn hạn chế, em mang hộ chiếu gốc đến để đối chiếu thủ công nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1319_03','V1319','阮明',3,'人工核验需要填写额外表格吗，流程会不会很繁琐呢？','rén gōng hé yàn xū yào tián xiě é wài biǎo gé ma ， liú chéng huì bú huì hěn fán suǒ ne ？','Đối chiếu thủ công có phải điền thêm mẫu gì không ạ, thủ tục có rườm rà lắm không?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1319_04','V1319','刘老师',4,'只填一张外籍考生信息备案表，十分钟就能完成全部手续啦。','zhǐ tián yī zhāng wài jí kǎo shēng xìn xī bèi àn biǎo ， shí fēn zhōng jiù néng wán chéng quán bù shǒu xù la 。','Chỉ cần điền một tờ đăng ký thông tin thí sinh nước ngoài thôi, mười phút là xong hết thủ tục.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1319_05','V1319','阮明',5,'核验完成后，我返回线上系统就能正常填报志愿了对吧？','hé yàn wán chéng hòu ， wǒ fǎn huí xiàn shàng xì tǒng jiù néng zhèng cháng tián bào zhì yuàn le duì ba ？','Sau khi đối chiếu xong, em quay lại hệ thống online là điền được nguyện vọng bình thường đúng không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1319_06','V1319','刘老师',6,'没错，后台同步信息之后，你直接正常报名即可。','méi cuò ， hòu tái tóng bù xìn xī zhī hòu ， nǐ zhí jiē zhèng cháng bào míng jí kě 。','Đúng rồi, sau khi hệ thống đồng bộ thông tin thì em đăng ký bình thường là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1319_07','V1319','阮明',7,'辛苦老师帮忙人工处理，不然我没法按时完成预报名咯。','xīn kǔ lǎo shī bāng máng rén gōng chǔ lǐ ， bù rán wǒ méi fǎ àn shí wán chéng yù bào míng gē 。','Cảm ơn thầy đã giúp em xử lý thủ công, không thì em không kịp hoàn thành đăng ký sơ bộ đúng hạn mất ạ.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1320','SHTN1','跨校联合科研交流会，不会主动上前和国内教授交换名片，请教带队老师社交方式',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1320','SIT1320','P1','suon_se','ban_chinh_thuc',NULL,'国内学术社交递名片讲究双手递送，自我介绍简洁得体，交流会主动结识导师是拓展科研资源的常规方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1320_01','V1320','阮明',1,'陈老师，交流会好多教授，我不知道怎么主动上前交流交换名片呢。','chén lǎo shī ， jiāo liú huì hǎo duō jiào shòu ， wǒ bù zhī dào zěn me zhǔ dòng shàng qián jiāo liú jiāo huàn míng piàn ne 。','Thầy Trần ơi, buổi giao lưu có nhiều giáo sư quá, em không biết chủ động lại gần trao đổi và trao danh thiếp thế nào ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1320_02','V1320','陈老师',2,'等教授休息空档再上前，先简单自我介绍，再双手递出名片吧。','děng jiào shòu xiū xī kōng dàng zài shàng qián ， xiān jiǎn dān zì wǒ jiè shào ， zài shuāng shǒu dì chū míng piàn ba 。','Đợi lúc giáo sư rảnh thì lại gần, trước tiên giới thiệu bản thân ngắn gọn, rồi hai tay đưa danh thiếp nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1320_03','V1320','阮明',3,'自我介绍需要先说学校姓名，还是直接讲我的研究方向呀？','zì wǒ jiè shào xū yào xiān shuō xué xiào xìng míng ， hái shì zhí jiē jiǎng wǒ de yán jiū fāng xiàng ya ？','Giới thiệu bản thân thì nên nói tên trường trước, hay là nói luôn hướng nghiên cứu của em ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1320_04','V1320','陈老师',4,'先报院校姓名，再简单说明研究课题，简短两三句就好嘛。','xiān bào yuàn xiào xìng míng ， zài jiǎn dān shuō míng yán jiū kè tí ， jiǎn duǎn liǎng sān jù jiù hǎo ma 。','Nói tên trường trước, rồi nói ngắn gọn đề tài nghiên cứu, khoảng hai ba câu là được rồi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1320_05','V1320','阮明',5,'交换名片之后，要不要主动记下教授的研究方向方便后续联系？','jiāo huàn míng piàn zhī hòu ， yào bù yào zhǔ dòng jì xià jiào shòu de yán jiū fāng xiàng fāng biàn hòu xù lián xì ？','Sau khi trao danh thiếp, em có nên chủ động ghi lại hướng nghiên cứu của giáo sư để tiện liên hệ sau này không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1320_06','V1320','陈老师',6,'最好简单记录，后续邮件沟通时提及本次交流会更有礼貌哈。','zuì hǎo jiǎn dān jì lù ， hòu xù yóu jiàn gōu tōng shí tí jí běn cì jiāo liú huì gèng yǒu lǐ mào hā 。','Tốt nhất nên ghi chú ngắn gọn, sau này gửi email nhắc đến buổi giao lưu này thì sẽ lịch sự hơn.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1320_07','V1320','阮明',7,'学到很多社交细节，我等下主动和各位老师交流。','xué dào hěn duō shè jiāo xì jié ， wǒ děng xià zhǔ dòng hé gè wèi lǎo shī jiāo liú 。','Em học được nhiều điều về giao tiếp quá, lát nữa em sẽ chủ động qua chào các thầy cô.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1321','SHTN1','创新竞赛结题答辩，评委指出项目落地可行性不足，现场简短答辩补救',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1321','SIT1321','P1','twist','chinh_thuc',NULL,'国内创新创业类竞赛不只看重实验创新，项目产业落地可行性是评委重点评分板块，缺少落地规划会大幅扣分。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_01','V1321','周教授',1,'你的项目实验效果很好，但缺少落地实践方案，实用性偏弱。','nǐ de xiàng mù shí yàn xiào guǒ hěn hǎo ， dàn quē shǎo luò dì shí jiàn fāng àn ， shí yòng xìng piān ruò 。','Kết quả thí nghiệm của em rất tốt, nhưng thiếu phương án triển khai thực tế, tính ứng dụng còn yếu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_02','V1321','阮明',2,'周教授，我前期侧重实验室研究，忽略产业落地这块，实在抱歉。','zhōu jiào shòu ， wǒ qián qī cè zhòng shí yàn shì yán jiū ， hū lüè chǎn yè luò dì zhè kuài ， shí zài bào qiàn 。','Thưa giáo sư Chu, giai đoạn đầu em chú trọng nghiên cứu trong phòng thí nghiệm, có bỏ qua phần triển khai thực tế, em thật sự xin lỗi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_03','V1321','周教授',3,'那你简单说说，如果落地推广，打算怎么优化现有方案呢？','nà nǐ jiǎn dān shuō shuō ， rú guǒ luò dì tuī guǎng ， dǎ suàn zěn me yōu huà xiàn yǒu fāng àn ne ？','Vậy em nói ngắn gọn xem, nếu triển khai thực tế thì em định tối ưu phương án hiện tại như thế nào?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_04','V1321','阮明',4,'我后续计划和本地小微企业合作，小规模试点测试产品性能。','wǒ hòu xù jì huà hé běn dì xiǎo wēi qǐ yè hé zuò ， xiǎo guī mó shì diǎn cè shì chǎn pǐn xìng néng 。','Sau này em dự định hợp tác với các doanh nghiệp nhỏ tại địa phương, thử nghiệm quy mô nhỏ để kiểm tra hiệu năng sản phẩm ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_05','V1321','周教授',5,'这个思路可行，下次结题材料补充一份落地实施规划吧。','zhè ge sī lù kě xíng ， xià cì jié tí cái liào bǔ chōng yī fèn luò dì shí shī guī huà ba 。','Hướng này khả thi đấy, lần kết đề tài sau em bổ sung thêm một bản kế hoạch triển khai thực tế nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_06','V1321','阮明',6,'好的，答辩结束我立刻完善落地方案，补充进结题报告。','hǎo de ， dá biàn jié shù wǒ lì kè wán shàn luò dì fāng àn ， bǔ chōng jìn jié tí bào gào 。','Vâng ạ, sau buổi bảo vệ em sẽ hoàn thiện ngay phương án triển khai và bổ sung vào báo cáo kết đề tài.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_07','V1321','周教授',7,'整体创新点突出，补齐落地规划不影响本次项目结项哈。','zhěng tǐ chuàng xīn diǎn tū chū ， bǔ qí luò dì guī huà bù yǐng xiǎng běn cì xiàng mù jié xiàng hā 。','Nhìn chung điểm sáng tạo của đề tài rất nổi bật, bổ sung kế hoạch triển khai không ảnh hưởng đến việc kết đề tài lần này đâu.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1321_08','V1321','阮明',8,'感谢教授给出改进建议，我会完整完善项目材料。','gǎn xiè jiào shòu gěi chū gǎi jìn jiàn yì ， wǒ huì wán zhěng wán shàn xiàng mù cái liào 。','Em cảm ơn giáo sư đã góp ý, em sẽ hoàn thiện đầy đủ tài liệu đề tài ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1322','SHTN1','申请导师名下横向科研项目，不清楚学生劳务补贴发放标准咨询师兄',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1322','SIT1322','P1','suon_se','tuy_y',NULL,'国内高校横向科研项目学生劳务补贴统一标准，不区分中外学生，凭工时记录按月发放，无特殊差异化待遇。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1322_01','V1322','阮明',1,'峰师兄，我想加入导师横向项目，学生劳务补贴是怎么计算的呀？','fēng shī xiōng ， wǒ xiǎng jiā rù dǎo shī héng xiàng xiàng mù ， xué shēng láo wù bǔ tiē shì zěn me jì suàn de ya ？','Anh Phong ơi, em muốn tham gia dự án ngang của thầy hướng dẫn, trợ cấp lao động cho sinh viên tính thế nào vậy anh?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1322_02','V1322','林峰',2,'按每月实际参与工时核算，基础标准校内统一规定好啦。','àn měi yuè shí jì cān yù gōng shí hé suàn ， jī chǔ biāo zhǔn xiào nèi tǒng yī guī dìng hǎo la 。','Tính theo số giờ tham gia thực tế mỗi tháng, mức cơ bản thì trường quy định thống nhất rồi.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1322_03','V1322','阮明',3,'留学生和国内学生补贴标准是一样的，还是会有差别呢？','liú xué shēng hé guó nèi xué shēng bǔ tiē biāo zhǔn shì yī yàng de ， hái shì huì yǒu chā bié ne ？','Mức trợ cấp cho du học sinh với sinh viên trong nước có giống nhau không, hay có khác biệt gì không anh?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1322_04','V1322','林峰',4,'完全统一标准，只看你的实验工作量，不分国籍嘛。','wán quán tǒng yī biāo zhǔn ， zhǐ kàn nǐ de shí yàn gōng zuò liàng ， bù fēn guó jí ma 。','Hoàn toàn thống nhất một mức, chỉ tính theo khối lượng công việc thí nghiệm thôi, không phân biệt quốc tịch đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1322_05','V1322','阮明',5,'补贴每月什么时候发放，需要自己提交工时记录表吗？','bǔ tiē měi yuè shén me shí hòu fā fàng ， xū yào zì jǐ tí jiāo gōng shí jì lù biǎo ma ？','Trợ cấp phát hàng tháng vào lúc nào vậy anh, em có cần tự nộp bảng ghi giờ làm không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1322_06','V1322','林峰',6,'每月底上交工时表，次月中旬财务统一发放到校园卡。','měi yuè dǐ shàng jiāo gōng shí biǎo ， cì yuè zhōng xún cái wù tǒng yī fā fàng dào xiào yuán kǎ 。','Cuối mỗi tháng nộp bảng giờ làm, giữa tháng sau phòng tài vụ sẽ phát thống nhất vào thẻ sinh viên.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1322_07','V1322','阮明',7,'明白了，工作量我会认真记录，好好参与项目研究。','míng bái le ， gōng zuò liàng wǒ huì rèn zhēn jì lù ， hǎo hǎo cān yù xiàng mù yán jiū 。','Em hiểu rồi, em sẽ ghi chép khối lượng công việc cẩn thận và tham gia dự án nghiêm túc ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1323','SHTN1','国际学术会议线下注册，忘记携带纸质接收函，会务处不允许入场',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1323','SIT1323','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内线下学术会议注册优先核验纸质录用证明，手机电子版仅作备用，临近截止时间无法临时补办入场资格。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1323_01','V1323','阮明',1,'小郑你好，我来办理会议注册，忘记打印纸质摘要接收函了怎么办？','xiǎo zhèng nǐ hǎo ， wǒ lái bàn lǐ huì yì zhù cè ， wàng jì dǎ yìn zhǐ zhì zhāi yào jiē shōu hán le zěn me bàn ？','Chào bạn Tiểu Trịnh, mình đến làm thủ tục đăng ký hội nghị, mình quên in thư xác nhận nhận bài bản giấy rồi, giờ phải làm sao?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1323_02','V1323','小郑',2,'线下注册必须核验纸质接收函，电子版图片暂时不能作为凭证哦。','xiàn xià zhù cè bì xū hé yàn zhǐ zhì jiē shōu hán ， diàn zi bǎn tú piàn zàn shí bù néng zuò wéi píng zhèng ó 。','Đăng ký trực tiếp bắt buộc phải kiểm tra thư xác nhận bản giấy, ảnh chụp bản điện tử tạm thời không dùng làm bằng chứng được ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1323_03','V1323','阮明',3,'附近有没有打印店，我现在去打印还来得及入场吗？','fù jìn yǒu méi yǒu dǎ yìn diàn ， wǒ xiàn zài qù dǎ yìn hái lái de jí rù chǎng ma ？','Gần đây có tiệm in nào không, mình đi in ngay bây giờ thì có kịp vào không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1323_04','V1323','小郑',4,'校门口打印店距离这里十分钟路程，注册通道一小时后关闭。','xiào mén kǒu dǎ yìn diàn jù lí zhè lǐ shí fēn zhōng lù chéng ， zhù cè tōng dào yī xiǎo shí hòu guān bì 。','Tiệm in ở cổng trường cách đây mười phút đi bộ, quầy đăng ký đóng cửa sau một tiếng nữa thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1323_05','V1323','阮明',5,'来回路上要二十分钟，赶不上本次上午分会场的汇报了吗？','lái huí lù shàng yào èr shí fēn zhōng ， gǎn bù shàng běn cì shàng wǔ fēn huì chǎng de huì bào le ma ？','Đi về mất khoảng hai mươi phút, vậy là không kịp phần báo cáo ở phân ban buổi sáng nay rồi phải không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1323_06','V1323','小郑',6,'是的，上午场次注册即将截止，你只能参加下午的论坛活动咯。','shì de ， shàng wǔ chǎng cì zhù cè jí jiāng jié zhǐ ， nǐ zhǐ néng cān jiā xià wǔ de lùn tán huó dòng gē 。','Đúng vậy, đăng ký cho buổi sáng sắp hết hạn rồi, bạn chỉ có thể tham gia diễn đàn buổi chiều thôi.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1323_07','V1323','阮明',7,'都怪我出门疏忽忘记打印，只能错过上午汇报环节。','dōu guài wǒ chū mén shū hū wàng jì dǎ yìn ， zhǐ néng cuò guò shàng wǔ huì bào huán jié 。','Đúng là tại mình sơ suất quên in trước khi ra khỏi nhà, đành phải lỡ mất phần báo cáo buổi sáng rồi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1324','SHTN1','撰写硕士调剂申请邮件，不清楚国内调剂规则，找留学生办公室老师指导措辞',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1324','SIT1324','P1','suon_se','ban_chinh_thuc',NULL,'国内研究生调剂邮件讲究客观务实，过度客套吹捧容易让导师反感，附件材料齐全、正文简短是最优格式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1324_01','V1324','阮明',1,'孙老师，我一志愿复试未通过，想写调剂申请邮件，不懂国内调剂规则呢。','sūn lǎo shī ， wǒ yī zhì yuàn fù shì wèi tōng guò ， xiǎng xiě tiáo jì shēn qǐng yóu jiàn ， bù dǒng guó nèi tiáo jì guī zé ne 。','Thầy Tôn ơi, em thi vào nguyện vọng một không qua phỏng vấn, em muốn viết email xin điều chỉnh nguyện vọng nhưng không rõ quy tắc điều chỉnh trong nước ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1324_02','V1324','孙老师',2,'调剂只能选择有空缺名额的专业，不能跨相差过大的学科门类哦。','tiáo jì zhǐ néng xuǎn zé yǒu kòng quē míng é de zhuān yè ， bù néng kuà xiāng chà guò dà de xué kē mén lèi ó 。','Điều chỉnh nguyện vọng chỉ được chọn ngành còn chỉ tiêu trống, không được chuyển sang nhóm ngành khác biệt quá lớn đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1324_03','V1324','阮明',3,'邮件里需要附上哪些材料，简历和成绩单都要粘贴附件吗？','yóu jiàn lǐ xū yào fù shàng nǎ xiē cái liào ， jiǎn lì hé chéng jì dān dōu yào zhān tiē fù jiàn ma ？','Trong email cần đính kèm những tài liệu gì ạ, sơ yếu lý lịch và bảng điểm có cần dán làm file đính kèm không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1324_04','V1324','孙老师',4,'简历、成绩单、护照扫描件全部作为附件，正文简洁说明调剂诉求。','jiǎn lì 、 chéng jì dān 、 hù zhào sǎo miáo jiàn quán bù zuò wéi fù jiàn ， zhèng wén jiǎn jié shuō míng tiáo jì sù qiú 。','Sơ yếu lý lịch, bảng điểm, bản scan hộ chiếu đều đính kèm hết, phần nội dung chính thì trình bày ngắn gọn nguyện vọng điều chỉnh thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1324_05','V1324','阮明',5,'发给导师的邮件，要不要过度夸赞对方课题组，会不会显得浮夸？','fā gěi dǎo shī de yóu jiàn ， yào bù yào guò dù kuā zàn duì fāng kè tí zǔ ， huì bú huì xiǎn de fú kuā ？','Gửi email cho thầy hướng dẫn thì có nên khen ngợi quá nhóm nghiên cứu của họ không ạ, sợ nghe sáo rỗng quá?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1324_06','V1324','孙老师',6,'客观说明自身科研经历即可，真诚简洁比刻意吹捧更受认可嘛。','kè guān shuō míng zì shēn kē yán jīng lì jí kě ， zhēn chéng jiǎn jié bǐ kè yì chuī pěng gèng shòu rèn kě ma 。','Cứ trình bày khách quan kinh nghiệm nghiên cứu của bản thân là được, chân thành ngắn gọn còn được đánh giá cao hơn là tâng bốc.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1324_07','V1324','阮明',7,'我按照您说的规范撰写邮件，写完请您帮忙再把关一下。','wǒ àn zhào nín shuō de guī fàn zhuàn xiě yóu jiàn ， xiě wán qǐng nín bāng máng zài bǎ guān yī xià 。','Em sẽ viết email theo đúng chuẩn thầy nói, viết xong nhờ thầy xem giúp em lại một lượt ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1325','SHTN1','科研成果申报评奖，不清楚国内学生成果署名排序加分规则，咨询学院科研秘书',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1325','SIT1325','P1','suon_se','ban_chinh_thuc',NULL,'国内高校科研评奖规则统一面向全体在校学生，中外学生成果加分、评奖标准无任何区别，公平统一核算分值。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1325_01','V1325','阮明',1,'小秦秘书，我申报校级科研成果奖，署名顺序加分标准我不太清楚。','xiǎo qín mì shū ， wǒ shēn bào xiào jí kē yán chéng guǒ jiǎng ， shǔ míng shùn xù jiā fēn biāo zhǔn wǒ bù tài qīng chǔ 。','Chị Tần thư ký ơi, em đăng ký giải thưởng nghiên cứu khoa học cấp trường, nhưng chưa rõ tiêu chuẩn cộng điểm theo thứ tự tác giả lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1325_02','V1325','小秦',2,'第一作者加分最高，第二、第三作者分值依次递减，通讯作者单独加分。','dì yī zuò zhě jiā fēn zuì gāo ， dì èr 、 dì sān zuò zhě fēn zhí yī cì dì jiǎn ， tōng xùn zuò zhě dān dú jiā fēn 。','Tác giả thứ nhất được cộng điểm cao nhất, tác giả thứ hai, thứ ba giảm dần, tác giả liên hệ được cộng điểm riêng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1325_03','V1325','阮明',3,'留学生作为一作，和国内学生的加分标准完全一样吗？','liú xué shēng zuò wéi yī zuò ， hé guó nèi xué shēng de jiā fēn biāo zhǔn wán quán yī yàng ma ？','Nếu du học sinh là tác giả chính thì tiêu chuẩn cộng điểm có hoàn toàn giống sinh viên trong nước không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1325_04','V1325','小秦',4,'评奖规则统一，不分中外学生，只看作者排序与期刊级别嘛。','píng jiǎng guī zé tǒng yī ， bù fēn zhōng wài xué shēng ， zhǐ kàn zuò zhě pái xù yǔ qī kān jí bié ma 。','Quy định xét giải là thống nhất, không phân biệt sinh viên trong hay ngoài nước, chỉ xét thứ tự tác giả và cấp bậc tạp chí thôi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1325_05','V1325','阮明',5,'多篇论文一起申报，是不是取分值最高的一篇计算奖项等级？','duō piān lùn wén yì qǐ shēn bào ， shì bú shì qǔ fēn zhí zuì gāo de yī piān jì suàn jiǎng xiàng děng jí ？','Nếu nộp nhiều bài cùng lúc thì có phải lấy bài có điểm cao nhất để tính hạng giải không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1325_06','V1325','小秦',6,'没错，系统自动核算最高分成果，其余论文作为辅助加分项。','méi cuò ， xì tǒng zì dòng hé suàn zuì gāo fēn chéng guǒ ， qí yú lùn wén zuò wéi fǔ zhù jiā fēn xiàng 。','Đúng vậy, hệ thống sẽ tự động tính bài có điểm cao nhất, các bài còn lại chỉ là điểm cộng phụ thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1325_07','V1325','阮明',7,'清楚加分规则了，我整理好论文材料提交申报。','qīng chǔ jiā fēn guī zé le ， wǒ zhěng lǐ hǎo lùn wén cái liào tí jiāo shēn bào 。','Em rõ quy tắc cộng điểm rồi, em sẽ chuẩn bị đầy đủ tài liệu bài báo rồi nộp đăng ký ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1401','SATN1','本地正宗川菜馆线下点餐，分不清微辣、中辣、特辣，询问服务员辣度区别',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1401','SIT1401','P1','twist','tuy_y',NULL,'川菜辣、麻分开调整，食客可自由增减花椒辣椒，店家都会按口味定制菜品。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1401_01','V1401','阮明',1,'你好，水煮鱼辣度分三档，微辣会不会也很呛呢？','nǐ hǎo ， shuǐ zhǔ yú là dù fēn sān dàng ， wēi là huì bú huì yě hěn qiāng ne ？','Cho hỏi, món cá om cay chia ba mức độ cay, vị cay nhẹ có bị tê quá không vậy?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1401_02','V1401','小琳',2,'微辣只放少量干辣椒，中辣加花椒，特辣铺满红油很刺激哦。','wēi là zhǐ fàng shǎo liàng gàn là jiāo ， zhōng là jiā huā jiāo ， tè là pù mǎn hóng yóu hěn cì jī ó 。','Cay nhẹ chỉ cho ít ớt khô thôi, cay vừa thêm hạt tiêu, còn cay đặc biệt thì phủ đầy dầu ớt, ăn kích thích lắm luôn.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1401_03','V1401','阮明',3,'我肠胃不耐辣，所有菜都做成微辣，再少放花椒行吗？','wǒ cháng wèi bù nài là ， suǒ yǒu cài dōu zuò chéng wēi là ， zài shǎo fàng huā jiāo xíng ma ？','Bụng mình không chịu được cay lắm, cho tất cả các món làm cay nhẹ, với lại bớt hạt tiêu lại được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1401_04','V1401','小琳',4,'没问题，我给后厨备注少麻少辣，不吃麻椒也能直接去掉嘛。','méi wèn tí ， wǒ gěi hòu chú bèi zhù shǎo má shǎo là ， bù chī má jiāo yě néng zhí jiē qù diào ma 。','Không vấn đề gì, mình ghi chú cho bếp là ít tê ít cay, không ăn hạt tiêu thì bỏ luôn cũng được.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1401_05','V1401','阮明',5,'除了水煮鱼，再来一份不辣的清炒时蔬均衡一下。','chú le shuǐ zhǔ yú ， zài lái yī fèn bù là de qīng chǎo shí shū jūn héng yī xià 。','Ngoài cá om cay, cho thêm một đĩa rau xào không cay nữa để cân bằng lại.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1401_06','V1401','小琳',6,'好嘞，主食要米饭还是红糖糍粑，糍粑是甜口不辣的哈。','hǎo lei ， zhǔ shí yào mǐ fàn hái shì hóng táng cí bā ， cí bā shì tián kǒu bù là de hā 。','Được luôn, món chính lấy cơm hay bánh nếp đường đỏ, bánh nếp là vị ngọt không cay đâu.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1401_07','V1401','阮明',7,'一碗米饭就够，麻烦上菜速度快一点啦。','yī wǎn mǐ fàn jiù gòu ， má fán shàng cài sù dù kuài yì diǎn la 。','Một bát cơm là đủ rồi, phiền lên món nhanh giúp mình với nhé.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1402','SATN1','高端中式酒楼提前电话订包厢，咨询最低消费、包厢服务费规则',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1402','SIT1402','P1','suon_se','ban_chinh_thuc',NULL,'中式酒楼包厢常设最低消费，茶位费、开瓶费是国内餐饮通用附加收费项目。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1402_01','V1402','阮明',1,'静姐您好，我想订周六六人包厢，想问下有没有最低消费呀？','jìng jiě nín hǎo ， wǒ xiǎng dìng zhōu liù liù rén bāo xiāng ， xiǎng wèn xià yǒu méi yǒu zuì dī xiāo fèi ya ？','Chị Tĩnh ơi, em muốn đặt phòng VIP cho sáu người vào thứ Bảy, cho em hỏi có mức chi tiêu tối thiểu không ạ?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1402_02','V1402','静姐',2,'小包厢最低消费三百八，不额外收包厢服务费，茶水另算哦。','xiǎo bāo xiāng zuì dī xiāo fèi sān bǎi bā ， bù é wài shōu bāo xiāng fú wù fèi ， chá shuǐ lìng suàn ó 。','Phòng nhỏ mức chi tiêu tối thiểu là ba trăm tám, không tính thêm phí phục vụ phòng đâu, còn trà nước tính riêng nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1402_03','V1402','阮明',3,'茶水是按人头收取茶位费吗？','chá shuǐ shì àn rén tóu shōu qǔ chá wèi fèi ma ？','Trà nước là tính phí trà theo đầu người đúng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1402_04','V1402','静姐',4,'对，每人十元茶位，包含免费续茶、餐前小碟凉菜嘛。','duì ， měi rén shí yuán chá wèi ， bāo hán miǎn fèi xù chá 、 cān qián xiǎo dié liáng cài ma 。','Đúng rồi, mỗi người mười tệ phí trà, bao gồm châm trà miễn phí và món khai vị nguội nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1402_05','V1402','阮明',5,'如果自带酒水，酒楼会收取开瓶费吗？','rú guǒ zì dài jiǔ shuǐ ， jiǔ lóu huì shōu qǔ kāi píng fèi ma ？','Nếu tự mang rượu vào thì nhà hàng có tính phí mở nắp không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1402_06','V1402','静姐',6,'自带白酒、红酒收取五十元开瓶费，啤酒不用收费哈。','zì dài bái jiǔ 、 hóng jiǔ shōu qǔ wǔ shí yuán kāi píng fèi ， pí jiǔ bù yòng shōu fèi hā 。','Tự mang rượu trắng, rượu vang thì tính năm mươi tệ phí mở nắp, còn bia thì không tính phí đâu.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1402_07','V1402','阮明',7,'清楚所有收费项目，现在预留周六晚上六点的包厢。','qīng chǔ suǒ yǒu shōu fèi xiàng mù ， xiàn zài yù liú zhōu liù wǎn shàng liù diǎn de bāo xiāng 。','Em rõ hết các khoản phí rồi, giờ em đặt giữ phòng lúc sáu giờ tối thứ Bảy nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1403','SATN1','使用国内外卖平台点餐，境外手机号无法注册，找同学帮忙代点外卖',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1403','SIT1403','P1','suon_se','tuy_y',NULL,'美团、饿了么等外卖平台实名注册仅支持大陆手机号，外籍留学生大多委托本土同学代下单。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1403_01','V1403','阮明',1,'浩宇，外卖软件必须大陆手机号注册，你能帮我代点一份家常菜吗？','hào yǔ ， wài mài ruǎn jiàn bì xū dà lù shǒu jī hào zhù cè ， nǐ néng bāng wǒ dài diǎn yī fèn jiā cháng cài ma ？','Hạo Vũ ơi, app đặt đồ ăn bắt buộc phải đăng ký bằng số điện thoại Trung Quốc đại lục, cậu đặt giúp tớ một suất cơm nhà được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1403_02','V1403','浩宇',2,'没问题，把想吃的店铺、菜品和宿舍地址发给我就行啦。','méi wèn tí ， bǎ xiǎng chī de diàn pù 、 cài pǐn hé sù shè dì zhǐ fā gěi wǒ jiù xíng la 。','Không vấn đề gì, cậu gửi tên quán, món ăn muốn ăn với địa chỉ ký túc xá cho tớ là được.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1403_03','V1403','阮明',3,'备注少辣少油，配送放宿舍楼下驿站不用打电话。','bèi zhù shǎo là shǎo yóu ， pèi sòng fàng sù shè lóu xià yì zhàn bù yòng dǎ diàn huà 。','Nhớ ghi chú ít cay ít dầu giúp tớ nhé, giao xuống trạm dưới tòa ký túc xá không cần gọi điện đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1403_04','V1403','浩宇',4,'我直接备注好，外卖超时还能申请商家小额补偿嘛。','wǒ zhí jiē bèi zhù hǎo ， wài mài chāo shí hái néng shēn qǐng shāng jiā xiǎo é bǔ cháng ma 。','Tớ ghi chú luôn cho, đồ ăn giao trễ còn có thể xin quán bồi thường chút tiền nữa đấy.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1403_05','V1403','阮明',5,'等下单完成，我立刻微信把餐费转给你。','děng xià dān wán chéng ， wǒ lì kè wēi xìn bǎ cān fèi zhuǎn gěi nǐ 。','Đợi đặt xong tớ chuyển tiền ăn cho cậu qua WeChat ngay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1403_06','V1403','浩宇',6,'小事而已，下次想吃外卖随时跟我说哈。','xiǎo shì ér yǐ ， xià cì xiǎng chī wài mài suí shí gēn wǒ shuō hā 。','Chuyện nhỏ thôi mà, lần sau muốn ăn gì cứ nói với tớ nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1403_07','V1403','阮明',7,'太感谢，境外号码连点外卖都不方便咯。','tài gǎn xiè ， jìng wài hào mǎ lián diǎn wài mài dōu bù fāng biàn gē 。','Cảm ơn cậu nhiều lắm, số điện thoại nước ngoài đến đặt đồ ăn cũng bất tiện thật.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1404','SATN1','寻找清真风味菜馆聚餐，和店主确认菜品不含猪肉、猪油食材',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1404','SIT1404','P1','suon_se','ban_chinh_thuc',NULL,'国内清真餐馆严格规避猪肉及猪油制品，食客可直接向店主确认食材，店家会如实说明。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1404_01','V1404','阮明',1,'马老板，我们几位同学饮食忌口猪肉，店里所有菜都不含猪油吗？','mǎ lǎo bǎn ， wǒ men jǐ wèi tóng xué yǐn shí jì kǒu zhū ròu ， diàn lǐ suǒ yǒu cài dōu bù hán zhū yóu ma ？','Chú Mã ơi, tụi cháu mấy đứa kiêng ăn thịt heo, quán mình các món có dùng mỡ heo không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1404_02','V1404','马老板',2,'本店是正宗清真店，全部食材牛羊肉，烹饪只用清油，放心点哦。','běn diàn shì zhèng zōng qīng zhēn diàn ， quán bù shí cái niú yáng ròu ， pēng rèn zhǐ yòng qīng yóu ， fàng xīn diǎn ó 。','Quán này là quán Hồi chính gốc, nguyên liệu toàn là thịt bò thịt cừu, nấu chỉ dùng dầu thực vật thôi, cứ yên tâm gọi món nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1404_03','V1404','阮明',3,'红烧菜的酱料会不会混入动物油脂，需要单独调整做法吗？','hóng shāo cài de jiàng liào huì bú huì hùn rù dòng wù yóu zhī ， xū yào dān dú tiáo zhěng zuò fǎ ma ？','Nước sốt kho đỏ có bị lẫn mỡ động vật không ạ, có cần điều chỉnh cách chế biến riêng không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1404_04','V1404','马老板',4,'酱料都是植物调配，没有荤油，不用额外修改做法嘛。','jiàng liào dōu shì zhí wù diào pèi ， méi yǒu hūn yóu ， bù yòng é wài xiū gǎi zuò fǎ ma 。','Nước sốt toàn pha từ nguyên liệu thực vật, không có mỡ động vật, không cần chỉnh cách làm gì đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1404_05','V1404','阮明',5,'那点一份大盘鸡、烤包子和两份素菜，六个人够吃吗？','nà diǎn yī fèn dà pán jī 、 kǎo bāo zi hé liǎng fèn sù cài ， liù gè rén gòu chī ma ？','Vậy cho cháu gọi một phần đại bàn kê, bánh nướng kẹp và hai phần rau xào, sáu người ăn đủ không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1404_06','V1404','马老板',6,'再加一碗手擀面，分量刚好，不会不够也不浪费哈。','zài jiā yī wǎn shǒu gǎn miàn ， fèn liàng gāng hǎo ， bú huì bù gòu yě bù làng fèi hā 。','Gọi thêm một tô mì tự cán nữa là vừa đủ, không thiếu mà cũng không thừa đâu.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1404_07','V1404','阮明',7,'好，那就按这个菜单下单，辛苦老板了。','hǎo ， nà jiù àn zhè ge cài dān xià dān ， xīn kǔ lǎo bǎn le 。','Vâng, vậy cứ theo thực đơn này mà đặt cho cháu, cảm ơn chú nhiều ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1405','SATN1','探访本地老字号淮扬菜馆，看不懂古风纸质菜单，请店员讲解招牌名菜',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1405','SIT1405','P1','twist','tuy_y',NULL,'老字号中式菜馆多使用传统雅致菜名，无配图，不熟悉中餐的游客需要店员通俗讲解菜品内容。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1405_01','V1405','阮明',1,'小哥，菜单上很多古风菜名我看不懂，能推荐两道淮扬招牌吗？','xiǎo gē ， cài dān shàng hěn duō gǔ fēng cài míng wǒ kàn bù dǒng ， néng tuī jiàn liǎng dào huái yáng zhāo pái ma ？','Anh ơi, thực đơn có nhiều tên món kiểu cổ em không hiểu, anh gợi ý giúp em hai món đặc sản Hoài Dương được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1405_02','V1405','阿泽',2,'狮子头、文思豆腐是本店必点，都是清淡不辣的经典菜品呢。','shī zi tóu 、 wén sī dòu fǔ shì běn diàn bì diǎn ， dōu shì qīng dàn bù là de jīng diǎn cài pǐn ne 。','Sư tử đầu với đậu hũ Văn Tư là hai món phải gọi của quán, đều là món kinh điển thanh đạm không cay đấy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1405_03','V1405','阮明',3,'狮子头是肥肉多还是瘦肉多，会不会很油腻呀？','shī zi tóu shì féi ròu duō hái shì shòu ròu duō ， huì bú huì hěn yóu nì ya ？','Sư tử đầu là mỡ nhiều hay nạc nhiều vậy, có bị ngấy lắm không anh?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1405_04','V1405','阿泽',4,'肥瘦三七配比，炖得软烂，搭配青菜吃完全不腻嘛。','féi shòu sān qī pèi bǐ ， dùn dé ruǎn làn ， dā pèi qīng cài chī wán quán bù nì ma 。','Tỷ lệ mỡ nạc ba bảy thôi, hầm mềm nhừ, ăn kèm rau xanh là không thấy ngấy tí nào đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1405_05','V1405','阮明',5,'文思豆腐切得特别细，吃起来是什么口感？','wén sī dòu fǔ qiè dé tè bié xì ， chī qǐ lái shì shén me kǒu gǎn ？','Đậu hũ Văn Tư thái sợi mảnh vậy, ăn vào có vị thế nào ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1405_06','V1405','阿泽',6,'豆腐丝入口即化，汤汁鲜，很适合口味清淡的客人哈。','dòu fǔ sī rù kǒu jí huà ， tāng zhī xiān ， hěn shì hé kǒu wèi qīng dàn de kè rén hā 。','Sợi đậu hũ tan ngay trong miệng, nước dùng ngọt thanh, rất hợp với khách khẩu vị nhẹ đấy.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1405_07','V1405','阮明',7,'那就这两道，再加一碗米饭尝尝本地口味。','nà jiù zhè liǎng dào ， zài jiā yī wǎn mǐ fàn cháng cháng běn dì kǒu wèi 。','Vậy cho em hai món này, thêm một bát cơm để nếm thử hương vị địa phương nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1406','SATN1','组队留学生聚餐，主动做东请客，和同行同学商量点菜数量与预算',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1406','SIT1406','P1','suon_se','tuy_y',NULL,'国内请客吃饭讲究荤素冷热搭配，点单数量一般比人数多一到两道，避免菜品不够显得失礼。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1406_01','V1406','阮明',1,'今天我请客，咱们四个人点菜控制在三百以内，够吃就行别浪费啦。','jīn tiān wǒ qǐng kè ， zán men sì gè rén diǎn cài kòng zhì zài sān bǎi yǐ nèi ， gòu chī jiù xíng bié làng fèi la 。','Hôm nay tớ mời, bốn đứa mình gọi món trong khoảng ba trăm thôi, đủ ăn là được đừng phí phạm nhé.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1406_02','V1406','阿凯',2,'你做东不用太节省，四菜一汤搭配荤素，差不多刚好两百多。','nǐ zuò dōng bù yòng tài jié shěng ， sì cài yī tāng dā pèi hūn sù ， chà bu duō gāng hǎo liǎng bǎi duō 。','Cậu làm chủ chi không cần tiết kiệm quá đâu, bốn món một canh có mặn có rau là khoảng hơn hai trăm thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1406_03','V1406','阮明',3,'那两道肉菜两道素菜，再加一份甜品均衡口味可以吗？','nà liǎng dào ròu cài liǎng dào sù cài ， zài jiā yī fèn tián pǐn jūn héng kǒu wèi kě yǐ ma ？','Vậy hai món mặn hai món rau, thêm một phần tráng miệng cho cân bằng khẩu vị được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1406_04','V1406','阿凯',4,'这个搭配很合适，冷热菜分开，吃着不会腻嘛。','zhè ge dā pèi hěn hé shì ， lěng rè cài fēn kāi ， chī zhe bú huì nì ma 。','Kết hợp vậy hợp lý đấy, món nóng món lạnh tách riêng ra, ăn sẽ không bị ngấy đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1406_05','V1406','阮明',5,'有没有大家都爱吃的本地菜，优先点大家熟悉的口味。','yǒu méi yǒu dà jiā dōu ài chī de běn dì cài ， yōu xiān diǎn dà jiā shú xī de kǒu wèi 。','Có món địa phương nào ai cũng thích ăn không, ưu tiên gọi món quen thuộc với mọi người nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1406_06','V1406','阿凯',6,'大家都爱吃糖醋里脊，直接放进菜单里哈。','dà jiā dōu ài chī táng cù lǐ jí ， zhí jiē fàng jìn cài dān lǐ hā 。','Ai cũng thích ăn sườn chua ngọt đấy, cứ cho luôn vào danh sách gọi món đi.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1406_07','V1406','阮明',7,'行，我现在喊服务员过来下单。','xíng ， wǒ xiàn zài hǎn fú wù yuán guò lái xià dān 。','Được, giờ tớ gọi phục vụ qua để đặt món luôn đây.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1407','SATN1','粤式早茶酒楼自助点茶，分不清点心蒸笼大小份、茶位费收费规则',NULL,'B1') ON CONFLICT DO NOTHING;
