INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1222_04','V1222','小林',4,'超过容量无法带上高铁，要么现场丢弃，要么快递寄走。','chāo guò róng liàng wú fǎ dài shàng gāo tiě ， yào me xiàn chǎng diū qì ， yào me kuài dì jì zǒu 。','Vượt quá dung tích thì không thể mang lên tàu cao tốc, hoặc là bỏ lại tại chỗ, hoặc là gửi chuyển phát nhanh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1222_05','V1222','阮明',5,'快递邮寄要多少钱，多久能寄到我的学校宿舍？','kuài dì yóu jì yào duō shǎo qián ， duō jiǔ néng jì dào wǒ de xué xiào sù shè ？','Gửi chuyển phát nhanh thì tốn bao nhiêu tiền ạ, bao lâu thì đến ký túc xá trường em?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1222_06','V1222','小林',6,'同城快递十元，第二天送达，现在登记地址就行咯。','tóng chéng kuài dì shí yuán ， dì èr tiān sòng dá ， xiàn zài dēng jì dì zhǐ jiù xíng gē 。','Chuyển phát nhanh nội thành mười tệ, hôm sau là giao đến, giờ đăng ký địa chỉ là được ạ.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1222_07','V1222','阮明',7,'那我选择寄回去吧，丢掉护肤品太可惜啦。','nà wǒ xuǎn zé jì huí qù ba ， diū diào hù fū pǐn tài kě xī la 。','Vậy em chọn gửi về vậy, vứt bỏ đồ dưỡng da thì tiếc quá.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1223','SDL1','乡村旅游农家乐点菜，不清楚菜品分量大小',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1223','SIT1223','P1','twist','tuy_y',NULL,'农家乐家常菜盘子大、分量足，单人就餐建议少点菜品，避免浪费。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1223_01','V1223','阮明',1,'芳姐，我一个人吃饭，点两个菜会不会太多呢？','fāng jiě ， wǒ yí gè rén chī fàn ， diǎn liǎng gè cài huì bú huì tài duō ne ？','Chị Phương ơi, em ăn một mình, gọi hai món có nhiều quá không?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1223_02','V1223','芳姐',2,'咱们农家乐菜盘分量很大，一个人点一荤一素肯定吃不完的。','zán men nóng jiā lè cài pán fèn liàng hěn dà ， yí gè rén diǎn yī hūn yī sù kěn dìng chī bù wán de 。','Quán nhà mình phần ăn to lắm, một người gọi một món mặn một món rau chắc chắn ăn không hết đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1223_03','V1223','阮明',3,'那只点一份农家炒土鸡，再加一碗米饭行吗？','nà zhǐ diǎn yī fèn nóng jiā chǎo tǔ jī ， zài jiā yī wǎn mǐ fàn xíng ma ？','Vậy chỉ gọi một đĩa gà ta xào kiểu nhà quê, thêm một bát cơm được không chị?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1223_04','V1223','芳姐',4,'土鸡一盘够两个人吃，要不换个小份青菜怎么样？','tǔ jī yī pán gòu liǎng gè rén chī ， yào bù huàn gè xiǎo fèn qīng cài zěn me yàng ？','Một đĩa gà ta đủ cho hai người ăn rồi, hay đổi sang phần rau xanh nhỏ hơn nhé?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1223_05','V1223','阮明',5,'好，那就土鸡加一份清炒青菜，少放一点油吧。','hǎo ， nà jiù tǔ jī jiā yī fèn qīng chǎo qīng cài ， shǎo fàng yì diǎn yóu ba 。','Được, vậy gọi gà ta với một phần rau xào, cho ít dầu thôi nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1223_06','V1223','芳姐',6,'没问题，清淡做法，十分钟就能上菜哈。','méi wèn tí ， qīng dàn zuò fǎ ， shí fēn zhōng jiù néng shàng cài hā 。','Không vấn đề gì, nấu thanh đạm, mười phút là có món lên rồi.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1223_07','V1223','阮明',7,'乡下菜分量实在，还好提前问您，避免浪费食物。','xiāng xià cài fèn liàng shí zài ， hái hǎo tí qián wèn nín ， bì miǎn làng fèi shí wù 。','Món ăn nhà quê thật đầy đặn, may mà em hỏi chị trước, không thì phí đồ ăn quá.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1224','SDL1','美术馆参观，想拍照被工作人员制止',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1224','SIT1224','P1','twist','ban_chinh_thuc',NULL,'国内美术馆、博物馆馆藏艺术品禁止拍照，闪光灯会加速画作老化，同时保护著作权。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1224_01','V1224','阮明',1,'不好意思，这幅油画太美了，我拍一张照片留存可以吗？','bù hǎo yì sī ， zhè fú yóu huà tài měi le ， wǒ pāi yī zhāng zhào piān liú cún kě yǐ ma ？','Xin lỗi anh, bức tranh sơn dầu này đẹp quá, em chụp một tấm ảnh lưu niệm được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1224_02','V1224','老杨',2,'展厅内全部展品禁止拍照，尤其是不能开闪光灯哦。','zhǎn tīng nèi quán bù zhǎn pǐn jìn zhǐ pāi zhào ， yóu qí shì bù néng kāi shǎn guāng dēng ó 。','Tất cả hiện vật trong phòng trưng bày đều cấm chụp ảnh, đặc biệt là không được bật đèn flash ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1224_03','V1224','阮明',3,'我不开闪光灯，单纯记录画面也不行吗？','wǒ bù kāi shǎn guāng dēng ， dān chún jì lù huà miàn yě bù xíng ma ？','Em không bật đèn flash, chỉ đơn thuần ghi lại hình ảnh thôi cũng không được sao ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1224_04','V1224','老杨',4,'这幅画作有版权保护，任何拍摄都会损伤颜料图层的。','zhè fú huà zuò yǒu bǎn quán bǎo hù ， rèn hé pāi shè dōu huì sǔn shāng yán liào tú céng de 。','Bức tranh này có bản quyền bảo vệ, bất kỳ việc chụp ảnh nào cũng sẽ làm hỏng lớp màu đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1224_05','V1224','阮明',5,'原来是这样，我不了解美术馆的规定，抱歉啦。','yuán lái shì zhè yàng ， wǒ bù liǎo jiě měi shù guǎn de guī dìng ， bào qiàn la 。','Ra là vậy, em không biết quy định của phòng trưng bày, xin lỗi anh ạ.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1224_06','V1224','老杨',6,'没关系，展厅门口都贴了提示，下次留意一下哈。','méi guān xì ， zhǎn tīng mén kǒu dōu tiē le tí shì ， xià cì liú yì yī xià hā 。','Không sao, ở cửa phòng trưng bày đều có dán thông báo, lần sau chú ý một chút nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1224_07','V1224','阮明',7,'好，我收起手机，安静慢慢欣赏画作。','hǎo ， wǒ shōu qǐ shǒu jī ， ān jìng màn màn xīn shǎng huà zuò 。','Vâng, em cất điện thoại đi, yên lặng từ từ thưởng thức tranh.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1225','SDL1','旅游途中肠胃不舒服，在景区药店买中成药',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1225','SIT1225','P1','suon_se','chinh_thuc',NULL,'国内药店中成药无需处方即可购买，药师会根据症状推荐对应药品，购药前说明自身症状。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_01','V1225','阮明',1,'药师您好，我旅游吃坏肚子，一直腹痛腹泻，该买什么药呢？','yào shī nín hǎo ， wǒ lǚ yóu chī huài dǔ zi ， yì zhí fù tòng fù xiè ， gāi mǎi shén me yào ne ？','Dược sĩ ơi, tôi đi du lịch bị đau bụng, cứ đau bụng tiêu chảy suốt, nên mua thuốc gì ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_02','V1225','陈药师',2,'先说说你的症状，一天大概拉肚子几次，有没有胃痛？','xiān shuō shuō nǐ de zhèng zhuàng ， yī tiān dà gài lā dù zi jǐ cì ， yǒu méi yǒu wèi tòng ？','Anh nói qua triệu chứng xem, một ngày đi ngoài khoảng mấy lần, có đau dạ dày không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_03','V1225','阮明',3,'已经跑厕所四次，肚子隐隐作痛，浑身没力气啦。','yǐ jīng pǎo cè suǒ sì cì ， dǔ zi yǐn yǐn zuò tòng ， hún shēn méi lì qì la 。','Tôi đã chạy vào nhà vệ sinh bốn lần rồi, bụng cứ âm ỉ đau, người mệt lả luôn.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_04','V1225','陈药师',4,'那给你拿一盒肠胃中成药，饭后温水服用，一天三次。','nà gěi nǐ ná yī hé cháng wèi zhōng chéng yào ， fàn hòu wēn shuǐ fú yòng ， yī tiān sān cì 。','Vậy tôi lấy cho anh một hộp thuốc đông y trị dạ dày, uống với nước ấm sau khi ăn, ngày ba lần.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_05','V1225','阮明',5,'这个药外国人服用有没有禁忌，会不会过敏啊？','zhè ge yào wài guó rén fú yòng yǒu méi yǒu jìn jì ， huì bú huì guò mǐn a ？','Thuốc này người nước ngoài dùng có kiêng kỵ gì không, có bị dị ứng không ạ?','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_06','V1225','陈药师',6,'药性温和，很少过敏，服药期间别吃生冷辛辣食物嘛。','yào xìng wēn hé ， hěn shǎo guò mǐn ， fú yào qī jiān bié chī shēng lěng xīn là shí wù ma 。','Thuốc này tính ôn hòa, ít khi gây dị ứng, trong thời gian uống thuốc thì đừng ăn đồ sống lạnh cay nóng nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_07','V1225','阮明',7,'好，麻烦给我一盒，请问一次吃几粒呢？','hǎo ， má fán gěi wǒ yī hé ， qǐng wèn yī cì chī jǐ lì ne ？','Vâng, phiền anh lấy cho tôi một hộp, cho tôi hỏi mỗi lần uống mấy viên ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1225_08','V1225','陈药师',8,'盒子上面有详细说明书，看不懂随时回来问我就行咯。','hé zi shàng miàn yǒu xiáng xì shuō míng shū ， kàn bù dǒng suí shí huí lái wèn wǒ jiù xíng gē 。','Trên hộp có hướng dẫn sử dụng chi tiết, không hiểu thì cứ quay lại hỏi tôi là được.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1226','SDL1','共享单车骑行游览古城，停车超出运营区被扣车',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1226','SIT1226','P1','that_bai_nhe','ban_chinh_thuc',NULL,'城市共享单车划定专属停车运营区，越区停车会收取高额调度费，路边白色/蓝色框才合规停车点。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1226_01','V1226','阮明',1,'你好，我的共享单车被锁在城外，提示超出运营区域怎么办？','nǐ hǎo ， wǒ de gòng xiǎng dān chē bèi suǒ zài chéng wài ， tí shì chāo chū yùn yíng qū yù zěn me bàn ？','Chào chị, xe đạp chia sẻ của tôi bị khóa ở ngoài thành, báo là vượt quá khu vực hoạt động, giờ phải làm sao ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1226_02','V1226','接线员',2,'您好先生，车辆驶出古城运营区会自动上锁，需要支付二十元调度费。','nín hǎo xiān shēng ， chē liàng shǐ chū gǔ chéng yùn yíng qū huì zì dòng shàng suǒ ， xū yào zhī fù èr shí yuán diào dù fèi 。','Chào anh, xe đi ra khỏi khu vực hoạt động của phố cổ sẽ tự động khóa lại, anh cần thanh toán phí điều phối 20 tệ ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1226_03','V1226','阮明',3,'我不知道古城有停车范围，随便停路边就被扣车了呢。','wǒ bù zhī dào gǔ chéng yǒu tíng chē fàn wéi ， suí biàn tíng lù biān jiù bèi kòu chē le ne 。','Tôi không biết phố cổ có giới hạn khu vực đỗ xe, chỉ đỗ đại ở lề đường thôi mà bị khóa xe luôn.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1226_04','V1226','接线员',4,'古城出入口都有提示牌，超出区域必须支付调度费解锁车辆。','gǔ chéng chū rù kǒu dōu yǒu tí shì pái ， chāo chū qū yù bì xū zhī fù diào dù fèi jiě suǒ chē liàng 。','Ở các lối ra vào phố cổ đều có biển báo, vượt khu vực thì bắt buộc phải trả phí điều phối mới mở khóa được xe ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1226_05','V1226','阮明',5,'支付完费用之后，我还能继续骑行回市区吗？','zhī fù wán fèi yòng zhī hòu ， wǒ hái néng jì xù qí xíng huí shì qū ma ？','Sau khi thanh toán xong phí, tôi có thể tiếp tục đạp xe về trung tâm thành phố không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1226_06','V1226','接线员',6,'缴费解锁后可以正常骑行，记得停在蓝色停车框内哦。','jiǎo fèi jiě suǒ hòu kě yǐ zhèng cháng qí xíng ， jì de tíng zài lán sè tíng chē kuāng nèi ó 。','Sau khi nộp phí mở khóa thì anh đạp bình thường được, nhớ đỗ trong khung màu xanh nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1226_07','V1226','阮明',7,'好吧，我马上缴费，下次一定看清停车范围再停放。','hǎo ba ， wǒ mǎ shàng jiǎo fèi ， xià cì yí dìng kàn qīng tíng chē fàn wéi zài tíng fàng 。','Vâng, tôi thanh toán ngay đây, lần sau nhất định sẽ xem kỹ khu vực đỗ xe rồi mới đỗ.','AM07') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1227','SDL1','景区停车场找不到自己停放的车辆，求助管理员',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1227','SIT1227','P1','suon_se','tuy_y',NULL,'大型景区停车场分A/B/C区域，分区标识偏小，找不到车可直接找管理员协助查找。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1227_01','V1227','阮明',1,'周叔，我找不到租的电动车了，停车场太大分不清区域呢。','zhōu shū ， wǒ zhǎo bú dào zū de diàn dòng chē le ， tíng chē chǎng tài dà fēn bù qīng qū yù ne 。','Chú Chu ơi, cháu tìm không ra xe điện thuê rồi, bãi đỗ xe rộng quá không phân biệt được khu vực.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1227_02','V1227','周叔',2,'你大概几点停进来的，车身是什么颜色呀？','nǐ dà gài jǐ diǎn tíng jìn lái de ， chē shēn shì shén me yán sè ya ？','Cháu đỗ vào khoảng mấy giờ, xe màu gì vậy?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1227_03','V1227','阮明',3,'半小时前停的，白色小电驴，车把挂着蓝色布袋。','bàn xiǎo shí qián tíng de ， bái sè xiǎo diàn lǘ ， chē bǎ guà zhe lán sè bù dài 。','Cháu đỗ nửa tiếng trước, xe điện nhỏ màu trắng, tay lái có treo túi vải màu xanh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1227_04','V1227','周叔',4,'那是B区停放区，跟着我走，这片都是白色电动车咯。','nà shì B qū tíng fàng qū ， gēn zhe wǒ zǒu ， zhè piàn dōu shì bái sè diàn dòng chē gē 。','Đó là khu đỗ xe B, đi theo chú, khu này toàn xe điện màu trắng.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1227_05','V1227','阮明',5,'太感谢您了，我绕三圈都没找到分区指示牌。','tài gǎn xiè nín le ， wǒ rào sān quān dōu méi zhǎo dào fēn qū zhǐ shì pái 。','Cảm ơn chú nhiều lắm, cháu đi vòng ba lần rồi mà vẫn không tìm thấy biển chỉ dẫn khu vực.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1227_06','V1227','周叔',6,'停车场分区牌子有点小，游客经常迷路，不用客气哈。','tíng chē chǎng fēn qū pái zi yǒu diǎn xiǎo ， yóu kè jīng cháng mí lù ， bù yòng kè qì hā 。','Biển chia khu ở bãi đỗ hơi nhỏ, khách du lịch hay bị lạc lắm, không cần khách sáo đâu.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1227_07','V1227','阮明',7,'还好有您带路，不然我要耽误下午的行程啦。','hái hǎo yǒu nín dài lù ， bù rán wǒ yào dān wù xià wǔ de xíng chéng la 。','May mà có chú dẫn đường, không thì cháu lỡ mất lịch trình buổi chiều rồi.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1228','SDL1','本地茶馆体验喝茶，不懂点茶流程询问茶艺师',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1228','SIT1228','P1','suon_se','ban_chinh_thuc',NULL,'中式茶馆讲究先选茶、温杯、洗茶再饮用，洗茶第一遍茶水不喝，直接倒掉。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1228_01','V1228','阮明',1,'小姐姐，我第一次来中式茶馆，点茶有什么讲究吗？','xiǎo jiě jiě ， wǒ dì yī cì lái zhōng shì chá guǎn ， diǎn chá yǒu shén me jiǎng jiū ma ？','Chị ơi, đây là lần đầu em đến trà quán kiểu Trung, gọi trà có gì cần lưu ý không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1228_02','V1228','小雯',2,'咱们可以先选茶叶，绿茶、红茶、乌龙茶口感差别很大呢。','zán men kě yǐ xiān xuǎn chá yè ， lǜ chá 、 hóng chá 、 wū lóng chá kǒu gǎn chā bié hěn dà ne 。','Mình có thể chọn loại trà trước, trà xanh, hồng trà, trà ô long hương vị khác nhau nhiều lắm đấy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1228_03','V1228','阮明',3,'乌龙茶味道清淡吗，适合新手喝吗？','wū lóng chá wèi dào qīng dàn ma ， shì hé xīn shǒu hē ma ？','Trà ô long vị có nhạt không, có hợp với người mới uống không chị?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1228_04','V1228','小雯',4,'乌龙茶香气足，不苦涩，很适合外国游客尝试嘛。','wū lóng chá xiāng qì zú ， bù kǔ sè ， hěn shì hé wài guó yóu kè cháng shì ma 。','Trà ô long thơm đậm, không đắng chát, rất hợp để khách du lịch nước ngoài thử đấy.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1228_05','V1228','阮明',5,'那就点一壶乌龙，整套泡茶流程可以教我看看吗？','nà jiù diǎn yī hú wū lóng ， zhěng tào pào chá liú chéng kě yǐ jiāo wǒ kàn kàn ma ？','Vậy thì gọi một ấm ô long, chị có thể dạy em cả quy trình pha trà được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1228_06','V1228','小雯',6,'当然可以，我泡茶的时候慢慢给你讲解每一步操作咯。','dāng rán kě yǐ ， wǒ pào chá de shí hòu màn màn gěi nǐ jiǎng jiě měi yī bù cāo zuò gē 。','Được chứ, lúc pha trà chị sẽ từ từ giải thích cho em từng bước một.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1228_07','V1228','阮明',7,'太期待啦，一直想体验正宗中式茶文化。','tài qī dài la ， yì zhí xiǎng tǐ yàn zhèng zōng zhōng shì chá wén huà 。','Em mong quá, em cứ muốn trải nghiệm văn hóa trà Trung Hoa chính gốc mãi.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1229','SDL1','线上订景区门票，证件姓名拼音和护照不一致无法核销',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1229','SIT1229','P1','twist','chinh_thuc',NULL,'国内景区外籍实名票务要求拼音与护照完全一致，字母大小写、拼写错误均无法检票入园。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_01','V1229','阮明',1,'您好，我线上预约门票检票失败，系统提示姓名不符呢。','nín hǎo ， wǒ xiàn shàng yù yuē mén piào jiǎn piào shī bài ， xì tǒng tí shì xìng míng bù fú ne 。','Chào chị, tôi đặt vé trực tuyến nhưng quét vé không được, hệ thống báo tên không khớp ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_02','V1229','工作人员',2,'我核对一下，你购票填写的拼音和护照拼音差一个字母。','wǒ hé duì yī xià ， nǐ gòu piào tián xiě de pīn yīn hé hù zhào pīn yīn chà yí gè zì mǔ 。','Để tôi kiểm tra lại, phiên âm pinyin anh điền lúc mua vé sai lệch một chữ cái so với hộ chiếu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_03','V1229','阮明',3,'我输入的时候不小心打错字母，没想到会无法入园啊。','wǒ shū rù de shí hòu bù xiǎo xīn dǎ cuò zì mǔ ， méi xiǎng dào huì wú fǎ rù yuán a 。','Lúc nhập tôi lỡ gõ nhầm một chữ, không ngờ lại không vào được cổng ạ.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_04','V1229','工作人员',4,'外籍游客门票实名严格匹配护照拼音，错一个字都不能核销。','wài jí yóu kè mén piào shí míng yán gé pǐ pèi hù zhào pīn yīn ， cuò yí gè zì dōu bù néng hé xiāo 。','Vé của khách nước ngoài phải khớp chính xác tuyệt đối với phiên âm hộ chiếu, sai một chữ cũng không xác nhận được ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_05','V1229','阮明',5,'那现在能现场修改订单信息，重新核销入园吗？','nà xiàn zài néng xiàn chǎng xiū gǎi dìng dān xìn xī ， chóng xīn hé xiāo rù yuán ma ？','Vậy bây giờ có thể sửa lại thông tin đơn hàng tại chỗ rồi xác nhận vào cổng lại được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_06','V1229','工作人员',6,'可以，出示护照原件，我后台帮你修改订单拼音信息。','kě yǐ ， chū shì hù zhào yuán jiàn ， wǒ hòu tái bāng nǐ xiū gǎi dìng dān pīn yīn xìn xī 。','Được, anh cho tôi xem hộ chiếu gốc, tôi sẽ sửa lại thông tin phiên âm trong hệ thống giúp anh.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_07','V1229','阮明',7,'辛苦您帮忙操作，下次订票我一定仔细核对护照拼音。','xīn kǔ nín bāng máng cāo zuò ， xià cì dìng piào wǒ yí dìng zǐ xì hé duì hù zhào pīn yīn 。','Cảm ơn chị đã giúp đỡ, lần sau đặt vé tôi nhất định sẽ kiểm tra kỹ phiên âm hộ chiếu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1229_08','V1229','工作人员',8,'没关系，很多外国游客都会输错拼音，修改很快的哈。','méi guān xì ， hěn duō wài guó yóu kè dōu huì shū cuò pīn yīn ， xiū gǎi hěn kuài de hā 。','Không sao đâu, nhiều khách nước ngoài cũng hay gõ nhầm phiên âm lắm, sửa nhanh thôi ạ.','AM06') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1230','SDL1','长途旅游大巴中途服务区休息，错过发车时间',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1230','SIT1230','P1','that_bai_nhe','ban_chinh_thuc',NULL,'长途旅游大巴服务区休息有固定时限，超时直接发车，不会原地等候迟到游客。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_01','V1230','阮明',1,'导游！大巴车是不是开走了，我去洗手间回来车不见了？','dǎo yóu ！ dà bā chē shì bú shì kāi zǒu le ， wǒ qù xǐ shǒu jiān huí lái chē bú jiàn le ？','Hướng dẫn viên ơi! Xe buýt chạy mất rồi phải không, em đi vệ sinh xong quay lại không thấy xe đâu cả?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_02','V1230','阿凯',2,'全车游客十分钟前就准时发车，我在车上清点人数少了你。','quán chē yóu kè shí fēn zhōng qián jiù zhǔn shí fā chē ， wǒ zài chē shàng qīng diǎn rén shù shǎo le nǐ 。','Cả xe khách đã khởi hành đúng giờ từ mười phút trước rồi, tôi kiểm đếm trên xe thấy thiếu mỗi bạn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_03','V1230','阮明',3,'服务区太大，我走错洗手间，回来晚了几分钟而已。','fú wù qū tài dà ， wǒ zǒu cuò xǐ shǒu jiān ， huí lái wǎn le jǐ fēn zhōng ér yǐ 。','Trạm dừng chân rộng quá, em đi nhầm nhà vệ sinh, chỉ về trễ có mấy phút thôi mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_04','V1230','阿凯',4,'大巴有固定休息时长，不能全车人等单独一位游客哦。','dà bā yǒu gù dìng xiū xī shí cháng ， bù néng quán chē rén děng dān dú yī wèi yóu kè ó 。','Xe buýt có thời gian nghỉ cố định, không thể để cả xe chờ một mình bạn được đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_05','V1230','阮明',5,'那我现在怎么前往下一个景点，车费能退一部分吗？','nà wǒ xiàn zài zěn me qián wǎng xià yí gè jǐng diǎn ， chē fèi néng tuì yī bù fèn ma ？','Vậy bây giờ em đi tới điểm tham quan tiếp theo bằng cách nào, tiền vé có được hoàn lại một phần không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_06','V1230','阿凯',6,'车费包含全程交通，无法退款，我帮你联系下一班顺路大巴。','chē fèi bāo hán quán chéng jiāo tōng ， wú fǎ tuì kuǎn ， wǒ bāng nǐ lián xì xià yī bān shùn lù dà bā 。','Tiền vé đã bao gồm cả hành trình rồi, không hoàn lại được đâu, để tôi liên hệ chuyến xe buýt tiện đường tiếp theo giúp bạn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_07','V1230','阮明',7,'麻烦您帮忙协调，实在不好意思耽误大家行程啦。','má fán nín bāng máng xié tiáo ， shí zài bù hǎo yì sī dān wù dà jiā xíng chéng la 。','Phiền anh sắp xếp giúp em, thật sự xin lỗi vì đã làm chậm trễ hành trình của mọi người.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1230_08','V1230','阿凯',8,'下次休息记得定好闹钟，准时回到大巴集合点哈。','xià cì xiū xī jì de dìng hǎo nào zhōng ， zhǔn shí huí dào dà bā jí hé diǎn hā 。','Lần sau nghỉ nhớ đặt báo thức, quay lại điểm tập trung xe buýt đúng giờ nhé.','AM06') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1301','SHTN1','咨询校内留学生全额奖学金申请材料与截止时间',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1301','SIT1301','P1','suon_se','ban_chinh_thuc',NULL,'国内高校留学生奖学金区分学业、科研两类，科研竞赛成果是重要加分项，逾期一律关闭申报通道不接受补交。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1301_01','V1301','阮明',1,'张老师您好，我想来问问全额留学生奖学金的申请要求啊。','zhāng lǎo shī nín hǎo ， wǒ xiǎng lái wèn wèn quán é liú xué shēng jiǎng xué jīn de shēn qǐng yāo qiú a 。','Chào thầy Trương, em muốn hỏi về yêu cầu xin học bổng toàn phần dành cho lưu học sinh ạ.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1301_02','V1301','张老师',2,'坐吧，今年申请截止下周五下午五点，材料可得提前备齐呢。','zuò ba ， jīn nián shēn qǐng jié zhǐ xià zhōu wǔ xià wǔ wǔ diǎn ， cái liào kě dé tí qián bèi qí ne 。','Ngồi đi, năm nay hạn nộp hồ sơ là 5 giờ chiều thứ Sáu tuần sau, hồ sơ phải chuẩn bị đầy đủ trước đấy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1301_03','V1301','阮明',3,'除了成绩单和护照，还需要额外提交科研证明吗？','chú le chéng jì dān hé hù zhào ， hái xū yào é wài tí jiāo kē yán zhèng míng ma ？','Ngoài bảng điểm và hộ chiếu ra, có cần nộp thêm giấy chứng nhận nghiên cứu khoa học không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1301_04','V1301','张老师',4,'有论文、竞赛获奖材料都可以附上，能加分不少嘛。','yǒu lùn wén 、 jìng sài huò jiǎng cái liào dōu kě yǐ fù shàng ， néng jiā fēn bù shǎo ma 。','Nếu có bài báo khoa học hay giấy khen thi đấu thì đều đính kèm được, sẽ cộng điểm kha khá đấy.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1301_05','V1301','阮明',5,'纸质材料是线下交到您办公室，还是直接线上上传系统？','zhǐ zhì cái liào shì xiàn xià jiāo dào nín bàn gōng shì ， hái shì zhí jiē xiàn shàng shàng chuán xì tǒng ？','Hồ sơ giấy thì nộp trực tiếp tại văn phòng thầy hay là tải trực tuyến lên hệ thống luôn ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1301_06','V1301','张老师',6,'先线上填报，再打印签字送过来，缺一份都不能初审通过哦。','xiān xiàn shàng tián bào ， zài dǎ yìn qiān zì sòng guò lái ， quē yī fèn dōu bù néng chū shěn tōng guò ó 。','Điền trực tuyến trước, rồi in ra ký tên mang đến, thiếu một bản cũng không qua được vòng sơ duyệt đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1301_07','V1301','阮明',7,'好嘞，我记好时间，这周就把所有材料整理完整。','hǎo lei ， wǒ jì hǎo shí jiān ， zhè zhōu jiù bǎ suǒ yǒu cái liào zhěng lǐ wán zhěng 。','Vâng ạ, em ghi nhớ thời gian rồi, tuần này em sẽ chuẩn bị đầy đủ hết hồ sơ.','AM08') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1302','SHTN1','撰写硕士保研申请文书，找专业课李教授修改个人陈述',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1302','SIT1302','P1','suon_se','ban_chinh_thuc',NULL,'国内硕博申请个人陈述重点突出科研规划，拜访导师修改文书属于学生常见礼貌求助，事后简单致谢更得体。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1302_01','V1302','阮明',1,'李教授，打扰您啦，这是我的保研个人陈述，想请您帮忙看看。','lǐ jiào shòu ， dǎ rǎo nín la ， zhè shì wǒ de bǎo yán gè rén chén shù ， xiǎng qǐng nín bāng máng kàn kàn 。','Thưa giáo sư Lý, làm phiền thầy chút ạ, đây là bài trình bày cá nhân xin bảo lưu học thẳng lên thạc sĩ của em, em muốn nhờ thầy xem giúp.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1302_02','V1302','李教授',2,'我简单翻一下，整体科研经历写得还算清晰，有两处逻辑可以调整。','wǒ jiǎn dān fān yī xià ， zhěng tǐ kē yán jīng lì xiě dé hái suàn qīng xī ， yǒu liǎng chù luó jí kě yǐ tiáo zhěng 。','Để thầy xem qua nhé, phần kinh nghiệm nghiên cứu nhìn chung viết khá rõ ràng, có hai chỗ về logic có thể điều chỉnh lại.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1302_03','V1302','阮明',3,'是不是我写实验成果那段太笼统，看不出研究价值呢？','shì bú shì wǒ xiě shí yàn chéng guǒ nà duàn tài lǒng tǒng ， kàn bù chū yán jiū jià zhí ne ？','Có phải đoạn em viết về kết quả thí nghiệm quá chung chung, không thấy rõ giá trị nghiên cứu không ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1302_04','V1302','李教授',4,'没错，补充一组实验数据会更有说服力，我给你标出来吧。','méi cuò ， bǔ chōng yī zǔ shí yàn shù jù huì gèng yǒu shuō fú lì ， wǒ gěi nǐ biāo chū lái ba 。','Đúng vậy, bổ sung thêm một bộ số liệu thí nghiệm sẽ thuyết phục hơn, để thầy đánh dấu ra cho em.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1302_05','V1302','阮明',5,'太感谢您了，留学生申请国内硕士，文书是不是特别看重科研规划？','tài gǎn xiè nín le ， liú xué shēng shēn qǐng guó nèi shuò shì ， wén shū shì bú shì tè bié kàn zhòng kē yán guī huà ？','Em cảm ơn thầy nhiều ạ, lưu học sinh xin học thạc sĩ trong nước thì hồ sơ có đặc biệt coi trọng kế hoạch nghiên cứu không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1302_06','V1302','李教授',6,'对，导师更在意你未来的研究方向，别只堆砌奖项就行啦。','duì ， dǎo shī gèng zài yì nǐ wèi lái de yán jiū fāng xiàng ， bié zhǐ duī qì jiǎng xiàng jiù xíng la 。','Đúng vậy, giáo viên hướng dẫn quan tâm hơn đến hướng nghiên cứu tương lai của em, đừng chỉ liệt kê giải thưởng là được.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1302_07','V1302','阮明',7,'我今晚按照您的批注修改，明天再来给您过目行吗？','wǒ jīn wǎn àn zhào nín de pī zhù xiū gǎi ， míng tiān zài lái gěi nín guò mù xíng ma ？','Tối nay em sẽ sửa theo góp ý của thầy, mai em mang lại cho thầy xem lại được không ạ?',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1303','SHTN1','邮件联系校外博导申请科研实习，对方迟迟未回复，找辅导员请教补救方法',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1303','SIT1303','P1','twist','ban_chinh_thuc',NULL,'国内高校教授日常邮件量大，联系导师邮件标题必须标注姓名、院校、事由，短时间重复发送邮件会被视作失礼。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1303_01','V1303','阮明',1,'杨辅导员，我上周给校外博导发实习申请邮件，到现在都没回信呢。','yáng fǔ dǎo yuán ， wǒ shàng zhōu gěi xiào wài bó dǎo fā shí xí shēn qǐng yóu jiàn ， dào xiàn zài dōu méi huí xìn ne 。','Chị Dương ơi, tuần trước em gửi email xin thực tập nghiên cứu cho thầy hướng dẫn bên ngoài trường, mà đến giờ vẫn chưa thấy trả lời ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1303_02','V1303','小杨',2,'别着急，很多教授邮件太多容易遗漏，先看看你的邮件标题规范不？','bié zháo jí ， hěn duō jiào shòu yóu jiàn tài duō róng yì yí lòu ， xiān kàn kàn nǐ de yóu jiàn biāo tí guī fàn bù ？','Đừng lo, nhiều giáo sư nhận email nhiều quá nên dễ bị sót lắm, em xem lại tiêu đề email đã đúng chuẩn chưa?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1303_03','V1303','阮明',3,'标题只写了"实习申请"，没有标注我的学校和专业，是不是太简单啦？','biāo tí zhǐ xiě le " shí xí shēn qǐng "， méi yǒu biāo zhù wǒ de xué xiào hé zhuān yè ， shì bú shì tài jiǎn dān la ？','Tiêu đề em chỉ ghi "Đơn xin thực tập" thôi, không ghi trường và chuyên ngành của em, vậy có phải là quá sơ sài không ạ?','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1303_04','V1303','小杨',4,'国内教授习惯清晰标题，建议重发一封，开头简单自我介绍一下。','guó nèi jiào shòu xí guàn qīng xī biāo tí ， jiàn yì zhòng fā yī fēng ， kāi tóu jiǎn dān zì wǒ jiè shào yī xià 。','Giáo sư trong nước thường quen với tiêu đề rõ ràng, em nên gửi lại một email khác, mở đầu giới thiệu bản thân ngắn gọn nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1303_05','V1303','阮明',5,'那间隔多久重发比较合适，会不会显得打扰人家呀？','nà jiàn gé duō jiǔ zhòng fā bǐ jiào hé shì ， huì bú huì xiǎn de dǎ rǎo rén jiā ya ？','Vậy cách bao lâu thì gửi lại là hợp lý ạ, có sợ làm phiền người ta không?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1303_06','V1303','小杨',6,'间隔七天最合适，措辞客气简洁，不要长篇大论嘛。','jiàn gé qī tiān zuì hé shì ， cuò cí kè qì jiǎn jié ， bú yào cháng piān dà lùn ma 。','Cách bảy ngày là hợp lý nhất, lời lẽ lịch sự ngắn gọn thôi, đừng viết dài dòng nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1303_07','V1303','阮明',7,'好，我重新整理邮件内容，今天傍晚重新发送试试看。','hǎo ， wǒ chóng xīn zhěng lǐ yóu jiàn nèi róng ， jīn tiān bàng wǎn chóng xīn fā sòng shì shì kàn 。','Vâng, em sẽ chỉnh lại nội dung email, chiều nay gửi lại thử xem sao ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1304','SHTN1','投递国际学术会议摘要，英文摘要翻译存在专业术语错误，被会务退回修改',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1304','SIT1304','P1','twist','chinh_thuc',NULL,'国内学术会议对专业术语有统一国标表述，留学生直译外文词汇极易出现错误，投稿前最好请国内同学校对。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1304_01','V1304','阮明',1,'您好，会务这边通知我的摘要初审驳回了，想知道具体哪里出错啦？','nín hǎo ， huì wù zhè biān tōng zhī wǒ de zhāi yào chū shěn bó huí le ， xiǎng zhī dào jù tǐ nǎ lǐ chū cuò la ？','Xin chào, bên ban tổ chức thông báo bài tóm tắt của em bị trả lại ở vòng sơ duyệt, em muốn biết cụ thể là sai ở đâu ạ?','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1304_02','V1304','小徐',2,'系统标注三处专业术语翻译偏差，和行业通用表述不一致呢。','xì tǒng biāo zhù sān chù zhuān yè shù yǔ fān yì piān chā ， hé háng yè tōng yòng biǎo shù bù yī zhì ne 。','Hệ thống đánh dấu ba chỗ dịch thuật ngữ chuyên ngành bị lệch, không khớp với cách dùng phổ biến trong ngành ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1304_03','V1304','阮明',3,'原来是我自行直译词汇，没有对照国内标准术语库对吧？','yuán lái shì wǒ zì xíng zhí yì cí huì ， méi yǒu duì zhào guó nèi biāo zhǔn shù yǔ kù duì ba ？','Thì ra là do em tự dịch trực tiếp, không đối chiếu với kho thuật ngữ chuẩn trong nước phải không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1304_04','V1304','小徐',4,'国际会议接收中文、英文稿件，专业名词一定要统一规范哦。','guó jì huì yì jiē shōu zhōng wén 、 yīng wén gǎo jiàn ， zhuān yè míng cí yí dìng yào tǒng yī guī fàn ó 。','Hội nghị quốc tế nhận cả bản thảo tiếng Trung lẫn tiếng Anh, thuật ngữ chuyên ngành nhất định phải thống nhất và chuẩn xác ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1304_05','V1304','阮明',5,'距离修改截止还有三天，我找实验室师兄帮忙校对来得及吗？','jù lí xiū gǎi jié zhǐ hái yǒu sān tiān ， wǒ zhǎo shí yàn shì shī xiōng bāng máng jiào duì lái de jí ma ？','Còn ba ngày nữa là hết hạn sửa, em nhờ anh khóa trên trong phòng thí nghiệm giúp hiệu đính thì có kịp không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1304_06','V1304','小徐',6,'完全来得及，修改完成重新上传，记得保存修改记录备查哈。','wán quán lái de jí ， xiū gǎi wán chéng chóng xīn shàng chuán ， jì de bǎo cún xiū gǎi jì lù bèi chá hā 。','Hoàn toàn kịp, sửa xong tải lên lại là được, nhớ lưu lại bản ghi chỉnh sửa để đối chiếu sau này nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1304_07','V1304','阮明',7,'太谢谢您提醒，不然我直接错过本次会议投稿机会咯。','tài xiè xiè nín tí xǐng ， bù rán wǒ zhí jiē cuò guò běn cì huì yì tóu gǎo jī huì gē 。','Em cảm ơn chị rất nhiều vì đã nhắc, không thì em đã bỏ lỡ cơ hội gửi bài lần này rồi.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1305','SHTN1','组队参加全国留学生创新竞赛，队内分工产生分歧找指导老师调解',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1305','SIT1305','P1','suon_se','ban_chinh_thuc',NULL,'国内学科竞赛看重团队协作均衡分工，只争抢展示环节、回避基础工作会被评委扣分，指导老师常介入协调团队矛盾。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1305_01','V1305','阮明',1,'王老师，我们小组做竞赛项目，大家对分工意见不太统一，想请您协调下。','wáng lǎo shī ， wǒ men xiǎo zǔ zuò jìng sài xiàng mù ， dà jiā duì fēn gōng yì jiàn bù tài tǒng yī ， xiǎng qǐng nín xié tiáo xià 。','Thầy Vương, nhóm em làm dự án thi đấu mà mọi người bất đồng ý kiến về phân công, em muốn nhờ thầy điều phối giúp ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1305_02','V1305','王老师',2,'先说说分歧在哪，是实验部分还是申报材料撰写这块呀？','xiān shuō shuō fēn qí zài nǎ ， shì shí yàn bù fèn hái shì shēn bào cái liào zhuàn xiě zhè kuài ya ？','Em nói xem bất đồng ở chỗ nào, là phần thí nghiệm hay phần viết hồ sơ đăng ký vậy?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1305_03','V1305','阮明',3,'两位国内同学都想做答辩汇报，没人愿意整理调研数据呢。','liǎng wèi guó nèi tóng xué dōu xiǎng zuò dá biàn huì bào ， méi rén yuàn yì zhěng lǐ diào yán shù jù ne 。','Hai bạn trong nước đều muốn làm phần thuyết trình bảo vệ, không ai chịu tổng hợp số liệu khảo sát cả ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1305_04','V1305','王老师',4,'答辩只有一人上台，数据整理是基础工作，咱们重新分配任务吧。','dá biàn zhǐ yǒu yī rén shàng tái ， shù jù zhěng lǐ shì jī chǔ gōng zuò ， zán men chóng xīn fēn pèi rèn wù ba 。','Bảo vệ thì chỉ có một người lên thuyết trình thôi, tổng hợp số liệu là công việc nền tảng, để thầy phân công lại nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1305_05','V1305','阮明',5,'我可以负责外文文献翻译，数据整理交给其中一位同学行不行？','wǒ kě yǐ fù zé wài wén wén xiàn fān yì ， shù jù zhěng lǐ jiāo gěi qí zhōng yī wèi tóng xué xíng bù xíng ？','Em có thể phụ trách dịch tài liệu nước ngoài, còn phần tổng hợp số liệu giao cho một bạn khác được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1305_06','V1305','王老师',6,'这个分配很合理，大家优势互补，今晚开会统一一下分工哈。','zhè ge fēn pèi hěn hé lǐ ， dà jiā yōu shì hù bǔ ， jīn wǎn kāi huì tǒng yī yī xià fēn gōng hā 。','Phân công vậy hợp lý đấy, mọi người bổ sung thế mạnh cho nhau, tối nay họp thống nhất lại phân công nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1305_07','V1305','阮明',7,'太好了，有您帮忙调解，团队就能专心推进项目啦。','tài hǎo le ， yǒu nín bāng máng tiáo jiě ， tuán duì jiù néng zhuān xīn tuī jìn xiàng mù la 。','Tuyệt quá ạ, có thầy giúp điều phối thì cả nhóm có thể tập trung đẩy nhanh dự án rồi.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1306','SHTN1','准备研究生复试面试，向同专业往届越南留学生请教面试流程与问答要点',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1306','SIT1306','P1','suon_se','tuy_y',NULL,'国内研究生复试注重礼貌礼仪，外籍考生语言表达存在短板时主动说明，面试官会适当降低语言要求，重点考察科研思维。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1306_01','V1306','阮明',1,'清哥，你去年硕士复试难不难呀，老师一般会问什么问题呢？','qīng gē ， nǐ qù nián shuò shì fù shì nán bù nán ya ， lǎo shī yì bān huì wèn shén me wèn tí ne ？','Anh Thanh ơi, năm ngoái anh phỏng vấn phúc khảo thạc sĩ có khó không, thầy cô thường hỏi gì vậy?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1306_02','V1306','阮清',2,'不会刻意为难留学生，大多围绕你的本科实验、未来研究计划提问嘛。','bú huì kè yì wéi nán liú xué shēng ， dà duō wéi rào nǐ de běn kē shí yàn 、 wèi lái yán jiū jì huà tí wèn ma 。','Không cố tình làm khó lưu học sinh đâu, chủ yếu xoay quanh thí nghiệm hồi đại học và kế hoạch nghiên cứu tương lai của mình thôi.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1306_03','V1306','阮明',3,'我普通话不算特别流利，面试可以适当使用英文回答专业问题吗？','wǒ pǔ tōng huà bù suàn tè bié liú lì ， miàn shì kě yǐ shì dàng shǐ yòng yīng wén huí dá zhuān yè wèn tí ma ？','Tiếng phổ thông của em nói chưa lưu loát lắm, phỏng vấn có được trả lời câu hỏi chuyên môn bằng tiếng Anh không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1306_04','V1306','阮清',4,'完全可以，遇到表达困难直接跟老师说明，老师们都能理解的。','wán quán kě yǐ ， yù dào biǎo dá kùn nán zhí jiē gēn lǎo shī shuō míng ， lǎo shī men dōu néng lǐ jiě de 。','Được chứ, gặp lúc diễn đạt khó khăn thì cứ nói thẳng với thầy cô, thầy cô đều hiểu mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1306_05','V1306','阮明',5,'复试有没有需要格外注意的礼仪，比如进门、离场这些细节？','fù shì yǒu méi yǒu xū yào gé wài zhù yì de lǐ yí ， bǐ rú jìn mén 、 lí chǎng zhè xiē xì jié ？','Phỏng vấn có cần chú ý lễ nghi gì đặc biệt không, kiểu như lúc vào phòng, lúc ra về ấy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1306_06','V1306','阮清',6,'进门先鞠躬问好，结束致谢再离场，简单大方就没问题啦。','jìn mén xiān jū gōng wèn hǎo ， jié shù zhì xiè zài lí chǎng ， jiǎn dān dà fāng jiù méi wèn tí la 。','Vào phòng thì cúi chào trước, kết thúc thì cảm ơn rồi ra về, đơn giản tự nhiên là không sao đâu.','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1306_07','V1306','阮明',7,'太感谢你分享经验，我这下心里踏实多咯。','tài gǎn xiè nǐ fēn xiǎng jīng yàn ， wǒ zhè xià xīn lǐ tà shí duō gē 。','Cảm ơn anh nhiều đã chia sẻ kinh nghiệm, giờ em thấy yên tâm hơn hẳn luôn.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1307','SHTN1','学术期刊投稿初审被拒，咨询期刊编辑拒稿原因、返修方向',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1307','SIT1307','P1','twist','chinh_thuc',NULL,'国内核心期刊初审拒稿后不支持即时返修，需补充完整实验数据、间隔周期重新投稿，一稿多投属于学术不端行为。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1307_01','V1307','阮明',1,'陈编辑您好，我的稿件初审被退回，想详细了解拒稿的核心原因。','chén biān jí nín hǎo ， wǒ de gǎo jiàn chū shěn bèi tuì huí ， xiǎng xiáng xì liǎo jiě jù gǎo de hé xīn yuán yīn 。','Chào biên tập viên Trần, bài của em bị trả lại ở vòng sơ duyệt, em muốn tìm hiểu kỹ lý do chính bị từ chối ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1307_02','V1307','陈编辑',2,'你的实验样本量偏少，论证支撑不足，达不到本刊收录标准呢。','nǐ de shí yàn yàng běn liàng piān shǎo ， lùn zhèng zhī chēng bù zú ， dá bú dào běn kān shōu lù biāo zhǔn ne 。','Mẫu thí nghiệm của em hơi ít, luận cứ chưa đủ thuyết phục, chưa đạt tiêu chuẩn đăng bài của tạp chí ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1307_03','V1307','阮明',3,'那我补充一组对照实验数据后，还能重新投稿这本期刊吗？','nà wǒ bǔ chōng yī zǔ duì zhào shí yàn shù jù hòu ， hái néng chóng xīn tóu gǎo zhè běn qī kān ma ？','Vậy nếu em bổ sung thêm một bộ số liệu thí nghiệm đối chứng, thì có thể gửi lại bài cho tạp chí này không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1307_04','V1307','陈编辑',4,'可以返修重投，但需要间隔一个投稿周期，不能立刻重复投递哦。','kě yǐ fǎn xiū zhòng tóu ， dàn xū yào jiàn gé yí gè tóu gǎo zhōu qī ， bù néng lì kè chóng fù tóu dì ó 。','Có thể sửa và gửi lại, nhưng cần cách một chu kỳ nộp bài, không được nộp lại ngay lập tức ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1307_05','V1307','阮明',5,'参考文献格式我也按照模板调整，会不会增加录用概率呢？','cān kǎo wén xiàn gé shì wǒ yě àn zhào mú bǎn tiáo zhěng ， huì bú huì zēng jiā lù yòng gài lǜ ne ？','Em cũng chỉnh định dạng tài liệu tham khảo theo đúng mẫu, như vậy có tăng khả năng được nhận không ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1307_06','V1307','陈编辑',6,'格式规范是基础，核心还是完善实验内容，你好好修改吧。','gé shì guī fàn shì jī chǔ ， hé xīn hái shì wán shàn shí yàn nèi róng ， nǐ hǎo hǎo xiū gǎi ba 。','Định dạng chuẩn chỉ là điều kiện cơ bản thôi, quan trọng nhất vẫn là hoàn thiện nội dung thí nghiệm, em cố gắng sửa lại nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1307_07','V1307','阮明',7,'明白啦，我重新完善实验内容，过段时间再投递过来。','míng bái la ， wǒ chóng xīn wán shàn shí yàn nèi róng ， guò duàn shí jiān zài tóu dì guò lái 。','Em hiểu rồi ạ, em sẽ hoàn thiện lại nội dung thí nghiệm, một thời gian nữa sẽ gửi lại bài.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1308','SHTN1','线下参加高校学术论坛，不会中文PPT汇报，求助会务志愿者调整设备',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1308','SIT1308','P1','twist','ban_chinh_thuc',NULL,'国内高校学术论坛鼓励外籍参会者使用英文PPT，会场一般配备翻译辅助设备，汇报时放慢语速是基本礼貌。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1308_01','V1308','阮明',1,'同学你好，我等下上台汇报，PPT只有英文，会场投影能切换中英字幕吗？','tóng xué nǐ hǎo ， wǒ děng xià shàng tái huì bào ，PPT zhǐ yǒu yīng wén ， huì chǎng tóu yǐng néng qiè huàn zhōng yīng zì mù ma ？','Chào bạn, lát nữa mình lên thuyết trình, PPT chỉ có tiếng Anh thôi, máy chiếu ở đây có chuyển được phụ đề tiếng Trung không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1308_02','V1308','小林',2,'会场设备自带字幕插件，我帮你调出中文翻译界面好不好？','huì chǎng shè bèi zì dài zì mù chā jiàn ， wǒ bāng nǐ diào chū zhōng wén fān yì jiè miàn hǎo bù hǎo ？','Thiết bị ở hội trường có sẵn plugin phụ đề, để mình bật giao diện dịch tiếng Trung giúp bạn nhé?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1308_03','V1308','阮明',3,'太好啦，我担心台下老师看不懂英文图表，听不懂我的讲解呢。','tài hǎo la ， wǒ dān xīn tái xià lǎo shī kàn bù dǒng yīng wén tú biǎo ， tīng bù dǒng wǒ de jiǎng jiě ne 。','Tuyệt quá, mình lo là thầy cô bên dưới không hiểu biểu đồ tiếng Anh, không nghe hiểu phần trình bày của mình.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1308_04','V1308','小林',4,'没关系，汇报时语速放慢一点，有听不懂的地方评委可以现场提问嘛。','méi guān xì ， huì bào shí yǔ sù fàng màn yì diǎn ， yǒu tīng bù dǒng de dì fāng píng wěi kě yǐ xiàn chǎng tí wèn ma 。','Không sao đâu, lúc trình bày bạn nói chậm lại một chút, chỗ nào không hiểu thì ban giám khảo có thể hỏi trực tiếp mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1308_05','V1308','阮明',5,'上台前还有五分钟调试时间，我现在能先试播一遍PPT吗？','shàng tái qián hái yǒu wǔ fēn zhōng tiáo shì shí jiān ， wǒ xiàn zài néng xiān shì bō yī biàn PPT ma ？','Trước khi lên còn năm phút để chỉnh máy, giờ mình có thể chạy thử PPT một lượt được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1308_06','V1308','小林',6,'可以，这边电脑你直接操作，有故障随时喊我就行咯。','kě yǐ ， zhè biān diàn nǎo nǐ zhí jiē cāo zuò ， yǒu gù zhàng suí shí hǎn wǒ jiù xíng gē 。','Được, máy tính bên này bạn cứ thao tác trực tiếp, có trục trặc gì thì gọi mình bất cứ lúc nào nhé.','AM11') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1308_07','V1308','阮明',7,'辛苦你帮忙调试，这下汇报不会手忙脚乱啦。','xīn kǔ nǐ bāng máng tiáo shì ， zhè xià huì bào bú huì shǒu máng jiǎo luàn la 。','Cảm ơn bạn đã giúp chỉnh máy, giờ thì mình trình bày sẽ không bị luống cuống nữa rồi.','AM02') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1309','SHTN1','申请实验室长期科研助研岗位，面试时不懂国内科研项目申报基础流程',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1309','SIT1309','P1','that_bai_nhe','chinh_thuc',NULL,'国内实验室助研岗除基础实验外，常需协助申报各类科研项目，有项目申报经验的学生会优先录用。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1309_01','V1309','阮明',1,'周老师您好，我特别希望留在实验室做长期助研，愿意配合所有科研工作。','zhōu lǎo shī nín hǎo ， wǒ tè bié xī wàng liú zài shí yàn shì zuò cháng qī zhù yán ， yuàn yì pèi hé suǒ yǒu kē yán gōng zuò 。','Chào thầy Chu, em rất mong được ở lại phòng thí nghiệm làm trợ lý nghiên cứu lâu dài, em sẵn sàng phối hợp mọi công việc nghiên cứu ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1309_02','V1309','周老师',2,'那简单问一下，你了解校内大学生创新项目的申报流程吗？','nà jiǎn dān wèn yī xià ， nǐ liǎo jiě xiào nèi dà xué shēng chuàng xīn xiàng mù dì shēn bào liú chéng ma ？','Vậy thầy hỏi đơn giản nhé, em có hiểu quy trình đăng ký dự án sáng tạo sinh viên trong trường không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1309_03','V1309','阮明',3,'抱歉老师，我之前只做基础实验，完全没接触项目申报这块呢。','bào qiàn lǎo shī ， wǒ zhī qián zhǐ zuò jī chǔ shí yàn ， wán quán méi jiē chù xiàng mù shēn bào zhè kuài ne 。','Em xin lỗi thầy, trước giờ em chỉ làm thí nghiệm cơ bản thôi, hoàn toàn chưa tiếp xúc với phần đăng ký dự án này ạ.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1309_04','V1309','周老师',4,'助研需要协助整理申报材料，不懂流程的话前期要花很多时间学习。','zhù yán xū yào xié zhù zhěng lǐ shēn bào cái liào ， bù dǒng liú chéng de huà qián qī yào huā hěn duō shí jiān xué xí 。','Trợ lý nghiên cứu cần hỗ trợ chuẩn bị hồ sơ đăng ký, nếu không hiểu quy trình thì giai đoạn đầu sẽ phải mất nhiều thời gian học hỏi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1309_05','V1309','阮明',5,'我可以快速自学申报规则，每周多花两小时熟悉流程行不行？','wǒ kě yǐ kuài sù zì xué shēn bào guī zé ， měi zhōu duō huā liǎng xiǎo shí shú xī liú chéng xíng bù xíng ？','Em có thể nhanh chóng tự học quy tắc đăng ký, mỗi tuần dành thêm hai tiếng để làm quen quy trình được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1309_06','V1309','周老师',6,'这次岗位名额有限，优先录取有申报经验的学生，你下次再来申请吧。','zhè cì gǎng wèi míng é yǒu xiàn ， yōu xiān lù qǔ yǒu shēn bào jīng yàn de xué shēng ， nǐ xià cì zài lái shēn qǐng ba 。','Lần này chỉ tiêu có hạn, thầy ưu tiên nhận sinh viên đã có kinh nghiệm đăng ký dự án, lần sau em quay lại nộp đơn nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1309_07','V1309','阮明',7,'好的老师，我先跟着师兄学习项目申报，明年再来投递岗位。','hǎo de lǎo shī ， wǒ xiān gēn zhe shī xiōng xué xí xiàng mù shēn bào ， míng nián zài lái tóu dì gǎng wèi 。','Vâng thưa thầy, em sẽ theo các anh chị khóa trên học cách đăng ký dự án trước, sang năm em sẽ nộp đơn lại ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1310','SHTN1','申报省级留学生科研创新项目，材料缺少中方导师签字无法提交系统',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1310','SIT1310','P1','twist','ban_chinh_thuc',NULL,'国内所有省级、校级科研项目申报均要求导师手写签字，电子签名、后期补签均无效，系统到期自动关闭通道。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1310_01','V1310','阮明',1,'何秘书，我申报省级留学生创新项目，系统一直提示材料不通过啊。','hé mì shū ， wǒ shēn bào shěng jí liú xué shēng chuàng xīn xiàng mù ， xì tǒng yì zhí tí shì cái liào bù tōng guò a 。','Chị Hà ơi, em đăng ký dự án sáng tạo nghiên cứu cấp tỉnh cho lưu học sinh, mà hệ thống cứ báo hồ sơ không đạt ạ.','AM05') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1310_02','V1310','小何',2,'我帮你查看一下，项目申报书缺少指导老师手写签字页呢。','wǒ bāng nǐ chá kàn yī xià ， xiàng mù shēn bào shū quē shǎo zhǐ dǎo lǎo shī shǒu xiě qiān zì yè ne 。','Để chị kiểm tra giúp em, hồ sơ đăng ký dự án đang thiếu trang chữ ký tay của thầy hướng dẫn đấy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1310_03','V1310','阮明',3,'导师今天外出开会，我能不能先线上提交，之后补签字吗？','dǎo shī jīn tiān wài chū kāi huì ， wǒ néng bù néng xiān xiàn shàng tí jiāo ， zhī hòu bǔ qiān zì ma ？','Hôm nay thầy hướng dẫn đi họp bên ngoài, em có thể nộp trực tuyến trước rồi bổ sung chữ ký sau được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1310_04','V1310','小何',4,'系统关闭前必须上传带签字扫描件，不支持后期补交材料的。','xì tǒng guān bì qián bì xū shàng chuán dài qiān zì sǎo miáo jiàn ， bù zhī chí hòu qī bǔ jiāo cái liào de 。','Trước khi hệ thống đóng bắt buộc phải tải lên bản scan có chữ ký, không hỗ trợ bổ sung tài liệu sau đâu em.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1310_05','V1310','阮明',5,'申报截止明天中午，我晚上联系导师签字再扫描来得及吗？','shēn bào jié zhǐ míng tiān zhōng wǔ ， wǒ wǎn shàng lián xì dǎo shī qiān zì zài sǎo miáo lái de jí ma ？','Hạn nộp là trưa mai, tối nay em liên hệ thầy ký rồi scan lại thì có kịp không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1310_06','V1310','小何',6,'抓紧时间没问题，签字一定要手写，电子签名系统不认哦。','zhuā jǐn shí jiān méi wèn tí ， qiān zì yí dìng yào shǒu xiě ， diàn zi qiān míng xì tǒng bù rèn ó 。','Tranh thủ thời gian thì không thành vấn đề, nhưng chữ ký nhất định phải viết tay, hệ thống không chấp nhận chữ ký điện tử đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1310_07','V1310','阮明',7,'我现在立刻联系导师，今晚一定补齐签字材料。','wǒ xiàn zài lì kè lián xì dǎo shī ， jīn wǎn yí dìng bǔ qí qiān zì cái liào 。','Em liên hệ thầy hướng dẫn ngay bây giờ, tối nay nhất định sẽ bổ sung đủ tài liệu có chữ ký ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1311','SHTN1','竞赛决赛现场答辩设备故障，PPT文件U盘损坏，和现场工作人员协商应急方案',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1311','SIT1311','P1','twist','ban_chinh_thuc',NULL,'国内竞赛答辩要求提前备份电子材料，U盘、云端双备份是通用习惯，设备故障可申请口述答辩作为应急方案。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1311_01','V1311','阮明',1,'吴师傅不好了，我的U盘读不出来，竞赛答辩马上轮到我上场啦！','wú shī fù bù hǎo le ， wǒ de U pán dú bù chū lái ， jìng sài dá biàn mǎ shàng lún dào wǒ shàng chǎng la ！','Thầy Ngô ơi, không xong rồi, USB của em không đọc được, sắp tới lượt em thuyết trình chung kết rồi!','AM02') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1311_02','V1311','老吴',2,'别慌，你云端有没有备份PPT？手机登录网盘直接调取也行嘛。','bié huāng ， nǐ yún duān yǒu méi yǒu bèi fèn PPT？ shǒu jī dēng lù wǎng pán zhí jiē diào qǔ yě xíng ma 。','Đừng hoảng, em có sao lưu PPT trên mây không? Đăng nhập ổ đám mây bằng điện thoại lấy trực tiếp cũng được mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1311_03','V1311','阮明',3,'我只存在U盘里，忘记云端备份，这下该怎么补救呢？','wǒ zhǐ cún zài U pán lǐ ， wàng jì yún duān bèi fèn ， zhè xià gāi zěn me bǔ jiù ne ？','Em chỉ lưu trong USB thôi, quên mất sao lưu lên mây, giờ phải khắc phục thế nào đây ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1311_04','V1311','老吴',4,'我给你十分钟，你口述项目核心内容，配合黑板手绘简图讲解。','wǒ gěi nǐ shí fēn zhōng ， nǐ kǒu shù xiàng mù hé xīn nèi róng ， pèi hé hēi bǎn shǒu huì jiǎn tú jiǎng jiě 。','Thầy cho em mười phút, em trình bày miệng nội dung cốt lõi của đề tài, kết hợp vẽ tay sơ đồ minh họa lên bảng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1311_05','V1311','阮明',5,'十分钟梳理全部研究内容有点紧张，能给我一张草稿纸整理思路吗？','shí fēn zhōng shū lǐ quán bù yán jiū nèi róng yǒu diǎn jǐn zhāng ， néng gěi wǒ yī zhāng cǎo gǎo zhǐ zhěng lǐ sī lù ma ？','Mười phút mà sắp xếp lại hết nội dung nghiên cứu thì hơi căng, thầy cho em xin một tờ giấy nháp để sắp ý được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1311_06','V1311','老吴',6,'没问题，这边纸笔你拿好，评委那边我帮你说明设备突发故障。','méi wèn tí ， zhè biān zhǐ bǐ nǐ ná hǎo ， píng wěi nà biān wǒ bāng nǐ shuō míng shè bèi tū fā gù zhàng 。','Không vấn đề gì, giấy bút đây em cầm lấy, còn phía ban giám khảo để thầy giải thích giúp em là thiết bị gặp sự cố bất ngờ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1311_07','V1311','阮明',7,'太感谢您，不然我直接没法完成本次决赛答辩咯。','tài gǎn xiè nín ， bù rán wǒ zhí jiē méi fǎ wán chéng běn cì jué sài dá biàn gē 。','Em cảm ơn thầy nhiều lắm, không thì em không cách nào hoàn thành phần thuyết trình chung kết lần này đâu.','AM11') ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1312','SHTN1','拜访意向硕导办公室，不清楚国内师生拜访礼仪，被同门学姐提醒注意事项',NULL,'B2') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1312','SIT1312','P1','suon_se','tuy_y',NULL,'国内拜访高校导师有固定礼仪，控制谈话时长、不随意打断发言、进门敲门是师生相处基本规矩。') ON CONFLICT DO NOTHING;
