INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT916','SXH3','说话直爽无意间冒犯中国同学，事后主动道歉、说明文化差异',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V916','SIT916','P1','twist','ban_chinh_thuc',NULL,'东南亚部分国家交流风格直白，和国内委婉含蓄的沟通方式有冲突，产生矛盾后主动解释文化差异并道歉，容易化解隔阂。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_01','V916','阮明',1,'昨天聊天我说话太直接，伤到你的感受，我郑重跟你道歉。','zuó tiān liáo tiān wǒ shuō huà tài zhí jiē， shāng dào nǐ de gǎn shòu， wǒ zhèng zhòng gēn nǐ dào qiàn。','Hôm qua nói chuyện tớ ăn nói thẳng quá, làm cậu buồn lòng, tớ xin lỗi cậu một cách nghiêm túc.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_02','V916','小林',2,'当时听完心里有点不舒服，知道你不是恶意就没关系。','dāng shí tīng wán xīn lǐ yǒu diǎn bù shū fú， zhī dào nǐ bú shì è yì jiù méi guān xì。','Lúc đó nghe xong tớ cũng hơi khó chịu, nhưng biết cậu không cố ý nên không sao đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_03','V916','阮明',3,'越南日常交流说话更直白，我还没完全适应委婉的中文表达。','yuè nán rì cháng jiāo liú shuō huà gèng zhí bái， wǒ hái méi wán quán shì yìng wěi wǎn de zhōng wén biǎo dá。','Người Việt hằng ngày nói chuyện thẳng thắn hơn, tớ vẫn chưa quen hẳn với cách nói chuyện tế nhị của tiếng Trung.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_04','V916','小林',4,'我明白文化差异，之后有不舒服我会直接跟你说。','wǒ míng bái wén huà chā yì， zhī hòu yǒu bù shū fú wǒ huì zhí jiē gēn nǐ shuō。','Tớ hiểu đó là khác biệt văn hóa mà, sau này có gì không thoải mái tớ sẽ nói thẳng với cậu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_05','V916','阮明',5,'之后我说话多斟酌用词，学着更委婉温和地表达想法。','zhī hòu wǒ shuō huà duō zhēn zhuó yòng cí， xué zhe gèng wěi wǎn wēn hé dì biǎo dá xiǎng fǎ。','Sau này tớ sẽ cân nhắc lời nói kỹ hơn, học cách diễn đạt tế nhị và ôn hòa hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_06','V916','小林',6,'我们互相包容两国说话习惯，不用因为小事隔阂。','wǒ men hù xiāng bāo róng liǎng guó shuō huà xí guàn， bù yòng yīn wèi xiǎo shì gé hé。','Mình bao dung với thói quen nói chuyện của hai nước nhé, đừng vì chuyện nhỏ mà xa cách nhau.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L916_07','V916','阮明',7,'非常感谢你愿意原谅我无心的冒犯。','fēi cháng gǎn xiè nǐ yuàn yì yuán liàng wǒ wú xīn de mào fàn。','Cảm ơn cậu rất nhiều vì đã sẵn lòng tha thứ cho sự vô ý của tớ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT917','SXH3','和中国朋友聊两国节日风俗，互相讲解本土传统习俗',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V917','SIT917','P1','suon_se','tuy_y',NULL,'聊节日、民俗是安全无冲突的跨文化社交话题，很容易拉近留学生与中国同学的距离。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L917_01','V917','阮明',1,'越南新年会摆很多鲜花祭祖，你们春节主要有哪些习俗？','yuè nán xīn nián huì bǎi hěn duō xiān huā jì zǔ， nǐ men chūn jié zhǔ yào yǒu nǎ xiē xí sú？','Tết Việt Nam thường bày rất nhiều hoa tươi để cúng tổ tiên, Tết của các cậu chủ yếu có những phong tục gì vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L917_02','V917','苏雯',2,'贴春联、包饺子、全家守岁，长辈还给晚辈发红包呢。','tiē chūn lián、 bāo jiǎo zi、 quán jiā shǒu suì， zhǎng bèi huán gěi wǎn bèi fā hóng bāo ne。','Dán câu đối, gói sủi cảo, cả nhà thức đón giao thừa, người lớn còn lì xì cho con cháu nữa đó.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L917_03','V917','阮明',3,'我们也有压岁钱，只是发放的时间、包装和中国不一样。','wǒ men yě yǒu yā suì qián， zhǐ shì fā fàng de shí jiān、 bāo zhuāng hé zhōng guó bù yí yàng。','Bên tớ cũng có tiền lì xì, chỉ là thời điểm phát, cách gói với bên Trung Quốc không giống nhau thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L917_04','V917','苏雯',4,'中秋你们也会赏月吃月饼吗，还是有特色本土点心？','zhōng qiū nǐ men yě huì shǎng yuè chī yuè bǐng ma， hái shì yǒu tè sè běn tǔ diǎn xīn？','Trung thu bên cậu có ngắm trăng ăn bánh trung thu không, hay có bánh đặc trưng riêng?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L917_05','V917','阮明',5,'我们有同类团圆节日，点心是糯米团子，风味完全不同。','wǒ men yǒu tóng lèi tuán yuán jié rì， diǎn xīn shì nuò mǐ tuán zi， fēng wèi wán quán bù tóng。','Bên tớ cũng có ngày đoàn viên tương tự, nhưng bánh là bánh trôi nếp, hương vị hoàn toàn khác luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L917_06','V917','苏雯',6,'有空交换各自节日照片，直观看看两国节日场景。','yǒu kòng jiāo huàn gè zì jié rì zhào piān， zhí guān kàn kàn liǎng guó jié rì chǎng jǐng。','Lúc nào rảnh trao đổi ảnh chụp ngày Tết của hai bên nhé, để xem trực quan không khí lễ Tết mỗi nước.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L917_07','V917','阮明',7,'好，多交流民俗，能更了解彼此国家文化。','hǎo， duō jiāo liú mín sú， néng gèng liǎo jiě bǐ cǐ guó jiā wén huà。','Ừ, trao đổi phong tục nhiều thì mới hiểu văn hóa của nhau hơn.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT918','SXH3','不清楚国内送礼禁忌，请教同学哪些礼物不适合送给长辈朋友',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V918','SIT918','P1','suon_se','ban_chinh_thuc',NULL,'中文大量谐音送礼禁忌，钟表（送终）、梨（离）、伞（散）均为送礼避讳物品，留学生提前询问可避免失礼。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L918_01','V918','阮明',1,'我想给中国长辈准备礼物，想问问有什么物品不能赠送？','wǒ xiǎng gěi zhōng guó zhǎng bèi zhǔn bèi lǐ wù， xiǎng wèn wèn yǒu shén me wù pǐn bù néng zèng sòng？','Em muốn chuẩn bị quà cho người lớn tuổi bên Trung Quốc, không biết có món gì không nên tặng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L918_02','V918','苏雯',2,'钟表、梨、雨伞这几类谐音不吉利，尽量避开哦。','zhōng biǎo、 lí、 yǔ sǎn zhè jǐ lèi xié yīn bù jí lì， jǐn liàng bì kāi ó。','Đồng hồ, lê, ô dù mấy thứ này đọc âm gần giống từ xui xẻo, nên tránh nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L918_03','V918','阮明',3,'送鲜花有没有讲究，白色、黄色花束适合探望长辈吗？','sòng xiān huā yǒu méi yǒu jiǎng jiū， bái sè、 huáng sè huā shù shì hé tàn wàng zhǎng bèi ma？','Tặng hoa tươi thì có kiêng kỵ gì không, bó hoa trắng, vàng có hợp để thăm người lớn tuổi không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L918_04','V918','苏雯',4,'白黄鲜花多用于丧葬，看望长辈选红色、粉色鲜花更合适。','bái huáng xiān huā duō yòng yú sāng zàng， kàn wàng zhǎng bèi xuǎn hóng sè、 fěn sè xiān huā gèng hé shì。','Hoa trắng, hoa vàng thường dùng trong tang lễ, thăm người lớn tuổi thì chọn hoa đỏ, hoa hồng sẽ hợp hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L918_05','V918','阮明',5,'刀具也不能作为礼品赠送，代表分割分离的寓意对吧？','dāo jù yě bù néng zuò wéi lǐ pǐn zèng sòng， dài biǎo fēn gē fēn lí de yù yì duì ba？','Dao kéo cũng không nên dùng làm quà tặng đúng không, vì mang ý nghĩa cắt đứt, chia lìa phải không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L918_06','V918','苏雯',6,'没错，刀具寓意不好，食品、茶叶、丝巾是稳妥选择。','méi cuò， dāo jù yù yì bù hǎo， shí pǐn、 chá yè、 sī jīn shì wěn tuǒ xuǎn zé。','Đúng vậy, dao kéo mang ý nghĩa không hay, thực phẩm, trà, khăn lụa là lựa chọn an toàn hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L918_07','V918','阮明',7,'我记下所有禁忌，挑选稳妥礼品送给长辈。','wǒ jì xià suǒ yǒu jìn jì， tiāo xuǎn wěn tuǒ lǐ pǐn sòng gěi zhǎng bèi。','Em ghi nhớ hết những điều kiêng kỵ rồi, sẽ chọn quà an toàn để tặng người lớn tuổi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT919','SXH3','朋友调侃本国文化，温和表达自己的看法，避免争执',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V919','SIT919','P1','that_bai_nhe','tuy_y',NULL,'国内年轻人偶尔会随口开玩笑，但涉及他国文化、风俗时需把握分寸，温和表达不适能有效避免社交矛盾升级。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L919_01','V919','阮明',1,'你刚刚调侃越南饮食的话，听着我心里有点不舒服。','nǐ gāng gāng tiáo kǎn yuè nán yǐn shí de huà， tīng zhe wǒ xīn lǐ yǒu diǎn bù shū fú。','Câu cậu vừa trêu về ẩm thực Việt Nam ấy, nghe xong tớ thấy hơi khó chịu trong lòng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L919_02','V919','小林',2,'我只是随口开玩笑，没有贬低你国家的意思。','wǒ zhǐ shì suí kǒu kāi wán xiào， méi yǒu biǎn dī nǐ guó jiā de yì si。','Tớ chỉ tiện miệng đùa thôi, không có ý coi thường nước cậu đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L919_03','V919','阮明',3,'每个国家饮食文化都值得尊重，玩笑最好不要拿本国特色调侃嘛。','měi gè guó jiā yǐn shí wén huà dōu zhí de zūn zhòng， wán xiào zuì hǎo bù yào ná běn guó tè sè diào kǎn ma。','Văn hóa ẩm thực nước nào cũng đáng được tôn trọng, đùa thì tốt nhất đừng đem đặc trưng của nước người ta ra chọc ghẹo chứ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L919_04','V919','小林',4,'我不清楚你会在意这个，之后我会注意说话分寸。','wǒ bù qīng chǔ nǐ huì zài yì zhè ge， zhī hòu wǒ huì zhù yì shuō huà fēn cùn。','Tớ không biết là cậu để bụng chuyện này, sau này tớ sẽ chú ý lời ăn tiếng nói hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L919_05','V919','阮明',5,'我们可以客观对比两国美食，但不要用调侃、取笑的语气。','wǒ men kě yǐ kè guān duì bǐ liǎng guó měi shí， dàn bú yào yòng tiáo kǎn、 qǔ xiào de yǔ qì。','Tụi mình có thể khách quan so sánh ẩm thực hai nước, nhưng đừng dùng giọng điệu châm chọc, giễu cợt.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L919_06','V919','小林',6,'我记住了，以后聊各国文化都会注意措辞。','wǒ jì zhù le， yǐ hòu liáo gè guó wén huà dōu huì zhù yì cuò cí。','Tớ nhớ rồi, sau này nói chuyện văn hóa các nước tớ sẽ chú ý cách dùng từ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L919_07','V919','阮明',7,'谢谢你理解我的感受，我们继续友好聊天。','xiè xiè nǐ lǐ jiě wǒ de gǎn shòu， wǒ men jì xù yǒu hǎo liáo tiān。','Cảm ơn cậu đã hiểu cho cảm giác của tớ, mình tiếp tục nói chuyện vui vẻ nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT920','SXH3','线上聊天用词误会，线下见面澄清、化解线上尴尬',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V920','SIT920','P1','twist','ban_chinh_thuc',NULL,'纯文字线上聊天缺少语气表情，极易产生误会，国内朋友遇到分歧倾向线下当面澄清，高效化解尴尬。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L920_01','V920','阮明',1,'昨天线上聊天那句话我用词有误，让你误会我的意思了。','zuó tiān xiàn shàng liáo tiān nà jù huà wǒ yòng cí yǒu wù， ràng nǐ wù huì wǒ de yì si le。','Hôm qua nhắn tin online câu đó em dùng từ chưa đúng, khiến chị hiểu lầm ý em rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L920_02','V920','苏雯',2,'文字看不到语气，我当时还以为你有点生气。','wén zì kàn bú dào yǔ qì， wǒ dāng shí hái yǐ wéi nǐ yǒu diǎn shēng qì。','Nhắn chữ không thấy được giọng điệu, lúc đó chị còn tưởng em hơi giận.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L920_03','V920','阮明',3,'线上打字缺少表情，很容易曲解情绪，我今天当面跟你解释清楚。','xiàn shàng dǎ zì quē shǎo biǎo qíng， hěn róng yì qū jiě qíng xù， wǒ jīn tiān dāng miàn gēn nǐ jiě shì qīng chǔ。','Nhắn tin online thiếu biểu cảm nên rất dễ hiểu sai cảm xúc, hôm nay em gặp trực tiếp giải thích rõ với chị.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L920_04','V920','苏雯',4,'线下聊开就没事了，之后重要事情尽量语音沟通。','xiàn xià liáo kāi jiù méi shì le， zhī hòu zhòng yào shì qíng jǐn liàng yǔ yīn gōu tōng。','Nói chuyện trực tiếp thế này là ổn rồi, sau này việc quan trọng nên cố gắng gọi điện trao đổi bằng giọng nói.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L920_05','V920','阮明',5,'文字容易产生误会，之后复杂想法直接语音或者见面聊。','wén zì róng yì chǎn shēng wù huì， zhī hòu fù zá xiǎng fǎ zhí jiē yǔ yīn huò zhě jiàn miàn liáo。','Nhắn chữ dễ gây hiểu lầm, sau này ý nào phức tạp thì em sẽ gọi điện hoặc gặp trực tiếp nói luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L920_06','V920','苏雯',6,'没问题，线上简单小事文字，重要话题线下沟通。','méi wèn tí， xiàn shàng jiǎn dān xiǎo shì wén zì， zhòng yào huà tí xiàn xià gōu tōng。','Không sao, việc nhỏ đơn giản thì nhắn tin, chuyện quan trọng thì gặp trực tiếp trao đổi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L920_07','V920','阮明',7,'太好了，误会说开我们不会有隔阂。','tài hǎo le， wù huì shuō kāi wǒ men bú huì yǒu gé hé。','Tốt quá, hiểu lầm nói rõ ra rồi thì mình sẽ không có khoảng cách nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT921','SXH4','留学生微信群发起线下小型茶话会，统计参与人数、地点',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V921','SIT921','P1','suon_se','tuy_y',NULL,'留学生线上社群自发组织线下小型聚会十分普遍，饮品、零食自带或AA分摊，场地提前预留。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L921_01','V921','阮明',1,'本周六下午两点校内咖啡馆举办留学生茶话会，有意向的群里回复1。','běn zhōu liù xià wǔ liǎng diǎn xiào nèi kā fēi guǎn jǔ bàn liú xué shēng chá huà huì， yǒu yì xiàng de qún lǐ huí fù 1。','Chiều thứ Bảy tuần này lúc 2 giờ ở quán cà phê trong trường có buổi trà đàm cho lưu học sinh, ai muốn tham gia thì trả lời 1 trong nhóm nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L921_02','V921','群友A',2,'咖啡馆座位有限，最多容纳十五个人，人数满了就截止报名吗？','kā fēi guǎn zuò wèi yǒu xiàn， zuì duō róng nà shí wǔ gè rén， rén shù mǎn le jiù jié zhǐ bào míng ma？','Quán cà phê chỗ ngồi có hạn, tối đa chứa được mười lăm người, đủ số là chốt sổ đăng ký luôn hả?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L921_03','V921','阮明',3,'没错，先回复先预留位置，到场饮品全部AA自行点单。','méi cuò， xiān huí fù xiān yù liú wèi zhì， dào chǎng yǐn pǐn quán bù AA zì xíng diǎn dān。','Đúng rồi, ai trả lời trước thì giữ chỗ trước, đến nơi đồ uống thì mọi người tự gọi tự trả nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L921_04','V921','群友B',4,'会分享各国零食吗，我可以带越南特色糖果过去。','huì fēn xiǎng gè guó líng shí ma， wǒ kě yǐ dài yuè nán tè sè táng guǒ guò qù。','Có chia sẻ đồ ăn vặt các nước không, tớ có thể mang kẹo đặc sản Việt Nam qua.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L921_05','V921','阮明',5,'欢迎大家自带本国小零食交换品尝，丰富茶话会内容。','huān yíng dà jiā zì dài běn guó xiǎo líng shí jiāo huàn pǐn cháng， fēng fù chá huà huì nèi róng。','Chào đón mọi người mang đồ ăn vặt nước mình đến trao đổi nếm thử, cho buổi trà đàm thêm phong phú.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L921_06','V921','阮明',6,'我傍晚统计最终人数，提前跟咖啡馆预留区域。','wǒ bàng wǎn tǒng jì zuì zhōng rén shù， tí qián gēn kā fēi guǎn yù liú qū yù。','Chiều tối tớ sẽ tổng hợp số người cuối cùng, rồi báo trước với quán cà phê để giữ chỗ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L921_07','V921','群友C',7,'我报名参加，周六准时到场。','wǒ bào míng cān jiā， zhōu liù zhǔn shí dào chǎng。','Tớ đăng ký tham gia nè, thứ Bảy tớ đến đúng giờ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT922','SXH4','和新朋友初次线下见面，挑选公共场所、确认往返交通',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V922','SIT922','P1','twist','ban_chinh_thuc',NULL,'初次线下见面优先校园周边公共场所，不单独前往偏僻地点，分别后互相报平安是国内年轻人通用社交安全习惯。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L922_01','V922','阮明',1,'我们第一次线下见面，选学校正门连锁奶茶店可以吗？','wǒ men dì yī cì xiàn xià jiàn miàn， xuǎn xué xiào zhèng mén lián suǒ nǎi chá diàn kě yǐ ma？','Lần đầu tụi mình gặp mặt trực tiếp, chọn quán trà sữa chuỗi ngay cổng chính trường được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L922_02','V922','陈雨',2,'公共场所很安全，就是我下午有课，只能停留一小时。','gōng gòng chǎng suǒ hěn ān quán， jiù shì wǒ xià wǔ yǒu kè， zhǐ néng tíng liú yī xiǎo shí。','Chỗ công cộng thì rất an toàn, chỉ là chiều em có tiết học, chỉ ở lại được một tiếng thôi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L922_03','V922','阮明',3,'一小时足够简单聊天，结束我可以送你回教学楼。','yī xiǎo shí zú gòu jiǎn dān liáo tiān， jié shù wǒ kě yǐ sòng nǐ huí jiào xué lóu。','Một tiếng cũng đủ để nói chuyện đơn giản rồi, xong anh có thể đưa em về tòa nhà học.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L922_04','V922','陈雨',4,'不用特意送我，校门口公交直达教学楼，交通很方便。','bù yòng tè yì sòng wǒ， xiào mén kǒu gōng jiāo zhí dá jiào xué lóu， jiāo tōng hěn fāng biàn。','Không cần anh đưa đâu ạ, xe buýt ở cổng trường đi thẳng đến tòa nhà học, rất tiện.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L922_05','V922','阮明',5,'见面结束记得发消息告诉我平安抵达教室哈。','jiàn miàn jié shù jì de fā xiāo xī gào sù wǒ píng ān dǐ dá jiào shì hā。','Gặp xong nhớ nhắn tin báo anh biết là em về đến lớp an toàn nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L922_06','V922','陈雨',6,'好，周六下午三点奶茶店门口碰面。','hǎo， zhōu liù xià wǔ sān diǎn nǎi chá diàn mén kǒu pèng miàn。','Vâng, ba giờ chiều thứ Bảy gặp nhau trước cửa quán trà sữa ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L922_07','V922','阮明',7,'准时赴约，初次见面简单聊一聊各自专业。','zhǔn shí fù yuē， chū cì jiàn miàn jiǎn dān liáo yī liáo gè zì zhuān yè。','Đến đúng giờ nhé, lần đầu gặp mặt thì nói chuyện đơn giản về chuyên ngành của mỗi người thôi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT923','SXH4','朋友频繁发消息打扰自习，委婉告知自己的作息学习时间',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V923','SIT923','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内学生重视自习、上课时间，会主动和朋友说明固定专注时段，委婉划定社交边界，对方一般都会体谅。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L923_01','V923','阮明',1,'不好意思，每天下午两点到五点我要专心自习，没法及时回复消息。','bù hǎo yì sī， měi tiān xià wǔ liǎng diǎn dào wǔ diǎn wǒ yào zhuān xīn zì xí， méi fǎ jí shí huí fù xiāo xī。','Xin lỗi cậu, mỗi ngày từ 2 giờ đến 5 giờ chiều tớ cần tập trung tự học, không kịp trả lời tin nhắn được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L923_02','V923','小杨',2,'我以为你随时有空，一有琐事就发消息打扰你了。','wǒ yǐ wéi nǐ suí shí yǒu kòng， yī yǒu suǒ shì jiù fā xiāo xī dǎ rǎo nǐ le。','Tớ cứ tưởng cậu lúc nào cũng rảnh, có việc lặt vặt là nhắn cậu, làm phiền cậu rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L923_03','V923','阮明',3,'自习时段需要安静专注，其余晚上七点之后我可以随时聊天嘛。','zì xí shí duàn xū yào ān jìng zhuān zhù， qí yú wǎn shàng qī diǎn zhī hòu wǒ kě yǐ suí shí liáo tiān ma。','Khung giờ tự học cần yên tĩnh tập trung, còn lại sau 7 giờ tối là tớ rảnh nói chuyện thoải mái mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L923_04','V923','小杨',4,'我记住你的作息，非休息时间不会频繁发消息打断你学习。','wǒ jì zhù nǐ de zuò xī， fēi xiū xī shí jiān bú huì pín fán fā xiāo xī dǎ duàn nǐ xué xí。','Tớ nhớ giờ giấc của cậu rồi, ngoài giờ nghỉ tớ sẽ không nhắn tin liên tục làm gián đoạn việc học của cậu nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L923_05','V923','阮明',5,'急事可以直接打电话，普通闲聊集中晚上再回复你。','jí shì kě yǐ zhí jiē dǎ diàn huà， pǔ tōng xián liáo jí zhōng wǎn shàng zài huí fù nǐ。','Việc gấp thì cứ gọi điện thẳng luôn, còn tán gẫu bình thường thì để tối tớ trả lời tập trung.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L923_06','V923','小杨',6,'没问题，我调整发消息的时间，不耽误你复习功课。','méi wèn tí， wǒ tiáo zhěng fā xiāo xī de shí jiān， bù dān wù nǐ fù xí gōng kè。','Không sao, tớ sẽ điều chỉnh giờ nhắn tin, không làm ảnh hưởng đến việc ôn bài của cậu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L923_07','V923','阮明',7,'十分感谢理解，我们错开自习时段聊天互不影响。','shí fēn gǎn xiè lǐ jiě， wǒ men cuò kāi zì xí shí duàn liáo tiān hù bù yǐng xiǎng。','Cảm ơn cậu nhiều vì đã thông cảm, mình tránh giờ tự học ra để nói chuyện, không ảnh hưởng lẫn nhau nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT924','SXH4','社交软件添加好友，简单自我介绍、说明结识契机',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V924','SIT924','P1','suon_se','tuy_y',NULL,'社交软件添加新朋友后，第一句主动自我介绍、说明相遇场景，是礼貌破冰的基础社交礼仪。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L924_01','V924','阮明',1,'你好，我是阮明，越南留学生，刚才羽毛球球场跟你搭话的人。','nǐ hǎo， wǒ shì ruǎn míng， yuè nán liú xué shēng， gāng cái yǔ máo qiú qiú chǎng gēn nǐ dā huà de rén。','Chào cậu, tớ là Nguyễn Minh, lưu học sinh Việt Nam, người vừa nãy bắt chuyện với cậu ở sân cầu lông đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L924_02','V924','小周',2,'你好，刚才打球聊了两句，特意添加好友方便之后约球场。','nǐ hǎo， gāng cái dǎ qiú liáo le liǎng jù， tè yì tiān jiā hǎo yǒu fāng biàn zhī hòu yuē qiú chǎng。','Chào cậu, vừa nãy đánh cầu nói chuyện được vài câu, nên kết bạn luôn cho tiện sau này hẹn sân.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L924_03','V924','阮明',3,'平时周四下午有空打球，有空可以在微信提前约场地。','píng shí zhōu sì xià wǔ yǒu kòng dǎ qiú， yǒu kòng kě yǐ zài wēi xìn tí qián yuē chǎng dì。','Bình thường chiều thứ Năm tớ rảnh đánh cầu, lúc nào rảnh thì nhắn WeChat hẹn sân trước nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L924_04','V924','小周',4,'没问题，我大部分周四没课，随时可以组队。','méi wèn tí， wǒ dà bù fèn zhōu sì méi kè， suí shí kě yǐ zǔ duì。','Không thành vấn đề, phần lớn thứ Năm tớ không có tiết, lúc nào cũng rủ đội được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L924_05','V924','阮明',5,'我汉语还在练习，有表达不通顺的地方麻烦多包涵。','wǒ hàn yǔ hái zài liàn xí， yǒu biǎo dá bù tōng shùn de dì fāng má fán duō bāo hán。','Tiếng Trung của tớ vẫn còn đang luyện, chỗ nào diễn đạt chưa trôi chảy thì mong cậu thông cảm nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L924_06','V924','小周',6,'互相学习，你也可以教我几句越南日常用语。','hù xiāng xué xí， nǐ yě kě yǐ jiāo wǒ jǐ jù yuè nán rì cháng yòng yǔ。','Học hỏi lẫn nhau mà, cậu cũng có thể dạy tớ vài câu tiếng Việt thông dụng đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L924_07','V924','阮明',7,'之后球场碰面再详细聊天。','zhī hòu qiú chǎng pèng miàn zài xiáng xì liáo tiān。','Vậy hẹn gặp lại ở sân cầu lông rồi nói chuyện chi tiết hơn nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT925','SXH4','多人出行计划出现分歧，投票协商统一游玩行程',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V925','SIT925','P1','suon_se','tuy_y',NULL,'多人集体出行意见不统一时，普遍采用投票少数服从多数，落选一方配合集体安排，不单独搞分歧行程。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L925_01','V925','阮明',1,'现在有两个游玩方案，爬山或者城市老街逛小店，大家投票选择。','xiàn zài yǒu liǎng gè yóu wán fāng àn， pá shān huò zhě chéng shì lǎo jiē guàng xiǎo diàn， dà jiā tóu piào xuǎn zé。','Giờ có hai phương án đi chơi, leo núi hoặc dạo phố cổ ngắm mấy cửa hàng nhỏ trong thành phố, mọi người bình chọn nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L925_02','V925','苏雯',2,'我倾向老街，爬山体力消耗太大，晚上还有作业要写。','wǒ qīng xiàng lǎo jiē， pá shān tǐ lì xiāo hào tài dà， wǎn shàng hái yǒu zuò yè yào xiě。','Mình nghiêng về phố cổ hơn, leo núi tốn sức quá, tối còn phải làm bài tập nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L925_03','V925','小林',3,'我想爬山，老街商铺人太多拍照拥挤。','wǒ xiǎng pá shān， lǎo jiē shāng pù rén tài duō pāi zhào yōng jǐ。','Mình muốn leo núi, phố cổ đông người quá chụp ảnh chen chúc lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L925_04','V925','阮明',4,'我们五个人举手表决，票数多的方案作为本周出行计划。','wǒ men wǔ gè rén jǔ shǒu biǎo jué， piào shù duō de fāng àn zuò wéi běn zhōu chū xíng jì huà。','Năm đứa mình giơ tay biểu quyết nhé, phương án nào nhiều phiếu hơn thì chọn làm lịch đi chơi tuần này.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L925_05','V925','小林',5,'行，少数服从多数，选老街我也配合大家行程。','xíng， shǎo shù fú cóng duō shù， xuǎn lǎo jiē wǒ yě pèi hé dà jiā xíng chéng。','Được, thiểu số phục tùng đa số, chọn phố cổ thì mình cũng theo lịch trình của mọi người.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L925_06','V925','阮明',6,'敲定老街路线，提前查公交、小吃店攻略。','qiāo dìng lǎo jiē lù xiàn， tí qián chá gōng jiāo、 xiǎo chī diàn gōng lüè。','Vậy chốt lộ trình phố cổ, tranh thủ tra trước tuyến xe buýt với mấy quán ăn vặt ngon.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L925_07','V925','苏雯',7,'统一行程之后，所有人周末同步出发。','tǒng yī xíng chéng zhī hòu， suǒ yǒu rén zhōu mò tóng bù chū fā。','Chốt lịch trình xong thì cuối tuần tất cả cùng xuất phát nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT926','SXH4','线下聚会结束后，主动发消息平安到家，告知同行朋友',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V926','SIT926','P1','suon_se','tuy_y',NULL,'多人线下活动解散后，互相在群内报平安是通用习惯，确认所有人安全抵达住处，避免同伴失联让人担心。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L926_01','V926','阮明',1,'我已经平安回到宿舍，大家到家都报一声平安哈。','wǒ yǐ jīng píng ān huí dào sù shè， dà jiā dào jiā dōu bào yī shēng píng ān hā。','Mình về tới ký túc xá an toàn rồi nè, mọi người về tới nơi thì báo một tiếng cho yên tâm nha.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L926_02','V926','苏雯',2,'我刚到楼下，马上进宿舍，路上公交很顺畅。','wǒ gāng dào lóu xià， mǎ shàng jìn sù shè， lù shàng gōng jiāo hěn shùn chàng。','Mình vừa tới dưới tòa nhà, sắp vào ký túc xá rồi, đường đi xe buýt suôn sẻ lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L926_03','V926','小林',3,'我还在步行回宿舍，十分钟左右到，一切顺利。','wǒ hái zài bù xíng huí sù shè， shí fēn zhōng zuǒ yòu dào， yī qiè shùn lì。','Mình vẫn đang đi bộ về ký túc xá, tầm mười phút nữa là tới, mọi thứ ổn cả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L926_04','V926','阮明',4,'今晚聚会很开心，下次有空再约线下活动。','jīn wǎn jù huì hěn kāi xīn， xià cì yǒu kòng zài yuē xiàn xià huó dòng。','Tối nay tụ tập vui thật đấy, lần sau rảnh lại hẹn đi chơi tiếp nha.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L926_05','V926','苏雯',5,'好，下周看课表再商量下次聚会时间。','hǎo， xià zhōu kàn kè biǎo zài shāng liáng xià cì jù huì shí jiān。','Ừ, để tuần sau xem lịch học rồi bàn tiếp thời gian tụ tập lần tới.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L926_06','V926','阮明',6,'大家早点休息，晚安。','dà jiā zǎo diǎn xiū xī， wǎn ān。','Mọi người nghỉ sớm đi, chúc ngủ ngon nha.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT927','SXH5','社团换届竞选，为参选朋友加油，赛后安慰落选社员',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V927','SIT927','P1','twist','ban_chinh_thuc',NULL,'社团竞选落选后，身边朋友会主动安慰鼓励，国内社团氛围看重同伴支持，不会因竞选结果疏远关系。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L927_01','V927','阮明',1,'刚才竞选演讲你发挥特别好，可惜差几票没能当选部长。','gāng cái jìng xuǎn yǎn jiǎng nǐ fā huī tè bié hǎo， kě xī chà jǐ piào méi néng dāng xuǎn bù zhǎng。','Bài phát biểu tranh cử của cậu vừa nãy phát huy rất tốt, tiếc là thiếu vài phiếu nên không trúng cử chủ nhiệm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L927_02','V927','小杨',2,'准备了很久还是落选，心里有点失落。','zhǔn bèi le hěn jiǔ hái shì luò xuǎn， xīn lǐ yǒu diǎn shī luò。','Chuẩn bị lâu vậy mà vẫn rớt, trong lòng cũng hơi thất vọng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L927_03','V927','阮明',3,'你的能力所有人都看得到，明年换届还有机会参选嘛。','nǐ de néng lì suǒ yǒu rén dōu kàn dé dào， míng nián huàn jiè hái yǒu jī huì cān xuǎn ma。','Năng lực của cậu ai cũng thấy rõ cả, sang năm bầu lại vẫn còn cơ hội ứng cử mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L927_04','V927','小杨',4,'下一年学业压力大，不一定有空参与社团管理。','xià yī nián xué yè yā lì dà， bù yí dìng yǒu kòng cān yù shè tuán guǎn lǐ。','Năm sau áp lực học tập nặng lắm, chưa chắc có thời gian tham gia quản lý câu lạc bộ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L927_05','V927','阮明',5,'就算不当部长，社团活动依旧可以正常参与组织工作。','jiù suàn bù dàng bù zhǎng， shè tuán huó dòng yī jiù kě yǐ zhèng cháng cān yù zǔ zhī gōng zuò。','Dù không làm chủ nhiệm thì cậu vẫn có thể tham gia bình thường vào công việc tổ chức của câu lạc bộ mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L927_06','V927','小杨',6,'谢谢你过来为我加油，还特意过来安慰我。','xiè xiè nǐ guò lái wèi wǒ jiā yóu， hái tè yì guò lái ān wèi wǒ。','Cảm ơn cậu đã đến cổ vũ cho mình, còn đặc biệt qua an ủi mình nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L927_07','V927','阮明',7,'我们是朋友，开心、失落都可以一起分担。','wǒ men shì péng yǒu， kāi xīn、 shī luò dōu kě yǐ yì qǐ fēn dān。','Chúng ta là bạn bè mà, vui hay buồn đều có thể chia sẻ cùng nhau.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT928','SXH5','新生向高年级学长学姐请教社交、校园生活避坑经验',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V928','SIT928','P1','suon_se','ban_chinh_thuc',NULL,'高校内新生主动向高年级学长学姐请教校园、社交经验是很普遍的行为，学长学姐一般都会耐心分享实用建议。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L928_01','V928','阮明',1,'学长，我刚入校不太熟悉校园社交，想请教一些避坑小经验。','xué zhǎng， wǒ gāng rù xiào bù tài shú xī xiào yuán shè jiāo， xiǎng qǐng jiào yī xiē bì kēng xiǎo jīng yàn。','Anh ơi, em mới vào trường chưa quen giao tiếp trong khuôn viên, muốn xin anh vài kinh nghiệm tránh sai lầm ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L928_02','V928','学长',2,'社团不用一次性报名五六个，选一两个真正感兴趣的深耕即可。','shè tuán bù yòng yí cì xìng bào míng wǔ liù gè， xuǎn yī liǎng gè zhēn zhèng gǎn xìng qù de shēn gēng jí kě。','Không cần đăng ký một lúc năm sáu câu lạc bộ đâu, chọn một hai cái thực sự thích rồi đầu tư sâu là được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L928_03','V928','阮明',3,'校外社交、兼职有哪些需要格外留意的陷阱？','xiào wài shè jiāo、 jiān zhí yǒu nǎ xiē xū yào gé wài liú yì de xiàn jǐng？','Vậy giao tiếp bên ngoài, làm thêm thì có những cạm bẫy nào cần đặc biệt chú ý ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L928_04','V928','学长',4,'陌生线下兼职、陌生网友单独见面一定要选公共场所。','mò shēng xiàn xià jiān zhí、 mò shēng wǎng yǒu dān dú jiàn miàn yí dìng yào xuǎn gōng gòng chǎng suǒ。','Việc làm thêm gặp ngoài đời với người lạ hay hẹn gặp bạn quen qua mạng nhất định phải chọn nơi công cộng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L928_05','V928','阮明',5,'和本国、中国同学相处，有什么容易产生误会的文化细节？','hé běn guó、 zhōng guó tóng xué xiāng chǔ， yǒu shén me róng yì chǎn shēng wù huì de wén huà xì jié？','Khi giao lưu với bạn cùng nước và bạn Trung Quốc, có chi tiết văn hóa nào dễ gây hiểu lầm không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L928_06','V928','学长',6,'送礼、借钱、作息边界提前沟通清楚，能减少大部分矛盾。','sòng lǐ、 jiè qián、 zuò xī biān jiè tí qián gōu tōng qīng chǔ， néng jiǎn shǎo dà bù fèn máo dùn。','Chuyện tặng quà, mượn tiền, giờ giấc sinh hoạt nên trao đổi rõ trước, sẽ giảm được phần lớn mâu thuẫn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L928_07','V928','阮明',7,'记下您的建议，避免社交踩坑吃亏。','jì xià nín de jiàn yì， bì miǎn shè jiāo cǎi kēng chī kuī。','Em ghi nhớ lời khuyên của anh rồi, để tránh vấp phải rắc rối trong giao tiếp ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT929','SXH5','班级集体短途出游，主动分担采购零食、清点人数的小事',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V929','SIT929','P1','suon_se','tuy_y',NULL,'班级集体活动大家主动分担琐碎工作，是体现集体意识、快速拉近同学关系的社交方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_01','V929','阮明',1,'班长，出游采购零食、清点人数的活我可以帮忙分担。','bān zhǎng， chū yóu cǎi gòu líng shí、 qīng diǎn rén shù de huó wǒ kě yǐ bāng máng fēn dān。','Lớp trưởng ơi, việc mua đồ ăn vặt với điểm danh số người cho chuyến đi chơi thì để mình giúp một tay.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_02','V929','班长',2,'太好了，全班三十人，清点人数很耗费精力。','tài hǎo le， quán bān sān shí rén， qīng diǎn rén shù hěn hào fèi jīng lì。','Tốt quá, cả lớp ba mươi người, điểm danh cũng tốn sức lắm.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_03','V929','阮明',3,'我统计所有人忌口，采购零食避开辣椒、坚果过敏原。','wǒ tǒng jì suǒ yǒu rén jì kǒu， cǎi gòu líng shí bì kāi là jiāo、 jiān guǒ guò mǐn yuán。','Mình sẽ thống kê xem ai kiêng món gì, mua đồ ăn vặt tránh ớt với các loại hạt dễ gây dị ứng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_04','V929','班长',4,'采购费用全班AA，我把预算清单发到班级群公示。','cǎi gòu fèi yòng quán bān AA， wǒ bǎ yù suàn qīng dān fā dào bān jí qún gōng shì。','Chi phí mua đồ chia đều cả lớp nhé, mình sẽ đăng bảng dự toán lên nhóm lớp công khai.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_05','V929','阮明',5,'集合时我站队伍末尾，确保没有人掉队遗漏。','jí hé shí wǒ zhàn duì wǔ mò wěi， què bǎo méi yǒu rén diào duì yí lòu。','Lúc tập trung mình sẽ đứng cuối hàng, đảm bảo không ai bị lạc hay bỏ sót.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_06','V929','班长',6,'有你分担工作，集体出游组织轻松很多。','yǒu nǐ fēn dān gōng zuò， jí tǐ chū yóu zǔ zhī qīng sōng hěn duō。','Có cậu chia sẻ công việc, tổ chức đi chơi tập thể nhẹ nhàng hơn hẳn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L929_07','V929','阮明',7,'班级集体活动大家互相搭把手，出行更顺利。','bān jí jí tǐ huó dòng dà jiā hù xiāng dā bǎ shǒu， chū xíng gèng shùn lì。','Hoạt động tập thể của lớp mà mọi người cùng giúp đỡ nhau thì chuyến đi sẽ suôn sẻ hơn nhiều.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT930','SXH5','社团线下团建，协调时间冲突无法到场，提前说明并托人转达祝福',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V930','SIT930','P1','that_bai_nhe','ban_chinh_thuc',NULL,'社团团建无法到场需要提前说明缘由，准备小礼物托人转交表达心意，体现重视社团集体、不失礼。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_01','V930','阮明',1,'学姐，团建当天我有汉语等级考试，没办法到场参与活动。','xué jiě， tuán jiàn dàng tiān wǒ yǒu hàn yǔ děng jí kǎo shì， méi bàn fǎ dào chǎng cān yù huó dòng。','Chị ơi, hôm team building em có kỳ thi năng lực tiếng Trung nên không thể tham gia được ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_02','V930','学姐',2,'团建一年只有一次，错过这次集体聚餐有点可惜。','tuán jiàn yī nián zhǐ yǒu yī cì， cuò guò zhè cì jí tǐ jù cān yǒu diǎn kě xī。','Team building một năm chỉ có một lần, bỏ lỡ bữa tiệc tập thể này cũng hơi tiếc.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_03','V930','阮明',3,'我提前买好社团小伴手礼，托到场的同学分给大家，转达我的祝福。','wǒ tí qián mǎi hǎo shè tuán xiǎo bàn shǒu lǐ， tuō dào chǎng de tóng xué fēn gěi dà jiā， zhuǎn dá wǒ de zhù fú。','Em đã mua sẵn chút quà nhỏ của câu lạc bộ, nhờ bạn nào có mặt hôm đó chia cho mọi người, gửi lời chúc của em ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_04','V930','学姐',4,'心意我们收下，考试优先，学业比团建重要。','xīn yì wǒ men shōu xià， kǎo shì yōu xiān， xué yè bǐ tuán jiàn zhòng yào。','Tấm lòng của em bọn chị nhận rồi, thi cử ưu tiên trước, học hành quan trọng hơn team building mà.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_05','V930','阮明',5,'下次社团小型聚会我一定到场，补上这次缺席。','xià cì shè tuán xiǎo xíng jù huì wǒ yí dìng dào chǎng， bǔ shàng zhè cì quē xí。','Lần tụ họp nhỏ tiếp theo của câu lạc bộ em nhất định sẽ có mặt, bù lại lần vắng này ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_06','V930','学姐',6,'祝你等级考试顺利，不用惦记团建的事。','zhù nǐ děng jí kǎo shì shùn lì， bù yòng diàn jì tuán jiàn de shì。','Chúc em thi năng lực suôn sẻ nhé, đừng bận tâm chuyện team building nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L930_07','V930','阮明',7,'十分抱歉错过集体团建，麻烦学姐代为向大家致歉。','shí fēn bào qiàn cuò guò jí tǐ tuán jiàn， má fán xué jiě dài wéi xiàng dà jiā zhì qiàn。','Em thật sự rất xin lỗi vì lỡ hẹn team building tập thể, phiền chị thay em xin lỗi mọi người ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT931','SXH6','朋友频繁借大额现金，委婉说明自身开销，拒绝频繁借钱',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V931','SIT931','P1','that_bai_nhe','ban_chinh_thuc',NULL,'国内朋友之间小额应急可互相周转，频繁大额借钱会明确划定边界委婉拒绝，避免金钱损耗友情。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_01','V931','阮明',1,'你最近频繁借大额生活费，我每月家里汇款固定，结余不多。','nǐ zuì jìn pín fán jiè dà é shēng huó fèi， wǒ měi yuè jiā lǐ huì kuǎn gù dìng， jié yú bù duō。','Dạo này cậu cứ mượn tiền sinh hoạt số lượng lớn hoài, mỗi tháng nhà gửi cho mình cố định, dư ra chẳng bao nhiêu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_02','V931','小杨',2,'我临时手头周转不开，才一次次找你借钱应急。','wǒ lín shí shǒu tóu zhōu zhuǎn bù kāi， cái yī cì cì zhǎo nǐ jiè qián yìng jí。','Mình nhất thời xoay không kịp nên mới phải tìm cậu mượn tạm nhiều lần vậy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_03','V931','阮明',3,'小额应急可以帮忙，但大额资金我自身学费、教材开销压力大嘛。','xiǎo é yìng jí kě yǐ bāng máng， dàn dà é zī jīn wǒ zì shēn xué fèi、 jiào cái kāi xiāo yā lì dà ma。','Số tiền nhỏ để ứng cấp thì mình giúp được, nhưng khoản lớn thì bản thân mình còn áp lực học phí, tiền sách vở nữa mà.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_04','V931','小杨',4,'明白你的难处，之后我尽量自己规划开支不再频繁借钱。','míng bái nǐ de nán chǔ， zhī hòu wǒ jǐn liàng zì jǐ guī huà kāi zhī bù zài pín fán jiè qián。','Mình hiểu khó khăn của cậu rồi, sau này mình sẽ cố tự lên kế hoạch chi tiêu, không mượn nhiều nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_05','V931','阮明',5,'如果是紧急看病这种急事我一定尽力帮忙，日常消费没法长期出借。','rú guǒ shì jǐn jí kàn bìng zhè zhǒng jí shì wǒ yí dìng jìn lì bāng máng， rì cháng xiāo fèi méi fǎ cháng qī chū jiè。','Nếu là việc gấp như đi khám bệnh thì mình nhất định sẽ cố hết sức giúp, còn chi tiêu hàng ngày thì mình không thể cho mượn dài hạn được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_06','V931','小杨',6,'我理解你的边界，不会再频繁向你借大额钱款。','wǒ lǐ jiě nǐ de biān jiè， bú huì zài pín fán xiàng nǐ jiè dà é qián kuǎn。','Mình hiểu giới hạn của cậu rồi, sẽ không mượn khoản lớn từ cậu thường xuyên nữa đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L931_07','V931','阮明',7,'我们维持轻松的朋友关系，不用因为金钱产生隔阂。','wǒ men wéi chí qīng sōng de péng yǒu guān xì， bù yòng yīn wèi jīn qián chǎn shēng gé hé。','Chúng ta cứ giữ tình bạn thoải mái vậy thôi, đừng để chuyện tiền bạc làm sứt mẻ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT932','SXH6','他人强行推销商品、邀约兼职，礼貌拉开距离明确拒绝',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V932','SIT932','P1','suon_se','ban_chinh_thuc',NULL,'校园内推销、兼职邀约十分常见，礼貌温和但态度明确拒绝，对方不会持续纠缠。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_01','V932','阮明',1,'不好意思，我没有购买护肤品、参与兼职的打算。','bù hǎo yì sī， wǒ méi yǒu gòu mǎi hù fū pǐn、 cān yù jiān zhí de dǎ suàn。','Xin lỗi, em không có ý định mua mỹ phẩm hay tham gia làm thêm gì cả.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_02','V932','推销人员',2,'这款产品留学生用很合适，兼职还能赚取生活费。','zhè kuǎn chǎn pǐn liú xué shēng yòng hěn hé shì， jiān zhí hái néng zhuàn qǔ shēng huó fèi。','Sản phẩm này rất hợp với du học sinh, làm thêm còn kiếm thêm tiền sinh hoạt được nữa đó.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_03','V932','阮明',3,'我课余全部用来复习汉语考试，没有时间做副业兼职嘛。','wǒ kè yú quán bù yòng lái fù xí hàn yǔ kǎo shì， méi yǒu shí jiān zuò fù yè jiān zhí ma。','Em dành hết thời gian ngoài giờ học để ôn thi tiếng Trung, không có thời gian làm thêm việc tay trái đâu ạ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_04','V932','推销人员',4,'耽误五分钟简单了解一下，不会占用你太久时间。','dān wù wǔ fēn zhōng jiǎn dān liǎo jiě yī xià， bú huì zhàn yòng nǐ tài jiǔ shí jiān。','Chỉ mất năm phút tìm hiểu sơ qua thôi, sẽ không chiếm nhiều thời gian của em đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_05','V932','阮明',5,'实在没有需求，我要赶回图书馆自习，先失陪了。','shí zài méi yǒu xū qiú， wǒ yào gǎn huí tú shū guǎn zì xí， xiān shī péi le。','Em thật sự không có nhu cầu, em phải chạy về thư viện tự học rồi, xin phép em đi trước ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_06','V932','推销人员',6,'好吧，不打扰你学习，有需要再联系我。','hǎo ba， bù dǎ rǎo nǐ xué xí， yǒu xū yào zài lián xì wǒ。','Thôi được, vậy không làm phiền em học nữa, khi nào cần thì liên hệ lại với anh nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L932_07','V932','阮明',7,'感谢介绍，我确实没有相关需求。','gǎn xiè jiè shào， wǒ què shí méi yǒu xiāng guān xū qiú。','Cảm ơn anh đã giới thiệu, nhưng em thực sự không có nhu cầu này ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT933','SXH6','很久没联系的老友，主动发消息分享日常、维系友谊',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V933','SIT933','P1','suon_se','tuy_y',NULL,'国内友情不会因为许久不联络直接变淡，主动分享日常、约定线上聊天是维系远距离友谊常用方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_01','V933','阮明',1,'好久不见，最近刷到你朋友圈，想起之前我们一起打球的日子。','hǎo jiǔ bú jiàn， zuì jìn shuā dào nǐ péng yǒu quān， xiǎng qǐ zhī qián wǒ men yì qǐ dǎ qiú de rì zi。','Lâu rồi không gặp, lúc nãy lướt thấy story cậu, tự nhiên nhớ lại hồi mình hay đi đánh bóng chung.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_02','V933','阿凯',2,'确实很久没聊天，你在中国留学生活还适应吗？','què shí hěn jiǔ méi liáo tiān， nǐ zài zhōng guó liú xué shēng huó hái shì yìng ma？','Đúng là lâu lắm rồi không trò chuyện, cuộc sống du học ở Trung Quốc của cậu ổn chứ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_03','V933','阮明',3,'一切顺利，汉语进步不少，拍了很多校园风景照片。','yī qiè shùn lì， hàn yǔ jìn bù bù shǎo， pāi le hěn duō xiào yuán fēng jǐng zhào piān。','Mọi thứ đều suôn sẻ, tiếng Trung tiến bộ kha khá, còn chụp được cả đống ảnh phong cảnh trường nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_04','V933','阿凯',4,'有空周末线上视频，聊聊各自近期的学习生活。','yǒu kòng zhōu mò xiàn shàng shì pín， liáo liáo gè zì jìn qī de xué xí shēng huó。','Rảnh thì cuối tuần mình gọi video online nhé, kể cho nhau nghe chuyện học hành gần đây.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_05','V933','阮明',5,'这周日晚上七点我有空，准时线上跟你聊天叙旧。','zhè zhōu rì wǎn shàng qī diǎn wǒ yǒu kòng， zhǔn shí xiàn shàng gēn nǐ liáo tiān xù jiù。','Tối chủ nhật này bảy giờ mình rảnh, đúng giờ đó lên online tám chuyện với cậu luôn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_06','V933','阿凯',6,'好，到时候线上碰面，多聊聊近况。','hǎo， dào shí hòu xiàn shàng pèng miàn， duō liáo liáo jìn kuàng。','Ok, vậy hẹn online gặp nhau, tám nhiều chuyện gần đây nha.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L933_07','V933','阮明',7,'许久不联系也要偶尔分享日常，别慢慢疏远。','xǔ jiǔ bù lián xì yě yào ǒu ěr fēn xiǎng rì cháng， bié màn màn shū yuǎn。','Lâu không liên lạc thì cũng phải thỉnh thoảng chia sẻ chuyện thường ngày, đừng để xa nhau dần nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT934','SXH6','朋友过度打探家庭、生活费隐私，温和转移话题守住边界',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V934','SIT934','P1','twist','tuy_y',NULL,'国内社交不会过度追问收入、家庭条件等隐私，若对方过度打探，温和转移话题是委婉守住边界的礼貌方式。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_01','V934','阮明',1,'生活费够用就行，我们换个话题聊聊周末去哪游玩吧。','shēng huó fèi gòu yòng jiù xíng， wǒ men huàn gè huà tí liáo liáo zhōu mò qù nǎ yóu wán ba。','Tiền sinh hoạt đủ xài là được rồi, mình đổi chủ đề đi, bàn xem cuối tuần đi chơi đâu nè.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_02','V934','小周',2,'只是好奇问问，你家里每月给你汇多少越南盾？','zhǐ shì hào qí wèn wèn， nǐ jiā lǐ měi yuè gěi nǐ huì duō shǎo yuè nán dùn？','Tò mò hỏi vậy thôi, mỗi tháng nhà cậu gửi cho cậu bao nhiêu tiền Việt vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_03','V934','阮明',3,'各国家庭收支习惯不一样，不太习惯细说家庭财务情况嘛。','gè guó jiā tíng shōu zhī xí guàn bù yí yàng， bù tài xí guàn xì shuō jiā tíng cái wù qíng kuàng ma。','Thói quen thu chi mỗi gia đình mỗi nước khác nhau, mình cũng không quen kể chi tiết chuyện tiền bạc trong nhà lắm.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_04','V934','小周',4,'抱歉，我不知道这是你的隐私，我之后不会再追问这类问题。','bào qiàn， wǒ bù zhī dào zhè shì nǐ de yǐn sī， wǒ zhī hòu bú huì zài zhuī wèn zhè lèi wèn tí。','Xin lỗi nha, mình không biết đây là chuyện riêng tư của cậu, sau này mình sẽ không hỏi mấy chuyện này nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_05','V934','阮明',5,'没关系，我们聊聊校园文艺晚会的节目更有意思。','méi guān xì， wǒ men liáo liáo xiào yuán wén yì wǎn huì de jié mù gèng yǒu yì si。','Không sao đâu, mình nói chuyện về tiết mục văn nghệ của trường thú vị hơn nè.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_06','V934','小周',6,'好，我们聊晚会，不聊私人家庭收支话题。','hǎo， wǒ men liáo wǎn huì， bù liáo sī rén jiā tíng shōu zhī huà tí。','Ừ, vậy mình bàn chuyện văn nghệ thôi, không nhắc đến chuyện thu chi riêng tư của gia đình nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L934_07','V934','阮明',7,'感谢理解，各自保留一点私人空间相处更舒服。','gǎn xiè lǐ jiě， gè zì bǎo liú yì diǎn sī rén kōng jiān xiāng chǔ gèng shū fú。','Cảm ơn cậu đã hiểu, mỗi người giữ chút không gian riêng thì chơi với nhau thoải mái hơn.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT935','SXH6','毕业前夕和要好的朋友约定，回国后定期线上联络',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V935','SIT935','P1','suon_se','ban_chinh_thuc',NULL,'毕业分离时好友会主动约定长期联络方式，国内年轻人十分看重长久稳定的友谊，不会因异地轻易断联。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_01','V935','阮明',1,'等我毕业回越南，我们也要保持联系，不能慢慢断了往来。','děng wǒ bì yè huí yuè nán， wǒ men yě yào bǎo chí lián xì， bù néng màn màn duàn le wǎng lái。','Đợi tôi tốt nghiệp về Việt Nam rồi, chúng ta vẫn phải giữ liên lạc, không được để quan hệ nhạt dần đâu đấy.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_02','V935','苏雯',2,'放心，每月固定一次线上视频，分享各自工作、生活近况。','fàng xīn， měi yuè gù dìng yī cì xiàn shàng shì pín， fēn xiǎng gè zì gōng zuò、 shēng huó jìn kuàng。','Yên tâm đi, mỗi tháng cố định gọi video một lần, chia sẻ tình hình công việc và cuộc sống của mỗi người.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_03','V935','阮明',3,'节假日互相寄本国小特产，线上聊天弥补不能线下见面的遗憾。','jié jià rì hù xiāng jì běn guó xiǎo tè chǎn， xiàn shàng liáo tiān mí bǔ bù néng xiàn xià jiàn miàn de yí hàn。','Vào các dịp lễ thì gửi cho nhau chút đặc sản quê mình, trò chuyện online cũng bù đắp phần nào cho việc không gặp trực tiếp được.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_04','V935','苏雯',4,'不管距离多远，我们的友谊不会因为回国分开变淡。','bù guǎn jù lí duō yuǎn， wǒ men de yǒu yì bú huì yīn wèi huí guó fēn kāi biàn dàn。','Dù khoảng cách có xa đến đâu, tình bạn của chúng ta cũng sẽ không nhạt đi chỉ vì ai đó về nước.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_05','V935','阮明',5,'回国之后时差一小时，提前约定双方都空闲的视频时段。','huí guó zhī hòu shí chà yī xiǎo shí， tí qián yuē dìng shuāng fāng dōu kòng xián de shì pín shí duàn。','Sau khi về nước thì lệch múi giờ một tiếng, mình hẹn trước khung giờ mà cả hai đều rảnh để gọi video.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_06','V935','苏雯',6,'我记好约定，毕业之后按时线上叙旧。','wǒ jì hǎo yuē dìng， bì yè zhī hòu àn shí xiàn shàng xù jiù。','Tôi sẽ ghi nhớ lời hẹn này, sau khi tốt nghiệp sẽ đúng giờ lên online ôn lại chuyện xưa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L935_07','V935','阮明',7,'很幸运在校期间认识你，长久维持这份跨国友谊。','hěn xìng yùn zài xiào qī jiān rèn shí nǐ， cháng jiǔ wéi chí zhè fèn kuà guó yǒu yì。','Thật may mắn khi quen được cậu trong thời gian học ở trường, mong tình bạn xuyên quốc gia này sẽ bền lâu.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1001','SKC1','深夜高烧腹泻无校医，求助室友陪同去校外急诊',NULL,'B2') ON CONFLICT DO NOTHING;
