INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1407','SIT1407','P1','twist','ban_chinh_thuc',NULL,'粤式早茶固定收取人头茶位费，蒸笼点心分大小份，多人就餐多选小份方便多尝几种口味。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1407_01','V1407','阮明',1,'你好，点心分大笼小笼，四人用餐选哪种分量合适呢？','nǐ hǎo ， diǎn xīn fēn dà lóng xiǎo lóng ， sì rén yòng cān xuǎn nǎ zhǒng fèn liàng hé shì ne ？','Chào chị, điểm tâm có lồng lớn lồng nhỏ, bốn người ăn thì chọn phần nào cho hợp ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1407_02','V1407','阿芳',2,'小笼三四只，大笼六只，四个人每种点心选小笼就够分哦。','xiǎo lóng sān sì zhǐ ， dà lóng liù zhǐ ， sì gè rén měi zhǒng diǎn xīn xuǎn xiǎo lóng jiù gòu fēn ó 。','Lồng nhỏ có ba bốn cái, lồng lớn có sáu cái, bốn người thì mỗi món chọn lồng nhỏ là đủ chia rồi đấy.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1407_03','V1407','阮明',3,'进门收的茶位费，是按人头一次性收取吗？','jìn mén shōu de chá wèi fèi ， shì àn rén tóu yí cì xìng shōu qǔ ma ？','Phí trà thu lúc vào cửa là tính một lần theo đầu người đúng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1407_04','V1407','阿芳',4,'没错，一人八元，不限续茶水，餐前小食也免费提供嘛。','méi cuò ， yī rén bā yuán ， bù xiàn xù chá shuǐ ， cān qián xiǎo shí yě miǎn fèi tí gōng ma 。','Đúng vậy, mỗi người tám tệ, châm trà thoải mái không giới hạn, món khai vị cũng miễn phí luôn nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1407_05','V1407','阮明',5,'点心现蒸需要等很久，还是几分钟就能上桌？','diǎn xīn xiàn zhēng xū yào děng hěn jiǔ ， hái shì jǐ fēn zhōng jiù néng shàng zhuō ？','Điểm tâm hấp tại chỗ có phải đợi lâu không, hay vài phút là lên bàn được ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1407_06','V1407','阿芳',6,'现蒸十到十五分钟，着急可以先选蒸好的点心哈。','xiàn zhēng shí dào shí wǔ fēn zhōng ， zháo jí kě yǐ xiān xuǎn zhēng hǎo de diǎn xīn hā 。','Hấp mới mất mười đến mười lăm phút, nếu gấp thì có thể chọn trước món đã hấp sẵn nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1407_07','V1407','阮明',7,'懂了，每种点心各点一笼小笼慢慢品尝。','dǒng le ， měi zhǒng diǎn xīn gè diǎn yī lóng xiǎo lóng màn màn pǐn cháng 。','Em hiểu rồi, mỗi loại điểm tâm gọi một lồng nhỏ để từ từ thưởng thức.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1408','SATN1','点特色地方臭美食螺蛳粉，同桌朋友接受不了气味产生小分歧',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1408','SIT1408','P1','twist','tuy_y',NULL,'螺蛳粉、臭豆腐这类气味浓烈食物，很多餐厅区分堂食区域，顾及其他食客体验，多人聚餐可选择打包食用。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1408_01','V1408','阮明',1,'这家螺蛳粉评价很高，我想点一份试试本地特色可以吗？','zhè jiā luó sī fěn píng jià hěn gāo ， wǒ xiǎng diǎn yī fèn shì shì běn dì tè sè kě yǐ ma ？','Quán ốc lê phấn này đánh giá cao lắm, tớ muốn gọi một suất thử đặc sản địa phương được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1408_02','V1408','子轩',2,'我闻不了酸笋的味道，整个包厢都会飘臭味，实在接受不了。','wǒ wén bù liǎo suān sǔn de wèi dào ， zhěng gè bāo xiāng dōu huì piāo chòu wèi ， shí zài jiē shòu bù liǎo 。','Tớ ngửi không nổi mùi măng chua đâu, cả phòng sẽ bị ám mùi hôi mất, thật sự không chịu nổi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1408_03','V1408','阮明',3,'那我单独打包一份，到外面走廊吃，不影响包厢里的你行吗？','nà wǒ dān dú dǎ bāo yī fèn ， dào wài miàn zǒu láng chī ， bù yǐng xiǎng bāo xiāng lǐ de nǐ xíng ma ？','Vậy để tớ gói riêng một phần, ra ngoài hành lang ăn, không ảnh hưởng đến cậu trong phòng, được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1408_04','V1408','子轩',4,'这样最好，等下咱们再点几份无异味小炒一起在包厢吃。','zhè yàng zuì hǎo ， děng xià zán men zài diǎn jǐ fèn wú yì wèi xiǎo chǎo yì qǐ zài bāo xiāng chī 。','Vậy là tốt nhất rồi, lát nữa mình gọi thêm mấy món xào không mùi ăn chung trong phòng nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1408_05','V1408','阮明',5,'没问题，我分开打包，不会让气味熏到大家嘛。','méi wèn tí ， wǒ fēn kāi dǎ bāo ， bú huì ràng qì wèi xūn dào dà jiā ma 。','Không vấn đề gì, tớ gói riêng ra, sẽ không để mùi ảnh hưởng đến mọi người đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1408_06','V1408','子轩',6,'多谢体谅，等下我请你喝奶茶补偿一下哈。','duō xiè tǐ liàng ， děng xià wǒ qǐng nǐ hē nǎi chá bǔ cháng yī xià hā 。','Cảm ơn cậu đã thông cảm nhé, lát nữa tớ mời cậu ly trà sữa để đền bù nha.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1408_07','V1408','阮明',7,'小事，主要是不想让大家用餐不舒服。','xiǎo shì ， zhǔ yào shì bù xiǎng ràng dà jiā yòng cān bù shū fú 。','Chuyện nhỏ mà, chủ yếu là không muốn để mọi người ăn uống khó chịu thôi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1409','SATN1','素食全素餐厅用餐，询问店员菜品是否含有葱蒜、蛋奶这类素食禁忌食材',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1409','SIT1409','P1','suon_se','ban_chinh_thuc',NULL,'中式纯素餐饮分净素、蛋奶素，食客可提前告知店家剔除五辛（葱蒜韭菜等），店家会单独调整烹饪。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1409_01','V1409','阮明',1,'芳姐，纯素菜品能不放葱蒜、鸡蛋吗，我饮食避开这类食材。','fāng jiě ， chún sù cài pǐn néng bù fàng cōng suàn 、 jī dàn ma ， wǒ yǐn shí bì kāi zhè lèi shí cái 。','Chị Phương ơi, món chay thuần có thể không cho hành tỏi, trứng gà được không ạ, em kiêng mấy loại nguyên liệu này.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1409_02','V1409','芳姐',2,'没问题，本店全素无蛋奶，葱姜蒜也可以完全剔除不加哦。','méi wèn tí ， běn diàn quán sù wú dàn nǎi ， cōng jiāng suàn yě kě yǐ wán quán tī chú bù jiā ó 。','Không vấn đề gì, quán chị hoàn toàn chay không trứng sữa, hành gừng tỏi cũng có thể bỏ hết ra không cho vào nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1409_03','V1409','阮明',3,'仿肉菜品是豆制品做的，没有动物成分对吧？','fǎng ròu cài pǐn shì dòu zhì pǐn zuò de ， méi yǒu dòng wù chéng fèn duì ba ？','Món giả mặn là làm từ đậu, không có thành phần động vật đúng không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1409_04','V1409','芳姐',4,'全部大豆、菌菇制作，口感像肉，本质都是素食食材嘛。','quán bù dà dòu 、 jūn gū zhì zuò ， kǒu gǎn xiàng ròu ， běn zhì dōu shì sù shí shí cái ma 。','Toàn làm từ đậu nành, nấm các loại, ăn có vị như thịt nhưng bản chất vẫn là nguyên liệu chay hết nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1409_05','V1409','阮明',5,'那点两道仿荤素菜，再加一份清炒时蔬。','nà diǎn liǎng dào fǎng hūn sù cài ， zài jiā yī fèn qīng chǎo shí shū 。','Vậy cho em gọi hai món chay giả mặn, thêm một phần rau xào tươi nữa.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1409_06','V1409','芳姐',6,'马上给后厨备注无葱蒜，十分钟就能上菜哈。','mǎ shàng gěi hòu chú bèi zhù wú cōng suàn ， shí fēn zhōng jiù néng shàng cài hā 。','Chị ghi chú ngay cho bếp là không cho hành tỏi, mười phút là có món lên nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1409_07','V1409','阮明',7,'太贴心，终于找到适配我饮食习惯的餐馆。','tài tiē xīn ， zhōng yú zhǎo dào shì pèi wǒ yǐn shí xí guàn de cān guǎn 。','Chu đáo quá, cuối cùng cũng tìm được quán hợp với thói quen ăn uống của em.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1410','SATN1','线上团购餐厅双人套餐，到店核销时发现团购仅限工作日，周末不可用',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1410','SIT1410','P1','that_bai_nhe','ban_chinh_thuc',NULL,'餐饮团购普遍设置工作日、节假日使用限制，下单前需看清规则，节假日大多无法使用低价套餐。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1410_01','V1410','阮明',1,'你好，我线上团购双人套餐，今天周六能直接核销使用吗？','nǐ hǎo ， wǒ xiàn shàng tuán gòu shuāng rén tào cān ， jīn tiān zhōu liù néng zhí jiē hé xiāo shǐ yòng ma ？','Chào chị, em đặt combo cặp đôi qua nhóm mua online, hôm nay thứ Bảy có dùng trực tiếp được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1410_02','V1410','小雯',2,'团购页面标注仅限周一至周五工作日，周末无法兑换套餐哦。','tuán gòu yè miàn biāo zhù jǐn xiàn zhōu yī zhì zhōu wǔ gōng zuò rì ， zhōu mò wú fǎ duì huàn tào cān ó 。','Trang nhóm mua ghi rõ chỉ áp dụng từ thứ Hai đến thứ Sáu thôi ạ, cuối tuần không đổi được combo đâu.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1410_03','V1410','阮明',3,'我下单时没仔细看使用时间，现在有别的解决办法吗？','wǒ xià dān shí méi zǐ xì kàn shǐ yòng shí jiān ， xiàn zài yǒu bié de jiě jué bàn fǎ ma ？','Lúc đặt em không để ý kỹ thời gian sử dụng, giờ có cách nào khác không chị?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1410_04','V1410','小雯',4,'套餐可申请全额退款，或者按原价单点店内菜品就餐。','tào cān kě shēn qǐng quán é tuì kuǎn ， huò zhě àn yuán jià dān diǎn diàn nèi cài pǐn jiù cān 。','Combo có thể xin hoàn tiền toàn bộ, hoặc gọi món lẻ theo giá gốc trong nhà hàng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1410_05','V1410','阮明',5,'退款多久能到支付账户，会不会扣除手续费？','tuì kuǎn duō jiǔ néng dào zhī fù zhàng hù ， huì bú huì kòu chú shǒu xù fèi ？','Vậy hoàn tiền bao lâu thì vào tài khoản thanh toán, có bị trừ phí gì không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1410_06','V1410','小雯',6,'退款实时到账，无任何扣费，现在就能操作嘛。','tuì kuǎn shí shí dào zhàng ， wú rèn hé kòu fèi ， xiàn zài jiù néng cāo zuò ma 。','Hoàn tiền là về ngay lập tức, không bị trừ phí gì cả, giờ làm luôn cũng được.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1410_07','V1410','阮明',7,'那我申请退款，直接单点菜品吃饭好了。','nà wǒ shēn qǐng tuì kuǎn ， zhí jiē dān diǎn cài pǐn chī fàn hǎo le 。','Vậy em xin hoàn tiền, rồi gọi món lẻ ăn luôn cho tiện.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1411','SATN1','去农家土菜馆体验本地农家菜，不清楚菜量大小，咨询老板娘避免点多浪费',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1411','SIT1411','P1','suon_se','tuy_y',NULL,'乡村农家乐菜品分量远大于市区餐馆，点菜前咨询店家可避免过量点餐，节约食材符合国内节约粮食理念。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1411_01','V1411','阮明',1,'桂婶，我们两个人吃饭，点三道菜会不会分量太多吃不完？','guì shěn ， wǒ men liǎng gè rén chī fàn ， diǎn sān dào cài huì bú huì fèn liàng tài duō chī bù wán ？','Thím Quế ơi, tụi con hai người thôi mà gọi ba món thì có nhiều quá ăn không hết không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1411_02','V1411','桂婶',2,'农家菜盘子超大，两个人两菜一汤刚好，三道容易浪费粮食呢。','nóng jiā cài pán zi chāo dà ， liǎng gè rén liǎng cài yī tāng gāng hǎo ， sān dào róng yì làng fèi liáng shí ne 。','Món nhà quê đĩa to lắm, hai người ăn hai món một canh là vừa đủ rồi, gọi ba món dễ phí đồ ăn lắm đấy.','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1411_03','V1411','阮明',3,'土鸡锅分量很大吗，一份够两人吃饱？','tǔ jī guō fèn liàng hěn dà ma ， yī fèn gòu liǎng rén chī bǎo ？','Nồi gà thả vườn phần có nhiều không thím, một phần hai người ăn no được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1411_04','V1411','桂婶',4,'土鸡锅搭配米饭刚好，不用再加其他荤菜嘛。','tǔ jī guō dā pèi mǐ fàn gāng hǎo ， bù yòng zài jiā qí tā hūn cài ma 。','Nồi gà ăn kèm cơm là vừa đủ rồi, không cần gọi thêm món mặn khác đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1411_05','V1411','阮明',5,'那就土鸡锅加一盘青菜，一碗例汤就行。','nà jiù tǔ jī guō jiā yī pán qīng cài ， yī wǎn lì tāng jiù xíng 。','Vậy con gọi nồi gà, thêm một đĩa rau xanh với một bát canh suông là được rồi.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1411_06','V1411','桂婶',6,'好嘞，食材都是自家菜园种的，新鲜实惠哈。','hǎo lei ， shí cái dōu shì zì jiā cài yuán zhǒng de ， xīn xiān shí huì hā 。','Được rồi con, nguyên liệu toàn là rau vườn nhà trồng, tươi mà lại rẻ nữa.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1411_07','V1411','阮明',7,'还好提前问您，不然点一堆菜白白浪费。','hái hǎo tí qián wèn nín ， bù rán diǎn yī duī cài bái bái làng fèi 。','May mà hỏi thím trước, không thì gọi cả đống món rồi lại lãng phí thôi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1412','SATN1','商务中式简餐宴请导师，请教本土同学中式餐桌入座、敬酒基础礼仪',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1412','SIT1412','P1','suon_se','ban_chinh_thuc',NULL,'中式宴请讲究主客座位尊卑、敬酒杯沿高低，晚辈主动照顾长辈是传统餐桌礼仪。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1412_01','V1412','阮明',1,'峰学长，今晚我请导师吃饭，中式餐桌入座顺序有讲究吗？','fēng xué zhǎng ， jīn wǎn wǒ qǐng dǎo shī chī fàn ， zhōng shì cān zhuō rù zuò shùn xù yǒu jiǎng jiū ma ？','Anh Phong ơi, tối nay em mời thầy hướng dẫn ăn cơm, chỗ ngồi ở bàn ăn kiểu Trung Quốc có gì cần chú ý không anh?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1412_02','V1412','林峰',2,'正对大门的主位留给老师，你坐在靠近门口方便叫服务员的位置。','zhèng duì dà mén de zhǔ wèi liú gěi lǎo shī ， nǐ zuò zài kào jìn mén kǒu fāng biàn jiào fú wù yuán de wèi zhì 。','Vị trí chính đối diện cửa ra vào để dành cho thầy, em ngồi gần cửa để tiện gọi nhân viên phục vụ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1412_03','V1412','阮明',3,'倒茶敬酒的时候，杯子高低有什么规矩呢？','dào chá jìng jiǔ de shí hòu ， bēi zi gāo dī yǒu shén me guī jǔ ne ？','Lúc rót trà mời rượu, chuyện cầm ly cao thấp có quy tắc gì không anh?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1412_04','V1412','林峰',4,'你的杯沿低于老师的杯子，表示尊重，敬酒只浅抿一口不用喝完嘛。','nǐ de bēi yán dī yú lǎo shī de bēi zi ， biǎo shì zūn zhòng ， jìng jiǔ zhǐ qiǎn mǐn yī kǒu bù yòng hē wán ma 。','Miệng ly của em phải thấp hơn ly của thầy, thể hiện sự tôn trọng, còn khi mời rượu chỉ cần nhấp một ngụm nhỏ thôi, không cần uống hết đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1412_05','V1412','阮明',5,'点菜要优先点老师爱吃的清淡菜品，少点辛辣重油对不对？','diǎn cài yào yōu xiān diǎn lǎo shī ài chī de qīng dàn cài pǐn ， shǎo diǎn xīn là zhòng yóu duì bú duì ？','Gọi món thì nên ưu tiên món thanh đạm thầy thích ăn, hạn chế món cay và nhiều dầu mỡ đúng không anh?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1412_06','V1412','林峰',6,'没错，兼顾长辈口味，冷热荤素均衡搭配最合适哈。','méi cuò ， jiān gù zhǎng bèi kǒu wèi ， lěng rè hūn sù jūn héng dā pèi zuì hé shì hā 。','Đúng rồi, phải để ý khẩu vị của người lớn tuổi, kết hợp cân bằng giữa món nóng lạnh, mặn chay là hợp lý nhất.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1412_07','V1412','阮明',7,'记住这些礼仪，今晚宴请不会失礼了。','jì zhù zhè xiē lǐ yí ， jīn wǎn yàn qǐng bú huì shī lǐ le 。','Nhớ hết mấy điều này rồi, tối nay mời cơm chắc không sợ thất lễ nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1413','SATN1','海鲜大排档挑选鲜活水产，分不清时价称重计价，担心缺斤少两询问老板',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1413','SIT1413','P1','twist','tuy_y',NULL,'海鲜大排档鲜活水产实时时价，行业默认沥干水分称重，游客可全程监督称重避免虚重。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1413_01','V1413','阮明',1,'老板，皮皮虾是按当天市价称重，价格写在门口黑板上吗？','lǎo bǎn ， pí pí xiā shì àn dàng tiān shì jià chēng zhòng ， jià gé xiě zài mén kǒu hēi bǎn shàng ma ？','Chú ơi, con tôm tít này tính theo giá thị trường hàng ngày, giá ghi trên bảng đen ở cửa đúng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1413_02','V1413','老杨',2,'对，每日海鲜时价更新，称重前会把筐里的水沥干再称哦。','duì ， měi rì hǎi xiān shí jià gēng xīn ， chēng zhòng qián huì bǎ kuāng lǐ de shuǐ lì gàn zài chēng ó 。','Đúng vậy, giá hải sản mỗi ngày mỗi cập nhật, trước khi cân sẽ để ráo nước trong rổ rồi mới cân nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1413_03','V1413','阮明',3,'称重能让我看着吗，担心带水分多算重量。','chēng zhòng néng ràng wǒ kàn zhe ma ， dān xīn dài shuǐ fèn duō suàn zhòng liàng 。','Lúc cân chú cho con xem được không, con sợ nước còn đọng lại làm tăng cân nặng.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1413_04','V1413','老杨',4,'完全可以，每一份海鲜当着客人面称重，不会缺斤少两嘛。','wán quán kě yǐ ， měi yī fèn hǎi xiān dāng zhe kè rén miàn chēng zhòng ， bú huì quē jīn shǎo liǎng ma 。','Được chứ, mỗi phần hải sản đều cân ngay trước mặt khách, không có chuyện thiếu cân đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1413_05','V1413','阮明',5,'加工费另外算，清蒸和爆炒收费一样吗？','jiā gōng fèi lìng wài suàn ， qīng zhēng hé bào chǎo shōu fèi yī yàng ma ？','Phí chế biến tính riêng, hấp và xào cay giá có giống nhau không chú?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1413_06','V1413','老杨',6,'清蒸加工最便宜，香辣爆炒会多收十块加工费哈。','qīng zhēng jiā gōng zuì pián yi ， xiāng là bào chǎo huì duō shōu shí kuài jiā gōng fèi hā 。','Hấp là rẻ nhất, còn xào cay thì tính thêm mười tệ phí chế biến đấy.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1413_07','V1413','阮明',7,'那选一斤皮皮虾清蒸，少放辣椒。','nà xuǎn yī jīn pí pí xiā qīng zhēng ， shǎo fàng là jiāo 。','Vậy con lấy một cân tôm tít hấp, cho ít ớt thôi nhé.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1414','SATN1','外卖送达餐品撒漏、变凉，联系商家客服协商补发、退款补偿',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1414','SIT1414','P1','suon_se','ban_chinh_thuc',NULL,'国内外卖商家对撒漏、变质餐品售后包容，支持全额退款或免费重送，常额外发放优惠券补偿顾客。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1414_01','V1414','阮明',1,'你好，外卖汤品全部撒漏，饭菜已经凉透没法食用，拍图发给您了。','nǐ hǎo ， wài mài tāng pǐn quán bù sā lòu ， fàn cài yǐ jīng liáng tòu méi fǎ shí yòng ， pāi tú fā gěi nín le 。','Chào chị, phần canh trong đơn giao hàng bị đổ hết, đồ ăn cũng nguội lạnh không dùng được nữa, em chụp ảnh gửi chị rồi ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1414_02','V1414','客服',2,'实在抱歉，配送途中颠簸导致漏汤，给你两种处理方案任选哦。','shí zài bào qiàn ， pèi sòng tú zhōng diān bǒ dǎo zhì lòu tāng ， gěi nǐ liǎng zhǒng chǔ lǐ fāng àn rèn xuǎn ó 。','Thành thật xin lỗi bạn, do lúc vận chuyển xóc quá nên canh bị đổ, bên mình có hai phương án xử lý, bạn chọn nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1414_03','V1414','阮明',3,'方案一是全额退款，二是重新配送一份新餐对吗？','fāng àn yī shì quán é tuì kuǎn ， èr shì chóng xīn pèi sòng yī fèn xīn cān duì ma ？','Phương án một là hoàn tiền toàn bộ, phương án hai là giao lại một phần đồ ăn mới, đúng không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1414_04','V1414','客服',4,'没错，重新配送半小时送到，退款立刻原路返还，还附赠五元无门槛券嘛。','méi cuò ， chóng xīn pèi sòng bàn xiǎo shí sòng dào ， tuì kuǎn lì kè yuán lù fǎn huán ， hái fù zèng wǔ yuán wú mén kǎn quàn ma 。','Đúng vậy, giao lại thì nửa tiếng là tới nơi, còn hoàn tiền thì về ngay theo đường thanh toán cũ, kèm thêm voucher năm tệ không điều kiện luôn.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1414_05','V1414','阮明',5,'我等下还有课，直接全额退款加上优惠券吧。','wǒ děng xià hái yǒu kè ， zhí jiē quán é tuì kuǎn jiā shàng yōu huì quàn ba 。','Em lát nữa còn phải đi học nên hoàn tiền toàn bộ với voucher luôn giúp em nhé.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1414_06','V1414','客服',6,'好，现在登记退款，优惠券五分钟自动发放到账户哈。','hǎo ， xiàn zài dēng jì tuì kuǎn ， yōu huì quàn wǔ fēn zhōng zì dòng fā fàng dào zhàng hù hā 。','Được rồi, bây giờ đăng ký hoàn tiền cho bạn, voucher trong năm phút sẽ tự động vào tài khoản nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1414_07','V1414','阮明',7,'多谢快速处理，下次还会光顾本店。','duō xiè kuài sù chǔ lǐ ， xià cì hái huì guāng gù běn diàn 。','Cảm ơn chị xử lý nhanh, lần sau em sẽ ủng hộ quán tiếp ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1415','SATN1','北方饺子馆点手工水饺，分不清荤素馅料，询问店员每种馅料食材构成',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1415','SIT1415','P1','suon_se','tuy_y',NULL,'北方水饺荤素馅料区分清晰，店家会直白说明食材，忌口肉类、海鲜的食客可直接挑选素馅。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1415_01','V1415','阮明',1,'小丽，饺子猪肉白菜、韭菜鸡蛋两种馅料，食材分别是什么呀？','xiǎo lì ， jiǎo zi zhū ròu bái cài 、 jiǔ cài jī dàn liǎng zhǒng xiàn liào ， shí cái fēn bié shì shén me ya ？','Lệ ơi, sủi cảo nhân thịt heo cải thảo với nhân hẹ trứng, hai loại này nguyên liệu là gì vậy?','AM01') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1415_02','V1415','小丽',2,'猪肉白菜是鲜肉搭配白菜，韭菜鸡蛋全素，不吃肉可以选这款哦。','zhū ròu bái cài shì xiān ròu dā pèi bái cài ， jiǔ cài jī dàn quán sù ， bù chī ròu kě yǐ xuǎn zhè kuǎn ó 。','Nhân thịt heo cải thảo là thịt tươi kết hợp với cải thảo, còn nhân hẹ trứng là chay hoàn toàn, không ăn thịt thì chọn loại này nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1415_03','V1415','阮明',3,'素饺子里面有没有放虾皮、猪油调味呢？','sù jiǎo zi lǐ miàn yǒu méi yǒu fàng xiā pí 、 zhū yóu tiáo wèi ne ？','Sủi cảo chay có cho tôm khô hay mỡ heo để nêm nếm không?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1415_04','V1415','小丽',4,'纯素韭菜鸡蛋只放青菜鸡蛋，没有任何肉类辅料嘛。','chún sù jiǔ cài jī dàn zhǐ fàng qīng cài jī dàn ， méi yǒu rèn hé ròu lèi fǔ liào ma 。','Nhân hẹ trứng thuần chay chỉ cho rau và trứng thôi, không có bất kỳ nguyên liệu thịt nào cả.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1415_05','V1415','阮明',5,'二十个饺子一人份，我一份素饺子配醋碟。','èr shí gè jiǎo zi yī rén fèn ， wǒ yī fèn sù jiǎo zi pèi cù dié 。','Hai mươi cái sủi cảo là một phần cho một người, cho mình một phần sủi cảo chay kèm chén giấm nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1415_06','V1415','小丽',6,'好嘞，现包现煮，十分钟就能端上桌哈。','hǎo lei ， xiàn bāo xiàn zhǔ ， shí fēn zhōng jiù néng duān shàng zhuō hā 。','Được rồi bạn, gói xong nấu ngay, mười phút là bưng ra bàn liền.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1415_07','V1415','阮明',7,'谢谢讲解，第一次吃北方水饺怕选错馅料。','xiè xiè jiǎng jiě ， dì yī cì chī běi fāng shuǐ jiǎo pà xuǎn cuò xiàn liào 。','Cảm ơn bạn giải thích nhé, lần đầu ăn sủi cảo miền Bắc mình sợ chọn nhầm nhân lắm.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1416','SATN1','多人聚餐轮流买单，国内同学坚持AA制，讲解国内年轻人聚餐付款习惯',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1416','SIT1416','P1','twist','tuy_y',NULL,'当代国内青年朋友日常聚餐普遍AA制，仅节日、生日等特殊场合才会有人主动做东请客。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1416_01','V1416','阮明',1,'这顿饭我来结账，上次聚餐都是你们买单，这次我请客吧。','zhè dùn fàn wǒ lái jié zhàng ， shàng cì jù cān dōu shì nǐ men mǎi dān ， zhè cì wǒ qǐng kè ba 。','Bữa này để tớ trả nhé, lần trước tụ tập toàn các cậu trả tiền rồi, lần này tớ mời.','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1416_02','V1416','晓雨',2,'不用单独请客，我们年轻人聚餐大多AA，分摊更公平不用互相亏欠。','bù yòng dān dú qǐng kè ， wǒ men nián qīng rén jù cān dà duō AA， fēn tān gèng gōng píng bù yòng hù xiāng kuī qiàn 。','Không cần mời riêng đâu, tụi mình trẻ tuổi ăn uống với nhau đa số là chia đều, chia ra thì công bằng hơn, khỏi ai nợ ai.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1416_03','V1416','阮明',3,'国内朋友之间，不流行轮流做东请客吃饭吗？','guó nèi péng yǒu zhī jiān ， bù liú xíng lún liú zuò dōng qǐng kè chī fàn ma ？','Giữa bạn bè trong nước, không thịnh hành thay phiên nhau mời cơm à?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1416_04','V1416','晓雨',4,'关系很好的好友偶尔请客，日常聚餐一律AA，大家都没有负担嘛。','guān xì hěn hǎo de hǎo yǒu ǒu ěr qǐng kè ， rì cháng jù cān yī lǜ AA， dà jiā dōu méi yǒu fù dān ma 。','Bạn bè thân thiết thì thỉnh thoảng mời nhau, còn tụ tập ngày thường thì đều chia đều hết, ai cũng không thấy áp lực gì cả.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1416_05','V1416','阮明',5,'那吃完饭我把我的那份钱微信转给你。','nà chī wán fàn wǒ bǎ wǒ de nà fèn qián wēi xìn zhuǎn gěi nǐ 。','Vậy ăn xong tớ chuyển khoản phần tiền của mình cho cậu qua WeChat nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1416_06','V1416','晓雨',6,'我等下发账单明细，每个人平分总额就行哈。','wǒ děng xià fā zhàng dān míng xì ， měi gè rén píng fēn zǒng é jiù xíng hā 。','Lát nữa tớ gửi chi tiết hóa đơn, mỗi người chia đều tổng số tiền là được rồi.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1416_07','V1416','阮明',7,'原来年轻人流行AA，和我家乡聚餐习惯不太一样。','yuán lái nián qīng rén liú xíng AA， hé wǒ jiā xiāng jù cān xí guàn bù tài yī yàng 。','Hóa ra giới trẻ ở đây quen chia đều, khác với thói quen tụ tập ở quê mình ghê.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1417','SATN1','云南风味野生菌火锅店用餐，店员提醒菌类必须完全煮熟，不可生食',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1417','SIT1417','P1','twist','ban_chinh_thuc',NULL,'云南野生食用菌存在天然毒素，当地餐饮强制要求长时间烹煮，店家有义务提醒食客禁止生食。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1417_01','V1417','阮明',1,'阿明，野生菌下锅煮多久才能吃，看起来很快就熟了呢？','ā míng ， yě shēng jūn xià guō zhǔ duō jiǔ cái néng chī ， kàn qǐ lái hěn kuài jiù shú le ne ？','Minh ơi, nấm rừng nấu bao lâu mới ăn được, nhìn thấy chín nhanh vậy đó?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1417_02','V1417','阿明',2,'所有野生菌必须煮满二十分钟，半生食用容易中毒，千万不能提前夹哦。','suǒ yǒu yě shēng jūn bì xū zhǔ mǎn èr shí fēn zhōng ， bàn shēng shí yòng róng yì zhòng dú ， qiān wàn bù néng tí qián jiā ó 。','Tất cả nấm rừng phải nấu đủ hai mươi phút, ăn tái dễ bị ngộ độc lắm, tuyệt đối không được gắp trước đâu nhé.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1417_03','V1417','阮明',3,'要是提前捞出误食，会出现什么不适症状？','yào shì tí qián lāo chū wù shí ， huì chū xiàn shén me bù shì zhèng zhuàng ？','Nếu lỡ gắp ra ăn sớm quá thì sẽ có triệu chứng khó chịu gì vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1417_04','V1417','阿明',4,'会头晕恶心产生幻觉，本店全程定时提醒，还会把控下锅时间嘛。','huì tóu yūn ě xīn chǎn shēng huàn jué ， běn diàn quán chéng dìng shí tí xǐng ， hái huì bǎ kòng xià guō shí jiān ma 。','Sẽ bị chóng mặt buồn nôn, thậm chí ảo giác, quán mình sẽ nhắc giờ liên tục và canh thời gian nấu cho khách luôn.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1417_05','V1417','阮明',5,'好，我严格等够二十分钟再吃，不会着急夹取。','hǎo ， wǒ yán gé děng gòu èr shí fēn zhōng zài chī ， bú huì zháo jí jiā qǔ 。','Được rồi, em sẽ đợi đủ hai mươi phút mới ăn, không vội gắp đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1417_06','V1417','阿明',6,'我定时提醒大家，菌汤也要多煮一会儿再喝哈。','wǒ dìng shí tí xǐng dà jiā ， jūn tāng yě yào duō zhǔ yī huì er zài hē hā 。','Anh sẽ nhắc giờ cho mọi người, nước canh nấm cũng phải nấu thêm một lát nữa mới uống nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1417_07','V1417','阮明',7,'感谢提醒，野生菌类饮食安全不能马虎。','gǎn xiè tí xǐng ， yě shēng jūn lèi yǐn shí ān quán bù néng mǎ hǔ 。','Cảm ơn anh nhắc nhở, chuyện an toàn khi ăn nấm rừng không thể lơ là được.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1418','SATN1','网红特色私房菜无线下门店，只能微信预约订位，阮明不会操作预约流程',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1418','SIT1418','P1','that_bai_nhe','ban_chinh_thuc',NULL,'小众网红私房菜多依靠微信线上预约控流，无线下现场排号机制，境外微信常无法正常加载小程序。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1418_01','V1418','阮明',1,'陈姐，我想到店直接吃饭，为什么前台说必须提前微信预约呢？','chén jiě ， wǒ xiǎng dào diàn zhí jiē chī fàn ， wèi shén me qián tái shuō bì xū tí qián wēi xìn yù yuē ne ？','Chị Trần ơi, em muốn đến quán ăn trực tiếp, sao lễ tân bảo phải đặt bàn qua WeChat trước vậy ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1418_02','V1418','陈姐',2,'本店位置少，不接待临时到店客人，只能微信小程序提前订位哦。','běn diàn wèi zhì shǎo ， bù jiē dài lín shí dào diàn kè rén ， zhǐ néng wēi xìn xiǎo chéng xù tí qián dìng wèi ó 。','Quán mình ít chỗ, không nhận khách đến đột xuất đâu, chỉ có thể đặt bàn trước qua mini app WeChat thôi ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1418_03','V1418','阮明',3,'我的境外微信打不开预约小程序，没有别的预约渠道吗？','wǒ de jìng wài wēi xìn dǎ bù kāi yù yuē xiǎo chéng xù ， méi yǒu bié de yù yuē qú dào ma ？','WeChat nước ngoài của em không mở được mini app đặt bàn, có cách nào khác để đặt không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1418_04','V1418','陈姐',4,'唯一预约渠道就是小程序，没有电话、线下登记通道的。','wéi yī yù yuē qú dào jiù shì xiǎo chéng xù ， méi yǒu diàn huà 、 xiàn xià dēng jì tōng dào de 。','Kênh đặt bàn duy nhất là mini app thôi, không có gọi điện hay đăng ký trực tiếp tại quán đâu.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1418_05','V1418','阮明',5,'我找国内同学帮忙预约，明天晚上还有空位吗？','wǒ zhǎo guó nèi tóng xué bāng máng yù yuē ， míng tiān wǎn shàng hái yǒu kòng wèi ma ？','Em nhờ bạn học người trong nước đặt giúp, tối mai còn chỗ trống không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1418_06','V1418','陈姐',6,'明天晚间座位还有，让同学填写你的到店人数和时间就行哈。','míng tiān wǎn jiān zuò wèi hái yǒu ， ràng tóng xué tián xiě nǐ de dào diàn rén shù hé shí jiān jiù xíng hā 。','Tối mai vẫn còn chỗ, chỉ cần bạn đó điền số người và giờ đến của em là được rồi.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1418_07','V1418','阮明',7,'只能拜托室友帮忙预约，今天没法就餐了。','zhǐ néng bài tuō shì yǒu bāng máng yù yuē ， jīn tiān méi fǎ jiù cān le 。','Vậy chỉ còn cách nhờ bạn cùng phòng đặt giúp thôi, hôm nay đành chịu không ăn được rồi.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1419','SATN1','江浙甜食菜馆点菜，菜品甜度太高吃不惯，联系服务员更换清淡口味菜品',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1419','SIT1419','P1','twist','tuy_y',NULL,'江浙菜系普遍偏甜，食客可提前备注减糖，菜品未大量食用前多数店家支持免费更换。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1419_01','V1419','阮明',1,'小琪，这道糖醋排骨甜度太高，我实在吃不惯能换一道咸鲜菜品吗？','xiǎo qí ， zhè dào táng cù pái gǔ tián dù tài gāo ， wǒ shí zài chī bù guàn néng huàn yī dào xián xiān cài pǐn ma ？','Tiểu Kỳ ơi, món sườn xào chua ngọt này ngọt quá, mình thật sự không quen ăn được, đổi sang món mặn mặn được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1419_02','V1419','小琪',2,'刚上桌十分钟还没动几口，可以免费更换其他咸口菜品哦。','gāng shàng zhuō shí fēn zhōng hái méi dòng jǐ kǒu ， kě yǐ miǎn fèi gēng huàn qí tā xián kǒu cài pǐn ó 。','Món vừa lên bàn mười phút, chưa đụng mấy đũa, có thể đổi miễn phí sang món mặn khác nha.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1419_03','V1419','阮明',3,'江浙菜默认甜度都这么高吗，点菜前可以提前备注少糖？','jiāng zhè cài mò rèn tián dù dōu zhè me gāo ma ， diǎn cài qián kě yǐ tí qián bèi zhù shǎo táng ？','Mấy món Giang Chiết mặc định đều ngọt như vậy à, gọi món trước có thể ghi chú ít đường được không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1419_04','V1419','小琪',4,'没错，下单时备注少糖，后厨会减少冰糖调味，口感清淡很多嘛。','méi cuò ， xià dān shí bèi zhù shǎo táng ， hòu chú huì jiǎn shǎo bīng táng tiáo wèi ， kǒu gǎn qīng dàn hěn duō ma 。','Đúng rồi, lúc gọi món ghi chú ít đường thì bếp sẽ giảm đường phèn nêm nếm, vị sẽ nhạt hơn nhiều đó.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1419_05','V1419','阮明',5,'换成清炒虾仁，全程少放糖，麻烦后厨调整口味。','huàn chéng qīng chǎo xiā rén ， quán chéng shǎo fàng táng ， má fán hòu chú tiáo zhěng kǒu wèi 。','Đổi sang tôm xào thanh đạm nhé, cho ít đường thôi, phiền bếp điều chỉnh khẩu vị giúp mình.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1419_06','V1419','小琪',6,'我马上通知后厨重做，十分钟新菜就能上桌哈。','wǒ mǎ shàng tōng zhī hòu chú zhòng zuò ， shí fēn zhōng xīn cài jiù néng shàng zhuō hā 。','Mình báo bếp làm lại ngay, mười phút nữa món mới sẽ lên bàn thôi.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1419_07','V1419','阮明',7,'多谢允许更换菜品，下次点菜一定提前备注少糖。','duō xiè yǔn xǔ gēng huàn cài pǐn ， xià cì diǎn cài yí dìng tí qián bèi zhù shǎo táng 。','Cảm ơn đã cho đổi món nha, lần sau gọi món mình sẽ ghi chú ít đường trước luôn.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1420','SATN1','跨城市特色小吃探店，分不清堂食、打包价格差异，询问摊主打包收费标准',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1420','SIT1420','P1','suon_se','tuy_y',NULL,'街边小吃堂食免费提供餐具，打包塑料餐盒单独收取少量打包费，是国内小吃通用收费规则。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1420_01','V1420','阮明',1,'李叔，这份特色粉堂食和打包带走，价格是一样的吗？','lǐ shū ， zhè fèn tè sè fěn táng shí hé dǎ bāo dài zǒu ， jià gé shì yī yàng de ma ？','Chú Lý ơi, phần bún đặc sản này ăn tại chỗ với gói mang về giá có giống nhau không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1420_02','V1420','李叔',2,'价格相同，打包需要额外收取一元打包盒费用哦。','jià gé xiāng tóng ， dǎ bāo xū yào é wài shōu qǔ yī yuán dǎ bāo hé fèi yòng ó 。','Giá như nhau, chỉ là gói mang về thì tính thêm một tệ tiền hộp thôi.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1420_03','V1420','阮明',3,'打包盒密封性好不好，路上二十分钟汤会不会洒出来？','dǎ bāo hé mì fēng xìng hǎo bù hǎo ， lù shàng èr shí fēn zhōng tāng huì bú huì sǎ chū lái ？','Hộp gói có kín không chú, để hai mươi phút trên đường nước canh có bị đổ ra không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1420_04','V1420','李叔',4,'加厚密封餐盒，盖子扣紧，短途携带不会漏汤嘛。','jiā hòu mì fēng cān hé ， gài zi kòu jǐn ， duǎn tú xié dài bú huì lòu tāng ma 。','Hộp đựng loại dày, kín, đậy nắp chặt rồi thì đi đường ngắn không lo chảy nước đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1420_05','V1420','阮明',5,'那打包一份，少放本地秘制甜辣酱。','nà dǎ bāo yī fèn ， shǎo fàng běn dì mì zhì tián là jiàng 。','Vậy gói cho cháu một phần, cho ít tương ớt ngọt đặc sản ở đây thôi nhé.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1420_06','V1420','李叔',6,'好嘞，打包盒装好，给你多套一层袋子防漏哈。','hǎo lei ， dǎ bāo hé zhuāng hǎo ， gěi nǐ duō tào yī céng dài zi fáng lòu hā 。','Được rồi, hộp gói xong, chú lồng thêm một lớp túi cho khỏi rò nước nha.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1420_07','V1420','阮明',7,'清楚打包收费，打包带走回宿舍慢慢吃。','qīng chǔ dǎ bāo shōu fèi ， dǎ bāo dài zǒu huí sù shè màn màn chī 。','Rõ giá gói mang về rồi, cháu mang về ký túc xá ăn từ từ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1421','SATN1','朝鲜族烤肉店自助烤肉，不懂炭火控温、烤肉类熟度，店员上前帮忙指导',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1421','SIT1421','P1','suon_se','ban_chinh_thuc',NULL,'朝鲜族烤肉有专属搭配吃法（生菜包肉），店员会主动指导火候、熟度区分，帮助新手食客。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1421_01','V1421','阮明',1,'善姬，炭火太旺肉一下子烤焦，怎么调节火力大小呢？','shàn jī ， tàn huǒ tài wàng ròu yī xià zi kǎo jiāo ， zěn me tiáo jié huǒ lì dà xiǎo ne ？','Seon-hui ơi, lửa than mạnh quá thịt bị cháy liền, làm sao chỉnh lửa nhỏ lại vậy ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1421_02','V1421','善姬',2,'把炭火挡板拉开一点散热，五花肉中火慢烤才不会发苦哦。','bǎ tàn huǒ dǎng bǎn lā kāi yì diǎn sàn rè ， wǔ huā ròu zhōng huǒ màn kǎo cái bú huì fā kǔ ó 。','Kéo tấm chắn than ra một chút cho tản nhiệt, thịt ba chỉ nướng lửa vừa mới không bị đắng đâu ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1421_03','V1421','阮明',3,'牛肉烤到几分熟最合适，全熟会不会肉质发硬？','niú ròu kǎo dào jǐ fēn shú zuì hé shì ， quán shú huì bú huì ròu zhì fā yìng ？','Thịt bò nướng tới mấy phần chín là hợp nhất ạ, chín hẳn thì thịt có bị dai không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1421_04','V1421','善姬',4,'牛肉烤到七分熟嫩度最好，猪肉必须完全烤熟才能食用嘛。','niú ròu kǎo dào qī fēn shú nèn dù zuì hǎo ， zhū ròu bì xū wán quán kǎo shú cái néng shí yòng ma 。','Thịt bò nướng bảy phần chín là mềm ngon nhất, còn thịt heo thì bắt buộc phải chín hẳn mới ăn được nhé.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1421_05','V1421','阮明',5,'生菜包肉搭配泡菜一起吃，是本地特色吃法对吧？','shēng cài bāo ròu dā pèi pào cài yì qǐ chī ， shì běn dì tè sè chī fǎ duì ba ？','Cuốn thịt với xà lách ăn kèm kim chi, đây là cách ăn đặc trưng ở đây đúng không ạ?','AM07') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1421_06','V1421','善姬',6,'没错，搭配蒜片泡菜解腻，很多外国游客都喜欢这种吃法哈。','méi cuò ， dā pèi suàn piàn pào cài jiě nì ， hěn duō wài guó yóu kè dōu xǐ huān zhè zhǒng chī fǎ hā 。','Đúng vậy, ăn kèm kim chi tỏi lát để đỡ ngán, nhiều khách nước ngoài rất thích cách ăn này ạ.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1421_07','V1421','阮明',7,'学会控温技巧，自己烤肉不会烤糊了。','xué huì kòng wēn jì qiǎo ， zì jǐ kǎo ròu bú huì kǎo hú le 。','Học được cách canh lửa rồi, tự nướng thịt sẽ không bị cháy khét nữa.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1422','SATN1','餐厅结账索要纸质发票，留学生不懂发票用途，前台服务员简单解释',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1422','SIT1422','P1','suon_se','ban_chinh_thuc',NULL,'国内消费餐饮可免费开具增值税发票，作为消费维权、单位报销法定凭证，每单仅可开具一次。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1422_01','V1422','阮明',1,'小周，我结账想要纸质发票，请问发票有什么用处呢？','xiǎo zhōu ， wǒ jié zhàng xiǎng yào zhǐ zhì fā piào ， qǐng wèn fā piào yǒu shén me yòng chǔ ne ？','Tiểu Chu ơi, em thanh toán muốn lấy hóa đơn giấy, cho em hỏi hóa đơn dùng để làm gì ạ?','AM04') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1422_02','V1422','小周',2,'国内企业报销、个人维权都需要发票，是消费凭证哦。','guó nèi qǐ yè bào xiāo 、 gè rén wéi quán dōu xū yào fā piào ， shì xiāo fèi píng zhèng ó 。','Trong nước doanh nghiệp thanh toán chi phí hay cá nhân bảo vệ quyền lợi đều cần hóa đơn, đó là chứng từ tiêu dùng ạ.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1422_03','V1422','阮明',3,'留学生个人就餐，不开公司抬头也能开具发票吗？','liú xué shēng gè rén jiù cān ， bù kāi gōng sī tái tóu yě néng kāi jù fā piào ma ？','Du học sinh ăn cá nhân, không xuất tên công ty thì vẫn xuất được hóa đơn chứ ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1422_04','V1422','小周',4,'可以直接开个人抬头，纸质发票当场打印交给你嘛。','kě yǐ zhí jiē kāi gè rén tái tóu ， zhǐ zhì fā piào dāng chǎng dǎ yìn jiāo gěi nǐ ma 。','Có thể xuất trực tiếp tên cá nhân, hóa đơn giấy in ngay tại chỗ và đưa cho em luôn.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1422_05','V1422','阮明',5,'发票丢失之后，还能回来重新打印一份吗？','fā piào diū shī zhī hòu ， hái néng huí lái chóng xīn dǎ yìn yī fèn ma ？','Nếu hóa đơn bị mất rồi, em quay lại xin in lại một bản được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1422_06','V1422','小周',6,'本店只能打印一次，丢失无法补打，妥善保管票据哈。','běn diàn zhǐ néng dǎ yìn yī cì ， diū shī wú fǎ bǔ dǎ ， tuǒ shàn bǎo guǎn piào jù hā 。','Quán chỉ in được một lần thôi, mất rồi không in bù được đâu, em giữ kỹ hóa đơn nhé.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1422_07','V1422','阮明',7,'明白了，开个人纸质发票留作消费凭证。','míng bái le ， kāi gè rén zhǐ zhì fā piào liú zuò xiāo fèi píng zhèng 。','Em hiểu rồi, xuất hóa đơn giấy tên cá nhân để giữ làm chứng từ tiêu dùng ạ.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1423','SATN1','药膳养生菜馆吃饭，分不清药膳食材药性，咨询店长适配自身体质菜品',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1423','SIT1423','P1','twist','chinh_thuc',NULL,'中式药膳讲究体质匹配，热性体质少食温补药材，药膳馆店员会根据食客身体状况推荐适配菜品。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1423_01','V1423','阮明',1,'王叔，我容易上火长痘，药膳菜品里人参、枸杞这类温补食材能吃吗？','wáng shū ， wǒ róng yì shàng huǒ zhǎng dòu ， yào shàn cài pǐn lǐ rén shēn 、 gǒu qǐ zhè lèi wēn bǔ shí cái néng chī ma ？','Chú Vương ơi, cháu dễ bị nóng trong nổi mụn, những món dược thiện có nhân sâm, kỷ tử loại ôn bổ này cháu ăn được không ạ?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1423_02','V1423','王叔',2,'人参温补容易加重上火，给你推荐清热的冬瓜百合药膳汤更适配。','rén shēn wēn bǔ róng yì jiā zhòng shàng huǒ ， gěi nǐ tuī jiàn qīng rè de dōng guā bǎi hé yào shàn tāng gèng shì pèi 。','Nhân sâm ôn bổ dễ làm nặng thêm nóng trong, chú gợi ý cháu dùng canh dược thiện đông qua bách hợp thanh nhiệt sẽ hợp hơn.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1423_03','V1423','阮明',3,'药膳菜都带有中药苦味吗，会不会很难入口？','yào shàn cài dōu dài yǒu zhōng yào kǔ wèi ma ， huì bú huì hěn nán rù kǒu ？','Các món dược thiện đều có vị đắng của thuốc bắc phải không ạ, có khó ăn lắm không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1423_04','V1423','王叔',4,'搭配肉类中和药味，口感鲜香，不会有浓重苦涩感嘛。','dā pèi ròu lèi zhōng hé yào wèi ， kǒu gǎn xiān xiāng ， bú huì yǒu nóng zhòng kǔ sè gǎn ma 。','Kết hợp với thịt để trung hòa vị thuốc, ăn sẽ thơm ngon, không bị đắng chát nồng đâu.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1423_05','V1423','阮明',5,'那就点一份百合老鸭汤，搭配两道清淡素菜。','nà jiù diǎn yī fèn bǎi hé lǎo yā tāng ， dā pèi liǎng dào qīng dàn sù cài 。','Vậy cháu gọi một phần canh vịt già bách hợp, kèm hai món chay thanh đạm ạ.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1423_06','V1423','王叔',6,'好，后厨减少温补药材，多放清热食材适配你的体质哈。','hǎo ， hòu chú jiǎn shǎo wēn bǔ yào cái ， duō fàng qīng rè shí cái shì pèi nǐ de tǐ zhì hā 。','Được, bếp sẽ giảm bớt dược liệu ôn bổ, cho thêm nguyên liệu thanh nhiệt để hợp thể trạng của cháu.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1423_07','V1423','阮明',7,'多亏专业讲解，选到适合自己体质的养生菜品。','duō kuī zhuān yè jiǎng jiě ， xuǎn dào shì hé zì jǐ tǐ zhì de yǎng shēng cài pǐn 。','Nhờ chú giải thích tận tình mà cháu chọn được món dưỡng sinh hợp với thể trạng của mình.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1424','SATN1','多人宴席包间点菜，服务员提醒冷热荤素搭配，均衡点菜符合中式宴席习惯',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1424','SIT1424','P1','suon_se','ban_chinh_thuc',NULL,'中式多人宴席点菜讲究凉菜、热荤、热素、汤、甜品完整搭配，菜品均衡是宴席待客基本礼仪。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1424_01','V1424','阮明',1,'阿豪，我们八个人只点四道荤菜，是不是素菜凉菜太少了？','ā háo ， wǒ men bā gè rén zhǐ diǎn sì dào hūn cài ， shì bú shì sù cài liáng cài tài shǎo le ？','A Hào ơi, tám người tụi mình chỉ gọi bốn món mặn, có phải món chay và món nguội hơi ít không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1424_02','V1424','阿豪',2,'中式宴席讲究冷热、荤素均衡，再加两道凉菜两道素菜搭配更好哦。','zhōng shì yàn xí jiǎng jiū lěng rè 、 hūn sù jūn héng ， zài jiā liǎng dào liáng cài liǎng dào sù cài dā pèi gèng hǎo ó 。','Tiệc kiểu Trung chú trọng cân bằng nóng lạnh, mặn chay, gọi thêm hai món nguội hai món chay nữa sẽ hợp hơn đó.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1424_03','V1424','阮明',3,'甜品和汤品需要单独再加吗？','tián pǐn hé tāng pǐn xū yào dān dú zài jiā ma ？','Món tráng miệng với món canh có cần gọi thêm riêng không?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1424_04','V1424','阿豪',4,'宴席标配一汤一甜品，饭后解腻，整套菜品结构更完整嘛。','yàn xí biāo pèi yī tāng yī tián pǐn ， fàn hòu jiě nì ， zhěng tào cài pǐn jié gòu gèng wán zhěng ma 。','Tiệc chuẩn phải có một canh một tráng miệng, ăn xong đỡ ngán, cả set món mới đầy đủ.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1424_05','V1424','阮明',5,'那按你的建议补充凉菜、素菜和甜汤。','nà àn nǐ de jiàn yì bǔ chōng liáng cài 、 sù cài hé tián tāng 。','Vậy theo gợi ý của cậu thì mình bổ sung thêm món nguội, món chay với canh ngọt.',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1424_06','V1424','阿豪',6,'这样搭配兼顾所有人口味，冷热交替吃起来更舒服哈。','zhè yàng dā pèi jiān gù suǒ yǒu rén kǒu wèi ， lěng rè jiāo tì chī qǐ lái gèng shū fú hā 。','Như vậy sẽ hợp khẩu vị mọi người, ăn xen kẽ nóng lạnh sẽ thấy dễ chịu hơn đó.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1424_07','V1424','阮明',7,'感谢提醒，不然点菜结构单一不够体面。','gǎn xiè tí xǐng ， bù rán diǎn cài jié gòu dān yī bù gòu tǐ miàn 。','Cảm ơn cậu nhắc nhở, không thì gọi món kiểu này nhìn đơn điệu quá không đẹp mắt.',NULL) ON CONFLICT DO NOTHING;

INSERT INTO situations (id,subdomain_id,name,description,difficulty_level) VALUES ('SIT1425','SATN1','异国风味融合中餐厅打卡，想搭配本地黄酒，询问黄酒饮用方式与酒精度',NULL,'B1') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_variants (id,situation_id,persona_id,outcome_type,register_level,context_note,cultural_note) VALUES ('V1425','SIT1425','P1','twist','tuy_y',NULL,'黄酒是中式传统佐餐酒，温热饮用是千年饮食习惯，适配红烧、卤味等重口味中式菜肴。') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1425_01','V1425','阮明',1,'阿远，搭配中餐的黄酒酒精度高吗，直接常温喝还是加热饮用？','ā yuǎn ， dā pèi zhōng cān de huáng jiǔ jiǔ jīng dù gāo ma ， zhí jiē cháng wēn hē hái shì jiā rè yǐn yòng ？','A Viễn ơi, rượu vàng ăn kèm món Trung độ cồn cao không, uống nguội bình thường hay phải hâm nóng lên?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1425_02','V1425','阿远',2,'黄酒十二度左右，国内习惯温热饮用，暖胃口感更柔和哦。','huáng jiǔ shí èr dù zuǒ yòu ， guó nèi xí guàn wēn rè yǐn yòng ， nuǎn wèi kǒu gǎn gèng róu hé ó 。','Rượu vàng khoảng mười hai độ, trong nước thường uống ấm, ấm bụng vị cũng dịu hơn nhiều đó.','AM03') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1425_03','V1425','阮明',3,'不加任何配料直接温酒，还是要搭配枸杞红枣一起煮？','bù jiā rèn hé pèi liào zhí jiē wēn jiǔ ， hái shì yào dā pèi gǒu qǐ hóng zǎo yì qǐ zhǔ ？','Không cho thêm gì hâm ấm trực tiếp, hay phải nấu kèm kỷ tử táo đỏ vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1425_04','V1425','阿远',4,'纯黄酒温煮即可，想甜一点再加几颗红枣，不强制搭配辅料嘛。','chún huáng jiǔ wēn zhǔ jí kě ， xiǎng tián yì diǎn zài jiā jǐ kē hóng zǎo ， bù qiáng zhì dā pèi fǔ liào ma 。','Rượu vàng nguyên chất hâm ấm là được rồi, muốn ngọt hơn thì cho thêm mấy trái táo đỏ, không bắt buộc phải kèm gì cả.','AM09') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1425_05','V1425','阮明',5,'一杯黄酒搭配什么菜品食用风味更协调？','yī bēi huáng jiǔ dā pèi shén me cài pǐn shí yòng fēng wèi gèng xié tiáo ？','Một ly rượu vàng ăn kèm món gì thì vị hợp nhất vậy?',NULL) ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1425_06','V1425','阿远',6,'红烧肉类、菌菇菜适配黄酒，清淡海鲜搭配会掩盖酒香哈。','hóng shāo ròu lèi 、 jūn gū cài shì pèi huáng jiǔ ， qīng dàn hǎi xiān dā pèi huì yǎn gài jiǔ xiāng hā 。','Thịt kho tàu, món nấm hợp với rượu vàng, còn hải sản thanh đạm ăn kèm sẽ át mất hương rượu đó.','AM06') ON CONFLICT DO NOTHING;
INSERT INTO dialogue_lines (id,variant_id,speaker,order_index,text_zh,pinyin,text_vi,attitude_marker_id) VALUES ('L1425_07','V1425','阮明',7,'那就温一小壶黄酒，配桌上红烧牛肉品尝。','nà jiù wēn yī xiǎo hú huáng jiǔ ， pèi zhuō shàng hóng shāo niú ròu pǐn cháng 。','Vậy hâm một bình nhỏ rượu vàng, ăn kèm với thịt bò kho trên bàn thử xem sao.',NULL) ON CONFLICT DO NOTHING;



INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT203','CP_M') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT204','CP_F') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT205','CP_H') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT206','CP_H') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT207','CP_H') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT214','CP_A') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT215','CP_A') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT216','CP_B') ON CONFLICT DO NOTHING;
INSERT INTO situation_cultural_pattern (situation_id,cultural_pattern_id) VALUES ('SIT219','CP_C') ON CONFLICT DO NOTHING;
